# -*- coding: utf-8 -*-
"""espanol-en A2 vocabulary — batch 2 (final 6 chapters, 12 words each)."""

CHAPTERS = {

'shopping-and-money': dict(num='V7', short='Shopping & Money', words=[
  ('la tienda', 'ˈtjenda', 'shop', 'Esa <b>tienda</b> cierra a las nueve.'),
  ('el precio', 'ˈpreθjo', 'price', 'El <b>precio</b> incluye el IVA.'),
  ('barato', 'baˈrato', 'cheap', 'Este mercado es muy <b>barato</b>.'),
  ('caro', 'ˈkaro', 'expensive', 'El centro comercial es más <b>caro</b>.'),
  ('pagar', 'paˈɣar', 'to pay', '¿Puedo <b>pagar</b> con tarjeta?'),
  ('en efectivo', 'en efekˈtiβo', 'in cash', 'Aquí solo se puede pagar <b>en efectivo</b>.'),
  ('las rebajas', 'reˈβaxas', 'sales', 'Las <b>rebajas</b> empiezan en enero.'),
  ('el descuento', 'desˈkwento', 'discount', 'Hay un <b>descuento</b> del veinte por ciento.'),
  ('el recibo', 'reˈθiβo', 'receipt', 'Guarda el <b>recibo</b> por si acaso.'),
  ('devolver', 'deβolˈβer', 'to return (an item)', 'Quiero <b>devolver</b> esta camiseta.'),
  ('la talla', 'ˈtaʎa', 'size (clothes)', '¿Tiene esta <b>talla</b> en azul?'),
  ('gastar', 'gasˈtar', 'to spend', 'No quiero <b>gastar</b> más de veinte euros.'),
]),

'technology-and-media': dict(num='V9', short='Technology & Media', words=[
  ('el móvil', 'ˈmoβil', 'mobile phone', 'Me dejé el <b>móvil</b> en casa.'),
  ('la pantalla', 'panˈtaʎa', 'screen', 'La <b>pantalla</b> está rota.'),
  ('descargar', 'deskarˈɣar', 'to download', 'Voy a <b>descargar</b> la aplicación.'),
  ('subir', 'suˈβir', 'to upload', 'Quiero <b>subir</b> las fotos del viaje.'),
  ('el correo', 'koˈreo', 'email', 'Te mando el documento por <b>correo</b>.'),
  ('la contraseña', 'kontraˈseɲa', 'password', 'He olvidado mi <b>contraseña</b> otra vez.'),
  ('el archivo', 'arˈtʃiβo', 'file', 'El <b>archivo</b> es demasiado grande.'),
  ('navegar', 'naβeˈɣar', 'to browse', 'Me gusta <b>navegar</b> por internet por la noche.'),
  ('la red', 'ˈreð', 'network', 'La <b>red</b> wifi no funciona hoy.'),
  ('el teclado', 'teˈklaðo', 'keyboard', 'Este <b>teclado</b> no tiene la eñe.'),
  ('las noticias', 'noˈtiθjas', 'news', 'Leo las <b>noticias</b> en el móvil.'),
  ('el usuario', 'uˈswarjo', 'user', 'El <b>usuario</b> debe aceptar las condiciones.'),
]),

'transport-and-travel': dict(num='V10', short='Transport & Travel', words=[
  ('el tren', 'ˈtren', 'train', 'El <b>tren</b> sale del andén dos.'),
  ('el vuelo', 'ˈbwelo', 'flight', 'El <b>vuelo</b> está retrasado una hora.'),
  ('el billete', 'biˈʎete', 'ticket', 'Compré un <b>billete</b> de ida y vuelta.'),
  ('la maleta', 'maˈleta', 'suitcase', 'Mi <b>maleta</b> pesa demasiado.'),
  ('el andén', 'anˈden', 'platform', 'Esperamos en el <b>andén</b> tres.'),
  ('retrasado', 'retraˈsaðo', 'delayed', 'El autobús va <b>retrasado</b> por el tráfico.'),
  ('facturar', 'faktuˈrar', 'to check in (luggage)', 'Hay que <b>facturar</b> la maleta grande.'),
  ('el destino', 'desˈtino', 'destination', 'Nuestro <b>destino</b> final es Sevilla.'),
  ('la parada', 'paˈraða', 'stop (bus)', 'La <b>parada</b> está enfrente del banco.'),
  ('el metro', 'ˈmetro', 'underground', 'El <b>metro</b> es lo más rápido en Madrid.'),
  ('alquilar', 'alkiˈlar', 'to rent', 'Vamos a <b>alquilar</b> un coche en la costa.'),
  ('el viajero', 'bjaˈxero', 'traveller', 'Cada <b>viajero</b> puede llevar dos maletas.'),
]),

'weather-detail': dict(num='V11', short='Weather', words=[
  ('la tormenta', 'torˈmenta', 'storm', 'La <b>tormenta</b> llegó por la noche.'),
  ('el granizo', 'graˈniθo', 'hail', 'El <b>granizo</b> dañó los coches.'),
  ('la niebla', 'ˈnjeβla', 'fog', 'Con esta <b>niebla</b> no se ve nada.'),
  ('despejado', 'despeˈxaðo', 'clear (sky)', 'Mañana el cielo estará <b>despejado</b>.'),
  ('húmedo', 'ˈumeðo', 'humid', 'El clima del norte es muy <b>húmedo</b>.'),
  ('seco', 'ˈseko', 'dry', 'El verano aquí es muy <b>seco</b>.'),
  ('el pronóstico', 'proˈnostiko', 'forecast', 'El <b>pronóstico</b> anuncia lluvia.'),
  ('la ola de calor', 'ˈola ðe kaˈlor', 'heatwave', 'La <b>ola de calor</b> durará tres días.'),
  ('helar', 'eˈlar', 'to freeze', 'Esta noche va a <b>helar</b> en la sierra.'),
  ('el relámpago', 'reˈlampaɣo', 'lightning', 'Un <b>relámpago</b> iluminó el cielo.'),
  ('el trueno', 'ˈtrweno', 'thunder', 'El <b>trueno</b> asustó al perro.'),
  ('la brisa', 'ˈbrisa', 'breeze', 'La <b>brisa</b> del mar es muy agradable.'),
]),

'work-and-jobs': dict(num='V12', short='Work & Jobs', words=[
  ('el sueldo', 'ˈsweldo', 'salary', 'El <b>sueldo</b> se paga a final de mes.'),
  ('la entrevista', 'entreˈβista', 'interview', 'Tengo una <b>entrevista</b> de trabajo el jueves.'),
  ('el jefe', 'ˈxefe', 'boss', 'Mi <b>jefe</b> es bastante simpático.'),
  ('la empresa', 'emˈpresa', 'company', 'La <b>empresa</b> tiene cien empleados.'),
  ('contratar', 'kontraˈtar', 'to hire', 'Van a <b>contratar</b> a dos personas más.'),
  ('despedir', 'despeˈðir', 'to dismiss', 'La empresa tuvo que <b>despedir</b> a varios empleados.'),
  ('el horario', 'oˈrarjo', 'schedule', 'Mi <b>horario</b> es de nueve a cinco.'),
  ('la reunión', 'reuˈnjon', 'meeting', 'La <b>reunión</b> empieza en diez minutos.'),
  ('el currículum', 'kuˈrrikulum', 'CV', 'Envié mi <b>currículum</b> a tres empresas.'),
  ('el compañero', 'kompaˈɲero', 'colleague', 'Mi <b>compañero</b> de oficina es de Valencia.'),
  ('en paro', 'en ˈparo', 'unemployed', 'Lleva seis meses <b>en paro</b>.'),
  ('solicitar', 'soliθiˈtar', 'to apply for', 'Voy a <b>solicitar</b> ese puesto.'),
]),

'problems-solutions': dict(num='V5', short='Problems & Solutions', words=[
  ('el problema', 'proˈβlema', 'problem', 'Tenemos un <b>problema</b> con la reserva.'),
  ('la avería', 'aβeˈria', 'breakdown', 'El coche tiene una <b>avería</b>.'),
  ('arreglar', 'arreˈɣlar', 'to fix', '¿Puedes <b>arreglar</b> el grifo?'),
  ('romperse', 'romˈperse', 'to break', 'La lavadora acaba de <b>romperse</b>.'),
  ('funcionar', 'funθjoˈnar', 'to work (machines)', 'El ascensor no quiere <b>funcionar</b>.'),
  ('quejarse', 'keˈxarse', 'to complain', 'Si el servicio es malo, hay que <b>quejarse</b>.'),
  ('la solución', 'soluˈθjon', 'solution', 'Hay una <b>solución</b> sencilla.'),
  ('perder', 'perˈðer', 'to lose', 'Acabo de <b>perder</b> las llaves.'),
  ('encontrar', 'enkonˈtrar', 'to find', 'No puedo <b>encontrar</b> mi cartera.'),
  ('la ayuda', 'aˈʝuða', 'help', 'Necesito <b>ayuda</b> con la maleta.'),
  ('resolver', 'resolˈβer', 'to solve', 'Vamos a <b>resolver</b> esto juntos.'),
  ('la queja', 'ˈkexa', 'complaint', 'Escribí una <b>queja</b> al hotel.'),
]),
}
