# -*- coding: utf-8 -*-
"""espanol-en A2 vocabulary — batch 1 (6 chapters, 12 words each)."""

CHAPTERS = {

'sports': dict(num='V8', short='Sports', words=[
  ('el fútbol', 'ˈfutβol', 'football', 'Juego al <b>fútbol</b> los sábados.'),
  ('el baloncesto', 'balonˈθesto', 'basketball', 'El <b>baloncesto</b> es muy popular en mi instituto.'),
  ('la natación', 'nataˈθjon', 'swimming', 'La <b>natación</b> es buena para la espalda.'),
  ('el equipo', 'eˈkipo', 'team', 'Mi <b>equipo</b> ganó el partido.'),
  ('el partido', 'parˈtiðo', 'match', 'El <b>partido</b> empieza a las ocho.'),
  ('ganar', 'gaˈnar', 'to win', 'Queremos <b>ganar</b> la copa este año.'),
  ('perder', 'perˈðer', 'to lose', 'No me gusta <b>perder</b> en casa.'),
  ('entrenar', 'entreˈnar', 'to train', 'Tengo que <b>entrenar</b> tres veces por semana.'),
  ('el entrenador', 'entrenaˈðor', 'coach', 'El <b>entrenador</b> es muy exigente.'),
  ('la cancha', 'ˈkantʃa', 'court', 'La <b>cancha</b> de tenis está libre.'),
  ('el campeonato', 'kampeoˈnato', 'championship', 'El <b>campeonato</b> termina en junio.'),
  ('marcar un gol', 'marˈkar un ˈgol', 'to score a goal', 'Mi hermana va a <b>marcar un gol</b> seguro.'),
]),

'cooking': dict(num='V1', short='Cooking', words=[
  ('cocinar', 'koθiˈnar', 'to cook', 'Me encanta <b>cocinar</b> para mi familia.'),
  ('la receta', 'reˈθeta', 'recipe', 'Esta <b>receta</b> es de mi abuela.'),
  ('hervir', 'erˈβir', 'to boil', 'Hay que <b>hervir</b> el agua primero.'),
  ('freír', 'freˈir', 'to fry', 'Vamos a <b>freír</b> las patatas.'),
  ('el horno', 'ˈorno', 'oven', 'El pollo está en el <b>horno</b>.'),
  ('la sartén', 'sarˈten', 'frying pan', 'Calienta la <b>sartén</b> antes de empezar.'),
  ('mezclar', 'meθˈklar', 'to mix', 'Tienes que <b>mezclar</b> los huevos con el azúcar.'),
  ('cortar', 'korˈtar', 'to cut', 'Voy a <b>cortar</b> la cebolla.'),
  ('el ingrediente', 'ingreˈðjente', 'ingredient', 'Falta un <b>ingrediente</b> importante.'),
  ('probar', 'proˈβar', 'to taste', '¿Quieres <b>probar</b> la salsa?'),
  ('añadir', 'aɲaˈðir', 'to add', 'Ahora hay que <b>añadir</b> la sal.'),
  ('la cuchara', 'kuˈtʃara', 'spoon', 'Necesito una <b>cuchara</b> de madera.'),
]),

'feelings-emotions': dict(num='V2', short='Feelings & Emotions', words=[
  ('alegre', 'aˈleɣre', 'cheerful', 'Hoy estoy muy <b>alegre</b> porque es viernes.'),
  ('triste', 'ˈtriste', 'sad', 'Está <b>triste</b> porque perdió su móvil.'),
  ('enfadado', 'enfaˈðaðo', 'angry', 'Mi padre está <b>enfadado</b> conmigo.'),
  ('nervioso', 'nerˈβjoso', 'nervous', 'Estoy <b>nervioso</b> por el examen.'),
  ('preocupado', 'preokuˈpaðo', 'worried', 'Está <b>preocupado</b> por su trabajo.'),
  ('orgulloso', 'orɣuˈʎoso', 'proud', 'Estoy muy <b>orgulloso</b> de ti.'),
  ('celoso', 'θeˈloso', 'jealous', 'El perro está <b>celoso</b> del gato.'),
  ('sorprendido', 'sorprenˈdiðo', 'surprised', 'Me quedé <b>sorprendido</b> con la noticia.'),
  ('cansado', 'kanˈsaðo', 'tired', 'Estoy <b>cansado</b> después del trabajo.'),
  ('tranquilo', 'tranˈkilo', 'calm', 'El mar me hace sentir <b>tranquilo</b>.'),
  ('asustado', 'asusˈtaðo', 'scared', 'El niño está <b>asustado</b> por la tormenta.'),
  ('emocionado', 'emoθjoˈnaðo', 'excited', 'Estoy <b>emocionado</b> por el viaje.'),
]),

'health-and-body': dict(num='V3', short='Health & Body', words=[
  ('la cabeza', 'kaˈβeθa', 'head', 'Me duele la <b>cabeza</b> desde esta mañana.'),
  ('el estómago', 'esˈtomaɣo', 'stomach', 'Tengo el <b>estómago</b> revuelto.'),
  ('la garganta', 'garˈɣanta', 'throat', 'Me duele la <b>garganta</b> al tragar.'),
  ('doler', 'doˈler', 'to hurt', 'Me va a <b>doler</b> la espalda mañana.'),
  ('la fiebre', 'ˈfjeβre', 'fever', 'El niño tiene <b>fiebre</b> alta.'),
  ('el resfriado', 'resfriˈaðo', 'cold (illness)', 'Tengo un <b>resfriado</b> terrible.'),
  ('la tos', 'ˈtos', 'cough', 'Esta <b>tos</b> no me deja dormir.'),
  ('el médico', 'ˈmeðiko', 'doctor', 'Voy al <b>médico</b> esta tarde.'),
  ('la cita', 'ˈθita', 'appointment', 'Tengo una <b>cita</b> a las diez.'),
  ('la pastilla', 'pasˈtiʎa', 'pill', 'Toma una <b>pastilla</b> cada ocho horas.'),
  ('descansar', 'deskanˈsar', 'to rest', 'El médico dice que debo <b>descansar</b>.'),
  ('encontrarse bien', 'enkonˈtrarse ˈβjen', 'to feel well', 'Hoy no voy a clase porque no me encuentro bien — no es fácil <b>encontrarse bien</b> en invierno.'),
]),

'music': dict(num='V4', short='Music', words=[
  ('la canción', 'kanˈθjon', 'song', 'Esta <b>canción</b> me encanta.'),
  ('el cantante', 'kanˈtante', 'singer', 'El <b>cantante</b> tiene una voz increíble.'),
  ('el grupo', 'ˈgrupo', 'band', 'Mi <b>grupo</b> favorito da un concierto mañana.'),
  ('el concierto', 'konˈθjerto', 'concert', 'Las entradas para el <b>concierto</b> están agotadas.'),
  ('el escenario', 'esθeˈnarjo', 'stage', 'El grupo salió al <b>escenario</b> a las diez.'),
  ('la letra', 'ˈletra', 'lyrics', 'La <b>letra</b> de esta canción es muy triste.'),
  ('el ritmo', 'ˈritmo', 'rhythm', 'Este <b>ritmo</b> es perfecto para bailar.'),
  ('tocar', 'toˈkar', 'to play (an instrument)', 'Sé <b>tocar</b> la guitarra.'),
  ('la batería', 'bateˈria', 'drums', 'Mi hermano toca la <b>batería</b>.'),
  ('el violín', 'bjoˈlin', 'violin', 'El <b>violín</b> es difícil de aprender.'),
  ('el auricular', 'aurikuˈlar', 'earphone', 'Siempre pierdo un <b>auricular</b> en el autobús.'),
  ('grabar', 'graˈβar', 'to record', 'Van a <b>grabar</b> un disco nuevo.'),
]),

'school-subjects': dict(num='V6', short='School Subjects', words=[
  ('las matemáticas', 'mateˈmatikas', 'maths', 'Las <b>matemáticas</b> son mi asignatura favorita.'),
  ('la historia', 'isˈtorja', 'history', 'La <b>historia</b> de España es fascinante.'),
  ('las ciencias', 'ˈθjenθjas', 'science', 'Tenemos <b>ciencias</b> los martes.'),
  ('el idioma', 'iˈðjoma', 'language', 'El <b>idioma</b> más útil depende de tus planes.'),
  ('la asignatura', 'asignaˈtura', 'school subject', '¿Cuál es tu <b>asignatura</b> preferida?'),
  ('el examen', 'ekˈsamen', 'exam', 'El <b>examen</b> de inglés es el lunes.'),
  ('aprobar', 'aproˈβar', 'to pass (an exam)', 'Espero <b>aprobar</b> todo en junio.'),
  ('suspender', 'suspenˈder', 'to fail (an exam)', 'No quiero <b>suspender</b> otra vez.'),
  ('la nota', 'ˈnota', 'mark, grade', 'Saqué buena <b>nota</b> en historia.'),
  ('los deberes', 'deˈβeres', 'homework', 'Hago los <b>deberes</b> después de cenar.'),
  ('el horario', 'oˈrarjo', 'timetable', 'El <b>horario</b> nuevo empieza en septiembre.'),
  ('el recreo', 'reˈkreo', 'break (at school)', 'Jugamos al fútbol en el <b>recreo</b>.'),
]),
}
