# espanol_c2_v1.py — Main Spanish C2 Vocabulary V01–V06

CHAPTERS = {}

CHAPTERS['estilistica-literaria'] = dict(
    level='c2', num='V01', short='Estilística Literaria',
    words=[
        ('estilística', 'es.ti.ˈlis.ti.ka', 'Disciplina que estudia los recursos expresivos y el estilo de una obra literaria o de un autor determinado.', 'La <b>estilística</b> de Rulfo se caracteriza por una sintaxis fragmentaria que imita el habla rural mexicana.'),
        ('voz narrativa', 'boθ na.ˈra.ti.βa', 'Instancia enunciadora que relata los hechos en un texto literario, con sus propias características, perspectivas y limitaciones.', 'La <b>voz narrativa</b> de esta novela oscila entre la omnisciencia y la ignorancia deliberada, generando una ambigüedad inquietante.'),
        ('intertextualidad', 'in.ter.teks.twa.li.ˈðað', 'Relación que mantiene un texto con otros textos anteriores, ya sea por cita explícita, alusión o transformación.', 'La <b>intertextualidad</b> en la obra de Borges es tan densa que cada cuento parece una red de referencias a la tradición literaria universal.'),
        ('polifonía', 'po.li.ˈfo.ni.a', 'Presencia de múltiples voces o conciencias independientes dentro de un texto narrativo, sin que ninguna sea subordinada a la del autor.', 'Bajtín vio en Dostoievski el modelo de la <b>polifonía</b> novelesca, donde cada personaje habla desde una perspectiva irreductible a las demás.'),
        ('écfrasis', 'ˈek.fra.sis', 'Descripción literaria detallada de una obra de arte visual, que busca traducir en palabras los efectos plásticos de la imagen.', 'La <b>écfrasis</b> del escudo de Aquiles en la Ilíada es uno de los ejemplos más celebrados de esta técnica en la literatura occidental.'),
        ('etopeya', 'e.to.ˈpe.ja', 'Figura retórica que consiste en la descripción de los rasgos morales, psicológicos y de carácter de una persona o personaje.', 'La <b>etopeya</b> del protagonista ocupa el segundo capítulo entero, revelando sus contradicciones internas antes de que actúe.'),
        ('catarsis', 'ka.ˈtar.sis', 'Proceso de purificación o liberación emocional que experimenta el espectador o lector ante la representación de conflictos intensos.', 'La escena final produce una <b>catarsis</b> tan poderosa que el público permanece en silencio durante varios minutos tras el telón.'),
        ('diégesis', 'ˈdje.xe.sis', 'Universo narrativo interno de una obra; el mundo ficticio donde ocurren los hechos relatados por el narrador.', 'El personaje que lee un libro dentro de la novela habita la misma <b>diégesis</b> que los demás, pero su lectura introduce otra capa ficcional.'),
        ('metalepsis', 'me.ta.ˈlep.sis', 'Transgresión de los límites entre niveles narrativos distintos, como cuando un personaje sale de su ficción o el narrador entra en ella.', 'La <b>metalepsis</b> final del relato, en que el protagonista le habla directamente al autor, rompe toda ilusión realista de manera deliberada.'),
        ('narrador no fiable', 'na.ra.ˈðor no ˈfja.βle', 'Narrador cuya versión de los hechos es cuestionable o distorsionada por razones psicológicas, morales o cognitivas.', 'Solo a mitad de la novela comprendemos que el <b>narrador no fiable</b> ha estado ocultando información clave sobre su propio crimen.'),
        ('estilo indirecto libre', 'es.ˈti.lo in.di.ˈrek.to ˈli.βɾe', 'Técnica narrativa que funde la voz del narrador con el discurso interior del personaje sin marcas tipográficas de distinción.', 'Mediante el <b>estilo indirecto libre</b>, Flaubert nos hace sentir los pensamientos de Emma Bovary sin separar jamás narración de consciencia.'),
        ('aporía', 'a.po.ˈɾi.a', 'Dificultad lógica o argumentativa irresoluble que el texto plantea sin ofrecer salida, generando una tensión interpretativa permanente.', 'El poema termina en una <b>aporía</b> magistral: afirma y niega simultáneamente la posibilidad del amor como lenguaje compartido.'),
    ]
)

CHAPTERS['linguistica-avanzada'] = dict(
    level='c2', num='V02', short='Lingüística Avanzada',
    words=[
        ('competencia pragmática', 'kom.pe.ˈten.θja pɾaɣ.ˈma.ti.ka', 'Capacidad del hablante para usar el lenguaje de manera adecuada al contexto social, cultural e interaccional.', 'La <b>competencia pragmática</b> incluye saber cuándo callar, cuándo interrumpir y cómo interpretar el silencio como acto comunicativo.'),
        ('acto de habla', 'ˈak.to ðe ˈa.βla', 'Unidad mínima de comunicación que realiza una acción social —prometer, ordenar, afirmar— más allá de transmitir información.', 'Decir «¿podrías abrir la ventana?» no es una pregunta sobre capacidades: es un <b>acto de habla</b> directivo encubierto bajo forma interrogativa.'),
        ('fuerza ilocutiva', 'ˈfweɾ.θa i.lo.ku.ˈti.βa', 'Intención o propósito comunicativo que subyace a un enunciado y determina qué acción social realiza al ser pronunciado.', 'La <b>fuerza ilocutiva</b> de «te lo advierto» es amenazante aunque las palabras, aisladas, parezcan meramente informativas.'),
        ('deixis', 'ˈdejk.sis', 'Función lingüística que ancla la referencia de expresiones al contexto espacial, temporal o personal de la enunciación.', 'Palabras como «aquí», «ahora» y «yo» son expresiones deícticas cuyo significado depende enteramente del contexto de la <b>deixis</b> enunciativa.'),
        ('presuposición', 'pɾe.su.po.si.ˈθjon', 'Contenido implícito que el hablante da por sentado antes de pronunciar un enunciado y que no se cuestiona directamente.', 'La pregunta «¿cuándo dejaste de mentir?» carga una <b>presuposición</b> acusatoria que el interlocutor no puede rechazar sin parecer evasivo.'),
        ('implicatura conversacional', 'im.pli.ˈka.tu.ɾa kon.βeɾ.sa.θjo.ˈnal', 'Significado adicional que se infiere de un enunciado a partir de las normas cooperativas de la conversación, sin estar codificado literalmente.', 'Responder «he comido» a «¿tienes hambre?» es una <b>implicatura conversacional</b> que comunica negativa sin negarla explícitamente.'),
        ('variación fonológica', 'ba.ɾja.ˈθjon fo.no.ˈlo.xi.ka', 'Diferencias sistemáticas en la realización de fonemas según factores geográficos, sociales o estilísticos dentro de una comunidad lingüística.', 'El seseo y el ceceo son muestras de <b>variación fonológica</b> que no afectan la comprensión mutua pero marcan identidades dialectales fuertes.'),
        ('morfofonología', 'moɾ.fo.fo.no.lo.ˈxi.a', 'Rama de la lingüística que estudia las interacciones entre la estructura morfológica de las palabras y su realización fonológica.', 'La <b>morfofonología</b> explica por qué el sufijo «-ción» alterna con «-sión» en pares como «producción» y «comprensión».'),
        ('pidgin', 'ˈpið.xin', 'Sistema lingüístico de contacto, simplificado y sin hablantes nativos, que surge cuando dos comunidades necesitan comunicarse sin idioma común.', 'El <b>pidgin</b> camerunés mezcla inglés, francés y lenguas bantúes en una gramática reducida que sirve para el comercio interétnico.'),
        ('criollo', 'ˈkɾjo.ʎo', 'Lengua de contacto que, habiendo partido de un pidgin, adquiere hablantes nativos y se convierte en el idioma principal de una comunidad.', 'El papiamento es un <b>criollo</b> ibérico hablado en las Antillas holandesas que ha alcanzado estatus de lengua oficial con literatura propia.'),
        ('diglosia', 'di.ˈɣlo.sja', 'Situación sociolingüística en que dos variedades de una lengua coexisten con funciones sociales diferenciadas: una alta y otra baja.', 'En muchas comunidades arabófonas existe <b>diglosia</b> entre el árabe clásico coránico, usado en escritura formal, y los dialectos locales cotidianos.'),
        ('lexicogénesis', 'lek.si.ko.ˈxe.ne.sis', 'Conjunto de procesos mediante los cuales una lengua crea nuevas unidades léxicas para nombrar realidades o conceptos emergentes.', 'La <b>lexicogénesis</b> digital ha incorporado préstamos, neologismos y calcos a un ritmo sin precedentes en la historia del español contemporáneo.'),
    ]
)

CHAPTERS['filosofia-del-lenguaje'] = dict(
    level='c2', num='V03', short='Filosofía del Lenguaje',
    words=[
        ('teoría referencial', 'te.o.ˈɾi.a re.fe.ˈɾen.θjal', 'Doctrina filosófica que sostiene que el significado de una expresión lingüística es el objeto o entidad a la que dicha expresión se refiere.', 'La <b>teoría referencial</b> enfrenta el problema de las expresiones sin referente actual, como «el unicornio» o «el rey de Francia».'),
        ('condiciones de verdad', 'kon.di.ˈθjo.nes ðe βeɾ.ˈðað', 'Circunstancias o estados del mundo que, de darse, harían verdadero un enunciado; base de la semántica formal de inspiración tarskiana.', 'Conocer las <b>condiciones de verdad</b> de «está lloviendo» equivale a saber qué situación meteorológica haría verdadera esa oración.'),
        ('holismo semántico', 'o.ˈliz.mo se.ˈman.ti.ko', 'Tesis según la cual el significado de cualquier expresión lingüística depende de su relación con el conjunto total de creencias o del lenguaje.', 'El <b>holismo semántico</b> de Quine implica que no podemos cambiar el significado de un término sin alterar toda la red de nuestras creencias.'),
        ('sentido y referencia', 'ˈsen.ti.ðo i re.fe.ˈɾen.θja', 'Distinción fregeana entre el modo de presentación de un objeto (sentido) y el objeto mismo al que apunta una expresión (referencia).', '«Lucero del alba» y «estrella vespertina» tienen la misma referencia —Venus— pero distinto <b>sentido y referencia</b> en la teoría de Frege.'),
        ('metalenguaje', 'me.ta.len.ˈɡwa.xe', 'Lenguaje de orden superior que se usa para hablar o describir otro lenguaje —el lenguaje objeto— sin confundirse con él.', 'Cuando decimos que «gato» tiene cinco letras, usamos el español como <b>metalenguaje</b> para hablar sobre la palabra, no sobre el animal.'),
        ('enunciado performativo', 'e.nun.ˈθja.ðo peɾ.foɾ.ma.ˈti.βo', 'Enunciado que no describe una realidad sino que la constituye o realiza mediante su propia pronunciación en el contexto adecuado.', '«Los declaro marido y mujer» es un clásico <b>enunciado performativo</b> de Austin: no informa sobre un matrimonio, sino que lo instaura.'),
        ('hermenéutica', 'eɾ.me.ˈnew.ti.ka', 'Teoría y práctica de la interpretación de textos, discursos y acciones humanas, con especial atención al papel del contexto y la tradición.', 'La <b>hermenéutica</b> de Gadamer sostiene que toda interpretación está mediada por un horizonte histórico que no podemos abandonar del todo.'),
        ('juegos de lenguaje', 'ˈxwe.ɣos ðe len.ˈɡwa.xe', 'Concepto wittgensteiniano que designa las múltiples prácticas lingüísticas entretejidas con formas de vida, cada una con sus propias reglas.', 'Según Wittgenstein, la metafísica surge de confundir <b>juegos de lenguaje</b> distintos, tomando preguntas gramaticales por preguntas empíricas.'),
        ('actitud proposicional', 'ak.ˈti.tuð pɾo.po.si.θjo.ˈnal', 'Estado mental —creer, desear, temer, esperar— cuyo contenido es una proposición que el sujeto toma como objeto de su actitud.', 'Creer que va a llover y desear que llueva son <b>actitudes proposicionales</b> distintas hacia el mismo contenido representacional.'),
        ('indexicalidad', 'in.dek.si.ka.li.ˈðað', 'Propiedad de ciertos signos cuyo significado depende del contexto de uso, de modo que no pueden interpretarse sin conocer quién habla, cuándo y dónde.', 'La <b>indexicalidad</b> del pronombre «yo» hace que su referencia cambie con cada hablante, a diferencia de un nombre propio fijo.'),
        ('opacidad referencial', 'o.pa.ˈsi.ðað re.fe.ˈɾen.θjal', 'Propiedad de ciertos contextos lingüísticos donde no es posible sustituir expresiones correferentes sin alterar el valor de verdad del enunciado.', 'La <b>opacidad referencial</b> aparece en «Lois cree que Superman es débil»: no podemos sustituir «Superman» por «Clark Kent» sin cambiar el sentido.'),
        ('comunidad de habla', 'ko.mu.ni.ˈðað ðe ˈa.βla', 'Grupo social cuyos miembros comparten normas, actitudes y recursos lingüísticos comunes que los distinguen de otros grupos.', 'La sociolingüística estudia cómo la <b>comunidad de habla</b> regula variaciones estilísticas que marcan pertenencia, prestigio o exclusión.'),
    ]
)

CHAPTERS['pensamiento-critico-avanzado'] = dict(
    level='c2', num='V04', short='Pensamiento Crítico Avanzado',
    words=[
        ('reductio ad absurdum', 're.ˈðuk.tjo að aβ.ˈsuɾ.ðum', 'Estrategia argumentativa que refuta una tesis demostrando que sus consecuencias lógicas llevan a una contradicción o absurdo inaceptable.', 'El matemático aplicó la <b>reductio ad absurdum</b> al asumir que la raíz de dos era racional y derivar de ahí una imposibilidad lógica.'),
        ('pendiente resbaladiza', 'pen.ˈdjen.te res.βa.la.ˈði.θa', 'Falacia que afirma, sin justificación suficiente, que aceptar una medida menor inevitablemente conduce a consecuencias extremas indeseables.', 'Argumentar que legalizar el cannabis llevará inevitablemente al colapso social es un ejemplo claro de <b>pendiente resbaladiza</b> sin evidencia empírica.'),
        ('carga de la prueba', 'ˈkaɾ.ɣa ðe la ˈpɾwe.βa', 'Obligación que tiene quien formula una afirmación de aportar evidencia que la sustente, en lugar de exigir que otros demuestren su falsedad.', 'En epistemología, la <b>carga de la prueba</b> recae sobre quien afirma la existencia de algo extraordinario, no sobre quien lo pone en duda.'),
        ('hombre de paja', 'ˈom.bɾe ðe ˈpa.xa', 'Falacia que consiste en distorsionar o exagerar la posición del adversario para refutarla más fácilmente, en lugar de atacar el argumento real.', 'Decir que los ecologistas «quieren que volvamos a las cavernas» es un <b>hombre de paja</b> que evita debatir las propuestas ambientales concretas.'),
        ('falsa dicotomía', 'ˈfal.sa di.ko.to.ˈmi.a', 'Error argumentativo que presenta solo dos opciones como únicas posibles, ignorando alternativas intermedias o distintas que también existen.', '«O estás con nosotros o estás contra nosotros» es la <b>falsa dicotomía</b> favorita de la retórica belicista para suprimir posiciones matizadas.'),
        ('razonamiento motivado', 'ra.θo.na.ˈmjen.to mo.ti.ˈβa.ðo', 'Tendencia cognitiva a buscar y evaluar evidencia de manera sesgada para confirmar conclusiones previamente deseadas o creídas.', 'El <b>razonamiento motivado</b> explica por qué personas inteligentes pueden mantener creencias erróneas ante evidencia contraria abrumadora.'),
        ('burbuja epistémica', 'ˈbuɾ.βu.xa e.pis.ˈte.mi.ka', 'Entorno informativo cerrado en que solo circulan ideas afines, impidiendo el contacto con perspectivas alternativas o cuestionadoras.', 'Las redes sociales algorítmicas crean una <b>burbuja epistémica</b> que refuerza las convicciones previas en lugar de ampliar el horizonte cognitivo.'),
        ('navaja de Occam', 'na.ˈβa.xa ðe ˈo.kam', 'Principio metodológico que prescribe no multiplicar entidades más allá de lo necesario para explicar un fenómeno, favoreciendo la hipótesis más simple.', 'Ante dos teorías igualmente predictivas, la <b>navaja de Occam</b> recomienda preferir la que postula menos entidades o supuestos adicionales.'),
        ('falsabilidad', 'fal.sa.βi.li.ˈðað', 'Criterio popperiano de demarcación científica: una teoría es científica si puede ser refutada por algún experimento o dato observable concebible.', 'La astrología carece de <b>falsabilidad</b> porque sus predicciones son tan vagas que ningún resultado empírico podría demostrar su error.'),
        ('humildad intelectual', 'u.ˈmil.dað in.te.lek.ˈtwal', 'Disposición epistémica que reconoce los propios límites cognitivos, la posibilidad de error y la legitimidad del desacuerdo razonado.', 'La <b>humildad intelectual</b> no implica relativismo: permite sostener convicciones firmes mientras se permanece abierto a revisarlas con buena evidencia.'),
        ('injusticia epistémica', 'in.xus.ˈti.θja e.pis.ˈte.mi.ka', 'Daño que se inflige a alguien en su capacidad como sujeto de conocimiento, ya sea desacreditando su testimonio o privándole de recursos cognitivos.', 'Miranda Fricker describe la <b>injusticia epistémica</b> testimonial que ocurre cuando se descarta sistemáticamente la palabra de ciertos grupos sociales.'),
        ('razonamiento abductivo', 'ra.θo.na.ˈmjen.to aβ.ˈðuk.ti.βo', 'Forma de inferencia que elige la hipótesis más explicativa y plausible para dar cuenta de un conjunto de datos o evidencias observadas.', 'El diagnóstico médico es un ejercicio de <b>razonamiento abductivo</b>: el clínico selecciona la causa más probable entre varias que explicarían los síntomas.'),
    ]
)

CHAPTERS['historia-ideas'] = dict(
    level='c2', num='V05', short='Historia de las Ideas',
    words=[
        ('escolasticismo', 'es.ko.las.ti.ˈθiz.mo', 'Corriente filosófica y teológica medieval que intentó armonizar la razón aristotélica con la fe cristiana mediante el método disputacional.', 'El <b>escolasticismo</b> de Tomás de Aquino construyó una síntesis monumental entre la metafísica de Aristóteles y la teología del dogma cristiano.'),
        ('empirismo', 'em.pi.ˈɾiz.mo', 'Corriente filosófica que sostiene que el conocimiento procede exclusivamente de la experiencia sensible y no de principios innatos o a priori.', 'El <b>empirismo</b> de Hume llevó sus premisas hasta el límite: si todo conocimiento viene de los sentidos, la causalidad misma se vuelve cuestionable.'),
        ('racionalismo', 'ra.θjo.na.ˈliz.mo', 'Corriente filosófica que defiende que la razón, con independencia de la experiencia, puede alcanzar verdades necesarias y universales.', 'El <b>racionalismo</b> cartesiano parte de la duda metódica para encontrar en el «cogito» una certeza indubitable sobre la que reconstruir el saber.'),
        ('dialéctica', 'dja.ˈlek.ti.ka', 'Método de pensamiento que avanza mediante la contraposición de tesis y antítesis, cuya superación genera una síntesis en un nivel superior.', 'La <b>dialéctica</b> hegeliana del amo y el esclavo muestra cómo las contradicciones históricas se resuelven transformando la relación entre las partes.'),
        ('positivismo', 'po.si.ti.ˈβiz.mo', 'Corriente filosófica que limita el conocimiento legítimo al que puede ser verificado mediante métodos científicos y datos empíricos observables.', 'El <b>positivismo</b> de Comte ordenó las ciencias en una jerarquía que culminaba en la sociología como ciencia suprema de los hechos humanos.'),
        ('fenomenología', 'fe.no.me.no.lo.ˈxi.a', 'Método filosófico que describe rigurosamente la estructura de la experiencia consciente tal como se presenta, suspendiendo los supuestos previos.', 'La <b>fenomenología</b> de Husserl propone la «epojé» o reducción: poner entre paréntesis el mundo natural para estudiar los actos puros de conciencia.'),
        ('existencialismo', 'ek.sis.ten.θja.ˈliz.mo', 'Corriente filosófica que sitúa la existencia individual concreta como punto de partida y afirma que la esencia humana no está predeterminada.', 'El <b>existencialismo</b> sartreano resume su núcleo en «la existencia precede a la esencia»: el ser humano se define por sus elecciones, no por su naturaleza.'),
        ('estructuralismo', 'es.tɾuk.tu.ɾa.ˈliz.mo', 'Paradigma intelectual que analiza los fenómenos culturales, lingüísticos y sociales en términos de estructuras relacionales subyacentes e impersonales.', 'El <b>estructuralismo</b> de Lévi-Strauss aplicó el modelo fonológico saussureano al análisis de los mitos y los sistemas de parentesco.'),
        ('posmodernismo', 'pos.mo.ðeɾ.ˈniz.mo', 'Movimiento intelectual y cultural que cuestiona los grandes relatos legitimadores de la modernidad y celebra la pluralidad, la ironía y la hibridación.', 'El <b>posmodernismo</b> de Lyotard proclama el fin de los «metarrelatos» —progreso, emancipación, ciencia— que habían dado cohesión al proyecto ilustrado.'),
        ('deconstrucción', 'de.kons.tɾuk.ˈθjon', 'Práctica filosófico-textual derridiana que desestabiliza las oposiciones binarias de un texto mostrando cómo el término subordinado socava al dominante.', 'La <b>deconstrucción</b> de la oposición habla/escritura en Derrida revela que la escritura no es mera transcripción sino condición de posibilidad del habla.'),
        ('teoría crítica', 'te.o.ˈɾi.a ˈkɾi.ti.ka', 'Corriente de pensamiento de la Escuela de Fráncfort que analiza críticamente las formas de dominación social, cultural e ideológica de la modernidad.', 'La <b>teoría crítica</b> de Adorno y Horkheimer en la Dialéctica de la Ilustración muestra cómo la razón puede convertirse en instrumento de opresión.'),
        ('círculo hermenéutico', 'ˈθiɾ.ku.lo eɾ.me.ˈnew.ti.ko', 'Estructura circular de la comprensión, en que el todo se entiende desde sus partes y estas desde el todo, sin que haya punto de partida absoluto.', 'El <b>círculo hermenéutico</b> no es un defecto lógico sino la condición misma de toda interpretación: leer es un movimiento continuo entre parte y totalidad.'),
    ]
)

CHAPTERS['arte-contemporaneo'] = dict(
    level='c2', num='V06', short='Arte Contemporáneo',
    words=[
        ('arte conceptual', 'ˈaɾ.te kon.θep.ˈtwal', 'Modalidad artística en que la idea o concepto es la obra misma, desplazando la habilidad técnica o el objeto físico a un lugar secundario.', 'En el <b>arte conceptual</b>, la propuesta de Duchamp de exhibir un urinario como escultura desplazó el foco de la pericia manual al gesto intelectual.'),
        ('apropiación', 'a.pɾo.pja.ˈθjon', 'Estrategia artística que consiste en tomar imágenes, objetos o textos preexistentes y recontextualizarlos para producir un nuevo significado.', 'La <b>apropiación</b> de iconos publicitarios por Warhol cuestionó las fronteras entre alta cultura y cultura de masas desde dentro del propio mercado del arte.'),
        ('hiperrealidad', 'i.peɾ.re.a.li.ˈðað', 'Condición posmoderna en que los signos y simulaciones ya no remiten a ninguna realidad exterior, sino que se constituyen como la única realidad.', 'Baudrillard sostuvo que Disneylandia es el paradigma de la <b>hiperrealidad</b>: no imita el mundo real, sino que disimula que el mundo real ya no existe.'),
        ('simulacro', 'si.mu.ˈla.kɾo', 'Copia sin original; representación que sustituye completamente al referente real hasta el punto de que este deja de importar o existir.', 'Los mapas que generan el territorio, y no al revés, son para Baudrillard el modelo del <b>simulacro</b> que define la cultura mediática contemporánea.'),
        ('ironía posmoderna', 'i.ˈɾo.ni.a pos.mo.ˈðeɾ.na', 'Distanciamiento reflexivo y autoconsciente que adopta el arte contemporáneo respecto a sus propias convenciones, géneros y tradiciones.', 'La <b>ironía posmoderna</b> de Koons al exhibir perritos de globo en acero inoxidable celebra y critique simultáneamente el kitsch de consumo masivo.'),
        ('crítica institucional', 'ˈkɾi.ti.ka ins.ti.tu.θjo.ˈnal', 'Práctica artística que examina, problematiza y subvierte las condiciones sociales, económicas e ideológicas de las instituciones del mundo del arte.', 'La <b>crítica institucional</b> de Hans Haacke expuso en el propio museo la red de intereses financieros y políticos que sostenían su colección.'),
        ('estética relacional', 'es.ˈte.ti.ka re.la.θjo.ˈnal', 'Paradigma artístico teorizado por Bourriaud que considera la obra como productora de relaciones humanas y situaciones de encuentro colectivo.', 'Las obras de Tiravanija, que consisten en cocinar arroz para el público, son el ejemplo canónico de la <b>estética relacional</b> que disuelve la autoría en la convivencia.'),
        ('bioarte', 'bjo.ˈaɾ.te', 'Práctica artística que utiliza organismos vivos, tejidos, ADN u otros materiales biológicos como medio expresivo, planteando cuestiones éticas sobre la vida.', 'Eduardo Kac creó con ingeniería genética un conejo fluorescente para su proyecto de <b>bioarte</b>, detonando debates sobre manipulación de la vida y propiedad artística.'),
        ('net art', 'net ˈaɾt', 'Práctica artística nacida en los años noventa que usa internet como medio, espacio y concepto, cuestionando la autoría, la distribución y la permanencia.', 'El <b>net art</b> pionero de JODI.org convertía el código fuente en obra visible, confrontando al usuario con la arquitectura oculta de la web.'),
        ('détournement', 'de.tuɾ.ˈnɑ̃', 'Técnica situacionista que reutiliza elementos de la cultura dominante alterando su contexto y significado para volverlos contra el sistema que los produjo.', 'El <b>détournement</b> situacionista intervenía anuncios publicitarios insertando mensajes anticapitalistas que explotaban la misma seducción visual del original.'),
        ('culture jamming', 'ˈkal.tʃuɾ ˈdʒa.miŋ', 'Práctica activista que interfiere, parodia o subvierte los mensajes de la cultura de masas y la publicidad para revelar sus mecanismos ideológicos.', 'El <b>culture jamming</b> de Adbusters transforma logos corporativos en críticas al consumismo, devolviendo al espectador la agencia sobre los signos que le rodean.'),
        ('espectáculo', 'es.ˈpek.ta.ku.lo', 'Concepto debordiano que designa la forma de vida social en que las relaciones humanas se han reducido a relaciones entre imágenes mediadas y mercancías.', 'Guy Debord diagnosticó en 1967 que el <b>espectáculo</b> no es un conjunto de imágenes sino una relación social entre personas mediada por imágenes.'),
    ]
)
