# -*- coding: utf-8 -*-
"""French definitions for fr/ A1-B2 vocabulaire flashcards & match games.

Keyed by chapter slug -> word id -> French def (translation + gloss).
REPLACE maps slug -> id -> full replacement word dict (used to swap the
Spanish-track false-friends entries for francophone ones).
"""

DEFS = {

# ---------- A1 ----------

'animals': {
  'dog': 'chien — l’animal de compagnie le plus courant',
  'cat': 'chat — petit animal de compagnie au pelage doux',
  'bird': 'oiseau — animal à ailes qui vole',
  'fish': 'poisson — animal qui vit dans l’eau',
  'horse': 'cheval — grand animal que l’on peut monter',
  'cow': 'vache — animal de la ferme qui donne du lait',
  'chicken': 'poule / poulet — oiseau élevé pour ses œufs et sa viande',
  'rabbit': 'lapin — petit animal aux longues oreilles',
  'elephant': 'éléphant — très grand animal gris',
  'monkey': 'singe — animal qui grimpe aux arbres',
},

'clothes': {
  'shirt': 'chemise — vêtement porté sur le haut du corps',
  'trousers': 'pantalon — vêtement pour les jambes (toujours pluriel en anglais !)',
  'jacket': 'veste / blouson — manteau court porté sur d’autres vêtements',
  'shoes': 'chaussures — ce que l’on porte aux pieds',
  'dress': 'robe — vêtement féminin couvrant le corps et les jambes',
  'hat': 'chapeau — couvre-chef porté sur la tête',
  'socks': 'chaussettes — portées aux pieds, dans les chaussures',
  'coat': 'manteau — long vêtement chaud porté dehors',
  'jeans': 'jean — pantalon décontracté en toile denim (pluriel en anglais)',
  'scarf': 'écharpe / foulard — tissu porté autour du cou',
},

'colours': {
  'red': 'rouge — la couleur du feu ou du sang',
  'blue': 'bleu — la couleur du ciel',
  'green': 'vert — la couleur de l’herbe',
  'yellow': 'jaune — une couleur vive comme le soleil',
  'black': 'noir — la couleur la plus sombre',
  'white': 'blanc — la couleur la plus claire',
  'orange': 'orange — entre le rouge et le jaune',
  'purple': 'violet — mélange sombre de rouge et de bleu',
  'brown': 'marron / brun — la couleur de la terre ou du bois',
  'pink': 'rose — un rouge clair',
},

'daily-routine': {
  'wake up': 'se réveiller — arrêter de dormir',
  'get dressed': 's’habiller — mettre ses vêtements',
  'have breakfast': 'prendre le petit-déjeuner (have, pas take !)',
  'go to school': 'aller à l’école',
  'have lunch': 'déjeuner — prendre le repas de midi',
  'do homework': 'faire ses devoirs (do, pas make !)',
  'have dinner': 'dîner — prendre le repas du soir',
  'watch TV': 'regarder la télé (watch, pas look at !)',
  'go to bed': 'aller se coucher',
  'brush teeth': 'se brosser les dents',
},

'family': {
  'mother': 'mère — le parent féminin',
  'father': 'père — le parent masculin',
  'brother': 'frère — un garçon de la même famille',
  'sister': 'sœur — une fille de la même famille',
  'grandmother': 'grand-mère — la mère de ton père ou de ta mère',
  'grandfather': 'grand-père — le père de ton père ou de ta mère',
  'cousin': 'cousin / cousine — l’enfant de ton oncle ou de ta tante',
  'aunt': 'tante — la sœur de ton père ou de ta mère',
  'uncle': 'oncle — le frère de ton père ou de ta mère',
  'parents': 'parents — ta mère et ton père seulement (les proches = relatives !)',
},

'food': {
  'bread': 'pain — aliment cuit à base de farine (indénombrable en anglais)',
  'apple': 'pomme — fruit rond, rouge ou vert',
  'chicken': 'poulet — la viande de poulet',
  'rice': 'riz — petits grains blancs ou bruns (indénombrable)',
  'coffee': 'café — boisson chaude et sombre',
  'water': 'eau — liquide transparent que l’on boit',
  'salad': 'salade — plat froid de légumes crus',
  'pasta': 'pâtes — aliment italien à base de farine et d’eau (singulier en anglais !)',
  'milk': 'lait — liquide blanc produit par les vaches',
  'orange': 'orange — agrume rond et juteux',
},

'hobbies': {
  'reading': 'la lecture — lire des livres pour le plaisir',
  'swimming': 'la natation — nager pour le sport ou le loisir',
  'cooking': 'la cuisine — préparer des plats',
  'cycling': 'le vélo — se déplacer à bicyclette',
  'dancing': 'la danse — bouger son corps en musique',
  'drawing': 'le dessin — faire des images au crayon',
  'gardening': 'le jardinage — cultiver plantes et fleurs',
  'photography': 'la photographie — prendre des photos',
  'travelling': 'les voyages — découvrir d’autres endroits',
  'music': 'la musique — jouer ou écouter des sons musicaux',
},

'house-and-rooms': {
  'kitchen': 'cuisine — la pièce où l’on prépare les repas',
  'bedroom': 'chambre — la pièce où l’on dort',
  'bathroom': 'salle de bains — la pièce avec douche et toilettes',
  'living room': 'salon — la pièce où la famille se détend',
  'garden': 'jardin — espace extérieur avec plantes et pelouse',
  'hall': 'entrée / couloir — l’espace derrière la porte d’entrée',
  'stairs': 'escalier — les marches entre deux étages (pluriel en anglais)',
  'window': 'fenêtre — ouverture vitrée dans un mur',
  'door': 'porte — l’entrée que l’on ouvre pour passer',
  'shelf': 'étagère — planche fixée au mur pour ranger',
},

'jobs': {
  'teacher': 'professeur — personne qui enseigne à l’école',
  'doctor': 'médecin — personne qui soigne les malades',
  'nurse': 'infirmier / infirmière — personne qui soigne les patients à l’hôpital',
  'chef': 'cuisinier professionnel — le « chef » français se dit boss !',
  'police officer': 'policier / policière — personne qui fait respecter la loi',
  'engineer': 'ingénieur — personne qui conçoit machines ou bâtiments',
  'driver': 'chauffeur / conducteur — personne qui conduit un véhicule',
  'farmer': 'agriculteur — personne qui cultive la terre',
  'waiter': 'serveur — personne qui sert au restaurant',
  'firefighter': 'pompier — personne qui éteint les incendies',
},

'numbers-and-time': {
  'minute': 'minute — soixante secondes',
  'hour': 'heure — soixante minutes (avec un h muet : an hour !)',
  'day': 'jour — une période de vingt-quatre heures',
  'week': 'semaine — une période de sept jours',
  'month': 'mois — une des douze parties de l’année',
  'year': 'année — trois cent soixante-cinq jours',
  'today': 'aujourd’hui — ce jour-ci',
  'tomorrow': 'demain — le jour suivant',
  'yesterday': 'hier — le jour précédent',
  'now': 'maintenant — en ce moment même',
},

'places-in-town': {
  'supermarket': 'supermarché — grand magasin d’alimentation',
  'school': 'école — le lieu où les enfants apprennent',
  'hospital': 'hôpital — le lieu où l’on soigne les malades',
  'park': 'parc — espace vert avec pelouses et arbres',
  'bank': 'banque — l’endroit où l’on garde son argent',
  'library': 'bibliothèque — FAUX AMI : pas « librairie » (= bookshop) !',
  'restaurant': 'restaurant — l’endroit où l’on paie pour manger',
  'station': 'gare — l’endroit où s’arrêtent les trains',
  'post office': 'bureau de poste — pour envoyer lettres et colis',
  'café': 'café — petit établissement pour boire et manger',
},

'weather': {
  'sunny': 'ensoleillé — avec beaucoup de soleil',
  'rainy': 'pluvieux — avec beaucoup de pluie',
  'cold': 'froid — à basse température',
  'hot': 'chaud — à haute température',
  'cloudy': 'nuageux — avec beaucoup de nuages',
  'windy': 'venteux — avec un vent fort',
  'snow': 'neige — eau gelée blanche qui tombe du ciel',
  'fog': 'brouillard — nuage épais au niveau du sol',
  'warm': 'doux / tiède — agréablement chaud',
  'temperature': 'température — la mesure du chaud et du froid',
},

# ---------- A2 ----------

'cooking': {
  'boil': 'faire bouillir — chauffer l’eau jusqu’aux bulles',
  'fry': 'faire frire / revenir — cuire dans l’huile chaude',
  'bake': 'cuire au four — pour le pain, les gâteaux',
  'chop': 'hacher / couper — en petits morceaux',
  'stir': 'remuer — tourner avec une cuillère',
  'recipe': 'recette — les instructions pour cuisiner un plat',
  'ingredient': 'ingrédient — un élément d’une recette',
  'oven': 'four — l’appareil fermé où l’on fait cuire',
  'pan': 'poêle / casserole — récipient de cuisson en métal',
  'slice': 'couper en tranches — en morceaux plats et fins',
},

'feelings-emotions': {
  'excited': 'enthousiaste / impatient — FAUX AMI : pas « excité » !',
  'worried': 'inquiet — qui se fait du souci',
  'disappointed': 'déçu — triste parce que quelque chose n’a pas eu lieu',
  'proud': 'fier — content d’une réussite',
  'nervous': 'nerveux / anxieux — inquiet avant un événement',
  'confused': 'perdu / désorienté — qui ne comprend pas',
  'surprised': 'surpris — qui ne s’y attendait pas',
  'lonely': 'seul et triste — la solitude qui pèse (≠ alone, simple fait d’être seul)',
  'relaxed': 'détendu — calme et sans inquiétude',
  'jealous': 'jaloux — qui veut ce que les autres ont',
},

'health-and-body': {
  'headache': 'mal de tête — douleur à la tête',
  'fever': 'fièvre — température du corps trop élevée',
  'appointment': 'rendez-vous (médical) — pas « appointements » !',
  'medicine': 'médicament — substance qui soigne',
  'symptom': 'symptôme — un signe de maladie',
  'recover': 'guérir / se rétablir — aller mieux après une maladie',
  'surgery': 'opération chirurgicale — aussi : cabinet médical en anglais britannique',
  'allergy': 'allergie — mauvaise réaction du corps à quelque chose',
  'prescription': 'ordonnance — le papier du médecin pour les médicaments',
  'diet': 'alimentation / régime — ce qu’une personne mange habituellement',
},

'music': {
  'guitar': 'guitare — instrument à cordes que l’on gratte',
  'piano': 'piano — grand instrument à clavier',
  'drums': 'batterie — instruments que l’on frappe avec des baguettes',
  'concert': 'concert — un spectacle de musique en direct',
  'band': 'groupe (de musique) — des musiciens qui jouent ensemble',
  'lyrics': 'paroles — les mots d’une chanson (pluriel en anglais)',
  'melody': 'mélodie — un air, une suite de notes',
  'rhythm': 'rythme — un motif sonore régulier et répété',
  'classical': 'classique — la musique traditionnelle savante',
  'choir': 'chorale / chœur — un groupe de chanteurs (prononcé « kwaïeur » !)',
},

'problems-solutions': {
  'problem': 'problème — une situation difficile',
  'solution': 'solution — la réponse à un problème',
  'mistake': 'erreur / faute — quelque chose de mal fait',
  'fix': 'réparer — remettre en état (familier et courant)',
  'complain': 'se plaindre — dire qu’on n’est pas content',
  'advice': 'conseils — indénombrable : un conseil = a piece of advice !',
  'repair': 'réparer — faire fonctionner à nouveau',
  'emergency': 'urgence — situation grave et inattendue',
  'accident': 'accident — événement malheureux et imprévu',
  'apologise': 's’excuser — dire pardon (apologise, pas « excuse myself » !)',
},

'school-subjects': {
  'textbook': 'manuel scolaire — le livre utilisé en classe',
  'homework': 'devoirs — le travail scolaire à la maison (indénombrable !)',
  'subject': 'matière — une discipline comme les maths ou l’histoire',
  'lesson': 'cours / leçon — une période d’enseignement',
  'exam': 'examen — passer un examen = take an exam (pas pass, qui veut dire réussir !)',
  'teacher': 'professeur — la personne qui enseigne',
  'classroom': 'salle de classe — la pièce où l’on étudie',
  'term': 'trimestre — une période de l’année scolaire',
  'grade': 'note — l’évaluation d’un travail scolaire',
  'university': 'université — l’enseignement supérieur',
},

'shopping-and-money': {
  'receipt': 'ticket de caisse / reçu — la preuve d’un achat (le p est muet !)',
  'discount': 'remise / réduction — une baisse de prix',
  'refund': 'remboursement — l’argent rendu après un retour',
  'currency': 'devise / monnaie — l’argent utilisé dans un pays',
  'budget': 'budget — un plan de dépenses',
  'checkout': 'caisse — l’endroit où l’on paie dans un magasin',
  'bargain': 'bonne affaire — quelque chose acheté pas cher',
  'invoice': 'facture — la note à payer pour des biens ou services',
  'afford': 'avoir les moyens de — pouvoir se payer quelque chose',
  'cash': 'espèces / liquide — l’argent en pièces et billets',
},

'sports': {
  'tennis': 'tennis — jeu de raquettes et de balle',
  'basketball': 'basket — jeu de ballon et de panier en hauteur',
  'athletics': 'athlétisme — course, saut, lancer',
  'gymnastics': 'gymnastique — exercices et figures sur agrès',
  'skiing': 'ski — glisser sur la neige avec de longues planches',
  'golf': 'golf — jeu de clubs et de petite balle',
  'volleyball': 'volley — jeu d’équipe avec un filet',
  'score': 'marquer — obtenir un point dans un match',
  'match': 'match — une rencontre entre deux équipes',
  'team': 'équipe — un groupe qui joue ensemble',
},

'technology-and-media': {
  'download': 'télécharger — copier des données depuis internet',
  'account': 'compte — un profil personnel sur un service',
  'password': 'mot de passe — le mot secret pour se connecter',
  'search engine': 'moteur de recherche — l’outil pour chercher en ligne',
  'update': 'mise à jour — une nouvelle version d’un logiciel',
  'wireless': 'sans fil — connecté sans câbles',
  'screen': 'écran — la surface d’affichage d’un appareil',
  'upload': 'téléverser / mettre en ligne — envoyer des données vers internet',
  'subscribe': 's’abonner — payer régulièrement pour un service',
  'battery': 'batterie / pile — la source d’énergie d’un appareil',
},

'transport-and-travel': {
  'departure': 'départ — l’heure à laquelle un véhicule part',
  'arrival': 'arrivée — l’heure à laquelle un véhicule arrive',
  'platform': 'quai — l’endroit où l’on monte dans le train',
  'ticket': 'billet / ticket — le titre de transport',
  'luggage': 'bagages — valises et sacs (indénombrable en anglais !)',
  'flight': 'vol — un voyage en avion',
  'border': 'frontière — la ligne entre deux pays',
  'passenger': 'passager — une personne qui voyage dans un véhicule',
  'timetable': 'horaires — le tableau des heures de transport',
  'customs': 'douane — le contrôle des marchandises à la frontière',
},

'weather-detail': {
  'foggy': 'brumeux — quand le brouillard gêne la visibilité',
  'storm': 'tempête / orage — très mauvais temps avec vent et pluie',
  'thunder': 'tonnerre — le bruit fort pendant l’orage',
  'lightning': 'éclair / foudre — la lumière soudaine de l’orage',
  'freezing': 'glacial — extrêmement froid',
  'boiling': 'étouffant — extrêmement chaud (familier)',
  'humid': 'humide — un air chaud et chargé d’eau',
  'breeze': 'brise — un vent léger et agréable',
  'forecast': 'prévisions (météo) — l’annonce du temps à venir',
  'shower': 'averse — une courte période de pluie (aussi : douche !)',
},

'work-and-jobs': {
  'salary': 'salaire — l’argent versé régulièrement pour un travail',
  'interview': 'entretien (d’embauche) — le rendez-vous pour obtenir un poste',
  'colleague': 'collègue — une personne avec qui l’on travaille',
  'office': 'bureau — le lieu de travail (le meuble se dit desk !)',
  'manager': 'responsable / chef — la personne qui dirige une équipe',
  'experience': 'expérience — les compétences acquises en travaillant',
  'part-time': 'à temps partiel — travailler moins que l’horaire complet',
  'unemployed': 'au chômage — sans emploi',
  'retire': 'prendre sa retraite — arrêter définitivement de travailler',
  'promotion': 'promotion — le passage à un poste supérieur',
},

# ---------- B1 ----------

'adjective-preposition': {
  'interested in': 'intéressé par — avoir envie de découvrir ou d’apprendre',
  'good at': 'doué en/pour — avoir la capacité de bien faire quelque chose',
  'bad at': 'mauvais en — ne pas être doué pour quelque chose',
  'afraid of': 'avoir peur de — éprouver de la crainte',
  'angry with': 'en colère contre quelqu’un (with, pas against !)',
  'tired of': 'fatigué de, lassé de — en avoir assez de quelque chose',
  'proud of': 'fier de — être satisfait d’une réussite',
  'worried about': 'inquiet pour/de — se faire du souci à propos de',
  'similar to': 'semblable à — qui ressemble à (to, pas que !)',
  'different from': 'différent de — qui n’est pas pareil (from, pas of)',
  'focused on': 'concentré sur — qui porte son attention sur',
  'aware of': 'conscient de — qui sait, qui est au courant de',
},

'collocations-make-do': {
  'make a decision': 'prendre une décision (make, pas take !) — choisir après réflexion',
  'make a mistake': 'faire une erreur — se tromper',
  'make progress': 'faire des progrès — avancer, s’améliorer',
  'make a difference': 'changer les choses — avoir un effet positif',
  'make money': 'gagner de l’argent (make, pas win !)',
  'make friends': 'se faire des amis — nouer des amitiés',
  'do homework': 'faire ses devoirs — le travail scolaire à la maison',
  'do exercise': 'faire de l’exercice — avoir une activité physique',
  'do your best': 'faire de son mieux — essayer le plus possible',
  'do research': 'faire des recherches — étudier, enquêter',
  'do a favour': 'rendre un service (do, pas make !)',
  'do well': 'bien réussir — obtenir de bons résultats',
},

'education-school': {
  'Curriculum': 'le programme scolaire — l’ensemble des matières enseignées',
  'Semester': 'le semestre — une période d’études d’environ six mois',
  'Deadline': 'la date limite, l’échéance — le délai à respecter',
  'Graduation': 'la remise des diplômes — la cérémonie de fin d’études',
  'Diploma': 'le diplôme — le certificat obtenu en fin de formation',
  'Tuition': 'les frais de scolarité — le coût des études',
  'Essay': 'la rédaction, la dissertation — un écrit sur un sujet donné',
  'Exam': 'l’examen — une épreuve qui évalue les connaissances',
  'Textbook': 'le manuel scolaire — le livre d’une matière',
  'Lecture': 'le cours magistral, la conférence — faux ami : pas « la lecture » !',
  'Grade': 'la note — le résultat d’un travail scolaire',
  'Attend': 'assister à, fréquenter — faux ami : pas « attendre » !',
},

'environment-nature': {
  'forest': 'la forêt — une grande étendue couverte d’arbres',
  'desert': 'le désert — une zone très sèche, presque sans végétation',
  'mountain': 'la montagne — un relief très élevé',
  'valley': 'la vallée — une zone basse entre des montagnes',
  'waterfall': 'la cascade, la chute d’eau',
  'river': 'le fleuve, la rivière — un grand cours d’eau',
  'drought': 'la sécheresse — une longue période sans pluie',
  'flood': 'l’inondation — l’eau qui déborde sur les terres',
  'habitat': 'l’habitat — le milieu naturel d’une espèce',
  'biodiversity': 'la biodiversité — la variété des êtres vivants d’un milieu',
  'pollution': 'la pollution — la contamination de l’environnement',
  'species': 'l’espèce — un groupe d’êtres vivants apparentés (singulier ET pluriel)',
  'ecosystem': 'l’écosystème — une communauté d’êtres vivants et leur milieu',
  'predator': 'le prédateur — un animal qui chasse d’autres animaux',
},

'phrasal-verbs-get-take': {
  'get up': 'se lever — sortir du lit',
  'get on': 'bien s’entendre (avec qqn) ; monter (dans un véhicule)',
  'get away': 's’échapper ; partir en vacances',
  'get back': 'rentrer, revenir',
  'get off': 'descendre (d’un véhicule)',
  'take off': 'enlever (un vêtement) ; décoller (avion)',
  'take on': 'accepter, assumer (une responsabilité)',
  'take over': 'prendre le contrôle, reprendre',
  'take part': 'participer — take part in = participer à',
  'take out': 'sortir, retirer ; inviter quelqu’un (à sortir)',
},

'phrasal-verbs-go-come': {
  'go_on': 'continuer ; se passer (What’s going on ? = Que se passe-t-il ?)',
  'go_through': 'traverser (une épreuve) ; vérifier soigneusement',
  'go_off': 'sonner (alarme) ; tourner (nourriture)',
  'go_ahead': 'aller de l’avant — poursuivre un projet',
  'come_across': 'tomber sur — trouver ou rencontrer par hasard',
  'come_up': 'survenir, être mentionné',
  'come_up_with': 'trouver, inventer (une idée, une solution)',
  'come_round': 'passer (chez quelqu’un) ; changer d’avis',
  'Come back': 'revenir — retourner à un endroit ou une activité',
  'Go without': 'se passer de — vivre sans quelque chose',
},

'sport-leisure': {
  'champ': 'le championnat — la compétition qui désigne le meilleur',
  'ref': 'l’arbitre — l’officiel qui fait respecter les règles',
  'spec': 'le spectateur — celui qui regarde l’épreuve',
  'pb': 'le record personnel — sa meilleure performance',
  'take_up': 'se mettre à — commencer un nouveau sport ou loisir',
  'ts': 'l’esprit d’équipe — la solidarité au sein d’un groupe',
  'draw': 'le match nul — une rencontre à égalité',
  'comp': 'concourir, être en compétition',
  'Personal trainer': 'le coach sportif — le professionnel qui encadre l’entraînement',
  'Warm up': 's’échauffer — préparer son corps avant l’effort',
  'Defend': 'défendre — protéger son but, empêcher l’adversaire de marquer',
  'Division': 'la division — un groupe d’équipes de même niveau',
},

'technology-media': {
  'dl': 'télécharger (depuis internet vers son appareil)',
  'ul': 'mettre en ligne, téléverser (vers internet)',
  'stream': 'regarder/écouter en streaming — en direct sur internet',
  'viral': 'devenir viral — se diffuser massivement en ligne',
  'algo': 'l’algorithme — les règles qui choisissent ce que vous voyez en ligne',
  'st': 'le temps d’écran — le temps passé devant les écrans',
  'cc': 'le créateur de contenu — il produit vidéos, posts ou podcasts',
  'se': 'le moteur de recherche — le programme qui explore internet',
  'Hack': 'pirater — s’introduire illégalement dans un système informatique',
  'Notification': 'la notification — l’alerte automatique d’une application',
},

'travel-holidays': {
  'Accommodation': 'l’hébergement, le logement — toujours singulier en anglais !',
  'Itinerary': 'l’itinéraire — le programme détaillé d’un voyage',
  'Jet lag': 'le décalage horaire — la fatigue après un long vol',
  'Currency': 'la devise, la monnaie — l’argent d’un pays',
  'Departure': 'le départ — le moment où l’on part',
  'Destination': 'la destination — l’endroit où l’on va',
  'Souvenir': 'le souvenir (objet rapporté) — pas le souvenir-mémoire (memory) !',
  'Round trip': 'l’aller-retour — un voyage avec retour au point de départ',
  'Sightseeing': 'le tourisme, la visite — go sightseeing = visiter les sites',
  'Cruise': 'la croisière — des vacances en bateau d’escale en escale',
  'Booking': 'la réservation — d’un hôtel, d’un transport, d’un spectacle',
  'Guide': 'le/la guide — la personne qui fait visiter',
},

'word-families-basic': {
  'decide': 'la décision — le nom formé sur decide',
  'happy': 'le bonheur — le nom formé sur happy (-ness)',
  'create': 'créatif — l’adjectif formé sur create',
  'compete': 'la compétition — le nom formé sur compete',
  'achieve': 'la réussite, l’accomplissement — le nom formé sur achieve',
  'pollute': 'la pollution — le nom formé sur pollute',
  'succeed': 'le succès, la réussite — le nom formé sur succeed',
  'develop': 'le développement — le nom formé sur develop',
  'Act / action / active': 'agir / l’action / actif — le verbe, le nom et l’adjectif d’une même racine',
  'Create / creative / creativity': 'créer / créatif / la créativité — la famille du mot create',
  'Educate / education / educated': 'éduquer / l’éducation / instruit — la famille du mot educate',
  'Help / helpful / helpfulness': 'aider / serviable / la serviabilité — la famille du mot help',
},

# ---------- B2 ----------

'collocations-adj-noun': {
  'se': 'des preuves solides — strong evidence (jamais powerful)',
  'si': 'une forte hausse — sharp increase : brutale et marquée',
  'dc': 'une vive inquiétude — deep concern (jamais big)',
  'hi2': 'un chômage élevé — high unemployment (jamais big)',
  'cr': 'un rôle crucial — une fonction extrêmement importante',
  'br': 'un large éventail — broad range (jamais big)',
  'wi': 'des inégalités généralisées — qui touchent de nombreux domaines',
  'mb': 'une avancée majeure — une découverte très importante',
  'Sharp rise': 'une hausse brutale — une augmentation soudaine et marquée',
  'Wide variety': 'une grande variété — de nombreux types différents',
  'High demand': 'une forte demande — très recherché (in high demand)',
},

'collocations-verbs': {
  'mc': 's’engager — make a commitment : promettre de se consacrer à',
  'ta': 'agir, passer à l’action — take action (jamais make)',
  'hi': 'avoir un impact — have an impact on (jamais make an impact on... attention)',
  'cor': 'mener des recherches — carry out research (jamais make)',
  'ra': 'parvenir à un accord — reach an agreement',
  'rais': 'sensibiliser — raise awareness : faire prendre conscience au public',
  'tr': 'assumer la responsabilité — take responsibility for',
  'dd': 'causer des dégâts — do damage (jamais make)',
  'Bear in mind': 'garder à l’esprit — ne pas oublier un élément important',
  'Rise to the challenge': 'se montrer à la hauteur — relever le défi',
  'Go hand in hand': 'aller de pair — deux choses étroitement liées',
  'Take hold of': 's’emparer de — saisir fermement, prendre le contrôle',
},

'environment-climate': {
  'ce': 'les émissions de carbone — le CO2 rejeté dans l’atmosphère',
  'biod': 'la biodiversité — la variété du vivant dans un milieu',
  'renew': 'les énergies renouvelables — soleil, vent, sources inépuisables',
  'ff': 'les énergies fossiles — charbon, pétrole et gaz',
  'nz': 'la neutralité carbone — équilibre entre émissions et absorption',
  'gg': 'les gaz à effet de serre — ils retiennent la chaleur terrestre',
  'cc': 'la crise climatique — la menace urgente du changement climatique',
  'sd': 'le développement durable — répondre aux besoins d’aujourd’hui sans compromettre demain',
  'Carbon footprint': 'l’empreinte carbone — le total des émissions d’une personne ou organisation',
  'Sea level rise': 'la montée des eaux — l’élévation du niveau des océans',
  'Climate sceptic': 'le climatosceptique — il met en doute le consensus scientifique',
  'Ecosystem': 'l’écosystème — une communauté d’êtres vivants et leur milieu',
},

'expressions-idioms': {
  'lr': 'à long terme, à la longue — in the long run',
  'mot': 'une question de temps — ce qui finira forcément par arriver',
  'tia': 'prendre en compte — take into account : considérer un facteur',
  'ghih': 'aller de pair — être étroitement liés',
  'mem': 'joindre les deux bouts — gagner juste assez pour vivre',
  'fsof': 'ne pas être à la hauteur de — rester en deçà d’un objectif',
  'cttw': 'se faire une raison, accepter — come to terms with',
  'ovo': 'au bord de, sur le point de — on the verge of',
  'Bite off more than you can chew': 'avoir les yeux plus gros que le ventre — accepter plus qu’on ne peut gérer',
  'In the same ballpark': 'du même ordre de grandeur — à peu près comparable',
  'Cut corners': 'rogner sur la qualité — bâcler pour aller vite ou économiser',
  'See the big picture': 'avoir une vue d’ensemble — voir au-delà des détails',
},

'false-friends': {
  'actual': 'en fait, en réalité — PAS « actuellement » (= currently) !',
  'sensible': 'raisonnable, sensé — PAS « sensible » (= sensitive) !',
  'eventually': 'finalement, à terme — PAS « éventuellement » (= possibly) !',
  'affect': 'affecter, avoir un effet sur — affect est le VERBE',
  'effect': 'l’effet, le résultat — effect est le NOM',
  'raise': 'lever, augmenter (transitif — exige un complément)',
  'rise': 'monter, augmenter (intransitif — sans complément)',
  'remind': 'rappeler quelque chose À quelqu’un — remember = se souvenir',
},

'health-lifestyle': {
  'wb': 'le bien-être — l’état de confort physique et mental',
  'nutr': 'la nutrition — l’apport des bons aliments et nutriments',
  'sed': 'la sédentarité — un mode de vie avec très peu d’activité physique',
  'bo': 'le burn-out, l’épuisement professionnel — causé par un stress prolongé',
  'wlb': 'l’équilibre vie pro / vie perso — du temps pour le travail ET pour soi',
  'mh': 'la santé mentale — l’état psychologique et émotionnel',
  'prev': 'une maladie évitable — qu’une bonne hygiène de vie peut prévenir',
  'hc': 'le système de santé — l’offre de soins d’un pays',
  'Wellbeing': 'le bien-être — se sentir bien, en bonne santé et heureux',
  'Immune system': 'le système immunitaire — la défense naturelle du corps',
},

'phrasal-verbs-look-bring': {
  'li': 'examiner, enquêter sur — look into a matter',
  'la': 's’occuper de, garder — look after someone',
  'lft': 'attendre avec impatience — look forward to + -ing !',
  'lof': 'guetter, faire attention à — look out for',
  'ba': 'provoquer, entraîner — bring about change',
  'bu': 'aborder (un sujet) ; élever (un enfant)',
  'bin': 'introduire (une loi, une règle, un système)',
  'bd': 'faire baisser ; faire tomber (un gouvernement, des prix)',
  'Look down on': 'mépriser, regarder de haut — juger inférieur',
},

'phrasal-verbs-put-set': {
  'put_off': 'reporter, remettre à plus tard — postpone',
  'put_up_with': 'supporter, tolérer — quelque chose de désagréable',
  'put_fwd': 'avancer, proposer — une idée ou un projet',
  'put_aside': 'mettre de côté — économiser de l’argent ou du temps',
  'set_up': 'créer, fonder — une entreprise, un système',
  'set_back': 'retarder — freiner la progression',
  'set_off': 'se mettre en route ; déclencher (une alarme)',
  'set_out': 'exposer en détail ; partir avec un objectif',
  'Set aside': 'réserver, mettre de côté ; laisser de côté provisoirement',
},

'phrasal-verbs-turn-run': {
  'td': 'refuser, décliner — turn down an offer ; baisser (le volume)',
  'tu': 'arriver, se pointer — souvent à l’improviste',
  'to': 's’avérer — it turned out that... = il s’est avéré que...',
  'ti': 'se transformer en, devenir',
  'roo': 'être à court de — ne plus avoir de',
  'ri': 'croiser (par hasard) ; rencontrer (un problème)',
  'rth': 'passer en revue, répéter rapidement',
  'ru': 'accumuler (une dette, une grosse facture)',
},

'society-culture': {
  'ineq': 'l’inégalité — des écarts injustes de statut ou de ressources',
  'discrim': 'la discrimination — un traitement injuste selon l’origine, le genre, l’âge...',
  'divers': 'la diversité — la présence de profils variés',
  'mob': 'la mobilité sociale — pouvoir changer de classe sociale',
  'prej': 'le préjugé — une opinion injuste formée sans connaître',
  'coh': 'la cohésion — la qualité d’un groupe uni et solidaire',
  'stigma': 'la stigmatisation — la marque d’infamie liée à une situation',
  'integ': 'l’intégration — réunir des groupes différents en une société',
  'Stereotype': 'le stéréotype — une image figée et simpliste d’un groupe',
  'Informal economy': 'l’économie informelle — l’activité non déclarée, hors régulation',
  'Generation gap': 'le fossé des générations — l’écart de valeurs entre jeunes et aînés',
},

'technology-innovation': {
  'ai': 'l’intelligence artificielle — des machines qui accomplissent des tâches humaines',
  'auto': 'l’automatisation — faire faire les tâches par la technologie',
  'cyber': 'la cybersécurité — protéger les systèmes des attaques numériques',
  'dp': 'la confidentialité des données — contrôler l’usage de ses informations',
  'df': 'l’empreinte numérique — les traces laissées en ligne',
  'disrupt': 'une technologie de rupture — elle bouleverse un secteur entier',
  'algo': 'l’algorithme — les règles de traitement d’un programme',
  'redund': 'le licenciement économique — la suppression d’un poste',
  'Scale up': 'passer à l’échelle supérieure — augmenter la taille ou la capacité',
  'User experience': 'l’expérience utilisateur — le ressenti à l’usage d’un produit',
  'Seamless': 'fluide, sans accroc — sans interruption ni problème',
},

'word-formation-adjectives': {
  'sust': 'durable — l’adjectif de sustain : qui peut se maintenir sans dommage',
  'innov': 'innovant — l’adjectif de innovate : qui introduit des idées nouvelles',
  'env': 'environnemental — l’adjectif de environment',
  'unrel': 'peu fiable — adjectif négatif : sur qui on ne peut pas compter',
  'irresp': 'irresponsable — adjectif négatif : qui manque de sérieux',
  'ineff': 'inefficace — adjectif négatif : qui ne produit pas le résultat voulu',
  'access': 'accessible — l’adjectif de access : facile d’accès ou d’usage',
  'afford': 'inabordable — adjectif négatif : trop cher pour être acheté',
  'Relentless': 'implacable, incessant — qui ne faiblit jamais',
  'Meticulous': 'méticuleux — extrêmement soigneux et précis',
  'Indispensable': 'indispensable — dont on ne peut absolument pas se passer',
  'Compelling': 'captivant, convaincant — impossible à ignorer',
},

'word-formation-nouns': {
  'aw': 'la conscience, la sensibilisation — le nom formé sur aware',
  'ineq2': 'l’inégalité — equal + préfixe négatif in- + suffixe -ity',
  'auto': 'l’automatisation — le nom formé sur automate',
  'div': 'la diversité — le nom formé sur diverse',
  'sust': 'la durabilité — le nom formé sur sustain',
  'commit': 'l’engagement — le nom formé sur commit',
  'innov': 'l’innovation — le nom formé sur innovate',
  'discrim': 'la discrimination — le nom formé sur discriminate',
  'Breakthrough': 'la percée, l’avancée décisive — la découverte qui change tout',
  'Backlash': 'le retour de bâton — une vive réaction négative du public',
  'Pitfall': 'le piège, l’écueil — une difficulté cachée',
  'Threshold': 'le seuil — le niveau à partir duquel quelque chose se déclenche',
},

'word-formation-prefixes': {
  'under': 'sous- (insuffisant) — underpaid = sous-payé',
  'over': 'sur- (excessif) — overworked = surmené',
  'mis': 'mal- (incorrectement) — misunderstand = mal comprendre',
  're': 're- (à nouveau) — rebuild = reconstruire',
  'pre': 'pré- (avant) — prepay = payer d’avance',
  'out': 'sur- (dépasser les autres) — outperform = surpasser',
  'inter': 'inter- (entre) — international = entre les nations',
  'dis': 'dé-/dis- (contraire) — disagree = ne pas être d’accord',
  'Mismanage': 'mal gérer — gérer de façon incompétente',
  'Overrated': 'surestimé, surcoté — qui ne mérite pas sa réputation',
  'Underestimate': 'sous-estimer — croire moindre que la réalité',
  'Counteract': 'contrer, neutraliser — agir contre des effets nocifs',
},

'work-careers': {
  'ent': 'l’entrepreneur — il crée et dirige sa propre entreprise',
  'red': 'le licenciement économique — le poste n’existe plus',
  'prom': 'la promotion — l’accès à un poste plus élevé et mieux payé',
  'cp': 'les perspectives de carrière — les possibilités d’évolution',
  'we': 'la conscience professionnelle — le sérieux au travail',
  'js': 'la satisfaction professionnelle — l’épanouissement au travail',
  'net': 'le réseautage — tisser des relations professionnelles utiles',
  'rw': 'le télétravail — travailler hors du bureau, souvent de chez soi',
  'Work-life balance': 'l’équilibre vie pro / vie perso',
  'Mentor': 'le mentor — la personne expérimentée qui guide un débutant',
  'Made redundant': 'être licencié (économique) — perdre son poste supprimé',
},

}

# Replacement entries: swap the Spanish-track false friends for French ones.
REPLACE = {
'false-friends': {
  'Actually (vs actualmente)': {
    'id': 'assist', 'word': 'Assist (≠ assister)', 'ipa': '',
    'def': 'aider — PAS « assister à » (= attend) ! To assist someone = aider quelqu’un.',
    'ex': 'She <b>assisted</b> the surgeon during the operation.',
  },
  'Sensible (vs sensible)': {
    'id': 'attend_ff', 'word': 'Attend (≠ attendre)', 'ipa': '',
    'def': 'assister à, être présent — PAS « attendre » (= wait for) !',
    'ex': 'Over 200 people <b>attended</b> the conference.',
  },
  'Eventually (vs eventualmente)': {
    'id': 'demand_ff', 'word': 'Demand (≠ demander)', 'ipa': '',
    'def': 'exiger — bien plus fort que « demander » (= ask for) !',
    'ex': 'The workers <b>demanded</b> better pay and conditions.',
  },
  'Library (vs librería)': {
    'id': 'library_ff', 'word': 'Library (≠ librairie)', 'ipa': '',
    'def': 'la bibliothèque — PAS la librairie (= bookshop) !',
    'ex': 'I borrowed three novels from the <b>library</b>.',
  },
},
}
