# -*- coding: utf-8 -*-
"""French definitions for fr/ B1-B2 vocabulaire flashcards & match games.

Keyed by chapter slug -> word id -> French def (translation + gloss).
REPLACE maps slug -> id -> full replacement word dict (used to swap the
Spanish-track false-friends entries for francophone ones).
"""

DEFS = {

# ---------- B1 ----------

'adjective-preposition': {
  'interested in': 'intéressé par — avoir envie de découvrir ou d’apprendre',
  'good at': 'doué en/pour — avoir la capacité de bien faire quelque chose',
  'bad at': 'mauvais en — ne pas être doué pour quelque chose',
  'afraid of': 'avoir peur de — éprouver de la crainte',
  'angry with': 'en colère contre quelqu’un (with, pas against !)',
  'tired of': 'fatigué de, lassé de — en avoir assez de quelque chose',
  'proud of': 'fier de — être satisfait d’une réussite',
  'worried about': 'inquiet pour/de — se faire du souci à propos de',
  'similar to': 'semblable à — qui ressemble à (to, pas que !)',
  'different from': 'différent de — qui n’est pas pareil (from, pas of)',
  'focused on': 'concentré sur — qui porte son attention sur',
  'aware of': 'conscient de — qui sait, qui est au courant de',
},

'collocations-make-do': {
  'make a decision': 'prendre une décision (make, pas take !) — choisir après réflexion',
  'make a mistake': 'faire une erreur — se tromper',
  'make progress': 'faire des progrès — avancer, s’améliorer',
  'make a difference': 'changer les choses — avoir un effet positif',
  'make money': 'gagner de l’argent (make, pas win !)',
  'make friends': 'se faire des amis — nouer des amitiés',
  'do homework': 'faire ses devoirs — le travail scolaire à la maison',
  'do exercise': 'faire de l’exercice — avoir une activité physique',
  'do your best': 'faire de son mieux — essayer le plus possible',
  'do research': 'faire des recherches — étudier, enquêter',
  'do a favour': 'rendre un service (do, pas make !)',
  'do well': 'bien réussir — obtenir de bons résultats',
},

'education-school': {
  'Curriculum': 'le programme scolaire — l’ensemble des matières enseignées',
  'Semester': 'le semestre — une période d’études d’environ six mois',
  'Deadline': 'la date limite, l’échéance — le délai à respecter',
  'Graduation': 'la remise des diplômes — la cérémonie de fin d’études',
  'Diploma': 'le diplôme — le certificat obtenu en fin de formation',
  'Tuition': 'les frais de scolarité — le coût des études',
  'Essay': 'la rédaction, la dissertation — un écrit sur un sujet donné',
  'Exam': 'l’examen — une épreuve qui évalue les connaissances',
  'Textbook': 'le manuel scolaire — le livre d’une matière',
  'Lecture': 'le cours magistral, la conférence — faux ami : pas « la lecture » !',
  'Grade': 'la note — le résultat d’un travail scolaire',
  'Attend': 'assister à, fréquenter — faux ami : pas « attendre » !',
},

'environment-nature': {
  'forest': 'la forêt — une grande étendue couverte d’arbres',
  'desert': 'le désert — une zone très sèche, presque sans végétation',
  'mountain': 'la montagne — un relief très élevé',
  'valley': 'la vallée — une zone basse entre des montagnes',
  'waterfall': 'la cascade, la chute d’eau',
  'river': 'le fleuve, la rivière — un grand cours d’eau',
  'drought': 'la sécheresse — une longue période sans pluie',
  'flood': 'l’inondation — l’eau qui déborde sur les terres',
  'habitat': 'l’habitat — le milieu naturel d’une espèce',
  'biodiversity': 'la biodiversité — la variété des êtres vivants d’un milieu',
  'pollution': 'la pollution — la contamination de l’environnement',
  'species': 'l’espèce — un groupe d’êtres vivants apparentés (singulier ET pluriel)',
  'ecosystem': 'l’écosystème — une communauté d’êtres vivants et leur milieu',
  'predator': 'le prédateur — un animal qui chasse d’autres animaux',
},

'phrasal-verbs-get-take': {
  'get up': 'se lever — sortir du lit',
  'get on': 'bien s’entendre (avec qqn) ; monter (dans un véhicule)',
  'get away': 's’échapper ; partir en vacances',
  'get back': 'rentrer, revenir',
  'get off': 'descendre (d’un véhicule)',
  'take off': 'enlever (un vêtement) ; décoller (avion)',
  'take on': 'accepter, assumer (une responsabilité)',
  'take over': 'prendre le contrôle, reprendre',
  'take part': 'participer — take part in = participer à',
  'take out': 'sortir, retirer ; inviter quelqu’un (à sortir)',
},

'phrasal-verbs-go-come': {
  'go_on': 'continuer ; se passer (What’s going on ? = Que se passe-t-il ?)',
  'go_through': 'traverser (une épreuve) ; vérifier soigneusement',
  'go_off': 'sonner (alarme) ; tourner (nourriture)',
  'go_ahead': 'aller de l’avant — poursuivre un projet',
  'come_across': 'tomber sur — trouver ou rencontrer par hasard',
  'come_up': 'survenir, être mentionné',
  'come_up_with': 'trouver, inventer (une idée, une solution)',
  'come_round': 'passer (chez quelqu’un) ; changer d’avis',
  'Come back': 'revenir — retourner à un endroit ou une activité',
  'Go without': 'se passer de — vivre sans quelque chose',
},

'sport-leisure': {
  'champ': 'le championnat — la compétition qui désigne le meilleur',
  'ref': 'l’arbitre — l’officiel qui fait respecter les règles',
  'spec': 'le spectateur — celui qui regarde l’épreuve',
  'pb': 'le record personnel — sa meilleure performance',
  'take_up': 'se mettre à — commencer un nouveau sport ou loisir',
  'ts': 'l’esprit d’équipe — la solidarité au sein d’un groupe',
  'draw': 'le match nul — une rencontre à égalité',
  'comp': 'concourir, être en compétition',
  'Personal trainer': 'le coach sportif — le professionnel qui encadre l’entraînement',
  'Warm up': 's’échauffer — préparer son corps avant l’effort',
  'Defend': 'défendre — protéger son but, empêcher l’adversaire de marquer',
  'Division': 'la division — un groupe d’équipes de même niveau',
},

'technology-media': {
  'dl': 'télécharger (depuis internet vers son appareil)',
  'ul': 'mettre en ligne, téléverser (vers internet)',
  'stream': 'regarder/écouter en streaming — en direct sur internet',
  'viral': 'devenir viral — se diffuser massivement en ligne',
  'algo': 'l’algorithme — les règles qui choisissent ce que vous voyez en ligne',
  'st': 'le temps d’écran — le temps passé devant les écrans',
  'cc': 'le créateur de contenu — il produit vidéos, posts ou podcasts',
  'se': 'le moteur de recherche — le programme qui explore internet',
  'Hack': 'pirater — s’introduire illégalement dans un système informatique',
  'Notification': 'la notification — l’alerte automatique d’une application',
},

'travel-holidays': {
  'Accommodation': 'l’hébergement, le logement — toujours singulier en anglais !',
  'Itinerary': 'l’itinéraire — le programme détaillé d’un voyage',
  'Jet lag': 'le décalage horaire — la fatigue après un long vol',
  'Currency': 'la devise, la monnaie — l’argent d’un pays',
  'Departure': 'le départ — le moment où l’on part',
  'Destination': 'la destination — l’endroit où l’on va',
  'Souvenir': 'le souvenir (objet rapporté) — pas le souvenir-mémoire (memory) !',
  'Round trip': 'l’aller-retour — un voyage avec retour au point de départ',
  'Sightseeing': 'le tourisme, la visite — go sightseeing = visiter les sites',
  'Cruise': 'la croisière — des vacances en bateau d’escale en escale',
  'Booking': 'la réservation — d’un hôtel, d’un transport, d’un spectacle',
  'Guide': 'le/la guide — la personne qui fait visiter',
},

'word-families-basic': {
  'decide': 'la décision — le nom formé sur decide',
  'happy': 'le bonheur — le nom formé sur happy (-ness)',
  'create': 'créatif — l’adjectif formé sur create',
  'compete': 'la compétition — le nom formé sur compete',
  'achieve': 'la réussite, l’accomplissement — le nom formé sur achieve',
  'pollute': 'la pollution — le nom formé sur pollute',
  'succeed': 'le succès, la réussite — le nom formé sur succeed',
  'develop': 'le développement — le nom formé sur develop',
  'Act / action / active': 'agir / l’action / actif — le verbe, le nom et l’adjectif d’une même racine',
  'Create / creative / creativity': 'créer / créatif / la créativité — la famille du mot create',
  'Educate / education / educated': 'éduquer / l’éducation / instruit — la famille du mot educate',
  'Help / helpful / helpfulness': 'aider / serviable / la serviabilité — la famille du mot help',
},

# ---------- B2 ----------

'collocations-adj-noun': {
  'se': 'des preuves solides — strong evidence (jamais powerful)',
  'si': 'une forte hausse — sharp increase : brutale et marquée',
  'dc': 'une vive inquiétude — deep concern (jamais big)',
  'hi2': 'un chômage élevé — high unemployment (jamais big)',
  'cr': 'un rôle crucial — une fonction extrêmement importante',
  'br': 'un large éventail — broad range (jamais big)',
  'wi': 'des inégalités généralisées — qui touchent de nombreux domaines',
  'mb': 'une avancée majeure — une découverte très importante',
  'Sharp rise': 'une hausse brutale — une augmentation soudaine et marquée',
  'Wide variety': 'une grande variété — de nombreux types différents',
  'High demand': 'une forte demande — très recherché (in high demand)',
},

'collocations-verbs': {
  'mc': 's’engager — make a commitment : promettre de se consacrer à',
  'ta': 'agir, passer à l’action — take action (jamais make)',
  'hi': 'avoir un impact — have an impact on (jamais make an impact on... attention)',
  'cor': 'mener des recherches — carry out research (jamais make)',
  'ra': 'parvenir à un accord — reach an agreement',
  'rais': 'sensibiliser — raise awareness : faire prendre conscience au public',
  'tr': 'assumer la responsabilité — take responsibility for',
  'dd': 'causer des dégâts — do damage (jamais make)',
  'Bear in mind': 'garder à l’esprit — ne pas oublier un élément important',
  'Rise to the challenge': 'se montrer à la hauteur — relever le défi',
  'Go hand in hand': 'aller de pair — deux choses étroitement liées',
  'Take hold of': 's’emparer de — saisir fermement, prendre le contrôle',
},

'environment-climate': {
  'ce': 'les émissions de carbone — le CO2 rejeté dans l’atmosphère',
  'biod': 'la biodiversité — la variété du vivant dans un milieu',
  'renew': 'les énergies renouvelables — soleil, vent, sources inépuisables',
  'ff': 'les énergies fossiles — charbon, pétrole et gaz',
  'nz': 'la neutralité carbone — équilibre entre émissions et absorption',
  'gg': 'les gaz à effet de serre — ils retiennent la chaleur terrestre',
  'cc': 'la crise climatique — la menace urgente du changement climatique',
  'sd': 'le développement durable — répondre aux besoins d’aujourd’hui sans compromettre demain',
  'Carbon footprint': 'l’empreinte carbone — le total des émissions d’une personne ou organisation',
  'Sea level rise': 'la montée des eaux — l’élévation du niveau des océans',
  'Climate sceptic': 'le climatosceptique — il met en doute le consensus scientifique',
  'Ecosystem': 'l’écosystème — une communauté d’êtres vivants et leur milieu',
},

'expressions-idioms': {
  'lr': 'à long terme, à la longue — in the long run',
  'mot': 'une question de temps — ce qui finira forcément par arriver',
  'tia': 'prendre en compte — take into account : considérer un facteur',
  'ghih': 'aller de pair — être étroitement liés',
  'mem': 'joindre les deux bouts — gagner juste assez pour vivre',
  'fsof': 'ne pas être à la hauteur de — rester en deçà d’un objectif',
  'cttw': 'se faire une raison, accepter — come to terms with',
  'ovo': 'au bord de, sur le point de — on the verge of',
  'Bite off more than you can chew': 'avoir les yeux plus gros que le ventre — accepter plus qu’on ne peut gérer',
  'In the same ballpark': 'du même ordre de grandeur — à peu près comparable',
  'Cut corners': 'rogner sur la qualité — bâcler pour aller vite ou économiser',
  'See the big picture': 'avoir une vue d’ensemble — voir au-delà des détails',
},

'false-friends': {
  'actual': 'en fait, en réalité — PAS « actuellement » (= currently) !',
  'sensible': 'raisonnable, sensé — PAS « sensible » (= sensitive) !',
  'eventually': 'finalement, à terme — PAS « éventuellement » (= possibly) !',
  'affect': 'affecter, avoir un effet sur — affect est le VERBE',
  'effect': 'l’effet, le résultat — effect est le NOM',
  'raise': 'lever, augmenter (transitif — exige un complément)',
  'rise': 'monter, augmenter (intransitif — sans complément)',
  'remind': 'rappeler quelque chose À quelqu’un — remember = se souvenir',
},

'health-lifestyle': {
  'wb': 'le bien-être — l’état de confort physique et mental',
  'nutr': 'la nutrition — l’apport des bons aliments et nutriments',
  'sed': 'la sédentarité — un mode de vie avec très peu d’activité physique',
  'bo': 'le burn-out, l’épuisement professionnel — causé par un stress prolongé',
  'wlb': 'l’équilibre vie pro / vie perso — du temps pour le travail ET pour soi',
  'mh': 'la santé mentale — l’état psychologique et émotionnel',
  'prev': 'une maladie évitable — qu’une bonne hygiène de vie peut prévenir',
  'hc': 'le système de santé — l’offre de soins d’un pays',
  'Wellbeing': 'le bien-être — se sentir bien, en bonne santé et heureux',
  'Immune system': 'le système immunitaire — la défense naturelle du corps',
},

'phrasal-verbs-look-bring': {
  'li': 'examiner, enquêter sur — look into a matter',
  'la': 's’occuper de, garder — look after someone',
  'lft': 'attendre avec impatience — look forward to + -ing !',
  'lof': 'guetter, faire attention à — look out for',
  'ba': 'provoquer, entraîner — bring about change',
  'bu': 'aborder (un sujet) ; élever (un enfant)',
  'bin': 'introduire (une loi, une règle, un système)',
  'bd': 'faire baisser ; faire tomber (un gouvernement, des prix)',
  'Look down on': 'mépriser, regarder de haut — juger inférieur',
},

'phrasal-verbs-put-set': {
  'put_off': 'reporter, remettre à plus tard — postpone',
  'put_up_with': 'supporter, tolérer — quelque chose de désagréable',
  'put_fwd': 'avancer, proposer — une idée ou un projet',
  'put_aside': 'mettre de côté — économiser de l’argent ou du temps',
  'set_up': 'créer, fonder — une entreprise, un système',
  'set_back': 'retarder — freiner la progression',
  'set_off': 'se mettre en route ; déclencher (une alarme)',
  'set_out': 'exposer en détail ; partir avec un objectif',
  'Set aside': 'réserver, mettre de côté ; laisser de côté provisoirement',
},

'phrasal-verbs-turn-run': {
  'td': 'refuser, décliner — turn down an offer ; baisser (le volume)',
  'tu': 'arriver, se pointer — souvent à l’improviste',
  'to': 's’avérer — it turned out that... = il s’est avéré que...',
  'ti': 'se transformer en, devenir',
  'roo': 'être à court de — ne plus avoir de',
  'ri': 'croiser (par hasard) ; rencontrer (un problème)',
  'rth': 'passer en revue, répéter rapidement',
  'ru': 'accumuler (une dette, une grosse facture)',
},

'society-culture': {
  'ineq': 'l’inégalité — des écarts injustes de statut ou de ressources',
  'discrim': 'la discrimination — un traitement injuste selon l’origine, le genre, l’âge...',
  'divers': 'la diversité — la présence de profils variés',
  'mob': 'la mobilité sociale — pouvoir changer de classe sociale',
  'prej': 'le préjugé — une opinion injuste formée sans connaître',
  'coh': 'la cohésion — la qualité d’un groupe uni et solidaire',
  'stigma': 'la stigmatisation — la marque d’infamie liée à une situation',
  'integ': 'l’intégration — réunir des groupes différents en une société',
  'Stereotype': 'le stéréotype — une image figée et simpliste d’un groupe',
  'Informal economy': 'l’économie informelle — l’activité non déclarée, hors régulation',
  'Generation gap': 'le fossé des générations — l’écart de valeurs entre jeunes et aînés',
},

'technology-innovation': {
  'ai': 'l’intelligence artificielle — des machines qui accomplissent des tâches humaines',
  'auto': 'l’automatisation — faire faire les tâches par la technologie',
  'cyber': 'la cybersécurité — protéger les systèmes des attaques numériques',
  'dp': 'la confidentialité des données — contrôler l’usage de ses informations',
  'df': 'l’empreinte numérique — les traces laissées en ligne',
  'disrupt': 'une technologie de rupture — elle bouleverse un secteur entier',
  'algo': 'l’algorithme — les règles de traitement d’un programme',
  'redund': 'le licenciement économique — la suppression d’un poste',
  'Scale up': 'passer à l’échelle supérieure — augmenter la taille ou la capacité',
  'User experience': 'l’expérience utilisateur — le ressenti à l’usage d’un produit',
  'Seamless': 'fluide, sans accroc — sans interruption ni problème',
},

'word-formation-adjectives': {
  'sust': 'durable — l’adjectif de sustain : qui peut se maintenir sans dommage',
  'innov': 'innovant — l’adjectif de innovate : qui introduit des idées nouvelles',
  'env': 'environnemental — l’adjectif de environment',
  'unrel': 'peu fiable — adjectif négatif : sur qui on ne peut pas compter',
  'irresp': 'irresponsable — adjectif négatif : qui manque de sérieux',
  'ineff': 'inefficace — adjectif négatif : qui ne produit pas le résultat voulu',
  'access': 'accessible — l’adjectif de access : facile d’accès ou d’usage',
  'afford': 'inabordable — adjectif négatif : trop cher pour être acheté',
  'Relentless': 'implacable, incessant — qui ne faiblit jamais',
  'Meticulous': 'méticuleux — extrêmement soigneux et précis',
  'Indispensable': 'indispensable — dont on ne peut absolument pas se passer',
  'Compelling': 'captivant, convaincant — impossible à ignorer',
},

'word-formation-nouns': {
  'aw': 'la conscience, la sensibilisation — le nom formé sur aware',
  'ineq2': 'l’inégalité — equal + préfixe négatif in- + suffixe -ity',
  'auto': 'l’automatisation — le nom formé sur automate',
  'div': 'la diversité — le nom formé sur diverse',
  'sust': 'la durabilité — le nom formé sur sustain',
  'commit': 'l’engagement — le nom formé sur commit',
  'innov': 'l’innovation — le nom formé sur innovate',
  'discrim': 'la discrimination — le nom formé sur discriminate',
  'Breakthrough': 'la percée, l’avancée décisive — la découverte qui change tout',
  'Backlash': 'le retour de bâton — une vive réaction négative du public',
  'Pitfall': 'le piège, l’écueil — une difficulté cachée',
  'Threshold': 'le seuil — le niveau à partir duquel quelque chose se déclenche',
},

'word-formation-prefixes': {
  'under': 'sous- (insuffisant) — underpaid = sous-payé',
  'over': 'sur- (excessif) — overworked = surmené',
  'mis': 'mal- (incorrectement) — misunderstand = mal comprendre',
  're': 're- (à nouveau) — rebuild = reconstruire',
  'pre': 'pré- (avant) — prepay = payer d’avance',
  'out': 'sur- (dépasser les autres) — outperform = surpasser',
  'inter': 'inter- (entre) — international = entre les nations',
  'dis': 'dé-/dis- (contraire) — disagree = ne pas être d’accord',
  'Mismanage': 'mal gérer — gérer de façon incompétente',
  'Overrated': 'surestimé, surcoté — qui ne mérite pas sa réputation',
  'Underestimate': 'sous-estimer — croire moindre que la réalité',
  'Counteract': 'contrer, neutraliser — agir contre des effets nocifs',
},

'work-careers': {
  'ent': 'l’entrepreneur — il crée et dirige sa propre entreprise',
  'red': 'le licenciement économique — le poste n’existe plus',
  'prom': 'la promotion — l’accès à un poste plus élevé et mieux payé',
  'cp': 'les perspectives de carrière — les possibilités d’évolution',
  'we': 'la conscience professionnelle — le sérieux au travail',
  'js': 'la satisfaction professionnelle — l’épanouissement au travail',
  'net': 'le réseautage — tisser des relations professionnelles utiles',
  'rw': 'le télétravail — travailler hors du bureau, souvent de chez soi',
  'Work-life balance': 'l’équilibre vie pro / vie perso',
  'Mentor': 'le mentor — la personne expérimentée qui guide un débutant',
  'Made redundant': 'être licencié (économique) — perdre son poste supprimé',
},

}

# Replacement entries: swap the Spanish-track false friends for French ones.
REPLACE = {
'false-friends': {
  'Actually (vs actualmente)': {
    'id': 'assist', 'word': 'Assist (≠ assister)', 'ipa': '',
    'def': 'aider — PAS « assister à » (= attend) ! To assist someone = aider quelqu’un.',
    'ex': 'She <b>assisted</b> the surgeon during the operation.',
  },
  'Sensible (vs sensible)': {
    'id': 'attend_ff', 'word': 'Attend (≠ attendre)', 'ipa': '',
    'def': 'assister à, être présent — PAS « attendre » (= wait for) !',
    'ex': 'Over 200 people <b>attended</b> the conference.',
  },
  'Eventually (vs eventualmente)': {
    'id': 'demand_ff', 'word': 'Demand (≠ demander)', 'ipa': '',
    'def': 'exiger — bien plus fort que « demander » (= ask for) !',
    'ex': 'The workers <b>demanded</b> better pay and conditions.',
  },
  'Library (vs librería)': {
    'id': 'library_ff', 'word': 'Library (≠ librairie)', 'ipa': '',
    'def': 'la bibliothèque — PAS la librairie (= bookshop) !',
    'ex': 'I borrowed three novels from the <b>library</b>.',
  },
},
}
