"""
francais/b1 — Grammaire B1 — batch 1 (G01–G04)
"""

CHAPTERS = {

"le-plus-que-parfait": {
    "level": "b1",
    "section": "grammaire",
    "num": "G01",
    "short": "Le Plus-que-parfait",
    "title": "Le Plus-que-parfait",
    "subtitle": "L'action antérieure dans le passé",
    "slides": [
        ("Qu'est-ce que le plus-que-parfait ?",
         "Le plus-que-parfait exprime une action passée <em>antérieure</em> à une autre action passée. Formation : auxiliaire (être/avoir) à l'imparfait + participe passé."),
        ("Formation avec <em>avoir</em>",
         "j'avais mangé · tu avais fini · il avait pris · nous avions compris · vous aviez dit · ils avaient vu"),
        ("Formation avec <em>être</em>",
         "j'étais arrivé(e) · tu étais parti(e) · il était allé · nous étions venus · vous étiez restés · ils étaient tombés<br><em>Accords identiques au passé composé avec être.</em>"),
        ("Emploi principal",
         "Quand il est arrivé, <em>j'avais déjà mangé</em>. (J'ai mangé AVANT son arrivée.)<br>Elle a dit qu'elle <em>avait oublié</em> ses clés.<br><em>Marqueurs :</em> déjà, avant que, quand, lorsque, parce que."),
        ("Distinguer PQP / PC / Imparfait",
         "<strong>PQP</strong> = action accomplie avant le moment passé de référence.<br><strong>Imparfait</strong> = état/habitude au moment passé.<br><strong>PC</strong> = action accomplie au moment passé.<br><em>Avant qu'il parte, elle avait préparé le dîner.</em>"),
        ("Avec <em>si</em> : condition irréelle dans le passé",
         "Si + PQP → conditionnel passé : <em>Si j'avais su, je n'aurais pas dit ça.</em><br>Cette structure exprime le regret ou la condition impossible dans le passé."),
    ],
    "traps": [
        ("Auxiliaire : avoir ou être ?", "Même règle qu'au PC : verbes de mouvement/état (aller, venir, partir, rester…) et pronominaux → être. Tous les autres → avoir. <em>Elle était venue mais il avait refusé.</em>"),
        ("Accord du participe", "Avec être : accord avec le sujet. Avec avoir : accord avec le COD si placé avant. <em>Les clés qu'il avait perdues.</em>"),
        ("PQP ≠ Conditionnel passé", "PQP : auxiliaire à l'imparfait. Conditionnel passé : auxiliaire au conditionnel. <em>avais mangé ≠ aurais mangé.</em>"),
        ("Marqueur <em>déjà</em>", "<em>Déjà</em> se place entre l'auxiliaire et le participe : <em>j'avais déjà vu</em>, pas *<em>j'avais vu déjà</em>."),
    ],
    "summary": [
        "Formation : avoir/être à l'<strong>imparfait</strong> + participe passé.",
        "Exprime une action <strong>antérieure</strong> à une autre action passée.",
        "Même règle auxiliaire et accords qu'au passé composé.",
        "Avec <em>si</em> (+ conditionnel passé) = condition irréelle passée.",
        "Marqueurs clés : <em>déjà, avant que, quand, parce que</em>.",
    ],
    "ex1": {
        "q": "Quand je suis arrivé, elle ___ déjà ___.",
        "opts": ["avait / parti", "était / partie", "a / parti", "avait / partis"],
        "ans": "était / partie",
        "exp": "'Partir' se conjugue avec être au plus-que-parfait. Le sujet 'elle' est féminin → accord : partie.",
    },
    "ex2": {
        "q": "Mettez au plus-que-parfait : 'Il prend le bus.'",
        "ans": "il avait pris le bus",
        "exp": "'Prendre' → participe passé 'pris'; auxiliaire 'avoir' à l'imparfait → avait pris.",
        "accept": ["il avait pris le bus.", "avait pris le bus"],
    },
    "ex3": {
        "q": "Laquelle de ces phrases est correcte ?",
        "opts": [
            "Nous avions déjà mangé quand ils sont arrivés.",
            "Nous avons déjà mangé quand ils étaient arrivés.",
            "Nous avions déjà mangé quand ils avaient arrivés.",
            "Nous étions mangé quand ils sont arrivés.",
        ],
        "ans": "Nous avions déjà mangé quand ils sont arrivés.",
        "exp": "PQP pour l'action antérieure (avions mangé) + PC pour l'action de référence (sont arrivés). 'Arriver' prend être mais pas dans ce contexte : *avaient arrivés est incorrect. 'étions mangé' est faux car manger prend avoir.",
    },
    "game_desc": "Plus-que-parfait — formation et emploi",
    "items": [
        ("pqp-def", "Le plus-que-parfait", "Temps exprimant une action accomplie avant une autre action passée", "le temps de l'antériorité passée", "Quand tu as appelé, j'avais déjà mangé.", "PQP exprime l'antériorité dans le passé", "le temps de l'antériorité passée"),
        ("pqp-form", "Formation du PQP", "Auxiliaire (être/avoir) à l'imparfait + participe passé", "imparfait de l'auxiliaire + participe passé", "Ils avaient compris la leçon.", "l'imparfait + le participe passé", "imparfait de l'auxiliaire + participe passé"),
        ("pqp-avoir", "PQP avec avoir", "j'avais mangé, tu avais pris, il avait compris", "j'avais + participe passé", "J'avais déjà vu ce film.", "avais + participe passé", "j'avais + participe passé"),
        ("pqp-etre", "PQP avec être", "j'étais parti(e), tu étais allé(e), il était venu", "j'étais + participe passé accordé", "Elle était déjà arrivée.", "étais/était + participe accordé", "j'étais + participe passé accordé"),
        ("pqp-deja", "Déjà au PQP", "Se place entre l'auxiliaire et le participe", "entre l'auxiliaire et le participe", "J'avais déjà mangé.", "entre l'auxiliaire et le participe", "entre l'auxiliaire et le participe"),
        ("pqp-si", "Si + PQP", "Condition irréelle dans le passé → conditionnel passé dans la principale", "condition impossible dans le passé", "Si j'avais su, j'aurais agi.", "condition passée irréelle", "condition impossible dans le passé"),
        ("pqp-accord", "Accord participe (PQP)", "Avec être : accord sujet. Avec avoir : accord COD placé avant.", "accord identique au PC", "Les clés qu'il avait perdues.", "même accord qu'au PC", "accord identique au PC"),
        ("pqp-vs-cond", "PQP vs conditionnel passé", "PQP : avait mangé. Conditionnel passé : aurait mangé.", "imparfait vs conditionnel de l'auxiliaire", "Il aurait fini si… / Il avait fini quand…", "imparfait ou conditionnel de l'auxiliaire", "imparfait vs conditionnel de l'auxiliaire"),
    ],
},

"le-futur-anterieur": {
    "level": "b1",
    "section": "grammaire",
    "num": "G02",
    "short": "Le Futur Antérieur",
    "title": "Le Futur Antérieur",
    "subtitle": "L'action accomplie avant un moment futur",
    "slides": [
        ("Qu'est-ce que le futur antérieur ?",
         "Le futur antérieur exprime une action qui sera <em>terminée</em> avant un moment ou une autre action future. Formation : auxiliaire (être/avoir) au futur simple + participe passé."),
        ("Formation",
         "j'aurai fini · tu auras mangé · il sera parti · nous aurons compris · vous serez arrivés · ils auront vu"),
        ("Emplois principaux",
         "<strong>1. Antériorité :</strong> Quand tu arriveras, j'<em>aurai déjà préparé</em> le dîner.<br><strong>2. Avec <em>dès que / aussitôt que / lorsque</em> :</strong> Dès qu'il <em>aura terminé</em>, il appellera.<br><strong>3. Supposition dans le futur :</strong> Elle n'est pas là — elle <em>aura oublié</em>."),
        ("Futur simple vs Futur antérieur",
         "Futur simple = action à venir. Futur antérieur = action qui sera accomplie.<br><em>Quand il arrivera</em> (FS) <em>j'aurai mangé</em> (FA). Les deux clauses peuvent avoir FS, mais FA marque l'antériorité."),
        ("Conjonctions déclencheurs",
         "<em>quand, lorsque, dès que, aussitôt que, une fois que, après que</em> → suivi de futur antérieur si l'action est accomplie avant la principale au futur simple."),
        ("Auxiliaire et accords",
         "Même règle qu'au PC et au PQP : être pour verbes de déplacement/état et pronominaux; avoir pour le reste. Accords identiques."),
    ],
    "traps": [
        ("Futur antérieur ≠ Conditionnel passé", "FA : j'aurai fini. Conditionnel passé : j'aurais fini. Ne pas confondre les formes de l'auxiliaire (futur vs conditionnel)."),
        ("Après <em>quand</em> au futur", "En français, après les conjonctions temporelles futures (quand, lorsque, dès que…), on emploie le futur (simple ou antérieur), jamais un présent. *Quand tu viendras (pas : quand tu viens) est courant mais FA est plus précis si l'action est accomplie."),
        ("Accord du participe", "Mêmes règles qu'au PC/PQP. Avec être : accord sujet. Avec avoir + COD antéposé : accord COD."),
        ("Supposition présente ≠ FA", "Pour la supposition présente, on utilise le futur simple : 'Il sera dans le train.' Pour une supposition d'action déjà accomplie : 'Il aura raté son train.'"),
    ],
    "summary": [
        "Formation : avoir/être au <strong>futur simple</strong> + participe passé.",
        "Exprime une action <strong>accomplie avant</strong> un moment futur.",
        "Déclenché par : <em>quand, dès que, une fois que, après que</em>.",
        "Peut exprimer une <strong>supposition</strong> sur une action déjà accomplie.",
        "Mêmes règles auxiliaire/accords qu'au PC.",
    ],
    "ex1": {
        "q": "Dès qu'il ___ (finir), il nous appellera.",
        "opts": ["finira", "aura fini", "avait fini", "aurait fini"],
        "ans": "aura fini",
        "exp": "Après 'dès que' + futur, on emploie le futur antérieur pour l'action accomplie avant l'action principale (appellera). 'Finira' marquerait deux actions simultanées; 'avait fini' est PQP; 'aurait fini' est conditionnel passé.",
    },
    "ex2": {
        "q": "Mettez au futur antérieur : 'Elle part.'",
        "ans": "elle sera partie",
        "exp": "'Partir' prend l'auxiliaire être. Futur de être : sera. Participe passé : partie (accord féminin).",
        "accept": ["elle sera partie.", "sera partie"],
    },
    "ex3": {
        "q": "Quand les invités arriveront, nous ___ le repas.",
        "opts": [
            "aurons préparé",
            "aurions préparé",
            "avions préparé",
            "préparerons",
        ],
        "ans": "aurons préparé",
        "exp": "Action accomplie (préparer) avant l'arrivée des invités (futur) → futur antérieur : aurons préparé. 'Aurions préparé' est conditionnel passé. 'Avions préparé' est PQP. 'Préparerons' marquerait simultanéité, pas antériorité.",
    },
    "game_desc": "Futur antérieur — formation et emploi",
    "items": [
        ("fa-def", "Le futur antérieur", "Action qui sera terminée avant un moment ou une action future", "action future accomplie", "J'aurai fini avant ton arrivée.", "action accomplie dans le futur", "action future accomplie"),
        ("fa-form", "Formation du FA", "Avoir/être au futur simple + participe passé", "futur de l'auxiliaire + participe passé", "Ils auront compris.", "futur simple + participe passé", "futur de l'auxiliaire + participe passé"),
        ("fa-avoir", "FA avec avoir", "j'aurai mangé, tu auras fini, il aura compris", "j'aurai + participe passé", "Nous aurons terminé à midi.", "aurai/auras/aura + participe passé", "j'aurai + participe passé"),
        ("fa-etre", "FA avec être", "je serai parti(e), tu seras arrivé(e)", "je serai + participe passé accordé", "Elle sera déjà partie.", "serai/seras/sera + participe accordé", "je serai + participe passé accordé"),
        ("fa-quand", "Quand + FA", "Après les conjonctions temporelles futures, FA pour action accomplie", "futur antérieur après quand/dès que", "Quand tu auras fini, nous sortirons.", "FA après conjonctions temporelles", "futur antérieur après quand/dès que"),
        ("fa-des-que", "Dès que / aussitôt que", "Conjonctions déclenchant le FA pour l'action accomplie", "dès que + futur antérieur", "Dès qu'il aura signé, c'est officiel.", "déclencheurs du FA", "dès que + futur antérieur"),
        ("fa-supposition", "Supposition accomplie", "FA exprime une supposition sur une action déjà accomplie", "supposer qu'une action est terminée", "Elle n'est pas là — elle aura oublié.", "supposition passée au FA", "supposer qu'une action est terminée"),
        ("fa-vs-pqp", "FA vs PQP", "FA = antériorité dans le futur. PQP = antériorité dans le passé.", "futur = FA, passé = PQP", "Il aura fini (futur) / Il avait fini (passé).", "antériorité future vs passée", "futur = FA, passé = PQP"),
    ],
},

"le-conditionnel-passe": {
    "level": "b1",
    "section": "grammaire",
    "num": "G03",
    "short": "Le Conditionnel Passé",
    "title": "Le Conditionnel Passé",
    "subtitle": "Regrets, reproches et conditions irréelles passées",
    "slides": [
        ("Formation",
         "Auxiliaire (être/avoir) au conditionnel présent + participe passé.<br>j'aurais mangé · tu serais parti(e) · il aurait voulu · nous aurions compris · vous seriez restés · elles auraient su"),
        ("Emploi 1 : condition irréelle dans le passé",
         "Si + plus-que-parfait → conditionnel passé.<br><em>Si j'avais étudié, j'aurais réussi l'examen.</em><br>La condition n'est pas remplie : il n'a pas étudié, donc il n'a pas réussi."),
        ("Emploi 2 : regrets",
         "<em>J'aurais voulu être chanteur.</em> (mais je ne l'ai pas été)<br><em>Tu aurais pu me prévenir !</em> (mais tu ne l'as pas fait)<br>Souvent avec <em>pouvoir, vouloir, devoir, aimer</em>."),
        ("Emploi 3 : reproches",
         "Conditionnel passé de <em>devoir, pouvoir</em> + infinitif = reproche.<br><em>Tu aurais dû appeler.</em> (tu n'as pas appelé — c'est une critique)<br><em>Elle aurait pu arriver à l'heure.</em>"),
        ("Emploi 4 : fait non confirmé",
         "Dans les médias : <em>Le président aurait déclaré…</em> = l'information n'est pas vérifiée.<br>Même emploi qu'au conditionnel présent mais pour le passé."),
        ("Mêmes auxiliaires et accords qu'au PC",
         "Être pour mouvement/état + pronominaux; avoir pour les autres. Accords identiques : sujet (être), COD antéposé (avoir)."),
    ],
    "traps": [
        ("Si + CP ≠ Si + futur", "Après si conditionnel, on n'utilise jamais le futur ni le conditionnel. Si + imparfait → cond. présent. Si + PQP → cond. passé."),
        ("Conditionnel passé ≠ Futur antérieur", "Formes similaires : CP = aurais/serais + PP; FA = aurai/serai + PP. L'auxiliaire est au conditionnel (CP) ou au futur (FA)."),
        ("Accord participe passé", "Mêmes règles qu'au PC. Avec être → accord sujet. Avec avoir + COD antéposé → accord COD."),
        ("Regret vs Reproche", "Regret = je parle de moi-même : 'J'aurais voulu…'. Reproche = je parle à/de quelqu'un : 'Tu aurais dû…', 'Il aurait pu…'."),
    ],
    "summary": [
        "Formation : avoir/être au <strong>conditionnel présent</strong> + participe passé.",
        "<strong>Condition irréelle passée :</strong> Si + PQP → conditionnel passé.",
        "<strong>Regrets :</strong> j'aurais voulu, tu aurais aimé…",
        "<strong>Reproches :</strong> tu aurais dû, il aurait pu…",
        "<strong>Fait non confirmé</strong> dans les médias.",
    ],
    "ex1": {
        "q": "Si elle avait su, elle ___ (venir).",
        "opts": ["serait venue", "est venue", "sera venue", "viendrait"],
        "ans": "serait venue",
        "exp": "Si + PQP → conditionnel passé. 'Venir' prend être → serait venue (accord féminin). 'Viendrait' est conditionnel présent (pour si + imparfait). 'Sera venue' est futur antérieur.",
    },
    "ex2": {
        "q": "Exprimez un reproche : 'Il ne m'a pas prévenu.' → Il ___ me prévenir.",
        "ans": "aurait dû",
        "exp": "Reproche avec 'devoir' au conditionnel passé : aurait dû + infinitif.",
        "accept": ["aurait dû", "il aurait dû me prévenir", "il aurait dû me prévenir."],
    },
    "ex3": {
        "q": "Quelle phrase exprime un regret ?",
        "opts": [
            "J'aurais voulu devenir médecin.",
            "Si tu avais étudié, tu aurais réussi.",
            "Le ministre aurait démissionné.",
            "Tu aurais dû appeler avant.",
        ],
        "ans": "J'aurais voulu devenir médecin.",
        "exp": "'J'aurais voulu' exprime un désir non réalisé dans le passé = regret personnel. La deuxième est une condition irréelle. La troisième est un fait non confirmé. La quatrième est un reproche.",
    },
    "game_desc": "Conditionnel passé — emplois et formation",
    "items": [
        ("cp-form", "Formation CP", "Avoir/être au conditionnel présent + participe passé", "conditionnel de l'auxiliaire + participe passé", "J'aurais mangé, tu serais parti.", "cond. présent + participe passé", "conditionnel de l'auxiliaire + participe passé"),
        ("cp-condition", "Condition irréelle passée", "Si + PQP → conditionnel passé dans la principale", "Si + PQP → conditionnel passé", "Si j'avais su, j'aurais agi.", "condition passée non réalisée", "Si + PQP → conditionnel passé"),
        ("cp-regret", "Regret", "Conditionnel passé de vouloir/aimer/pouvoir pour exprimer un désir non réalisé", "j'aurais voulu / tu aurais aimé", "J'aurais voulu être peintre.", "désir passé non réalisé", "j'aurais voulu / tu aurais aimé"),
        ("cp-reproche", "Reproche", "Devoir/pouvoir au conditionnel passé + infinitif", "aurais dû / aurait pu + infinitif", "Tu aurais dû me dire la vérité.", "critique d'une action non faite", "aurais dû / aurait pu + infinitif"),
        ("cp-media", "Fait non confirmé", "Conditionnel passé dans les médias pour info non vérifiée", "information non confirmée au passé", "Le président aurait signé l'accord.", "rumeur ou info non vérifiée", "information non confirmée au passé"),
        ("cp-vs-fa", "CP vs FA", "CP : aurais mangé. FA : aurai mangé. L'auxiliaire diffère.", "conditionnel vs futur de l'auxiliaire", "J'aurais fini (CP) / J'aurai fini (FA).", "auxiliaire au cond. ou au futur", "conditionnel vs futur de l'auxiliaire"),
        ("cp-pqp-pair", "Si + PQP / CP", "Structure des phrases conditionnelles irréelles passées", "paire PQP + conditionnel passé", "Si tu avais étudié, tu aurais réussi.", "Si + PQP + conditionnel passé", "paire PQP + conditionnel passé"),
        ("cp-accord", "Accord au CP", "Même règle qu'au PC : être → accord sujet; avoir + COD antéposé → accord COD.", "accord identique au PC", "Elle serait venue. / Les lettres qu'il aurait écrites.", "accord comme au PC", "accord identique au PC"),
    ],
},

"le-subjonctif-present": {
    "level": "b1",
    "section": "grammaire",
    "num": "G04",
    "short": "Le Subjonctif Présent",
    "title": "Le Subjonctif Présent",
    "subtitle": "Doute, émotion, volonté et obligation",
    "slides": [
        ("Formation régulière",
         "Radical de la 3e personne du pluriel (présent) + terminaisons : <em>-e, -es, -e, -ions, -iez, -ent</em>.<br>ils parlent → que je <em>parle</em>; ils finissent → que je <em>finisse</em>; ils prennent → que je <em>prenne</em>."),
        ("Verbes irréguliers principaux",
         "être : que je <em>sois</em>, que tu <em>sois</em>, qu'il <em>soit</em>, que nous <em>soyons</em>, que vous <em>soyez</em>, qu'ils <em>soient</em><br>avoir : que j'<em>aie</em>, que tu <em>aies</em>, qu'il <em>ait</em>, que nous <em>ayons</em>, que vous <em>ayez</em>, qu'ils <em>aient</em><br>aller, faire, pouvoir, savoir, vouloir : formes à mémoriser."),
        ("Emploi 1 : volonté et souhait",
         "<em>Il faut que tu <strong>viennes</strong>.</em><br><em>Je veux que tu <strong>finisses</strong> tes devoirs.</em><br><em>J'aimerais qu'il <strong>soit</strong> là.</em><br>Verbes déclencheurs : vouloir, désirer, exiger, souhaiter, préférer, demander, permettre, interdire…"),
        ("Emploi 2 : émotion",
         "<em>Je suis content(e) qu'il <strong>puisse</strong> venir.</em><br><em>C'est dommage que tu <strong>partes</strong>.</em><br>Déclencheurs : être content/triste/surpris/désolé/heureux, regretter, avoir peur…"),
        ("Emploi 3 : doute et incertitude",
         "<em>Je doute qu'il <strong>vienne</strong>.</em><br><em>Il est possible qu'elle <strong>ait</strong> raison.</em><br>Déclencheurs : douter, ne pas croire, il est possible/douteux/peu probable…"),
        ("Emploi 4 : expressions impersonnelles",
         "Il faut que · Il est important que · Il est nécessaire que · Il est essentiel que + subjonctif.<br><em>Il faut que vous <strong>sachiez</strong> la vérité.</em>"),
    ],
    "traps": [
        ("Subjonctif seulement si deux sujets différents", "Si le sujet est le même, on utilise l'infinitif : Je veux <em>partir</em> (pas : *que je parte). Je veux qu'<em>il parte</em> (sujets différents → subjonctif)."),
        ("Indicatif après <em>penser / croire</em> affirmatif", "Je pense qu'il <em>est</em> là (indicatif, affirmation). Je ne pense pas qu'il <em>soit</em> là (subjonctif, doute/négation)."),
        ("<em>Bien que</em> toujours subjonctif", "<em>Bien que</em> (although) déclenche toujours le subjonctif : <em>Bien qu'il soit fatigué, il travaille.</em>"),
        ("Terminaisons -ions/-iez", "Pour nous et vous, les terminaisons (-ions, -iez) peuvent ressembler à l'imparfait — mais le subjonctif n'a pas de accent circonflexe (pas d'accent sur le i)."),
    ],
    "summary": [
        "Formation : radical 3pp + <strong>-e, -es, -e, -ions, -iez, -ent</strong>.",
        "Après verbes de <strong>volonté</strong> : vouloir, exiger, demander…",
        "Après verbes d'<strong>émotion</strong> : être content/triste/surpris…",
        "Après verbes de <strong>doute</strong> : douter, il est possible…",
        "Deux sujets différents → subjonctif; même sujet → infinitif.",
    ],
    "ex1": {
        "q": "Il faut que tu ___ (savoir) la vérité.",
        "opts": ["saches", "sais", "sauras", "saurais"],
        "ans": "saches",
        "exp": "'Il faut que' déclenche le subjonctif. 'Savoir' → subjonctif irrégulier : je sache, tu saches. 'Sais' est présent indicatif; 'sauras' est futur; 'saurais' est conditionnel.",
    },
    "ex2": {
        "q": "Mettez au subjonctif : 'Elle (être) contente.'",
        "ans": "qu'elle soit contente",
        "exp": "Être au subjonctif → soit. Phrase subordonnée = qu'elle soit contente.",
        "accept": ["qu'elle soit contente", "elle soit contente", "qu'elle soit contente."],
    },
    "ex3": {
        "q": "Quelle phrase demande le subjonctif ?",
        "opts": [
            "Je suis content qu'il vienne.",
            "Je pense qu'il vient ce soir.",
            "Je sais qu'elle est là.",
            "Il dit qu'il viendra demain.",
        ],
        "ans": "Je suis content qu'il vienne.",
        "exp": "Émotion (être content) avec deux sujets différents → subjonctif (vienne). Les autres ont des verbes de déclaration/certitude (penser affirmatif, savoir, dire) qui prennent l'indicatif.",
    },
    "game_desc": "Subjonctif présent — formation et déclencheurs",
    "items": [
        ("subj-form", "Formation subjonctif", "Radical 3pp du présent + -e, -es, -e, -ions, -iez, -ent", "radical 3pp + terminaisons en -e", "Ils parlent → que je parle.", "radical 3pp + terminaisons en -e", "radical 3pp + terminaisons en -e"),
        ("subj-etre", "Être au subjonctif", "que je sois, tu sois, il soit, nous soyons, vous soyez, ils soient", "sois / soit / soyons", "Il faut qu'il soit là.", "formes de être au subjonctif", "sois / soit / soyons"),
        ("subj-avoir", "Avoir au subjonctif", "que j'aie, tu aies, il ait, nous ayons, vous ayez, ils aient", "aie / ait / ayons", "Il est important qu'elle ait le document.", "formes de avoir au subjonctif", "aie / ait / ayons"),
        ("subj-volonte", "Volonté → subjonctif", "Vouloir, exiger, demander, préférer, souhaiter + que + subjonctif", "vouloir/exiger que + subjonctif", "Je veux qu'il parte maintenant.", "volonté + subjonctif", "vouloir/exiger que + subjonctif"),
        ("subj-emotion", "Émotion → subjonctif", "Être content/triste/surpris/désolé + que + subjonctif", "émotion + que + subjonctif", "Je suis désolée qu'il ne puisse pas venir.", "émotion + subjonctif", "émotion + que + subjonctif"),
        ("subj-doute", "Doute → subjonctif", "Douter, ne pas croire, il est possible/douteux + que + subjonctif", "doute + que + subjonctif", "Je doute qu'il vienne à l'heure.", "doute + subjonctif", "doute + que + subjonctif"),
        ("subj-deux-sujets", "Deux sujets → subjonctif", "Si les deux clauses ont des sujets différents, le subjonctif est obligatoire", "sujets différents = subjonctif", "Je veux qu'il finisse (≠ Je veux finir).", "deux sujets = subjonctif", "sujets différents = subjonctif"),
        ("subj-bien-que", "Bien que + subjonctif", "La conjonction 'bien que' déclenche toujours le subjonctif", "bien que + subjonctif toujours", "Bien qu'il soit fatigué, il continue.", "bien que = subjonctif obligatoire", "bien que + subjonctif toujours"),
    ],
},

}
