"""
francais/b1 — Grammaire B1 — batch 3 (G09–G12)
"""

CHAPTERS = {

"la-voix-passive": {
    "level": "b1",
    "section": "grammaire",
    "num": "G09",
    "short": "La Voix Passive",
    "title": "La Voix Passive",
    "subtitle": "Être + participe passé — mettre l'accent sur l'objet",
    "slides": [
        ("Formation",
         "Être (conjugué au temps voulu) + <strong>participe passé</strong> accordé avec le sujet.<br>Actif : Le chef signe le contrat. → Passif : Le contrat <em>est signé</em> par le chef."),
        ("La préposition <em>par</em> et <em>de</em>",
         "<em>Par</em> introduit l'agent d'une action physique/concrète : <em>La fenêtre a été cassée <strong>par</strong> les enfants.</em><br><em>De</em> s'emploie avec certains verbes d'état ou d'opinion : <em>Elle est aimée <strong>de</strong> tout le monde. / Il est entouré <strong>de</strong> ses amis.</em>"),
        ("Emploi aux différents temps",
         "Présent passif : <em>est signé</em>.<br>Imparfait passif : <em>était signé</em>.<br>Passé composé passif : <em>a été signé</em>.<br>Futur passif : <em>sera signé</em>.<br>Conditionnel passif : <em>serait signé</em>."),
        ("Accord du participe passé",
         "Le participe passé s'accorde toujours avec le <strong>sujet</strong> de la phrase passive.<br><em>La lettre a été envoyée.</em> (féminin singulier)<br><em>Les documents ont été signés.</em> (masculin pluriel)"),
        ("Voix passive vs construction pronominale",
         "Pour éviter le passif, on utilise souvent le pronom <em>on</em> ou une forme réfléchie :<br><em>On parle français ici.</em> = <em>Le français est parlé ici.</em><br><em>Ce mot s'emploie rarement.</em> = Ce mot est rarement employé."),
        ("Limites du passif",
         "Les verbes avec COI (parler à, téléphoner à, ressembler à…) ne peuvent pas être mis au passif directement. On ne dit pas *'Il est téléphoné par son ami'. On dit : Son ami lui a téléphoné."),
    ],
    "traps": [
        ("Accord obligatoire", "Au passif, le participe passé s'accorde toujours avec le sujet, même avec 'avoir' comme auxiliaire dans la forme active correspondante. <em>La maison a été vendue</em> (vendue = accord féminin sg)."),
        ("Passé composé passif vs Passif avec état", "<em>La porte est fermée</em> peut être un passif (= on a fermé la porte) ou un état résultant. Le contexte détermine le sens. Pour l'action : <em>La porte a été fermée par le gardien</em>."),
        ("<em>Par</em> vs <em>de</em>", "Ne pas interchanger par et de librement. 'De' est réservé aux verbes d'état/sentiment et certains verbes figés. En cas de doute, utiliser 'par'."),
        ("Verbes sans passif", "Verbes intransitifs (aller, venir, partir…) et verbes avec COI ne se mettent pas au passif. On ne peut mettre au passif que le COD."),
    ],
    "summary": [
        "Formation : <strong>être (temps voulu) + participe passé accordé</strong> avec le sujet.",
        "Agent introduit par <strong>par</strong> (action) ou <strong>de</strong> (état/sentiment).",
        "Accord du participe toujours avec le <strong>sujet</strong> passif.",
        "Alternative : <em>on</em> actif ou construction pronominale.",
        "Seul le <strong>COD</strong> peut devenir sujet du passif.",
    ],
    "ex1": {
        "q": "La lettre ___ (écrire) par le directeur hier.",
        "opts": ["a été écrite", "est écrite", "a écrit", "est écrit"],
        "ans": "a été écrite",
        "exp": "Action passée accomplie → passé composé passif : a été + participe passé accordé. 'Lettre' est féminin → écrite. 'Est écrite' est présent passif. 'A écrit' est actif.",
    },
    "ex2": {
        "q": "Mettez au passif : 'Tous les élèves admirent ce professeur.'",
        "ans": "ce professeur est admiré de tous les élèves",
        "exp": "Passif présent. 'Ce professeur' devient sujet. Verbe d'admiration → 'de' tous les élèves. Accord : professeur (masculin sg) → admiré.",
        "accept": ["ce professeur est admiré de tous les élèves", "ce professeur est admiré de tous les élèves.", "est admiré de tous les élèves"],
    },
    "ex3": {
        "q": "Quelle phrase passive est correcte ?",
        "opts": [
            "Les décisions ont été prises par le comité.",
            "Les décisions ont été pris par le comité.",
            "Les décisions sont prises de le comité.",
            "Les décisions étaient pris par le comité.",
        ],
        "ans": "Les décisions ont été prises par le comité.",
        "exp": "'Décisions' est féminin pluriel → accord : prises. 'Pris' sans accord est incorrect ici. 'De le comité' est incorrect (la préposition de + article défini → du, mais ici on utilise par pour une action). 'Étaient pris' : accord manquant.",
    },
    "game_desc": "Voix passive — formation et emploi",
    "items": [
        ("vp-form", "Formation passive", "Être (conjugué) + participe passé accordé avec le sujet", "être + participe passé accordé", "Le rapport est signé par la directrice.", "être + participe passé accordé sujet", "être + participe passé accordé"),
        ("vp-accord", "Accord au passif", "Le participe passé s'accorde toujours avec le sujet de la phrase passive", "accord avec le sujet passif", "Les lettres ont été envoyées.", "accord sujet = accord participe", "accord avec le sujet passif"),
        ("vp-par", "Agent avec par", "Par introduit l'agent d'une action concrète ou physique", "action concrète → par", "La fenêtre a été cassée par les enfants.", "action physique = par", "action concrète → par"),
        ("vp-de", "Agent avec de", "De s'emploie avec des verbes d'état, sentiment ou certains verbes figés", "état/sentiment → de", "Il est entouré de ses amis.", "état/sentiment = de", "état/sentiment → de"),
        ("vp-temps", "Passif aux temps", "Le passif se conjugue à tous les temps via l'auxiliaire être", "temps = auxiliaire être conjugué", "Elle sera convoquée demain.", "être à tous les temps + participe", "temps = auxiliaire être conjugué"),
        ("vp-on", "Alternative avec on", "On + actif = équivalent courant du passif en français parlé", "on + actif = passif informel", "On parle français ici = Le français est parlé ici.", "on + actif remplace le passif", "on + actif = passif informel"),
        ("vp-pronominal", "Construction pronominale passive", "Forme réfléchie (se + verbe) exprimant un sens passif", "se + verbe = sens passif", "Ce vin se boit frais.", "se + verbe = passif de manière", "se + verbe = sens passif"),
        ("vp-limites", "Limites du passif", "Seuls les verbes transitifs directs (COD) peuvent être mis au passif", "COD uniquement → passif possible", "On ne peut pas mettre au passif les verbes avec COI.", "COD = passif; COI = pas de passif", "COD uniquement → passif possible"),
    ],
},

"les-temps-du-passe-recapitulatif": {
    "level": "b1",
    "section": "grammaire",
    "num": "G10",
    "short": "Récapitulatif des Temps du Passé",
    "title": "Récapitulatif des Temps du Passé",
    "subtitle": "PC, imparfait, PQP — choisir le bon temps",
    "slides": [
        ("Les quatre temps du passé en usage courant",
         "<strong>Passé composé (PC) :</strong> action accomplie, datée ou délimitée dans le passé.<br><strong>Imparfait (IMP) :</strong> état, description, habitude ou action en cours dans le passé.<br><strong>Plus-que-parfait (PQP) :</strong> action antérieure à une autre action passée.<br><strong>Passé simple (PS) :</strong> écrit littéraire — narration formelle."),
        ("Passé composé vs Imparfait",
         "PC = événement ponctuel, séquence d'actions, résultat visible.<br>IMP = décor, contexte, état mental/physique, habitude (souvent/toujours/chaque jour).<br><em>Il <strong>pleuvait</strong> (IMP) quand je <strong>suis sorti</strong> (PC).</em>"),
        ("Plus-que-parfait : l'antécédent du passé",
         "PQP = action déjà terminée AVANT l'action principale au passé.<br><em>Quand il est arrivé, elle <strong>avait déjà préparé</strong> le repas.</em><br>Marqueurs : déjà, avant de, parce que, comme."),
        ("Storytelling : les trois temps ensemble",
         "Dans un récit au passé, les trois temps se combinent :<br>IMP = décor / états → <em>Il faisait nuit, les rues étaient désertes.</em><br>PQP = contexte antérieur → <em>Il avait travaillé toute la journée.</em><br>PC = action narrative → <em>Soudain, il a entendu un bruit.</em>"),
        ("Expressions de temps associées",
         "PC : soudain, tout à coup, un jour, puis, ensuite, finalement.<br>IMP : toujours, souvent, chaque jour, à cette époque, d'habitude, quand (+ état).<br>PQP : déjà, avant que, parce que (+ raison antérieure)."),
        ("Passé simple — lecture uniquement",
         "Le PS est réservé à la littérature et l'écrit formel. On le reconnaît mais ne le produit pas en oral. Il <em>parla</em> (PC : il a parlé), il <em>prit</em> (PC : il a pris), ils <em>vinrent</em> (PC : ils sont venus)."),
    ],
    "traps": [
        ("Avant / Après", "'Avant de + inf.' = action non encore faite. 'Après + inf. passé' = action déjà faite. Pour l'antériorité dans le passé → PQP, pas PC seul."),
        ("Habitude = toujours imparfait", "Quand on décrit une habitude passée (souvent, chaque matin, tous les jours…), utiliser l'imparfait, même pour des actions qui semblent ponctuelles."),
        ("Confusion PC / PQP", "PC marque une action dans la ligne narrative principale. PQP marque un flash-back antérieur. <em>Il était parti avant que j'arrive</em> (PQP), pas <em>il est parti</em>."),
        ("Passé simple en lecture", "À l'écrit, -a/-it/-ut/-int sont souvent du passé simple. Les reconnaître mais les reformuler en PC à l'oral."),
    ],
    "summary": [
        "<strong>PC</strong> = action accomplie, ponctuelle ou délimitée dans le passé.",
        "<strong>Imparfait</strong> = état, habitude, contexte, action en cours.",
        "<strong>PQP</strong> = action antérieure à une autre action passée.",
        "Dans un récit : IMP (décor) + PQP (contexte) + PC (événements).",
        "Passé simple : uniquement à l'écrit formel — reconnaître, pas produire.",
    ],
    "ex1": {
        "q": "Elle ___ (regarder) la télé quand le téléphone ___ (sonner).",
        "opts": [
            "regardait / a sonné",
            "a regardé / sonnait",
            "regardait / sonnait",
            "avait regardé / a sonné",
        ],
        "ans": "regardait / a sonné",
        "exp": "Action en cours (décor) → imparfait : regardait. Événement ponctuel interrompant → PC : a sonné. Les deux au même temps (regardait/sonnait) ne distingue pas les deux actions.",
    },
    "ex2": {
        "q": "Mettez au bon temps : 'Quand il est arrivé, elle ___ (déjà / partir).'",
        "ans": "était déjà partie",
        "exp": "Action antérieure à 'il est arrivé' → PQP. 'Partir' prend être → était partie. 'Déjà' se place entre les deux éléments de l'auxiliaire : était déjà partie.",
        "accept": ["était déjà partie", "elle était déjà partie", "était déjà partie."],
    },
    "ex3": {
        "q": "Laquelle de ces phrases est la description de décor (imparfait) ?",
        "opts": [
            "Le soleil brillait et les oiseaux chantaient.",
            "Soudain, il a crié.",
            "Hier, elle a acheté des fleurs.",
            "Quand tu as appelé, j'ai dormi.",
        ],
        "ans": "Le soleil brillait et les oiseaux chantaient.",
        "exp": "Description de l'état/décor → imparfait (brillait, chantaient). 'Soudain il a crié' = événement ponctuel (PC). 'Hier elle a acheté' = action accomplie (PC). 'Quand tu as appelé, j'ai dormi' : dormi devrait être à l'imparfait pour exprimer l'action en cours.",
    },
    "game_desc": "Temps du passé — choisir entre PC, imparfait et PQP",
    "items": [
        ("rp-pc", "Passé composé", "Action accomplie, ponctuelle ou délimitée dans le passé", "action ponctuelle ou accomplie", "Hier, il a téléphoné.", "action délimitée dans le passé", "action ponctuelle ou accomplie"),
        ("rp-imp", "Imparfait", "État, habitude ou action en cours dans le passé", "état, habitude, décor", "Il faisait beau ce matin-là.", "contexte / décor = imparfait", "état, habitude, décor"),
        ("rp-pqp", "Plus-que-parfait", "Action antérieure à une autre action passée", "avant une autre action passée", "Elle avait déjà mangé quand il est arrivé.", "antériorité = PQP", "avant une autre action passée"),
        ("rp-recit", "Récit au passé", "IMP (décor) + PQP (contexte antérieur) + PC (événements narratifs)", "combiner IMP + PQP + PC", "Il faisait nuit. Il avait travaillé. Soudain, il a entendu…", "trois temps combinés dans un récit", "combiner IMP + PQP + PC"),
        ("rp-habitude", "Habitude = imparfait", "Les actions habituelles dans le passé prennent l'imparfait", "habitude passée = imparfait", "Chaque matin, il prenait un café.", "habitude = toujours imparfait", "habitude passée = imparfait"),
        ("rp-soudain", "Soudain = PC", "Les marqueurs d'événement ponctuel (soudain, tout à coup) signalent le PC", "marqueur ponctuel = PC", "Tout à coup, elle a compris.", "soudain/tout à coup = PC", "marqueur ponctuel = PC"),
        ("rp-deja-pqp", "Déjà + PQP", "Déjà souligne l'antériorité au plus-que-parfait", "déjà + PQP = antériorité", "Il avait déjà vu ce film.", "déjà renforce le PQP", "déjà + PQP = antériorité"),
        ("rp-ps", "Passé simple", "Temps littéraire de la narration formelle — reconnaître sans produire", "passé simple = écrit littéraire", "Il parla longuement. (= il a parlé)", "passé simple = narration formelle", "passé simple = écrit littéraire"),
    ],
},

"les-prepositions-avancees": {
    "level": "b1",
    "section": "grammaire",
    "num": "G11",
    "short": "Les Prépositions Avancées",
    "title": "Les Prépositions Avancées",
    "subtitle": "Prépositions de temps, de lieu et de manière",
    "slides": [
        ("Prépositions de temps",
         "<em>en</em> + mois/saison/an : <em>en mars, en été, en 2024</em>.<br><em>dans</em> + durée future : <em>dans dix minutes</em>.<br><em>depuis</em> + point de départ : <em>depuis lundi</em>.<br><em>pendant</em> + durée : <em>pendant deux heures</em>.<br><em>il y a</em> + durée passée : <em>il y a trois jours</em>."),
        ("Depuis vs Pendant vs Pour",
         "<em>depuis</em> : action toujours en cours → présent ou imparfait. <em>J'habite ici depuis 2010.</em><br><em>pendant</em> : durée limitée, terminée. <em>J'ai habité là-bas pendant un an.</em><br><em>pour</em> : durée prévue dans le futur. <em>Je pars pour trois semaines.</em>"),
        ("Prépositions de lieu",
         "<em>à</em> : ville, position. <em>sur</em> : sur/au-dessus. <em>sous</em> : sous. <em>devant / derrière</em>. <em>entre</em>. <em>en face de</em>. <em>à côté de</em>. <em>au bout de</em>. <em>en haut de / en bas de</em>.<br><em>chez</em> : chez quelqu'un (à la maison de)."),
        ("Prépositions de manière",
         "<em>avec</em> : avec soin. <em>sans</em> : sans effort. <em>par</em> : par hasard, par écrit, par cœur. <em>en</em> : en voiture, en silence, en colère. <em>à</em> : à pied, à voix haute, à temps."),
        ("Prépositions avec pays et villes",
         "Villes → <em>à</em> : à Paris, à Madrid.<br>Pays féminins / commençant par voyelle → <em>en</em> : en France, en Espagne, en Iran.<br>Pays masculins → <em>au</em> : au Portugal, au Japon.<br>Pays pluriels → <em>aux</em> : aux États-Unis.<br>Retour : <em>de / du / de la / des</em>."),
        ("Prépositions figées avec verbes",
         "Penser <em>à</em> · rêver <em>de</em> · parler <em>de</em> · s'occuper <em>de</em> · profiter <em>de</em> · remercier <em>de/pour</em> · féliciter <em>pour</em> · dépendre <em>de</em> · croire <em>à/en</em> · ressembler <em>à</em>."),
    ],
    "traps": [
        ("<em>Dans</em> vs <em>en</em> pour les durées", "'Dans' = durée avant la fin d'une action future (dans 5 min = dans 5 minutes ce sera fait). 'En' = durée pour accomplir une action (en 5 min = il faut 5 min). *En dix minutes, j'arrive ≠ dans dix minutes."),
        ("<em>Depuis</em> + présent (pas passé composé)", "Pour une action toujours en cours, on utilise le présent + depuis : <em>Je travaille ici depuis 5 ans</em> (pas *j'ai travaillé)."),
        ("Pays masculins vs féminins", "La plupart des pays se terminant par -e sont féminins (France, Espagne). Exceptions : le Mexique, le Cambodge, le Mozambique. Masculins courants : le Japon, le Brésil, le Canada, le Portugal."),
        ("<em>Chez</em> ne s'emploie qu'avec des personnes ou des marques", "<em>chez le médecin, chez moi, chez Renault</em>. Pour les lieux physiques, on utilise à, dans ou au : <em>dans le restaurant</em> (pas *chez le restaurant sauf sens figuré de marque)."),
    ],
    "summary": [
        "<strong>Depuis</strong> = action en cours; <strong>pendant</strong> = durée terminée; <strong>pour</strong> = durée prévue.",
        "<strong>Dans</strong> + durée future; <strong>en</strong> + temps mis pour faire qqch.",
        "Pays : <strong>en</strong> (féminin), <strong>au</strong> (masculin), <strong>aux</strong> (pluriel); villes → <strong>à</strong>.",
        "Prépositions figées : penser à, rêver de, s'occuper de…",
        "<strong>Chez</strong> = à la maison de / au cabinet de (personnes/marques uniquement).",
    ],
    "ex1": {
        "q": "Elle habite à Lyon ___ cinq ans. (durée toujours en cours)",
        "opts": ["depuis", "pendant", "pour", "dans"],
        "ans": "depuis",
        "exp": "'Depuis' exprime une durée qui a commencé dans le passé et continue dans le présent. 'Pendant' = durée terminée. 'Pour' = durée future prévue. 'Dans' = avant l'échéance.",
    },
    "ex2": {
        "q": "Complétez : 'Je pars ___ Japon la semaine prochaine.'",
        "ans": "au",
        "exp": "Le Japon est un pays masculin → préposition 'au' (à + le). Les pays masculins commençant par une consonne prennent 'au'.",
        "accept": ["au", "au Japon"],
    },
    "ex3": {
        "q": "Quelle phrase est correcte ?",
        "opts": [
            "J'ai appris cette chanson en dix minutes.",
            "J'ai appris cette chanson dans dix minutes.",
            "J'habite ici depuis trois ans passés.",
            "Il travaille ici pendant 2020.",
        ],
        "ans": "J'ai appris cette chanson en dix minutes.",
        "exp": "'En + durée' = temps nécessaire pour accomplir une action. 'Dans + durée' = dans combien de temps une action aura lieu. 'Depuis trois ans passés' est incorrect (on dit depuis trois ans). 'Pendant 2020' est incorrect (pendant s'utilise avec une durée, pas une année seule).",
    },
    "game_desc": "Prépositions avancées — temps, lieu, pays",
    "items": [
        ("prep-depuis", "Depuis", "Action toujours en cours depuis un point de départ dans le passé + présent", "durée en cours → depuis + présent", "Il habite ici depuis 2015.", "action en cours = depuis + présent", "durée en cours → depuis + présent"),
        ("prep-pendant", "Pendant", "Durée limitée et terminée dans le passé ou le futur", "durée terminée → pendant", "J'ai étudié pendant deux heures.", "durée finie = pendant", "durée terminée → pendant"),
        ("prep-pour", "Pour (durée)", "Durée prévue, planifiée dans le futur", "durée future prévue → pour", "Je pars pour une semaine.", "durée planifiée = pour", "durée future prévue → pour"),
        ("prep-dans-duree", "Dans + durée", "Temps restant avant qu'une action ait lieu", "temps avant l'échéance → dans", "Le train part dans 5 minutes.", "dans = avant l'échéance", "temps avant l'échéance → dans"),
        ("prep-en-duree", "En + durée", "Temps nécessaire pour accomplir une action", "temps mis pour faire = en", "Il a couru le marathon en 3 heures.", "en = temps pour accomplir", "temps nécessaire pour faire = en"),
        ("prep-pays-en", "En + pays féminin", "En + pays féminin ou commençant par une voyelle", "pays féminin → en", "en France, en Espagne, en Italie", "pays féminin = en", "pays féminin → en"),
        ("prep-pays-au", "Au + pays masculin", "Au + pays masculin commençant par une consonne", "pays masculin → au", "au Japon, au Portugal, au Brésil", "pays masculin = au", "pays masculin → au"),
        ("prep-chez", "Chez", "Préposition pour 'à la maison/au bureau de' (personnes ou marques)", "chez = à la maison de qqn", "Je suis chez le médecin.", "chez = lieu de qqn", "chez = à la maison de qqn"),
    ],
},

"les-expressions-idiomatiques": {
    "level": "b1",
    "section": "grammaire",
    "num": "G12",
    "short": "Expressions Idiomatiques B1",
    "title": "Expressions Idiomatiques B1",
    "subtitle": "Expressions figées courantes du français",
    "slides": [
        ("Expressions avec <em>avoir</em>",
         "<em>avoir l'air</em> + adj. : paraître. <em>Avoir du mal à</em> : trouver difficile. <em>Avoir beau</em> + inf. : faire qqch en vain. <em>Avoir l'habitude de</em>. <em>Avoir envie de</em>. <em>Avoir honte de</em>. <em>Avoir hâte de</em> : être impatient."),
        ("Expressions avec <em>faire</em>",
         "<em>faire semblant de</em> : prétendre. <em>faire exprès</em> : intentionnellement. <em>faire attention à</em>. <em>faire confiance à</em>. <em>se faire à</em> : s'habituer. <em>faire la queue</em>. <em>ne faire que</em> + inf. : faire seulement qqch."),
        ("Expressions avec <em>mettre</em> et <em>prendre</em>",
         "<em>mettre du temps à</em> : prendre du temps pour. <em>se mettre à</em> : commencer. <em>prendre le temps de</em>. <em>prendre en compte</em> : considérer. <em>prendre la parole</em> : commencer à parler. <em>prendre conscience de</em>."),
        ("Expressions avec <em>se</em> (pronominaux)",
         "<em>se rendre compte de</em> : réaliser. <em>s'en sortir</em> : s'en tirer. <em>s'y mettre</em> : commencer. <em>en vouloir à</em> : être fâché contre. <em>se passer de</em> : faire sans. <em>s'en aller</em> : partir."),
        ("Expressions idiomatiques diverses",
         "<em>au fur et à mesure</em> : progressivement. <em>à la longue</em> : avec le temps. <em>tant bien que mal</em> : difficilement mais quand même. <em>de toute façon</em> : de toute manière. <em>quoi qu'il en soit</em> : quoi qu'il arrive."),
        ("Registre : familier vs standard",
         "Familier → Standard : <em>bosser</em> (travailler) · <em>bouquin</em> (livre) · <em>boulot</em> (travail) · <em>sympa</em> (sympathique) · <em>chouette</em> (agréable).<br>Les expressions idiomatiques varient selon le registre — apprendre quel registre les utilise."),
    ],
    "traps": [
        ("<em>Avoir beau</em> ne signifie pas 'beau'", "'Il a beau essayer' = même s'il essaie / il a beau faire qqch mais sans résultat. Ce n'est pas un compliment sur l'apparence."),
        ("<em>Se rendre compte</em> ne se traduit pas mot à mot", "'Se rendre compte de' = to realize. *'Réaliser' existe mais est un faux ami partiel — réaliser qqch = to carry out sth. Pour 'to realize', préférer 'se rendre compte'."),
        ("<em>Faire semblant</em> vs <em>faire exprès</em>", "Faire semblant = prétendre (feindre). Faire exprès = agir intentionnellement. <em>Il fait semblant de dormir</em> (il fait comme s'il dormait). <em>Il l'a fait exprès</em> (ce n'était pas un accident)."),
        ("<em>Ne faire que</em> + infinitif", "Cette structure exprime qu'on ne fait rien d'autre : <em>Il ne fait que se plaindre</em> = Il se plaint continuellement. L'infinitif est à la forme positive (pas de ne…pas autour du verbe principal)."),
    ],
    "summary": [
        "<strong>avoir beau</strong> + inf. = faire en vain; <strong>avoir du mal à</strong> = trouver difficile.",
        "<strong>faire semblant</strong> = prétendre; <strong>faire exprès</strong> = intentionnellement.",
        "<strong>se mettre à</strong> = commencer; <strong>se rendre compte</strong> = réaliser.",
        "<strong>au fur et à mesure</strong> = progressivement; <strong>de toute façon</strong> = anyway.",
        "Apprendre le <strong>registre</strong> de chaque expression (familier vs standard).",
    ],
    "ex1": {
        "q": "Il ___ essayer, rien ne change. (en vain)",
        "opts": ["a beau", "a beau de", "fait semblant de", "a du mal à"],
        "ans": "a beau",
        "exp": "'Avoir beau + infinitif' exprime une action faite en vain. 'A beau de' est incorrect (avoir beau ne prend pas de préposition). 'Fait semblant de' = prétend. 'A du mal à' = trouve difficile.",
    },
    "ex2": {
        "q": "Complétez : 'Elle n'a pas remarqué tout de suite, mais elle s'en est ___ ___.' (réaliser)",
        "ans": "rendu compte",
        "exp": "Se rendre compte (de) = réaliser, prendre conscience. Au passé composé pronominal : s'est rendu compte.",
        "accept": ["rendu compte", "elle s'en est rendu compte", "s'en est rendu compte"],
    },
    "ex3": {
        "q": "Laquelle de ces expressions signifie 'progressivement' ?",
        "opts": [
            "au fur et à mesure",
            "de toute façon",
            "quoi qu'il en soit",
            "tant bien que mal",
        ],
        "ans": "au fur et à mesure",
        "exp": "'Au fur et à mesure' = progressivement, en avançant. 'De toute façon' = anyway. 'Quoi qu'il en soit' = whatever happens. 'Tant bien que mal' = avec difficulté mais quand même.",
    },
    "game_desc": "Expressions idiomatiques B1 — avoir, faire, se rendre compte",
    "items": [
        ("ei-avoir-beau", "Avoir beau + inf.", "Faire quelque chose en vain, sans résultat", "action vaine → avoir beau + inf.", "Il a beau travailler, il n'avance pas.", "avoir beau = agir en vain", "action vaine → avoir beau + inf."),
        ("ei-avoir-mal", "Avoir du mal à", "Trouver quelque chose difficile", "difficulté → avoir du mal à", "J'ai du mal à comprendre cet exercice.", "avoir du mal à = trouver difficile", "difficulté → avoir du mal à"),
        ("ei-faire-semblant", "Faire semblant de", "Prétendre, simuler une action", "prétendre = faire semblant", "Il fait semblant de ne pas entendre.", "faire semblant = prétendre", "prétendre = faire semblant"),
        ("ei-faire-expres", "Faire exprès", "Agir intentionnellement, délibérément", "intentionnel → faire exprès", "Elle a fait exprès d'arriver en retard.", "faire exprès = intentionnel", "intentionnel → faire exprès"),
        ("ei-se-mettre", "Se mettre à", "Commencer une action (souvent soudainement)", "commencer → se mettre à", "Il s'est mis à pleuvoir.", "se mettre à = commencer", "commencer → se mettre à"),
        ("ei-rendre-compte", "Se rendre compte de", "Réaliser, prendre conscience de quelque chose", "réaliser → se rendre compte de", "Elle s'est rendu compte de son erreur.", "se rendre compte = réaliser", "réaliser → se rendre compte de"),
        ("ei-au-fur", "Au fur et à mesure", "Progressivement, en même temps que quelque chose avance", "progressivement = au fur et à mesure", "Au fur et à mesure, il comprenait mieux.", "au fur et à mesure = progressivement", "progressivement = au fur et à mesure"),
        ("ei-ne-faire-que", "Ne faire que + inf.", "Faire seulement une chose, continuellement", "seulement + continuellement → ne faire que", "Il ne fait que se plaindre.", "ne faire que = seulement, toujours", "seulement + continuellement → ne faire que"),
    ],
},

}
