"""francais B2 vocabulary — V01–V04"""

CHAPTERS = {
    "la-politique": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V01",
        "short": "La Politique",
        "title": "La Politique",
        "subtitle": "Vocab — démocratie, gouvernance et engagement civique",
        "game_desc": "Maîtrisez le vocabulaire politique avancé",
        "words": [
            {"word": "le suffrage universel", "ipa": "/syf.ʁaʒ y.ni.vɛʁ.sɛl/", "def": "droit de vote accordé à tous les citoyens adultes", "ex": "Le suffrage universel a été instauré en France en 1848 pour les hommes."},
            {"word": "le scrutin", "ipa": "/skʁy.tɛ̃/", "def": "mode de vote ; résultat d'une élection", "ex": "Au second tour du scrutin, les électeurs choisissent entre deux candidats."},
            {"word": "la laïcité", "ipa": "/la.i.si.te/", "def": "séparation de l'Église et de l'État", "ex": "La laïcité est l'un des principes fondamentaux de la République française."},
            {"word": "le mandat", "ipa": "/mɑ̃.da/", "def": "durée pendant laquelle un élu exerce ses fonctions", "ex": "Le président de la République française a un mandat de cinq ans."},
            {"word": "la souveraineté", "ipa": "/su.vʁɛ.nə.te/", "def": "pouvoir suprême d'un État sur son territoire", "ex": "La souveraineté nationale appartient au peuple."},
            {"word": "le lobbying", "ipa": "/lɔ.bjɪŋ/", "def": "activité visant à influencer des décisions politiques", "ex": "Les associations environnementales font du lobbying auprès du gouvernement."},
            {"word": "la coalition", "ipa": "/kɔ.a.li.sjɔ̃/", "def": "alliance de partis politiques pour gouverner ensemble", "ex": "Aucun parti n'ayant la majorité, une coalition a été formée."},
            {"word": "le référendum", "ipa": "/ʁe.fe.ʁɑ̃.dɔm/", "def": "vote direct des citoyens sur une question précise", "ex": "En 2005, un référendum a été organisé sur le traité constitutionnel européen."},
            {"word": "la démagogie", "ipa": "/de.ma.gɔ.ʒi/", "def": "discours flatteur qui exploite les émotions du peuple", "ex": "Les experts ont critiqué ses promesses impossibles, qualifiant cela de démagogie."},
            {"word": "le pluralisme", "ipa": "/ply.ʁa.lism/", "def": "coexistence de plusieurs partis, courants ou opinions", "ex": "Le pluralisme politique est garanti par la Constitution."},
            {"word": "l'abstention (f)", "ipa": "/aps.tɑ̃.sjɔ̃/", "def": "fait de ne pas voter lors d'une élection", "ex": "Le taux d'abstention record lors des élections inquiète les élus."},
            {"word": "la censure", "ipa": "/sɑ̃.syʁ/", "def": "contrôle et suppression de contenus jugés indésirables", "ex": "L'Assemblée nationale a voté une motion de censure contre le gouvernement."},
            {"word": "le clivage", "ipa": "/kli.vaʒ/", "def": "division profonde entre groupes politiques ou sociaux", "ex": "Le clivage gauche-droite structure encore la vie politique française."},
            {"word": "la transparence", "ipa": "/tʁɑ̃s.pa.ʁɑ̃s/", "def": "obligation pour les élus de rendre leurs actes accessibles au public", "ex": "Les lois sur la transparence obligent les ministres à déclarer leurs revenus."},
            {"word": "l'immunité parlementaire (f)", "ipa": "/i.my.ni.te paʁ.lə.mɑ̃.tɛʁ/", "def": "protection légale accordée aux membres du parlement", "ex": "L'immunité parlementaire empêche qu'un député soit poursuivi pour ses votes."},
        ],
        "items": [
            ("politique-suffrage", "le suffrage universel", "droit de vote pour tous les citoyens adultes", "le vote de tous · droit civique · élection", "Le suffrage universel garantit que chaque voix compte dans une démocratie.", "suffrage universel = droit de vote pour tous", "droit de vote pour tous"),
            ("politique-scrutin", "le scrutin", "mode ou résultat d'un vote", "tour de vote · élection · bulletin", "Le candidat a remporté le scrutin dès le premier tour.", "scrutin = mode ou résultat d'un vote", "mode ou résultat d'un vote"),
            ("politique-laicite", "la laïcité", "séparation de l'Église et de l'État", "neutralité religieuse · principe républicain · État", "La laïcité garantit la neutralité religieuse de l'école publique.", "laïcité = séparation Église-État", "séparation de l'Église et de l'État"),
            ("politique-mandat", "le mandat", "durée d'exercice d'une fonction élective", "quinquennat · terme · mandat présidentiel", "Après deux mandats, le président ne peut pas se représenter.", "mandat = durée d'une fonction élective", "durée d'exercice d'une fonction élective"),
            ("politique-souverainete", "la souveraineté", "pouvoir suprême d'un État", "indépendance · autorité · nation", "La souveraineté nationale s'exprime par les urnes.", "souveraineté = pouvoir suprême d'un État", "pouvoir suprême d'un État"),
            ("politique-coalition", "la coalition", "alliance de partis pour gouverner", "alliance · accord · gouvernement", "La coalition a réussi à former un gouvernement stable.", "coalition = alliance de partis", "alliance de partis pour gouverner"),
            ("politique-referendum", "le référendum", "vote direct des citoyens sur une question", "consultation · plébiscite · vote populaire", "Le référendum a rejeté la réforme proposée par le gouvernement.", "référendum = vote direct du peuple", "vote direct des citoyens sur une question"),
            ("politique-abstention", "l'abstention", "fait de ne pas voter", "non-participation · désengagement · taux", "La forte abstention traduit une crise de confiance envers les élus.", "abstention = refus de voter", "fait de ne pas voter"),
        ],
    },

    "la-philosophie": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V02",
        "short": "La Philosophie",
        "title": "La Philosophie",
        "subtitle": "Vocab — concepts, courants et penseurs",
        "game_desc": "Maîtrisez le vocabulaire philosophique avancé",
        "words": [
            {"word": "l'empirisme (m)", "ipa": "/ɑ̃.pi.ʁism/", "def": "doctrine selon laquelle la connaissance vient de l'expérience sensible", "ex": "L'empirisme de Locke s'oppose au rationalisme de Descartes."},
            {"word": "le rationalisme", "ipa": "/ʁa.sjɔ.na.lism/", "def": "doctrine selon laquelle la raison est la source principale de la connaissance", "ex": "Le rationalisme affirme que certaines vérités sont accessibles par la seule raison."},
            {"word": "la dialectique", "ipa": "/dja.lɛk.tik/", "def": "méthode de raisonnement par opposition et dépassement de contradictions", "ex": "La dialectique hégélienne repose sur la thèse, l'antithèse et la synthèse."},
            {"word": "l'ontologie (f)", "ipa": "/ɔ̃.tɔ.lɔ.ʒi/", "def": "branche de la philosophie qui étudie l'être en tant qu'être", "ex": "La question centrale de l'ontologie est : 'Qu'est-ce qui existe vraiment ?'"},
            {"word": "l'éthique (f)", "ipa": "/e.tik/", "def": "réflexion sur les valeurs morales et la conduite humaine", "ex": "L'éthique médicale encadre les décisions difficiles dans les soins de santé."},
            {"word": "le déterminisme", "ipa": "/de.tɛʁ.mi.nism/", "def": "doctrine selon laquelle tout événement est causalement déterminé", "ex": "Le déterminisme remet en question la notion de libre arbitre."},
            {"word": "l'épistémologie (f)", "ipa": "/e.pis.te.mɔ.lɔ.ʒi/", "def": "étude philosophique de la nature et des limites de la connaissance", "ex": "L'épistémologie s'interroge sur la validité des méthodes scientifiques."},
            {"word": "le nihilisme", "ipa": "/ni.i.lism/", "def": "doctrine qui nie toute valeur morale ou sociale absolue", "ex": "Nietzsche a critiqué le nihilisme tout en y voyant un passage nécessaire."},
            {"word": "l'utilitarisme (m)", "ipa": "/y.ti.li.ta.ʁism/", "def": "doctrine morale qui juge les actes par leurs conséquences sur le bonheur collectif", "ex": "L'utilitarisme de Bentham préconise le plus grand bonheur du plus grand nombre."},
            {"word": "la phénoménologie", "ipa": "/fe.nɔ.me.nɔ.lɔ.ʒi/", "def": "méthode philosophique qui part de l'expérience vécue du sujet", "ex": "Husserl a fondé la phénoménologie pour décrire les structures de la conscience."},
            {"word": "l'aliénation (f)", "ipa": "/a.lje.na.sjɔ̃/", "def": "état de dépossession de soi-même ; sentiment d'être étranger à sa propre vie", "ex": "Marx considérait que le travail industriel provoquait l'aliénation de l'ouvrier."},
            {"word": "la transcendance", "ipa": "/tʁɑ̃s.sɑ̃.dɑ̃s/", "def": "caractère de ce qui dépasse les limites de l'expérience humaine", "ex": "La transcendance divine est un concept central dans les religions monothéistes."},
            {"word": "l'immanence (f)", "ipa": "/i.ma.nɑ̃s/", "def": "caractère de ce qui est contenu dans la réalité même, sans extériorité", "ex": "Spinoza défend une vision de l'immanence où Dieu et nature sont un."},
            {"word": "le libre arbitre", "ipa": "/libʁ aʁ.bitʁ/", "def": "capacité humaine de faire des choix libres, sans contrainte causale totale", "ex": "La question du libre arbitre oppose déterministes et philosophes de la liberté."},
            {"word": "l'existentialisme (m)", "ipa": "/ɛɡ.zis.tɑ̃.sja.lism/", "def": "courant philosophique centré sur l'existence individuelle et la liberté de choix", "ex": "Sartre résume l'existentialisme par la formule : 'l'existence précède l'essence'."},
        ],
        "items": [
            ("philo-empirisme", "l'empirisme", "connaissance fondée sur l'expérience sensible", "expérience · sens · observation", "Pour l'empiriste, toute idée vient d'abord des sens.", "empirisme = connaissance par l'expérience", "connaissance fondée sur l'expérience sensible"),
            ("philo-dialectique", "la dialectique", "raisonnement par opposition de contraires", "thèse · antithèse · synthèse", "La dialectique hégélienne mène à une synthèse dépassant les contradictions.", "dialectique = raisonnement par opposition", "raisonnement par opposition de contraires"),
            ("philo-ethique", "l'éthique", "réflexion sur les valeurs morales et la conduite", "morale · valeurs · bien et mal", "L'éthique nous pousse à réfléchir avant d'agir.", "éthique = réflexion sur les valeurs morales", "réflexion sur les valeurs morales et la conduite"),
            ("philo-determinisme", "le déterminisme", "doctrine où tout événement est causalement déterminé", "cause · effet · liberté", "Le déterminisme suppose que nos actes sont dictés par des causes antérieures.", "déterminisme = tout est déterminé par des causes", "doctrine où tout événement est causalement déterminé"),
            ("philo-nihilisme", "le nihilisme", "rejet de toute valeur morale absolue", "néant · rejet · valeurs", "Le nihilisme remet en cause le fondement même de la morale.", "nihilisme = rejet de toute valeur absolue", "rejet de toute valeur morale absolue"),
            ("philo-utilitarisme", "l'utilitarisme", "morale fondée sur le bonheur du plus grand nombre", "bonheur · conséquences · collectif", "L'utilitarisme évalue une action à l'aune de ses effets sur le bien commun.", "utilitarisme = bonheur du plus grand nombre", "morale fondée sur le bonheur du plus grand nombre"),
            ("philo-alienation", "l'aliénation", "dépossession de soi, sentiment d'être étranger à sa vie", "dépossession · travail · Marx", "L'aliénation au travail est un thème central de la philosophie marxiste.", "aliénation = sentiment d'être étranger à soi", "dépossession de soi, sentiment d'être étranger à sa vie"),
            ("philo-existentialisme", "l'existentialisme", "courant philosophique centré sur la liberté individuelle", "liberté · choix · Sartre", "L'existentialisme insiste sur la responsabilité de chacun face à ses actes.", "existentialisme = liberté et responsabilité individuelles", "courant philosophique centré sur la liberté individuelle"),
        ],
    },

    "les-sciences": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V03",
        "short": "Les Sciences",
        "title": "Les Sciences",
        "subtitle": "Vocab — méthode, recherche et découvertes",
        "game_desc": "Maîtrisez le vocabulaire scientifique avancé",
        "words": [
            {"word": "l'hypothèse (f)", "ipa": "/i.pɔ.tɛz/", "def": "proposition provisoire à vérifier par l'expérience", "ex": "Les chercheurs ont formulé une hypothèse sur l'origine de la maladie."},
            {"word": "le paradigme", "ipa": "/pa.ʁa.dim/", "def": "modèle théorique dominant dans une communauté scientifique", "ex": "La relativité d'Einstein a provoqué un changement de paradigme en physique."},
            {"word": "la reproductibilité", "ipa": "/ʁə.pʁɔ.dyk.ti.bi.li.te/", "def": "capacité d'une expérience à donner les mêmes résultats dans d'autres conditions", "ex": "La reproductibilité des expériences est essentielle à la validité scientifique."},
            {"word": "le biais", "ipa": "/bjɑ/", "def": "erreur systématique qui fausse les résultats d'une étude", "ex": "Le biais de confirmation pousse à ne retenir que les données qui confirment ses attentes."},
            {"word": "l'inférence (f)", "ipa": "/ɛ̃.fe.ʁɑ̃s/", "def": "processus de déduction logique à partir de données", "ex": "L'inférence statistique permet d'estimer des paramètres à partir d'un échantillon."},
            {"word": "la peer review", "ipa": "/piːʁ ʁi.vju/", "def": "évaluation par les pairs d'un travail scientifique avant publication", "ex": "Son article a été accepté après une peer review rigoureuse."},
            {"word": "le génie génétique", "ipa": "/ʒe.ni ʒe.ne.tik/", "def": "ensemble des techniques de modification de l'ADN des organismes vivants", "ex": "Le génie génétique permet de créer des cultures résistantes aux maladies."},
            {"word": "la nanotechnologie", "ipa": "/na.nɔ.tɛk.nɔ.lɔ.ʒi/", "def": "manipulation de la matière à l'échelle atomique et moléculaire", "ex": "La nanotechnologie ouvre des perspectives révolutionnaires en médecine."},
            {"word": "le chercheur / la chercheuse", "ipa": "/ʃɛʁ.ʃœʁ/", "def": "personne qui conduit des recherches scientifiques", "ex": "La chercheuse a publié ses résultats dans une revue internationale."},
            {"word": "l'essai clinique (m)", "ipa": "/e.sɛ kli.nik/", "def": "étude contrôlée testant l'efficacité d'un traitement sur des patients", "ex": "Le médicament est en phase III d'essai clinique avant sa mise sur le marché."},
            {"word": "la falsifiabilité", "ipa": "/fal.si.fja.bi.li.te/", "def": "capacité d'une théorie à être réfutée par des observations", "ex": "Popper exigeait la falsifiabilité comme critère de scientificité."},
            {"word": "l'échantillon (m)", "ipa": "/e.ʃɑ̃.ti.jɔ̃/", "def": "sous-ensemble représentatif d'une population étudiée", "ex": "L'étude portait sur un échantillon de 2 000 participants."},
            {"word": "la variable indépendante", "ipa": "/va.ʁjabl ɛ̃.de.pɑ̃.dɑ̃t/", "def": "facteur manipulé par le chercheur pour observer son effet", "ex": "Dans l'expérience, la température était la variable indépendante."},
            {"word": "la corrélation", "ipa": "/kɔ.ʁe.la.sjɔ̃/", "def": "relation statistique entre deux variables, sans nécessairement impliquer une causalité", "ex": "Il y a une forte corrélation entre niveau d'éducation et espérance de vie."},
            {"word": "la peer pressure", "ipa": "/piːʁ pʁɛ.sœʁ/", "def": "pression exercée par un groupe sur un individu pour le conformer à ses normes", "ex": "La peer pressure peut freiner la pensée critique dans une équipe de recherche."},
        ],
        "items": [
            ("sciences-hypothese", "l'hypothèse", "proposition provisoire à vérifier par l'expérience", "supposition · test · vérification", "Toute démarche scientifique commence par formuler une hypothèse.", "hypothèse = proposition provisoire à vérifier", "proposition provisoire à vérifier par l'expérience"),
            ("sciences-paradigme", "le paradigme", "modèle théorique dominant dans une discipline", "modèle · cadre · révolution", "Un paradigme dominant oriente les questions qu'une discipline se pose.", "paradigme = modèle théorique dominant", "modèle théorique dominant dans une discipline"),
            ("sciences-biais", "le biais", "erreur systématique qui fausse les résultats", "distorsion · erreur · confirmation", "Identifier les biais est crucial pour garantir la rigueur d'une étude.", "biais = erreur systématique dans une étude", "erreur systématique qui fausse les résultats"),
            ("sciences-reproductibilite", "la reproductibilité", "capacité à reproduire les mêmes résultats", "répétition · vérification · fiabilité", "Sans reproductibilité, les résultats d'une expérience ne peuvent être validés.", "reproductibilité = mêmes résultats reproductibles", "capacité à reproduire les mêmes résultats"),
            ("sciences-falsifiabilite", "la falsifiabilité", "capacité d'une théorie à être réfutée", "réfutation · Popper · critère", "La falsifiabilité distingue la science des croyances non vérifiables.", "falsifiabilité = possibilité de réfutation", "capacité d'une théorie à être réfutée"),
            ("sciences-echantillon", "l'échantillon", "sous-ensemble représentatif d'une population", "population · représentation · taille", "Un petit échantillon peut biaiser les résultats d'une enquête.", "échantillon = sous-groupe représentatif", "sous-ensemble représentatif d'une population"),
            ("sciences-correlation", "la corrélation", "relation statistique entre deux variables", "lien · statistique · causalité", "Une corrélation n'implique pas nécessairement un lien de causalité.", "corrélation = relation statistique entre variables", "relation statistique entre deux variables"),
            ("sciences-essai-clinique", "l'essai clinique", "étude contrôlée testant un traitement sur des patients", "phase · médicament · patients", "Les essais cliniques de phase III impliquent des milliers de volontaires.", "essai clinique = test contrôlé d'un traitement", "étude contrôlée testant un traitement sur des patients"),
        ],
    },

    "le-droit": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V04",
        "short": "Le Droit",
        "title": "Le Droit",
        "subtitle": "Vocab — justice, loi et procédures",
        "game_desc": "Maîtrisez le vocabulaire juridique avancé",
        "words": [
            {"word": "la jurisprudence", "ipa": "/ʒy.ʁis.pʁy.dɑ̃s/", "def": "ensemble des décisions de justice qui font référence pour les affaires similaires", "ex": "La jurisprudence de la Cour de cassation influence les décisions des tribunaux inférieurs."},
            {"word": "le litige", "ipa": "/li.tiʒ/", "def": "désaccord juridique entre deux parties soumis à un tribunal", "ex": "Le litige commercial a été résolu à l'amiable sans passer par un procès."},
            {"word": "la présomption d'innocence", "ipa": "/pʁe.zɔ̃p.sjɔ̃ d‿i.nɔ.sɑ̃s/", "def": "principe selon lequel tout accusé est considéré innocent jusqu'à preuve du contraire", "ex": "La présomption d'innocence est un droit fondamental dans les pays démocratiques."},
            {"word": "le plaidoyer", "ipa": "/plɛ.dwa.je/", "def": "discours de défense prononcé devant un tribunal ; argument public en faveur d'une cause", "ex": "L'avocat a fait un plaidoyer convaincant pour la relaxe de son client."},
            {"word": "la mise en examen", "ipa": "/miz ɑ̃n‿ɛɡ.za.mɛ̃/", "def": "statut officiel d'un suspect faisant l'objet d'une enquête judiciaire", "ex": "Le chef d'entreprise a été placé en mise en examen pour fraude fiscale."},
            {"word": "le recours", "ipa": "/ʁə.kuʁ/", "def": "action d'appel ou de contestation d'une décision judiciaire", "ex": "La famille a déposé un recours devant la Cour européenne des droits de l'homme."},
            {"word": "la déposition", "ipa": "/de.po.zi.sjɔ̃/", "def": "déclaration faite sous serment devant un tribunal ou un enquêteur", "ex": "Le témoin a fait une déposition accablante pour l'accusé."},
            {"word": "l'inculpation (f)", "ipa": "/ɛ̃.kyl.pa.sjɔ̃/", "def": "mise en cause officielle d'une personne dans une affaire criminelle", "ex": "L'inculpation du ministre a provoqué une crise politique majeure."},
            {"word": "la prescription", "ipa": "/pʁɛs.kʁip.sjɔ̃/", "def": "extinction du droit de poursuivre après un certain délai", "ex": "Les crimes contre l'humanité sont imprescriptibles en droit français."},
            {"word": "l'acquittement (m)", "ipa": "/a.ki.tmɑ̃/", "def": "décision de justice déclarant un accusé non coupable", "ex": "Après dix ans de procédure, il a obtenu son acquittement."},
            {"word": "la juridiction", "ipa": "/ʒy.ʁi.dik.sjɔ̃/", "def": "autorité et compétence d'un tribunal pour juger certains types d'affaires", "ex": "Cette affaire relève de la juridiction du tribunal administratif."},
            {"word": "le droit positif", "ipa": "/dʁwa pɔ.zi.tif/", "def": "ensemble des règles juridiques en vigueur dans un État à un moment donné", "ex": "Le droit positif s'oppose au droit naturel dans la théorie juridique."},
            {"word": "la clause", "ipa": "/kloz/", "def": "disposition particulière d'un contrat ou d'un texte juridique", "ex": "La clause de non-concurrence interdit au salarié de travailler pour un concurrent."},
            {"word": "l'arbitrage (m)", "ipa": "/aʁ.bi.tʁaʒ/", "def": "mode de résolution des litiges par un tiers neutre en dehors des tribunaux", "ex": "Les deux entreprises ont opté pour l'arbitrage international pour régler leur différend."},
            {"word": "la peine suspendue", "ipa": "/pɛn sys.pɑ̃.dy/", "def": "condamnation dont l'exécution est différée sous conditions", "ex": "Le juge a prononcé une peine de prison suspendue assortie d'une mise à l'épreuve."},
        ],
        "items": [
            ("droit-jurisprudence", "la jurisprudence", "décisions de justice servant de référence", "précédent · tribunal · arrêt", "La jurisprudence crée un droit vivant au-delà des textes de loi.", "jurisprudence = décisions judiciaires de référence", "décisions de justice servant de référence"),
            ("droit-litige", "le litige", "désaccord juridique entre deux parties", "conflit · procès · tribunal", "Régler un litige à l'amiable évite souvent un procès long et coûteux.", "litige = désaccord juridique entre deux parties", "désaccord juridique entre deux parties"),
            ("droit-presomption", "la présomption d'innocence", "principe : innocent jusqu'à preuve du contraire", "innocent · accusé · preuve", "La présomption d'innocence protège tout accusé avant son jugement.", "présomption d'innocence = innocent jusqu'à preuve contraire", "principe : innocent jusqu'à preuve du contraire"),
            ("droit-recours", "le recours", "action d'appel ou contestation d'une décision", "appel · contestation · cour", "La victime a exercé un recours devant la cour d'appel.", "recours = appel d'une décision judiciaire", "action d'appel ou contestation d'une décision"),
            ("droit-prescription", "la prescription", "extinction du droit de poursuivre après un délai", "délai · imprescriptible · loi", "La prescription pénale varie selon la gravité des infractions.", "prescription = fin du droit de poursuivre", "extinction du droit de poursuivre après un délai"),
            ("droit-acquittement", "l'acquittement", "décision judiciaire déclarant l'accusé non coupable", "non-coupable · verdict · relaxe", "L'acquittement met fin aux poursuites pénales contre l'accusé.", "acquittement = verdict de non-culpabilité", "décision judiciaire déclarant l'accusé non coupable"),
            ("droit-clause", "la clause", "disposition particulière d'un contrat", "contrat · condition · disposition", "Lire attentivement les clauses d'un contrat avant de le signer est indispensable.", "clause = disposition particulière d'un contrat", "disposition particulière d'un contrat"),
            ("droit-arbitrage", "l'arbitrage", "résolution de litiges par un tiers neutre", "médiation · neutre · différend", "L'arbitrage international évite les procédures judiciaires étatiques.", "arbitrage = résolution amiable par un tiers", "résolution de litiges par un tiers neutre"),
        ],
    },
}
