"""
francais_c2_g2.py — French C2 Grammar chapters G07–G12
G07 La Rhétorique Argumentative Avancée
G08 Les Registres de Langue et la Variation Stylistique
G09 La Ponctuation Expressive et la Typographie Soutenue
G10 L'Orthographe des Accords Complexes
G11 La Syntaxe de l'Écrit Académique
G12 La Stylistique Comparée et l'Analyse de Discours
"""

CHAPTERS = {

# ── G07 La Rhétorique Argumentative Avancée ──────────────────────────────
"la-rhetorique-argumentative-avancee": {
    "level": "c2",
    "section": "grammaire",
    "num": "G07",
    "short": "Rhétorique avancée",
    "title": "La Rhétorique Argumentative Avancée",
    "subtitle": "Figures de pensée, stratégies de persuasion et argumentation sophistiquée",
    "slides": [
        ("Au-delà des figures de style", "À C2, la rhétorique n'est pas seulement un catalogue de figures : c'est la maîtrise stratégique de la persuasion. Cela implique de comprendre comment ethos (crédibilité), pathos (émotion) et logos (logique) se combinent et se renforcent mutuellement dans un discours efficace."),
        ("L'enthymème et le syllogisme rhétorique", "Syllogisme logique : Tous les hommes sont mortels + Socrate est un homme → Socrate est mortel. Enthymème : syllogisme incomplet où une prémisse est implicite. Ex. : 'Il est philosophe, donc il cherche la vérité.' (prémisse implicite : 'Tout philosophe cherche la vérité'). L'enthymème est plus persuasif car le lecteur complète lui-même et devient acteur du raisonnement."),
        ("La concession rhétorique avancée", "Stratégie pro-concessive : accorder généreusement l'antithèse pour mieux l'invalider. 'Certes, il est vrai que X — et personne ne peut le nier — cependant, cette concession même révèle que…' La concession renforce l'ethos du locuteur (il paraît honnête) tout en affaiblissant l'adversaire."),
        ("L'ironie et l'antiphrase soutenues", "Ironie = dire le contraire de ce qu'on pense pour créer un effet de décalage. Antiphrase = procédé microtextuel de l'ironie : 'Quel beau résultat !' (= lamentable). À C2, identifier l'ironie systémique (qui traverse tout un texte, pas juste une phrase) est essentiel. Indices : registres inadéquats, hyperboles absurdes, ton trop solennel sur un sujet trivial."),
        ("La prétérition et la paralipse", "Prétérition : affirmer qu'on ne dira pas quelque chose, tout en le disant : 'Je ne mentionnerai pas ses nombreux scandales…' La paralipse (ellipse narrative) est l'omission délibérée d'une information attendue pour en augmenter le poids implicite. Les deux impliquent le lecteur dans la construction du sens."),
        ("L'hypotypose et l'enargeia", "Hypotypose : description si vive et précise qu'elle rend la scène présente aux yeux du lecteur, comme si on y était. Liée à l'enargeia (évidence) dans la rhétorique classique. Procédés : présent de narration, accumulation sensorielle, dialogues directs, détails concrets. Effet : transformation du lecteur en témoin."),
        ("La réfutation et la concession sélective", "Stratégie avancée : réfuter non pas en niant l'antithèse mais en en acceptant sélectivement la part vraie et en montrant qu'elle ne contredit pas la thèse. Ex. : 'X a raison sur A, mais A n'implique pas non-B, au contraire…' Cela crée un discours plus solide que la simple dénégation."),
        ("Le topos et le lieu commun argumentatif", "Topos (lieu rhétorique) : argument type applicable à de nombreuses situations. Ex. : 'topos du plus/moins' (si X vaut pour le majeur, il vaut a fortiori pour le mineur). 'Topos de la définition' : démontrer par la définition du terme. 'Topos de l'exemple' : un cas concret illustre la règle générale. Connaître les topoi permet de construire des arguments rapidement."),
        ("L'apostrophe et l'interpellation directe", "Apostrophe : s'adresser directement à une personne ou une entité absente, à un objet ou à une abstraction. Ex. : 'Ô liberté, que de crimes on commet en ton nom !' Effet : dramatisation, élévation du registre, implication émotionnelle. Fréquente dans les oraisons funèbres, les manifestes et la poésie engagée."),
        ("La gradation thématique dans l'argumentation", "Structurer un développement de telle sorte que chaque argument successif soit plus fort, plus englobant ou plus fondamental que le précédent. Éviter de mettre le meilleur argument en premier (l'effet s'atténue). Construire vers un sommet argumentatif : l'argument ultime résout la problématique et ouvre l'horizon."),
    ],
    "traps": [
        ("Ironie non signalée", "L'ironie sans marqueur contextuel peut être prise au premier degré. À C2, en production, accompagner l'ironie d'un signal contextuel (guillemets, registre décalé, parenthèse) pour éviter le contresens. En analyse, chercher les indices de registre inadéquat."),
        ("Enthymème non reconstruit", "Accepter un enthymème sans vérifier la prémisse implicite : 'Il est riche, donc il est heureux.' (prémisse implicite : 'La richesse rend heureux' — questionnable). L'analyse critique d'un argument exige de rendre explicite toutes les prémisses."),
        ("Concession sans réfutation", "Accorder l'antithèse sans ensuite la réfuter ou la nuancer transforme l'essai en plaidoyer pour l'adversaire. La concession rhétorique doit toujours être suivie d'un pivot ('cependant', 'or', 'mais') et d'une réponse."),
        ("Confondre prétérition et paralipse", "Prétérition : je dis ce que je prétends ne pas dire. Paralipse : j'omets délibérément une information attendue. Les deux créent un non-dit ; mais la prétérition est active (mentionner en feignant de ne pas le faire) et la paralipse est passive (ne pas mentionner ce qu'on est censé raconter)."),
    ],
    "summary": [
        "Enthymème = syllogisme avec prémisse implicite — plus persuasif car le lecteur complète.",
        "Concession rhétorique avancée : accorder généreusement puis réfuter — renforce l'ethos.",
        "Ironie systémique : traverse tout un texte ; indices = registres inadéquats, hyperboles absurdes.",
        "Prétérition : dire ce qu'on prétend ne pas dire. Paralipse : omettre délibérément.",
        "Gradation thématique : argument le plus fort en dernier — construire vers un sommet.",
    ],
    "ex1": {
        "q": "Qu'est-ce qu'un enthymème ?",
        "opts": [
            "Un syllogisme logique complet avec trois propositions explicites",
            "Un syllogisme rhétorique avec une prémisse implicite",
            "Une figure de style basée sur la répétition",
            "Une technique de concession sans réfutation",
        ],
        "ans": "Un syllogisme rhétorique avec une prémisse implicite",
        "exp": "L'enthymème est un syllogisme incomplet : une des prémisses reste implicite, car elle est jugée évidente ou partagée par le public. 'Il est médecin, donc on peut lui faire confiance' laisse implicite 'Les médecins sont dignes de confiance'. Le lecteur complète le raisonnement et se sent acteur de la conclusion.",
    },
    "ex2": {
        "q": "Identifiez le procédé : 'Je ne dirai pas combien de fois ce candidat a menti au cours de sa carrière.'",
        "ans": "Prétérition : le locuteur dit ce qu'il prétend ne pas dire. En affirmant ne pas mentionner les mensonges du candidat, il les mentionne et en souligne implicitement la multiplicité.",
        "exp": "La prétérition est un procédé rhétorique par lequel on énonce quelque chose en déclarant ne pas vouloir l'énoncer. L'effet est de souligner l'information tout en conservant une apparence de discrétion ou de modération.",
        "accept": ["prétérition", "dire ce qu'on ne veut pas dire", "litote rhétorique", "mention par déni"],
    },
    "ex3": {
        "q": "Selon la rhétorique classique, quel est l'effet de l'hypotypose sur le lecteur ?",
        "opts": [
            "Elle résume l'argument principal de manière logique",
            "Elle transforme le lecteur en témoin en rendant la scène présente à ses yeux",
            "Elle affaiblit l'argumentation par un excès de détails",
            "Elle remplace la preuve logique par l'émotion brute",
        ],
        "ans": "Elle transforme le lecteur en témoin en rendant la scène présente à ses yeux",
        "exp": "L'hypotypose (du grec hypotyposis, 'esquisse') est une description si vive qu'elle rend la scène immédiatement présente, transformant le lecteur en témoin oculaire. Elle ne remplace pas la logique mais la renforce par une présence sensorielle et émotionnelle.",
    },
    "game_desc": "Maîtrisez la rhétorique argumentative avancée au niveau C2",
    "items": [
        ("g7-enthymeme", "l'enthymème", "syllogisme rhétorique avec une prémisse implicite, jugée évidente ou partagée", "le syllogisme incomplet · la prémisse implicite · le raisonnement court", "'Il est philosophe, donc il cherche la vérité.' — prémisse implicite : 'tout philosophe cherche la vérité'.", "enthymème = syllogisme avec prémisse implicite que le lecteur complète", "syllogisme rhétorique dont une prémisse reste implicite"),
        ("g7-pretention", "la prétérition", "figure disant ce qu'on prétend ne pas dire, pour en souligner l'importance tout en affectant la discrétion", "mentionner par déni · dire sans dire · l'affectation de silence", "'Je ne mentionnerai pas ses scandales…' — la prétérition mentionne en feignant de ne pas le faire.", "prétérition = dire ce qu'on prétend ne pas dire", "figure consistant à mentionner ce qu'on prétend vouloir taire"),
        ("g7-hypotypose", "l'hypotypose", "description si vive qu'elle rend la scène présente aux yeux du lecteur", "l'enargeia · la description vive · la scène présente", "Une hypotypose de bataille : sons, odeurs, cris, confusion — le lecteur y est.", "hypotypose = description si vive qu'elle rend la scène présente", "description si vive qu'elle rend la scène présente aux yeux du lecteur"),
        ("g7-apostrophe", "l'apostrophe rhétorique", "interpellation directe d'une personne absente, d'un objet ou d'une abstraction", "l'adresse à l'absent · la personnification par apostrophe · Ô liberté", "'Ô liberté, que de crimes on commet en ton nom !' — apostrophe à une abstraction.", "apostrophe = interpellation directe d'une personne absente ou d'une abstraction", "interpellation directe d'une personne absente, d'un objet ou d'une abstraction"),
        ("g7-concession-avancee", "la concession rhétorique avancée", "stratégie accordant généreusement l'antithèse pour mieux la réfuter et renforcer l'ethos", "pro-concession · accorder pour mieux réfuter · la générosité tactique", "Concéder tout ce qu'on peut concéder, puis pivot : 'cependant, cette concession révèle que…'", "concession avancée = accorder généreusement l'antithèse pour mieux la réfuter", "stratégie accordant généreusement l'antithèse pour mieux la réfuter"),
        ("g7-topos", "le topos argumentatif", "argument type récurrent applicable à de nombreuses situations dans l'argumentation rhétorique", "le lieu rhétorique · le lieu commun · l'argument-type", "Topos du plus/moins : si X vaut pour le cas majeur, il vaut a fortiori pour le cas mineur.", "topos = argument type récurrent applicable à de nombreuses situations", "argument type récurrent applicable à de nombreuses situations argumentatives"),
        ("g7-ironie-systemique", "l'ironie systémique", "ironie qui traverse tout un texte par des registres inadéquats et des décalages persistants", "l'ironie de registre · le décalage total · le texte ironique", "Voltaire dans Candide : ironie systémique par le narratif naïf face aux horreurs vécues.", "ironie systémique = ironie traversant tout un texte par décalages persistants", "ironie traversant tout un texte par des registres inadéquats persistants"),
        ("g7-gradation-thematique", "la gradation thématique", "organisation des arguments du plus faible au plus fort pour un effet argumentatif croissant", "l'argument ultime · la montée argumentative · le climax logique", "Placer l'argument le plus englobant et le plus fondamental en dernier.", "gradation thématique = arguments du plus faible au plus fort", "organisation des arguments du plus faible au plus fort pour un effet croissant"),
    ],
},

# ── G08 Les Registres de Langue et la Variation Stylistique ──────────────
"les-registres-de-langue-et-variation": {
    "level": "c2",
    "section": "grammaire",
    "num": "G08",
    "short": "Registres de langue",
    "title": "Les Registres de Langue et la Variation Stylistique",
    "subtitle": "Maîtriser et alterner les registres pour un effet stylistique maîtrisé",
    "slides": [
        ("Les cinq registres du français", "Soutenu (littéraire/académique) · Standard (correct, neutre) · Courant (conversation ordinaire) · Familier (relâché, entre proches) · Vulgaire (grossier, tabou). À C2, la maîtrise implique : reconnaître chaque registre, le produire intentionnellement, et identifier quand un texte mélange des registres pour un effet stylistique."),
        ("Marqueurs du registre soutenu", "Lexique : vocables rares ou savants (maint, naguère, courroux, forfait). Syntaxe : inversion, subjonctif de concordance, propositions participiales. Morphologie : formes verbales littéraires (PS, subj. imparfait). Absence de contractions (ne + verbe sans élision abusive). Pas de mots tronqués (cinéma, non *ciné)."),
        ("Marqueurs du registre familier", "Lexique : verlan, troncations (appart, sympa, exam), expressions idiomatiques (avoir la flemme, ça m'énerve). Syntaxe : dislocation (moi, j'aime bien), absence du ne (il vient pas), interrogation avec est-ce que ou intonation seule. Morphologie : contractions (j'suis, t'as)."),
        ("La variation diasystémique", "Variation diachronique (époque : archaïsmes vs néologismes) · Diatopique (géographique : patois, régionalismes, français québécois) · Diastratique (sociale : sociolectes, argots, jargon professionnel) · Diaphasique (situationnelle : registre de politesse vs intime). À C2, identifier chaque type de variation dans un texte est attendu."),
        ("L'effet stylistique du mélange de registres", "L'alternance consciente de registres crée des effets : bathos (descente comique du solennel au trivial) · ironie (décalage entre sujet grave et ton badin) · caractérisation de personnage (le paysan parlant latin, le bourgeois utilisant l'argot). Ex. Flaubert, Zola : mélange registre médical/registre populaire."),
        ("Le registre dans la presse", "Presse de qualité : registre standard à soutenu, phrases syntaxiquement complexes, conditionnel journalistique, formules de mise à distance. Presse populaire : titres courts, registre courant à familier, phrases nominales percutantes. Analyser le registre d'un article révèle son lectorat cible et sa ligne éditoriale."),
        ("Jargon et langue de spécialité", "Chaque domaine professionnel développe un jargon (lexique spécialisé + conventions discursives). Médical, juridique, économique, informatique. À C2, savoir utiliser le jargon du domaine traité (droit, philosophie, sociologie) avec précision et l'expliquer quand le contexte le nécessite."),
        ("Archaïsmes et néologismes comme outils stylistiques", "Archaïsme intentionnel : employer un mot archaïque ('moult', 'naguère', 'ains') pour l'effet de patine, d'ironie ou d'élévation. Néologisme : créer ou employer un mot nouveau (verlanisation, anglicisme intégré, mot-valise) pour nommer un concept nouveau ou créer un effet de modernité revendiquée."),
        ("La polyphonie et les niveaux de voix", "Un texte peut intégrer plusieurs voix à des registres différents (polyphonie bakhtinienne). Ex. : le narrateur omniscient en registre soutenu, les dialogues en registre courant, la pensée intérieure en SIL à l'imparfait. Analyser la polyphonie d'un texte révèle les rapports de pouvoir et d'identité entre les personnages."),
        ("Produire dans plusieurs registres", "À C2, savoir produire le même message dans plusieurs registres : 'Il est décédé' (standard) / 'Il a trépassé' (soutenu/littéraire) / 'Il est mort' (courant) / 'Il a claqué' (familier). Chaque choix lexical implique une posture énonciative et une relation au destinataire."),
    ],
    "traps": [
        ("Mélange involontaire de registres", "Employer 'super' (familier) dans un essai académique, ou 'nonobstant' (soutenu) dans un SMS. Le mélange involontaire affaiblit la cohérence stylistique. À C2, le mélange est intentionnel et justifié par un effet recherché."),
        ("Confondre registre familier et incorrection grammaticale", "L'absence du 'ne' dans 'il vient pas' est un marqueur de registre familier, non une faute absolue. Mais '*il a pas venir' est incorrect à tous les registres. Distinguer la variation stylistique de l'erreur grammaticale."),
        ("Jargon sans définition dans un écrit général", "Employer un terme de spécialité ('héméralope', 'syllepse', 'habitus') sans le définir dans un texte destiné à un public non spécialisé. Le jargon non défini exclut le lecteur. À C2, choisir entre employer et définir, ou reformuler en langage courant."),
        ("Prendre l'archaïsme pour une faute", "Rencontrer 'moult', 'naguère', 'ains', 'maint' dans un texte littéraire et les analyser comme des fautes : ce sont des archaïsmes stylistiques délibérés. Contextualiser dans l'époque ou l'intention de l'auteur avant de juger."),
    ],
    "summary": [
        "Cinq registres : soutenu · standard · courant · familier · vulgaire.",
        "Variation diasystémique : diachronique, diatopique, diastratique, diaphasique.",
        "Mélange intentionnel de registres : bathos, ironie, caractérisation.",
        "Polyphonie : plusieurs voix à registres différents coexistent dans un texte.",
        "À C2 : reconnaître, produire et alterner les registres avec intention stylistique.",
    ],
    "ex1": {
        "q": "Quel type de variation désigne les différences de registre liées à la situation de communication (formel vs intime) ?",
        "opts": [
            "Variation diachronique",
            "Variation diatopique",
            "Variation diastratique",
            "Variation diaphasique",
        ],
        "ans": "Variation diaphasique",
        "exp": "La variation diaphasique (ou stylistique situationnelle) concerne les choix de registre selon la situation de communication : parler différemment à son patron, à ses amis, ou dans un discours public. La diachronique touche l'époque, la diatopique la géographie, la diastratique la classe sociale.",
    },
    "ex2": {
        "q": "Réécrivez en registre soutenu : 'Il est mort hier soir dans son appart.'",
        "ans": "Il a trépassé dans la nuit, dans son appartement.",
        "exp": "Le registre soutenu remplace 'il est mort' (courant) par 'il a trépassé' (littéraire), supprime la troncation 'appart' et emploie 'dans la nuit' pour une formulation plus solennelle. Le registre familier ('appart') est incompatible avec le registre soutenu ('trépassé').",
        "accept": ["trépassé", "s'est éteint", "a rendu l'âme", "appartement", "registre soutenu"],
    },
    "ex3": {
        "q": "Quel est l'effet stylistique nommé quand un texte passe brusquement d'un registre solennel à un registre trivial ou comique ?",
        "opts": [
            "L'hypotypose",
            "Le bathos",
            "L'anaphore",
            "L'épiphore",
        ],
        "ans": "Le bathos",
        "exp": "Le bathos (du grec bathys, 'profond') désigne la descente comique ou décevante d'un registre élevé vers un registre trivial ou vulgaire, créant un effet de surprise, d'ironie ou de ridicule. Pope en a fait une théorie satirique dans son 'Peri Bathous'. L'hypotypose est une description vive ; l'anaphore et l'épiphore sont des répétitions.",
    },
    "game_desc": "Maîtrisez les registres de langue et la variation stylistique au C2",
    "items": [
        ("g8-cinq-registres", "les cinq registres du français", "soutenu, standard, courant, familier, vulgaire — hiérarchie des niveaux de langue", "le niveau de langue · les registres · la variation situationnelle", "Soutenu : 'Il a trépassé.' Standard : 'Il est décédé.' Courant : 'Il est mort.' Familier : 'Il a claqué.'", "cinq registres = soutenu, standard, courant, familier, vulgaire", "hiérarchie des cinq niveaux de langue du soutenu au vulgaire"),
        ("g8-diaphasique", "la variation diaphasique", "variation de registre selon la situation de communication (formel vs intime)", "la variation situationnelle · le registre de politesse · la variation stylistique", "Parler à son patron en registre standard vs à ses amis en registre familier : variation diaphasique.", "variation diaphasique = changement de registre selon la situation", "variation de registre selon la situation de communication"),
        ("g8-bathos", "le bathos", "descente comique brusque d'un registre solennel vers un registre trivial ou vulgaire", "la chute stylistique · le comique de registre · l'anticlimax de niveau", "'Il mourut pour la patrie, pour l'honneur, pour un sandwich.' — bathos par chute triviale finale.", "bathos = descente brusque du solennel au trivial pour effet comique", "descente brusque d'un registre solennel vers un registre trivial ou comique"),
        ("g8-polyphonie", "la polyphonie textuelle", "coexistence de plusieurs voix à registres différents dans un même texte", "la pluralité de voix · Bakhtine · le dialogisme", "Zola : narrateur soutenu + dialogue ouvrier familier — polyphonie caractéristique du roman naturaliste.", "polyphonie = coexistence de plusieurs voix à registres différents", "coexistence de plusieurs voix à registres différents dans un même texte"),
        ("g8-jargon", "le jargon de spécialité", "lexique et conventions discursives propres à un domaine professionnel ou académique", "la langue de spécialité · le lexique technique · le vocabulaire expert", "Le jargon juridique : 'la jurisprudence', 'la plaidoirie', 'le prononcé du jugement'.", "jargon = lexique et conventions propres à un domaine de spécialité", "lexique et conventions discursives propres à un domaine professionnel"),
        ("g8-archaisme", "l'archaïsme stylistique", "emploi délibéré d'un mot ou d'une construction ancienne pour un effet de patine ou d'ironie", "le mot archaïque · naguère · moult · la patine littéraire", "'Moult fois il tenta de la convaincre.' — archaïsme pour effet de conte médiéval.", "archaïsme stylistique = emploi délibéré de mots anciens pour un effet", "emploi délibéré d'un mot ou d'une construction ancienne pour un effet"),
        ("g8-diastratique", "la variation diastratique", "variation de registre liée à la position sociale du locuteur : sociolectes et argots", "le sociolecte · l'argot de classe · la variation sociale", "L'argot de banlieue (verlan, troncations) vs la langue de la bourgeoisie cultivée : variation diastratique.", "variation diastratique = variation liée à la position sociale", "variation de registre liée à la position sociale du locuteur"),
        ("g8-diatopique", "la variation diatopique", "variation géographique du français : patois, régionalismes, français québécois, africain", "la variation régionale · les régionalismes · le français plurilingue", "Le français québécois 'magasiner' (= faire du shopping) vs le français hexagonal : variation diatopique.", "variation diatopique = variation géographique du français", "variation géographique du français incluant patois et régionalismes"),
    ],
},

# ── G09 La Ponctuation Expressive et la Typographie Soutenue ─────────────
"la-ponctuation-expressive-et-typographie": {
    "level": "c2",
    "section": "grammaire",
    "num": "G09",
    "short": "Ponctuation expressive",
    "title": "La Ponctuation Expressive et la Typographie Soutenue",
    "subtitle": "Maîtriser toutes les ressources de la ponctuation et de la mise en page soutenue",
    "slides": [
        ("La ponctuation comme système", "La ponctuation n'est pas un code arbitraire mais un système sémiotique qui code le rythme, la hiérarchie syntaxique et les nuances sémantiques. À C2, chaque signe doit être choisi intentionnellement. Mal ponctuer = altérer le sens."),
        ("Le tiret cadratin (—) vs le tiret demi-cadratin (–)", "Tiret cadratin (—) : dialogue littéraire (répliques), incidente (— information — ), rupture narrative forte. Tiret demi-cadratin (–) : plages de valeurs (pp. 15–30), certains titres, énumération dans les listes typographiques. En France, le tiret cadratin est la norme pour le dialogue, sans espace avant le contenu."),
        ("Les guillemets français (« »)", "Obligatoires en français typographique standard : guillemets français « » avec espace insécable fine à l'intérieur. Emplois : discours direct, citation, distanciation (emploi ironique ou métalinguistique d'un mot). Les guillemets anglais ("") sont une importation typographique non recommandée en écriture académique française."),
        ("Les points de suspension (…)", "Emplois légitimes : aposiopèse (phrase inachevée volontairement), suspension suggestive, énumération ouverte (et ainsi de suite…), hésitation dans le discours direct. Emploi à éviter : fins de paragraphes sans justification émotionnelle, effet de vague dans un raisonnement qui devrait être précis."),
        ("Le point-virgule", "Séparateur de propositions indépendantes ayant une relation logique forte (plus liées que si séparées par un point, moins dépendantes que si séparées par une virgule). Ex. : 'Il parlait lentement ; ses mots pesaient.' Très fréquent dans la prose académique et littéraire française, au contraire du style anglophone."),
        ("Les parenthèses et les crochets", "Parenthèses ( ) : information incidente facultative, précision, exemple, renvoi bibliographique. Crochets [ ] : en citation, pour indiquer une interpolation de l'éditeur ou du commentateur (*'il [le candidat] refusa'). Distinguer de la mise entre tirets cadratins : les tirets sont plus emphatiques, les parenthèses plus discrètes."),
        ("La majuscule à valeur symbolique", "Majuscule d'honneur : les titres institutionnels (la République, l'État, le Parlement). Majuscule de personnification : 'la Mort prit son manteau…' Majuscule de nom propre utilisé comme nom commun (un Harpagon = un avare). Règle : les adjectifs de nationalité prennent la minuscule ('un auteur français') ; les noms de nationalité, la majuscule ('un Français')."),
        ("L'italique et ses fonctions", "Italique : titres d'œuvres (Il Gattopardo), mots étrangers (un modus vivendi), terme technique lors de sa définition, mise en relief discret. Ne pas souligner : c'est une convention typographique réservée aux manuscrits anciens. En écriture académique, l'italique remplace les guillemets pour les titres d'œuvres."),
        ("La césure et le rythme visuel", "La disposition visuelle d'un texte (longueur des paragraphes, blancs, tirets, alinéas) fait partie du style. Un paragraphe très court après plusieurs longs crée un choc visuel et logique. La mise en blanc (blanc typographique entre sections) signale un saut temporel, une rupture thématique ou une pause narrative."),
        ("Cohérence typographique", "Un texte C2 doit être cohérent typographiquement : toujours les mêmes guillemets, toujours la même convention pour les titres, ponctuation uniforme. L'incohérence typographique signale un manque de soin rédactionnel, même si le contenu est solide."),
    ],
    "traps": [
        ("Guillemets anglais dans un texte académique français", "Employer \"...\" au lieu de « ... » dans un texte académique ou littéraire français. Les guillemets anglais sont réservés à l'usage en ligne ou quand la typographie française n'est pas disponible. Dans toute production C2 soignée, « » avec espace insécable."),
        ("Abuser des points de suspension", "Terminer chaque paragraphe par '…' sans justification émotionnelle ou rhétorique. Les points de suspension doivent signifier quelque chose : l'indicible, la suspension, l'ouverture. Employés sans raison, ils affaiblissent le style."),
        ("Confondre tiret cadratin et tiret demi-cadratin", "Employer — (cadratin) pour les plages de pages ou — (demi-cadratin) pour le dialogue. Faire le bon choix selon le contexte typographique est une marque de maîtrise professionnelle."),
        ("Majuscule des adjectifs de nationalité", "*'un auteur Français' — la nationalité en adjectif prend la minuscule en français. 'Un auteur français' mais 'un Français' (nom). Cette règle est systématiquement testée dans les écrits académiques et les concours."),
    ],
    "summary": [
        "Tiret cadratin (—) : dialogue, incidente, rupture forte. Demi-cadratin (–) : valeurs, listes.",
        "Guillemets français (« ») obligatoires en texte académique ; guillemets anglais (\") à éviter.",
        "Point-virgule : sépare des propositions liées logiquement, plus courant en français qu'en anglais.",
        "Italique : titres d'œuvres, mots étrangers, termes définis.",
        "Adjectifs de nationalité : minuscule (un auteur français) ; noms de nationalité : majuscule (un Français).",
    ],
    "ex1": {
        "q": "Quelle ponctuation convient pour séparer deux propositions indépendantes logiquement liées dans la prose académique française ?",
        "opts": [
            "Le point d'exclamation",
            "La virgule seule",
            "Le point-virgule",
            "Les points de suspension",
        ],
        "ans": "Le point-virgule",
        "exp": "Le point-virgule sépare deux propositions syntaxiquement indépendantes mais logiquement liées, indiquant une relation plus étroite que le point et plus distancée que la virgule. Il est très caractéristique de la prose académique et littéraire française et plus fréquent qu'en anglais.",
    },
    "ex2": {
        "q": "Corrigez la faute typographique : 'L'auteur \"Camus\" est né en Algérie.'",
        "ans": "L'auteur Camus est né en Algérie. (ou : L'auteur « Camus » est né en Algérie si la mise en relief est voulue, avec les guillemets français.)",
        "exp": "Les guillemets anglais (\"\") sont incorrects en typographie française. Les guillemets français (« ») s'imposent. De plus, pour un nom propre d'auteur célèbre, les guillemets ne sont généralement pas nécessaires : 'l'auteur Camus' suffit.",
        "accept": ["guillemets français", "« Camus »", "sans guillemets", "guillemets anglais incorrects"],
    },
    "ex3": {
        "q": "Quelle est la règle typographique pour les adjectifs de nationalité en français ?",
        "opts": [
            "Ils prennent toujours une majuscule",
            "Ils prennent la minuscule (un auteur français)",
            "Ils ne s'emploient jamais avec un nom de personne",
            "Ils prennent la majuscule uniquement au pluriel",
        ],
        "ans": "Ils prennent la minuscule (un auteur français)",
        "exp": "En français, les adjectifs de nationalité s'écrivent avec une minuscule : 'un film français', 'la littérature espagnole'. Les noms de nationalité prennent une majuscule : 'un Français', 'une Espagnole'. Cette distinction est constante et testée dans tous les concours académiques.",
    },
    "game_desc": "Maîtrisez la ponctuation expressive et la typographie soutenue au C2",
    "items": [
        ("g9-tiret-cadratin", "le tiret cadratin (—)", "tiret long pour le dialogue littéraire, les incidentes et les ruptures fortes", "le dialogue · l'incidente · la rupture narrative", "— Il refusa, dit-il froidement. — Vous avez tort. (dialogue au tiret cadratin)", "tiret cadratin = dialogue, incidentes, ruptures — le tiret long (—)", "tiret long pour le dialogue littéraire, les incidentes et les ruptures"),
        ("g9-guillemets-fr", "les guillemets français (« »)", "guillemets typographiques français obligatoires avec espace insécable fine à l'intérieur", "« les guillemets à chevrons » · l'espace insécable · la citation française", "« Il viendra demain », dit-elle. — guillemets français + espace insécable fine.", "guillemets français = « » avec espace insécable, obligatoires en académique", "guillemets français obligatoires en texte académique avec espace insécable"),
        ("g9-point-virgule", "le point-virgule", "signe séparant deux propositions indépendantes logiquement liées dans la prose soutenue", "les propositions liées · la liaison forte · le séparateur intermédiaire", "'Il parlait lentement ; ses mots pesaient comme des pierres.' — propositions liées au point-virgule.", "point-virgule = séparateur de propositions indépendantes logiquement liées", "sépare des propositions indépendantes ayant une relation logique forte"),
        ("g9-italique", "l'italique", "convention typographique pour les titres d'œuvres, les mots étrangers et les termes définis", "les titres en italique · les mots étrangers · la mise en relief typographique", "L'italique dans Il Gattopardo (titre d'œuvre) et in situ (locution latine).", "italique = titres d'œuvres, mots étrangers, termes définis", "convention typographique pour titres d'œuvres et mots étrangers"),
        ("g9-maj-nationalite", "la majuscule des nationalités", "noms de nationalité = majuscule ; adjectifs de nationalité = minuscule", "un Français / un auteur français · nom vs adjectif · la règle capitale", "'un Français' (nom, majuscule) vs 'un auteur français' (adjectif, minuscule).", "nationalité : nom = majuscule (un Français) ; adjectif = minuscule (auteur français)", "noms de nationalité en majuscule, adjectifs de nationalité en minuscule"),
        ("g9-parentheses", "les parenthèses vs les tirets", "parenthèses : information incidente discrète ; tirets cadratins : information incidente emphatique", "l'incidente entre parenthèses · l'incidente entre tirets · l'emphase différenciée", "Information discrète : (voir page 45). Information emphatique : — ce fait est crucial —", "parenthèses (discret) vs tirets cadratins (emphatique) pour les incidentes", "parenthèses pour incidentes discrètes ; tirets cadratins pour incidentes emphatiques"),
        ("g9-points-suspension", "les points de suspension (…)", "signalent l'aposiopèse, la suspension suggestive ou l'énumération ouverte", "l'inachèvement · l'ellipse graphique · la suspension · …", "'Si tu savais…' — aposiopèse : phrase délibérément inachevée par les points de suspension.", "points de suspension = aposiopèse, suspension ou énumération ouverte", "signalent l'aposiopèse, la suspension suggestive ou l'énumération ouverte"),
        ("g9-crochets", "les crochets [ ]", "signalent une interpolation de l'éditeur ou du commentateur dans une citation", "l'interpolation · la citation commentée · [sic]", "Il [le président] refusa — les crochets indiquent que 'le président' remplace un pronom.", "crochets = interpolation dans une citation ou commentaire éditorial", "signalent une interpolation de l'éditeur ou du commentateur dans une citation"),
    ],
},

# ── G10 L'Orthographe des Accords Complexes ──────────────────────────────
"l-orthographe-des-accords-complexes": {
    "level": "c2",
    "section": "grammaire",
    "num": "G10",
    "short": "Accords complexes",
    "title": "L'Orthographe des Accords Complexes",
    "subtitle": "Maîtriser les accords difficiles du participe passé et de l'adjectif",
    "slides": [
        ("Récapitulatif des accords du participe passé", "Avec avoir : accord avec le COD si celui-ci est antéposé au verbe. 'La lettre que j'ai écrite.' Avec être : accord avec le sujet. 'Elle est partie.' Verbes pronominaux réfléchis/réciproques : accord si le pronom SE est COD. 'Elle s'est lavée' (COD = se = elle) vs 'Elle s'est lavé les mains' (COD = les mains, après)."),
        ("Les verbes pronominaux et l'accord du PP", "Se verbe : si SE est COD → accord. 'Ils se sont vus.' (= ils ont vu eux-mêmes) Si SE est COI → pas d'accord. 'Ils se sont parlé.' (= ils ont parlé à eux-mêmes) Verbes essentiellement pronominaux (toujours se) : accord systématique. 'Elle s'est enfuie / souvenue.'"),
        ("Le participe passé avec 'faire' + infinitif", "Toujours invariable : 'Elle les a fait venir.' / 'Les tableaux qu'il a fait peindre.' Le COD ne déclenchera jamais l'accord car 'fait' gouverne l'infinitif, non le COD directement. Exception : 'elle s'est faite belle' (faire = rendre, attributif, non causatif)."),
        ("Le participe passé des verbes impersonnels", "Toujours invariable : 'Les inondations qu'il y a eu.' / 'La chaleur qu'il a fait.' Le sujet grammatical est toujours 'il' impersonnel — jamais de vrai COD antéposé au participe."),
        ("Accord de l'adjectif avec plusieurs sujets", "Sujets coordonnés avec 'et' : accord au pluriel. 'Sa prudence et sa générosité étaient remarquables.' Sujets coordonnés avec 'ou/ni' : accord selon le sens. Si exclusion mutuelle → singulier : 'Ni l'un ni l'autre n'est arrivé.' Si les deux sont possibles → pluriel : 'Ni sa prudence ni sa bonté ne manquaient.'"),
        ("L'accord des adjectifs de couleur", "Adjectif simple : accord normal. 'Des robes vertes.' Adjectif composé ou nom utilisé comme adjectif : invariable. 'Des robes bleu marine / des yeux noisette / des tenues kaki.' Exception : 'rose', 'mauve', 'écarlate', 'pourpre' s'accordent car ce sont des adjectifs à part entière."),
        ("Demi-, semi-, mi-, nu-", "Toujours invariables avant un nom ou adjectif : 'à demi nu', 'des semi-remorques', 'mi-temps'. Après un nom relié par un tiret : 'des bras nus' mais 'nu-pieds' (invariable composé figé). 'À demi' = invariable ; 'demi' devant un nom + tiret = invariable. 'Deux heures et demie' = s'accorde quand après le nom."),
        ("Participe passé après 'en'", "Après 'en' pronom, le participe passé est toujours invariable : 'Des pommes ? J'en ai mangé.' Le COD 'en' est partitif et ne déclenche jamais l'accord, même antéposé."),
        ("Accord de 'tout'", "Adjectif : accord en genre et nombre. 'Toutes les fleurs.' Adverbe devant un adjectif : invariable, SAUF devant un adjectif féminin commençant par une consonne ou un h aspiré (euphonie). 'Elles sont toutes honteuses / tout étonnées.' Pronom : 'Tout est bien qui finit bien.' Nom : 'Le tout est de comprendre.'"),
        ("Accords dans les locutions figées", "Certaines locutions au participe passé sont invariables par convention : 'Ci-joint les documents.' / 'Ci-annexé la liste.' (invariables en tête de phrase ou avant le nom). 'Les documents ci-joints.' (s'accorde après le nom). 'Étant donné les circonstances' (invariable) vs 'les circonstances étant données' (s'accorde)."),
    ],
    "traps": [
        ("Accord de PP avec 'en'", "*'Des pommes ? J'en ai mangées.' — faute classique. Après 'en' partitif, le PP est toujours invariable : 'J'en ai mangé'. Le 'en' représente une quantité indéfinie et ne peut pas être antéposé au sens syntaxique requis pour l'accord."),
        ("Accord de 'fait' + infinitif", "*'Les pièces qu'il a faites réparer.' — faute fréquente. 'Fait' + infinitif est toujours invariable : 'Les pièces qu'il a fait réparer.' Seule exception : 'elle s'est faite belle' (faire attributif)."),
        ("Accord de 'tout' adverbe devant adjectif féminin", "*'Elles sont toutes timides' — faux, car 'timide' commence par une consonne au féminin → accord : 'elles sont toutes timides'. Mais : '*elles sont toutes étonnées' → 'tout étonnées' (adjectif à initiale vocalique → pas d'accord de l'adverbe 'tout'). Règle d'euphonie souvent mal appliquée."),
        ("'Ci-joint' invariable ou variable ?", "En tête de phrase ou directement avant le nom : invariable ('Ci-joint la facture'). Après le nom : s'accorde ('La facture ci-jointe'). Après un verbe : s'accorde ('Vous trouverez ci-jointe la facture'). Cette règle est systématiquement testée dans les concours administratifs."),
    ],
    "summary": [
        "PP avec avoir : accord si COD antéposé (sauf 'en' partitif et 'fait' + inf.).",
        "PP pronominal : accord si SE = COD ; invariable si SE = COI ('se sont parlé').",
        "Adjectifs de couleur composés : invariables (bleu marine, gris clair).",
        "'Tout' adverbe : invariable sauf devant adj. féminin commençant par consonne.",
        "'Ci-joint' : invariable en tête ; variable après le nom ou le verbe.",
    ],
    "ex1": {
        "q": "Choisissez la forme correcte : 'Les lettres que j'ai _____ (envoyer).'",
        "opts": [
            "envoyé",
            "envoyés",
            "envoyées",
            "envoyer",
        ],
        "ans": "envoyées",
        "exp": "Le COD 'les lettres' est antéposé au verbe 'ai envoyé' (relatif 'que' = 'les lettres' = féminin pluriel). Règle : avec avoir, le PP s'accorde avec le COD antéposé en genre et en nombre → 'envoyées' (féminin pluriel).",
    },
    "ex2": {
        "q": "Expliquez la différence d'accord : 'Elle s'est lavée.' vs 'Elle s'est lavé les mains.'",
        "ans": "'Elle s'est lavée' : SE est COD (= elle a lavé elle-même), donc PP s'accorde avec SE (féminin singulier). 'Elle s'est lavé les mains' : SE est COI (= elle a lavé les mains à elle-même), le COD est 'les mains' (après le verbe) → pas d'accord du PP.",
        "exp": "La règle du PP pronominal repose sur la fonction de SE : si SE = COD, accord ; si SE = COI (et que le COD est exprimé après), pas d'accord. Tester : 'a lavé QUI ?' → elle (SE = COD → accord). 'A lavé QUOI ?' → les mains (SE = COI → pas d'accord).",
        "accept": ["SE = COD → accord", "SE = COI → pas d'accord", "les mains = COD après", "pronominal accord"],
    },
    "ex3": {
        "q": "Quelle est la règle d'accord pour les adjectifs de couleur composés ('bleu marine', 'gris clair') ?",
        "opts": [
            "Ils s'accordent normalement avec le nom",
            "Ils sont toujours invariables",
            "Ils s'accordent uniquement au féminin",
            "Ils s'accordent au pluriel uniquement",
        ],
        "ans": "Ils sont toujours invariables",
        "exp": "Les adjectifs de couleur composés (bleu marine, gris clair, bleu roi) et les noms utilisés comme adjectifs de couleur (kaki, noisette, marron) sont invariables. 'Des chaussures bleu marine' (non *bleues marines). Les adjectifs simples comme 'vert', 'rouge' s'accordent normalement.",
    },
    "game_desc": "Maîtrisez les accords complexes du participe passé et de l'adjectif au C2",
    "items": [
        ("g10-pp-avoir-cod", "accord du PP avec avoir (COD antéposé)", "le PP avec avoir s'accorde avec le COD si et seulement si celui-ci est placé avant le verbe", "les lettres que j'ai écrites · le COD antéposé · l'accord du participe", "'La lettre que j'ai écrite' : COD 'que' = 'lettre' (féminin) → PP féminin singulier.", "PP avec avoir = accord avec le COD antéposé au verbe", "accord du PP avec avoir si et seulement si le COD est antéposé"),
        ("g10-pp-pronominal", "accord du PP pronominal (SE = COD vs COI)", "PP pronominal s'accorde si SE est COD ; invariable si SE est COI (et COD après)", "elle s'est lavée · elle s'est lavé les mains · SE = COD ou COI", "'S'est lavée' (SE = COD) vs 's'est lavé les mains' (SE = COI, COD après).", "PP pronominal = accord si SE = COD ; invariable si SE = COI", "accord si SE est COD ; invariable si SE est COI avec COD exprimé après"),
        ("g10-fait-inf", "PP 'fait' + infinitif (invariable)", "la locution 'fait' + infinitif est toujours invariable, quelle que soit la position du COD", "fait réparer · les pièces qu'il a fait réparer · causatif invariable", "'Les voitures qu'il a fait réparer' — PP 'fait' invariable même avec COD antéposé.", "fait + infinitif = toujours invariable (sauf 'se faire attributif')", "la locution fait + infinitif est toujours invariable"),
        ("g10-en-partitif", "PP avec 'en' partitif (invariable)", "après le pronom 'en' partitif, le PP est toujours invariable", "en ai mangé · j'en ai vu · 'en' ne déclenche pas l'accord", "'Des pommes ? J'en ai mangé.' — 'en' partitif → PP toujours invariable.", "PP après 'en' partitif = toujours invariable", "le pronom 'en' partitif n'entraîne jamais l'accord du participe passé"),
        ("g10-couleur-composee", "adjectifs de couleur composés (invariables)", "les adjectifs de couleur composés et les noms utilisés comme couleurs sont invariables", "bleu marine · gris clair · kaki · noisette · invariable de couleur", "'Des robes bleu marine' (non *bleues marines) — couleur composée invariable.", "couleur composée = adjectif de couleur composé toujours invariable", "les adjectifs de couleur composés et les noms-couleurs sont invariables"),
        ("g10-tout-adv", "tout adverbe devant adjectif féminin", "'tout' adverbe est invariable sauf devant un adjectif féminin commençant par une consonne ou h aspiré", "tout étonnée · toutes honteuses · l'accord euphonique de tout", "'Elles sont tout étonnées' (voyelle → pas d'accord) vs 'toutes honteuses' (consonne → accord).", "tout adverbe = invariable sauf devant adjectif féminin + consonne/h aspiré", "invariable sauf devant adj. féminin commençant par consonne ou h aspiré"),
        ("g10-ci-joint", "'ci-joint' : accord conditionnel", "invariable en tête de phrase ou avant le nom ; s'accorde après le nom ou après un verbe", "ci-jointe la lettre · la lettre ci-jointe · la lettre vous est ci-jointe", "'Ci-joint la facture.' (invariable) vs 'La facture ci-jointe.' (accord après nom).", "ci-joint = invariable en tête ; s'accorde après le nom", "invariable en tête de phrase ; s'accorde après le nom ou après un verbe"),
        ("g10-verbe-impersonnel", "PP des verbes impersonnels (invariable)", "les participes passés des constructions impersonnelles sont toujours invariables", "il y a eu · il a fait · qu'il y a eu · invariable impersonnel", "'Les inondations qu'il y a eu' — PP invariable : sujet grammatical = 'il' impersonnel.", "PP impersonnel = toujours invariable (sujet = il impersonnel)", "les participes passés des constructions impersonnelles sont toujours invariables"),
    ],
},

# ── G11 La Syntaxe de l'Écrit Académique ─────────────────────────────────
"la-syntaxe-de-l-ecrit-academique": {
    "level": "c2",
    "section": "grammaire",
    "num": "G11",
    "short": "Syntaxe académique",
    "title": "La Syntaxe de l'Écrit Académique",
    "subtitle": "Construire des phrases académiques longues, précises et cohérentes",
    "slides": [
        ("Définition de l'écrit académique", "L'écrit académique en français se caractérise par : précision lexicale, organisation syntaxique complexe, modalisation explicite, citation et attribution des sources, structure argumentative claire, registre soutenu constant. Il s'adresse à un lecteur expert et n'explique pas ce qui est censé être connu."),
        ("La phrase académique complexe", "Structure type : [cadrage thématique] + [sujet + verbe principal] + [compléments/subordonnées] + [modalisateur final]. Ex. : 'Si l'on considère les résultats de l'enquête de Bourdieu (1979) [cadrage], il apparaît que la légitimité culturelle [sujet] dépend fondamentalement de la position sociale [verbe + compl.], bien que des trajectoires individuelles exceptionnelles modèrent ce déterminisme [concession finale].'"),
        ("Les nominalisations dans l'écrit académique", "L'écrit académique préfère les GN denses aux propositions verbales : 'La mise en œuvre de cette politique' (non : 'quand on met en œuvre cette politique'). Avantages : densité, précision, neutralité énonciative. Risque : opacité si les nominalisations s'enchaînent sans verbe sémantique fort."),
        ("La voix passive et la neutralité", "Le passif neutralise l'agent et met le processus en avant : 'Il a été établi que…' / 'Ces résultats ont été obtenus par…' / 'Des mesures ont été adoptées.' Fréquent dans les sciences et les rapports officiels pour effacer la subjectivité du locuteur. À ne pas abuser : le passif répété alourdit le style."),
        ("La définition et la dérivation terminologique", "Tout terme technique doit être défini à son introduction : 'Par X, nous entendons…' / 'Le concept de X désigne ici…' / 'X (au sens de Y) renvoie à…'. Puis employer le terme de manière cohérente sans en changer la définition. Les variations synonymiques libres sont déconseillées dans l'écrit académique."),
        ("La citation et l'intégration des sources", "Citation courte (< 5 mots) intégrée dans le texte avec guillemets et référence. Citation longue (> 5 mots) en bloc indenté sans guillemets. Règle : toute citation doit être suivie d'un commentaire analytique. Paraphrase avec attribution : '(Selon X, 2005)' ou 'Comme le soutient X (2005)…'. Jamais de citation 'flottante' sans ancrage."),
        ("Les connecteurs méta-discursifs", "Organisent la structure du discours lui-même : 'Nous verrons dans un premier temps…' / 'Avant d'examiner X, il convient de…' / 'Cette analyse nous conduit à…' / 'Pour résumer les points précédents…'. Ces connecteurs guident le lecteur dans la structure de l'argumentation."),
        ("L'objectivation énonciative", "Éviter le 'je' scolaire : préférer 'nous' (pluriel de majesté/modestie), 'on', le passif ou les tournures impersonnelles. 'Il convient de souligner' (non 'je souligne'). 'Force est de constater' (non 'je constate'). 'La présente étude vise à' (non 'dans cette étude, j'essaie de')."),
        ("La subordination dans l'écrit académique", "Les subordonnées permettent de préciser, nuancer, conditionner et hiérarchiser l'information. Subordonnées causales, concessives, consécutives et conditionnelles sont particulièrement fréquentes. La maîtrise des formes verbales (subjonctif, conditionnel) dans ces subordonnées est un marqueur du niveau C2."),
        ("L'équilibre entre longueur et clarté", "Une phrase académique longue n'est pas nécessairement obscure si : la structure syntaxique est claire (sujet verbe objet bien articulés), les incidentes sont bien signalées (virgules, tirets), les subordonnées sont dans l'ordre logique. Relire à voix basse : si on perd le fil, couper la phrase en deux."),
    ],
    "traps": [
        ("Nominalisation en cascade sans verbe fort", "'La mise en place de la restructuration de l'organisation des processus de production…' — trop de GN abstraits s'enchaînant. Introduire un verbe sémantique pour aérer : 'Restructurer les processus de production exige que l'organisation…'"),
        ("Citation flottante (sans ancrage ni commentaire)", "*'Les sciences sociales sont menacées. « La crise de la sociologie est profonde et durable. » Les données le confirment.' — la citation est flottante : qui la cite, quand, dans quel contexte ? Toujours introduire et commenter."),
        ("'Je' scolaire dans un écrit académique", "*'Dans cette dissertation, je vais vous montrer que…' / '*Je pense que…' — registre scolaire. L'écrit académique C2 emploie 'nous', les tournures impersonnelles, ou le passif pour effacer la subjectivité.",),
        ("Définir et redéfinir le même terme", "Donner une définition de X au début et en donner une autre, légèrement différente, plus loin. L'écrit académique exige une cohérence terminologique stricte : une définition, un terme, employés de manière constante jusqu'à la fin."),
    ],
    "summary": [
        "Phrase académique : cadrage + sujet + verbe + compléments + modalisateur.",
        "Nominalisations : densité et neutralité, mais à ne pas accumuler sans verbe fort.",
        "Passif : neutralise l'agent, met le processus en avant — ne pas abuser.",
        "Objectivation : nous / on / passif / impersonnel au lieu du 'je' scolaire.",
        "Citation : toujours introduire, citer avec guillemets et référence, puis commenter.",
    ],
    "ex1": {
        "q": "Quelle formule convient le mieux pour introduire un terme technique dans un écrit académique ?",
        "opts": [
            "X, c'est quand on fait…",
            "Par X, nous entendons…",
            "X veut dire que…",
            "X, ça désigne en gros…",
        ],
        "ans": "Par X, nous entendons…",
        "exp": "'Par X, nous entendons…' est la formule académique standard pour introduire une définition de terme technique. Elle emploie le 'nous' académique, le registre soutenu ('entendons'), et signale clairement une définition. Les autres options ('c'est quand', 'veut dire', 'ça désigne en gros') relèvent du registre courant ou familier.",
    },
    "ex2": {
        "q": "Reformulez en objectivant l'énonciation : 'Dans cet essai, je vais montrer que la mondialisation accentue les inégalités.'",
        "ans": "La présente analyse vise à démontrer que la mondialisation accentue les inégalités sociales.",
        "exp": "L'objectivation énonciative supprime le 'je' scolaire et remplace 'je vais montrer' par une formulation impersonnelle ('la présente analyse vise à démontrer'). Le terme 'essai' peut être remplacé par 'analyse' ou 'étude'. L'impersonnel crée une impression d'objectivité attendue en contexte académique.",
        "accept": ["présente analyse", "cette étude vise", "nous visons à", "il s'agit de", "objectivation"],
    },
    "ex3": {
        "q": "Qu'est-ce qu'une citation 'flottante' dans un écrit académique ?",
        "opts": [
            "Une citation trop longue dépassant cinq lignes",
            "Une citation sans introduction, attribution ni commentaire analytique",
            "Une citation en langue étrangère sans traduction",
            "Une citation en italique non justifiée typographiquement",
        ],
        "ans": "Une citation sans introduction, attribution ni commentaire analytique",
        "exp": "La citation 'flottante' est une citation insérée sans que le lecteur sache qui parle, dans quel contexte, et ce qu'on en déduit. Elle viole les règles de l'intégration académique : toute citation doit être précédée d'une introduction (auteur, contexte) et suivie d'un commentaire analytique.",
    },
    "game_desc": "Maîtrisez la syntaxe de l'écrit académique au niveau C2",
    "items": [
        ("g11-phrase-acad", "la phrase académique complexe", "phrase organisée en cadrage + sujet + verbe + compléments + modalisateur final", "la structure académique · la phrase longue argumentée · le cadrage initial", "Si l'on considère [cadrage] il apparaît que [verbe épistémique] + argument + bien que [concession].", "phrase académique = cadrage + sujet + verbe + compléments + modalisateur", "structure organisée en cadrage, sujet, verbe, compléments et modalisateur"),
        ("g11-nominalisation", "la nominalisation académique", "transformation d'une proposition verbale en groupe nominal pour la densité et la neutralité", "mise en œuvre · restructuration · la densité nominale · le GN abstrait", "'La mise en œuvre de cette réforme' (vs 'quand on met en œuvre cette réforme') — nominalisation.", "nominalisation académique = GN dense remplaçant une proposition verbale", "transformation d'une proposition en GN pour densité et neutralité énonciative"),
        ("g11-objectivation", "l'objectivation énonciative", "suppression du 'je' scolaire au profit du nous, on, passif ou impersonnel en contexte académique", "nous · on · la présente étude · il convient de · impersonnel", "'Il convient de souligner' (non 'je souligne') — objectivation en écrit académique.", "objectivation = nous/on/passif/impersonnel au lieu du 'je' scolaire", "suppression du je au profit de nous, on, passif ou impersonnel"),
        ("g11-citation", "l'intégration des citations", "citation courte avec guillemets + référence ; longue en bloc indenté ; toujours commentée", "la citation introduite · la citation commentée · la référence · la paraphrase", "Toute citation doit être introduite (qui ?, quand ?), citée avec référence et commentée.", "citation = introduire + guillemets + référence + commentaire", "citation : introduire, citer avec référence, puis commenter analytiquement"),
        ("g11-connecteurs-meta", "les connecteurs méta-discursifs", "connecteurs organisant la structure du discours académique lui-même", "nous verrons · avant d'examiner · cette analyse conduit à · guide du lecteur", "'Avant d'examiner X, il convient de…' — connecteur méta-discursif guidant le lecteur.", "connecteurs méta-discursifs = connecteurs organisant la structure du discours", "connecteurs organisant la structure du discours académique lui-même"),
        ("g11-passif-acad", "le passif de neutralisation", "voix passive effaçant l'agent pour mettre le processus en avant dans le discours académique", "il a été établi · des mesures ont été adoptées · effacement de l'agent", "'Il a été démontré que…' — passif effaçant l'agent pour créer une apparence d'objectivité.", "passif de neutralisation = passif effaçant l'agent pour mettre le processus en avant", "passif effaçant l'agent pour mettre le processus en avant"),
        ("g11-terminologie", "la cohérence terminologique", "utilisation constante du même terme avec la même définition tout au long d'un texte académique", "la définition unique · le terme stable · pas de synonymes libres", "Définir 'stratification sociale' une fois et employer ce terme de manière constante.", "cohérence terminologique = même terme, même définition, tout au long du texte", "utilisation constante du même terme avec la même définition"),
        ("g11-subordination", "la subordination dans l'écrit académique", "emploi de subordonnées causales, concessives, conditionnelles pour préciser et nuancer", "bien que + subjonctif · puisque + indicatif · si + conditionnel · la nuance subordonnée", "'Bien que les résultats soient encourageants, des réserves s'imposent.' — concessive académique.", "subordination académique = causales, concessives, conditionnelles pour nuancer", "subordonnées causales, concessives et conditionnelles pour préciser et nuancer"),
    ],
},

# ── G12 La Stylistique Comparée et l'Analyse de Discours ─────────────────
"la-stylistique-comparee-et-analyse-de-discours": {
    "level": "c2",
    "section": "grammaire",
    "num": "G12",
    "short": "Stylistique comparée",
    "title": "La Stylistique Comparée et l'Analyse de Discours",
    "subtitle": "Analyser les discours, comparer les styles et produire une écriture maîtrisée",
    "slides": [
        ("La stylistique : définition à C2", "La stylistique est l'étude scientifique du style d'un texte : comment les choix linguistiques (phonique, lexical, syntaxique, rhétorique) créent des effets sémantiques et pragmatiques particuliers. À C2, elle implique non seulement d'identifier les figures mais d'analyser leur fonctionnement dans l'économie d'un texte entier."),
        ("L'isotopie sémantique", "Réseau cohérent de sèmes (unités de sens minimales) traversant tout un texte et créant son unité thématique. Ex. : dans un texte sur la guerre, le champ isotopique de la violence (bruit, sang, cri, mort) crée une cohérence sémantique. L'analyse de l'isotopie révèle les axes thématiques profonds."),
        ("L'énonciation et la deixis", "Énonciation : acte de production du discours par un sujet situé dans un temps et un espace. Deixis : ensemble des éléments linguistiques qui renvoient à la situation d'énonciation (je/tu, ici/là, maintenant/alors). L'analyse énonciative répond à : Qui parle ? À qui ? Quand ? Où ? Avec quelle visée ?"),
        ("Analyse du discours : pragmatique et actes de langage", "Acte de langage (Austin, Searle) : toute énonciation accomplit un acte (affirmer, promettre, ordonner, questionner, menacer). Acte illocutoire = intention du locuteur ; acte perlocutoire = effet sur l'interlocuteur. Identifier les actes de langage dans un discours politique ou littéraire révèle les enjeux de pouvoir."),
        ("Texte vs discours", "Texte : objet linguistique clos, analysable formellement. Discours : texte en situation, avec ses conditions de production, ses locuteurs, son contexte socio-historique. L'analyse de discours (Foucault, Maingueneau) s'intéresse aux formations discursives : quels thèmes sont dicibles, par qui, dans quel contexte."),
        ("La cohésion et la cohérence textuelle", "Cohésion : mécanismes linguistiques maintenant l'unité formelle (anaphore pronominale, connecteurs, ellipse). Cohérence : unité sémantique et pragmatique (les phrases parlent du même thème, s'enchaînent logiquement). Un texte peut être formellement cohésif mais sémantiquement incohérent. À C2, analyser les deux."),
        ("L'intertextualité", "Présence dans un texte de traces d'autres textes : citation explicite, allusion, pastiche, parodie, hypotexte/hypertexte (Genette). Ex. : Barthes, Eco, Proust font de l'intertextualité un mode de signification. La reconnaître révèle la culture littéraire de l'auteur et les jeux de sens supplémentaires."),
        ("La comparaison stylistique", "Comparer deux textes sur un thème commun : identifier les points de convergence (registre, thème, procédés communs) et de divergence (ton, rythme, perspective, idéologie). Méthode : analyser séparément, puis confronter explicitement. Éviter le plan par auteur ('A puis B') : préférer le plan par aspects stylistiques."),
        ("La métalangue de l'analyse", "L'analyse stylistique à C2 emploie une métalangue précise : anaphore, deixis, isotopie, polyphonie, énonciation, modalisation, focalisation, hypotexte. Chaque terme employé doit être utilisé correctement et illustré par une citation du texte. La métalangue est au service de l'analyse, non un catalogue à placer."),
        ("Produire un style personnel au niveau C2", "À C2, produire une prose personnelle implique : choix lexicaux précis et non attendus, maîtrise des constructions syntaxiques complexes, jeu intentionnel sur les registres et les rythmes, cohérence thématique et stylistique tout au long du texte. Le style n'est pas une accumulation de figures mais une vision singulière exprimée linguistiquement."),
    ],
    "traps": [
        ("Confondre figure et effet", "Identifier 'métaphore' sans en analyser l'effet : 'il y a une métaphore ici.' À C2, toujours compléter : 'cette métaphore filée X → Y produit l'effet de Z en reliant les champs sémantiques A et B, ce qui suggère que…'"),
        ("Plan par auteur dans une stylistique comparée", "Traiter texte A en partie 1 et texte B en partie 2 sans jamais les confronter explicitement. La stylistique comparée exige un plan par aspects (registre, rythme, figure dominant, énonciation) qui croise les deux textes à chaque étape."),
        ("Métalangue sans illustration", "Écrire 'ce texte est très isotopique et il y a de l'énonciation' sans citer le texte. Chaque concept analytique doit être illustré par une citation précise avec son numéro de ligne."),
        ("Style = accumulation de figures", "Multiplier les figures sans cohérence thématique ne produit pas un 'beau style' mais un texte artificiel. Le style est une cohérence entre la forme et le sens, pas un catalogue de procédés.",),
    ],
    "summary": [
        "Stylistique C2 : analyser comment les choix linguistiques créent des effets sémantiques.",
        "Isotopie : réseau cohérent de sèmes traversant le texte — révèle l'unité thématique.",
        "Énonciation : Qui parle ? À qui ? Quand ? Avec quelle visée ? (deixis + actes de langage).",
        "Cohésion (formelle) vs cohérence (sémantique) — analyser les deux.",
        "Stylistique comparée : plan par aspects (registre, rythme, procédés), pas par auteur.",
    ],
    "ex1": {
        "q": "Qu'est-ce que l'isotopie sémantique dans un texte ?",
        "opts": [
            "La répétition d'un mot clé tout au long du texte",
            "Un réseau cohérent de sèmes traversant le texte et créant son unité thématique",
            "La mesure de la longueur des phrases dans un texte",
            "L'emploi d'une même figure de style à plusieurs reprises",
        ],
        "ans": "Un réseau cohérent de sèmes traversant le texte et créant son unité thématique",
        "exp": "L'isotopie sémantique (Greimas) est la récurrence d'unités de sens (sèmes) qui créent une cohérence thématique à travers le texte. C'est plus que la répétition d'un seul mot : c'est un réseau de termes partageant des sèmes communs ('bruit', 'cri', 'sang', 'mort' forment une isotopie de la violence).",
    },
    "ex2": {
        "q": "Définissez la différence entre 'cohésion textuelle' et 'cohérence textuelle'.",
        "ans": "La cohésion concerne les mécanismes linguistiques formels maintenant l'unité du texte (anaphores, connecteurs, ellipses). La cohérence concerne l'unité sémantique et pragmatique : les phrases parlent du même thème et s'enchaînent logiquement. Un texte peut être cohésif (bien lié formellement) sans être cohérent (sans sens global).",
        "exp": "Exemple : 'Il pleut. Marie chante. La chimie est une science.' est cohésif (phrases correctes) mais incohérent (pas de lien sémantique). L'analyse à C2 examine les deux dimensions : comment le texte tient-il formellement ? Et comment fait-il sens globalement ?",
        "accept": ["cohésion = formelle", "cohérence = sémantique", "cohésion = anaphores connecteurs", "cohérence = unité thématique"],
    },
    "ex3": {
        "q": "Quel plan est recommandé dans une stylistique comparée de deux textes ?",
        "opts": [
            "Plan par auteur : texte A en partie 1, texte B en partie 2",
            "Plan chronologique : du plus ancien au plus récent",
            "Plan par aspects stylistiques croisant les deux textes à chaque étape",
            "Plan thèse/antithèse sur les qualités respectives des deux auteurs",
        ],
        "ans": "Plan par aspects stylistiques croisant les deux textes à chaque étape",
        "exp": "La stylistique comparée exige de confronter les textes à chaque étape de l'analyse. Un plan par auteur (A puis B) produit deux analyses séparées, non une comparaison. Un plan par aspects (registre, rythme, figures dominantes, énonciation) permet de montrer convergences et divergences à chaque niveau d'analyse.",
    },
    "game_desc": "Maîtrisez la stylistique comparée et l'analyse de discours au niveau C2",
    "items": [
        ("g12-isotopie", "l'isotopie sémantique", "réseau cohérent de sèmes traversant un texte et créant son unité thématique", "le réseau sémantique · les sèmes communs · Greimas · l'unité de sens", "Isotopie de la violence dans un texte de guerre : bruit, sang, cri, mort, destruction.", "isotopie = réseau cohérent de sèmes créant l'unité thématique d'un texte", "réseau cohérent de sèmes traversant le texte et créant son unité thématique"),
        ("g12-enonciation", "l'analyse énonciative", "étude de l'acte de production du discours : Qui parle ? À qui ? Quand ? Avec quelle visée ?", "le sujet énonciateur · la deixis · la situation d'énonciation", "Analyse énonciative : identifie le locuteur, l'allocutaire, le cadre spatio-temporel et la visée.", "analyse énonciative = Qui parle ? À qui ? Quand ? Avec quelle visée ?", "étude de l'acte de production du discours et de ses conditions"),
        ("g12-acte-langage", "l'acte de langage", "acte accompli par une énonciation : affirmer, promettre, ordonner, menacer, questionner", "Austin · Searle · l'illocutoire · le perlocutoire", "'Fermez la porte !' accomplit un acte d'ordre (illocutoire) et peut provoquer l'obéissance (perlocutoire).", "acte de langage = acte accompli par une énonciation (Austin/Searle)", "acte accompli par une énonciation : affirmer, promettre, ordonner, etc."),
        ("g12-cohesion-coherence", "cohésion vs cohérence textuelle", "cohésion = liaisons formelles ; cohérence = unité sémantique et pragmatique du texte", "formelle vs sémantique · les connecteurs · le sens global", "Un texte peut être cohésif (bien lié) sans être cohérent (sans sens global unifié).", "cohésion = liaisons formelles ; cohérence = unité sémantique", "cohésion (formelle) vs cohérence (unité sémantique et pragmatique)"),
        ("g12-intertextualite", "l'intertextualité", "présence dans un texte de traces d'autres textes : citation, allusion, pastiche, hypotexte", "Genette · le palimpseste · l'hypertexte · l'allusion littéraire", "'Madame Bovary, c'est moi' — allusion intertextuelle à Flaubert dans un nouveau contexte.", "intertextualité = traces d'autres textes dans un texte (Genette)", "présence de traces d'autres textes : citation, allusion, pastiche, parodie"),
        ("g12-deixis", "la deixis", "éléments linguistiques renvoyant à la situation d'énonciation (je, ici, maintenant)", "les déictiques · je/tu/ici/là/maintenant · la situation d'énonciation", "'Je suis ici maintenant' — trois déictiques renvoyant au locuteur, au lieu, au moment.", "deixis = éléments renvoyant à la situation d'énonciation (je, ici, maintenant)", "éléments linguistiques renvoyant à la situation d'énonciation"),
        ("g12-style-personnel", "le style personnel au C2", "cohérence entre choix lexicaux, syntaxiques et thématiques créant une voix singulière", "la voix · la singularité stylistique · le style comme vision", "Le style n'est pas un catalogue de figures mais une cohérence entre forme et sens.", "style personnel = cohérence form/sens créant une voix singulière", "cohérence entre choix lexicaux, syntaxiques et thématiques créant une voix"),
        ("g12-discours-formation", "la formation discursive", "ensemble de thèmes, règles et positions idéologiques qui définissent ce qui est 'dicible' dans un contexte", "Foucault · le discours · l'archive · l'épistémè", "La formation discursive du XIXe siècle rendait certains sujets (colonisation, genre) 'non questionnables'.", "formation discursive = ensemble de règles définissant ce qui est dicible (Foucault)", "ensemble de thèmes et règles définissant ce qui est dicible dans un contexte"),
    ],
},

}
