"""
francais/b1 — Grammaire B1 — batch 2 (G05–G08)
"""

CHAPTERS = {

"les-pronoms-relatifs-composes": {
    "level": "b1",
    "section": "grammaire",
    "num": "G05",
    "short": "Les Pronoms Relatifs Composés",
    "title": "Les Pronoms Relatifs Composés",
    "subtitle": "Lequel, laquelle, lesquels, lesquelles",
    "slides": [
        ("Rappel : pronoms relatifs simples",
         "<em>qui</em> (sujet) · <em>que</em> (objet direct) · <em>où</em> (lieu/temps) · <em>dont</em> (de + antécédent).<br>Les pronoms composés s'utilisent après une <strong>préposition</strong> (à, avec, pour, sur, dans, par…)."),
        ("Formes : lequel, laquelle…",
         "Accordent avec le nom antécédent :<br>masculin singulier → <em>lequel</em><br>féminin singulier → <em>laquelle</em><br>masculin pluriel → <em>lesquels</em><br>féminin pluriel → <em>lesquelles</em>"),
        ("Contractions avec <em>à</em> et <em>de</em>",
         "à + lequel → <em>auquel</em><br>à + lesquels → <em>auxquels</em><br>à + lesquelles → <em>auxquelles</em><br>à + laquelle → laquelle (pas de contraction)<br>de + lequel → <em>duquel</em><br>de + lesquels → <em>desquels</em><br>de + lesquelles → <em>desquelles</em>"),
        ("Emploi après préposition",
         "C'est le problème <em>auquel</em> je pense. (penser à)<br>La table <em>sur laquelle</em> j'ai posé mon livre.<br>Les collègues <em>avec lesquels</em> je travaille.<br>L'entreprise <em>pour laquelle</em> il travaille."),
        ("<em>Dont</em> vs <em>duquel</em>",
         "<em>Dont</em> remplace 'de + antécédent' dans une structure directe.<br>Mais après une préposition complexe (à côté de, au sujet de, près de…), on utilise <em>duquel/de laquelle/desquels/desquelles</em>.<br><em>La maison à côté de laquelle il y a un parc.</em>"),
        ("<em>Quoi</em> : pronom relatif composé pour les choses abstraites",
         "Après préposition, <em>quoi</em> peut référer à une chose indéfinie ou une proposition :<br><em>C'est ce à quoi je pensais.</em><br><em>Je ne sais pas sur quoi compter.</em>"),
    ],
    "traps": [
        ("Accord en genre/nombre", "'Lequel' s'accorde avec l'antécédent, pas avec le sujet de la proposition relative. <em>La réunion à laquelle j'ai assisté</em> (réunion = féminin → laquelle)."),
        ("<em>Dont</em> ne suit pas une préposition", "On ne dit pas *<em>pour dont</em>, *<em>avec dont</em>. 'Dont' remplace 'de + antécédent' directement. Après une autre préposition, utiliser <em>duquel/de laquelle</em>."),
        ("Contraction <em>à + laquelle</em>", "<em>À + laquelle</em> ne se contracte pas : <em>la table à laquelle</em> (pas : *aulaquelle)."),
        ("<em>Lequel</em> pour les personnes ?", "Pour les personnes, on préfère <em>qui</em> après une préposition : <em>la personne avec qui je travaille</em> (plus courant que <em>avec laquelle</em>). Pour les objets, on utilise toujours <em>lequel/laquelle…</em>"),
    ],
    "summary": [
        "Pronoms composés = <strong>lequel/laquelle/lesquels/lesquelles</strong> après préposition.",
        "Accord en <strong>genre et nombre</strong> avec l'antécédent.",
        "Contractions : à + lequel → <strong>auquel</strong>; de + lequel → <strong>duquel</strong>.",
        "Après préposition complexe (à côté de…) → <strong>duquel/de laquelle</strong>.",
        "Pour personnes + préposition, préférer <em>qui</em>; pour objets → <em>lequel</em>.",
    ],
    "ex1": {
        "q": "Le projet ___ nous travaillons est urgent. (sur)",
        "opts": ["sur lequel", "sur laquelle", "auquel", "duquel"],
        "ans": "sur lequel",
        "exp": "'Projet' est masculin singulier → lequel. La préposition 'sur' reste séparée : 'sur lequel'. 'Auquel' = à+lequel (pas sur). 'Duquel' = de+lequel.",
    },
    "ex2": {
        "q": "Complétez : 'La conférence ___ j'ai participé était intéressante.' (à)",
        "ans": "à laquelle",
        "exp": "'Conférence' est féminin → laquelle. À + laquelle ne se contracte pas.",
        "accept": ["à laquelle", "laquelle"],
    },
    "ex3": {
        "q": "Laquelle de ces phrases est correcte ?",
        "opts": [
            "L'immeuble à côté duquel il y a un café.",
            "L'immeuble à côté dont il y a un café.",
            "L'immeuble à côté lequel il y a un café.",
            "L'immeuble auquel côté il y a un café.",
        ],
        "ans": "L'immeuble à côté duquel il y a un café.",
        "exp": "Après une préposition complexe (à côté de), on utilise 'duquel' (de + lequel, masculin). 'Dont' ne peut pas suivre une préposition. 'Lequel' seul après 'à côté' est incorrect. 'Auquel côté' ne correspond à aucune règle.",
    },
    "game_desc": "Pronoms relatifs composés — formes et emploi",
    "items": [
        ("prc-lequel", "Lequel", "Pronom relatif composé masculin singulier après préposition", "masculin singulier après préposition", "Le problème auquel je pense.", "masculin sg après préposition", "masculin singulier après préposition"),
        ("prc-laquelle", "Laquelle", "Pronom relatif composé féminin singulier après préposition", "féminin singulier après préposition", "La réunion à laquelle j'ai assisté.", "féminin sg après préposition", "féminin singulier après préposition"),
        ("prc-lesquels", "Lesquels/Lesquelles", "Pronoms relatifs composés pluriels après préposition", "pluriel après préposition", "Les projets auxquels nous participons.", "pluriel après préposition", "pluriel après préposition"),
        ("prc-auquel", "Auquel", "Contraction à + lequel (masculin singulier)", "à + lequel = auquel", "C'est le problème auquel je pense.", "contraction de à + lequel", "à + lequel = auquel"),
        ("prc-duquel", "Duquel", "Contraction de + lequel (masculin singulier)", "de + lequel = duquel", "La maison à côté duquel est rouge.", "contraction de de + lequel", "de + lequel = duquel"),
        ("prc-dont-vs-duquel", "Dont vs Duquel", "Dont = de + antécédent direct. Duquel = après préposition complexe.", "dont simple vs duquel après prep. complexe", "La maison dont je parle / à côté de laquelle.", "dont simple, duquel après prép. complexe", "dont simple vs duquel après prep. complexe"),
        ("prc-personnes", "Lequel pour les personnes", "Pour les personnes après préposition, 'qui' est plus courant que 'lequel'", "préférer qui pour les personnes", "La personne avec qui/laquelle je travaille.", "qui ou lequel pour les personnes", "préférer qui pour les personnes"),
        ("prc-quoi", "Ce à quoi / sur quoi", "Quoi = pronom relatif pour chose abstraite ou proposition entière", "quoi après préposition pour l'abstrait", "C'est ce à quoi je pensais.", "quoi pour les abstractions", "quoi après préposition pour l'abstrait"),
    ],
},

"les-connecteurs-logiques": {
    "level": "b1",
    "section": "grammaire",
    "num": "G06",
    "short": "Les Connecteurs Logiques",
    "title": "Les Connecteurs Logiques",
    "subtitle": "Cause, conséquence, opposition, concession",
    "slides": [
        ("Connecteurs de cause",
         "<em>parce que</em> (réponse directe à 'pourquoi') · <em>car</em> (explication, en début ou milieu de phrase) · <em>puisque</em> (cause connue, évidente) · <em>comme</em> (cause en tête de phrase) · <em>à cause de / grâce à</em> + nom."),
        ("Cause : nuances",
         "<em>parce que</em> : raison principale. <em>puisque</em> : cause déjà connue des deux interlocuteurs. <em>comme</em> : toujours en tête de phrase. <em>grâce à</em> : cause positive. <em>à cause de</em> : cause neutre/négative."),
        ("Connecteurs de conséquence",
         "<em>donc</em> (conclusion logique) · <em>alors</em> (résultat dans la narration) · <em>c'est pourquoi</em> (formel) · <em>par conséquent</em> (écrit formel) · <em>ainsi</em> (formel) · <em>du coup</em> (familier)."),
        ("Connecteurs d'opposition",
         "<em>mais</em> (opposition simple) · <em>cependant / pourtant / toutefois / néanmoins</em> (opposition plus forte, registre soutenu) · <em>par contre / en revanche</em> (contraste)."),
        ("Connecteurs de concession",
         "<em>bien que / quoique</em> + subjonctif · <em>même si</em> + indicatif · <em>malgré</em> + nom · <em>quand même</em> (renforcement) · <em>bien sûr … mais</em>."),
        ("Connecteurs d'addition",
         "<em>et, aussi, de plus, en plus, par ailleurs, d'autre part, en outre</em> (formel) · <em>non seulement … mais aussi</em>."),
    ],
    "traps": [
        ("<em>Parce que</em> vs <em>puisque</em>", "'Parce que' donne une information nouvelle. 'Puisque' part d'une prémisse partagée : <em>Puisque tu es là, on peut commencer</em> (les deux savent qu'il est là)."),
        ("<em>Bien que</em> + subjonctif", "Ne jamais écrire 'bien que + indicatif'. *<em>Bien qu'il est là</em> est fautif → <em>Bien qu'il soit là</em>."),
        ("<em>Malgré</em> + nom (pas + verbe)", "*<em>Malgré qu'il pleuve</em> est non standard. On dit : <em>Malgré la pluie</em> ou <em>bien qu'il pleuve</em>."),
        ("<em>Par contre</em> vs <em>en revanche</em>", "Les deux expriment le contraste. 'Par contre' est courant mais parfois considéré familier. 'En revanche' est neutre/soutenu."),
    ],
    "summary": [
        "<strong>Cause :</strong> parce que, car, puisque, comme, grâce à, à cause de.",
        "<strong>Conséquence :</strong> donc, alors, c'est pourquoi, par conséquent.",
        "<strong>Opposition :</strong> mais, cependant, pourtant, en revanche.",
        "<strong>Concession :</strong> bien que + subjonctif; même si + indicatif; malgré + nom.",
        "<strong>Addition :</strong> de plus, par ailleurs, non seulement … mais aussi.",
    ],
    "ex1": {
        "q": "___ il fait froid, nous sortons quand même.",
        "opts": ["Bien que", "Parce que", "Donc", "Grâce à"],
        "ans": "Bien que",
        "exp": "On exprime une concession (action malgré l'obstacle). 'Bien que' déclenche le subjonctif mais ici on évalue le connecteur. 'Parce que' introduit une cause; 'Donc' une conséquence; 'Grâce à' nécessite un nom.",
    },
    "ex2": {
        "q": "Choisissez le bon connecteur de conséquence : 'Il a manqué son train, ___ il est arrivé en retard.'",
        "ans": "donc",
        "exp": "Connecteur de conséquence logique entre deux faits : donc / alors / c'est pourquoi.",
        "accept": ["donc", "alors", "c'est pourquoi", "par conséquent", "du coup"],
    },
    "ex3": {
        "q": "Quelle phrase est grammaticalement correcte ?",
        "opts": [
            "Bien qu'il soit fatigué, il continue à travailler.",
            "Bien qu'il est fatigué, il continue à travailler.",
            "Malgré qu'il pleuve, nous sortons.",
            "Puisque que tu veux, reste.",
        ],
        "ans": "Bien qu'il soit fatigué, il continue à travailler.",
        "exp": "'Bien que' exige le subjonctif (soit, pas est). 'Malgré' ne se construit pas avec 'que + verbe' (→ malgré la pluie). 'Puisque que' est une répétition fautive de la conjonction.",
    },
    "game_desc": "Connecteurs logiques — cause, conséquence, opposition",
    "items": [
        ("conn-parce-que", "Parce que", "Connecteur de cause répondant directement à 'pourquoi'", "cause directe", "Je reste parce qu'il pleut.", "cause en réponse à pourquoi", "cause directe"),
        ("conn-puisque", "Puisque", "Connecteur de cause pour une réalité déjà connue des deux interlocuteurs", "cause évidente ou connue", "Puisque tu es là, commençons.", "cause connue = puisque", "cause évidente ou connue"),
        ("conn-donc", "Donc", "Connecteur de conséquence logique", "conséquence logique", "Il a raté son bus, donc il est en retard.", "conséquence logique", "conséquence logique"),
        ("conn-cependant", "Cependant / Pourtant", "Connecteurs d'opposition soutenue", "opposition forte, registre soutenu", "Il travaille; cependant, il n'avance pas.", "opposition soutenue", "opposition forte, registre soutenu"),
        ("conn-bien-que", "Bien que + subjonctif", "Connecteur de concession toujours suivi du subjonctif", "bien que + subjonctif", "Bien qu'il soit tard, je reste.", "concession + subjonctif obligatoire", "bien que + subjonctif"),
        ("conn-malgre", "Malgré + nom", "Connecteur de concession suivi d'un nom, jamais d'une proposition", "malgré + nom (pas de verbe)", "Malgré la pluie, nous sortons.", "malgré + nom uniquement", "malgré + nom (pas de verbe)"),
        ("conn-grace-a", "Grâce à / À cause de", "Grâce à = cause positive; à cause de = cause neutre/négative", "cause positive vs négative", "Grâce à lui, j'ai réussi. / À cause du bruit, je n'ai pas dormi.", "grâce à (positif) / à cause de (négatif)", "cause positive vs négative"),
        ("conn-non-seulement", "Non seulement … mais aussi", "Connecteur d'addition emphatique", "addition emphatique", "Il est non seulement intelligent mais aussi travailleur.", "non seulement + mais aussi", "addition emphatique"),
    ],
},

"le-discours-indirect": {
    "level": "b1",
    "section": "grammaire",
    "num": "G07",
    "short": "Le Discours Indirect",
    "title": "Le Discours Indirect",
    "subtitle": "Rapporter les paroles de quelqu'un",
    "slides": [
        ("Discours direct vs indirect",
         "Direct : Il dit : <em>«Je suis fatigué.»</em><br>Indirect : Il dit qu'<em>il est fatigué</em>.<br>Changements possibles : personnes grammaticales, temps, expressions de temps."),
        ("Concordance des temps — verbe introducteur au présent",
         "Si le verbe introducteur est au présent/futur, <strong>les temps ne changent pas</strong>.<br>Il dit : «Je viendrai.» → Il dit qu'<em>il viendra</em>.<br>Elle dit : «J'ai faim.» → Elle dit qu'<em>elle a faim</em>."),
        ("Concordance des temps — verbe introducteur au passé",
         "Présent → <strong>imparfait</strong> · Passé composé → <strong>PQP</strong> · Futur → <strong>Conditionnel présent</strong> · Futur antérieur → <strong>Conditionnel passé</strong>.<br>Il a dit : «Je <em>suis</em> là.» → Il a dit qu'<em>il était</em> là."),
        ("Questions indirectes",
         "<em>Oui/non</em> : Il a demandé <em>si</em> elle viendrait.<br><em>Mots interrogatifs :</em> Il a demandé <em>où</em> elle habitait · <em>ce que</em> tu voulais · <em>ce qui</em> se passait · <em>quand</em> tu partais · <em>pourquoi</em> il était en retard.<br>L'inversion n'est pas conservée."),
        ("Changements de personnes et de déictiques",
         "Je → il/elle · Mon → son/sa · Tu → je/il/elle (selon contexte).<br>Ici → là · Maintenant → alors / à ce moment-là · Aujourd'hui → ce jour-là · Demain → le lendemain · Hier → la veille."),
        ("Ordres et conseils au discours indirect",
        "Impératif → de + infinitif.<br>Il dit : <em>«Viens !»</em> → Il dit à Marie de <em>venir</em>.<br>Il dit : <em>«Ne pars pas.»</em> → Il dit à Marie de ne pas <em>partir</em>."),
    ],
    "traps": [
        ("Pas d'inversion dans les questions indirectes", "On ne garde pas l'inversion. *'Il a demandé où habitait-elle' → Il a demandé où <em>elle habitait</em>."),
        ("<em>Ce que / Ce qui</em> pour 'quoi/que'", "Question directe : Qu'est-ce que tu veux ? → Indirect : Il a demandé <em>ce que</em> tu voulais (pas *<em>que</em> tu voulais). Ce qui = sujet; ce que = objet."),
        ("Impératif → de + infinitif", "L'impératif du discours direct devient 'dire à qqn de + inf.' : *'Il a dit qu'il parte' est incorrect."),
        ("Pas de changement si verbe introducteur au présent", "Si le verbe introducteur est au présent, pas de concordance obligatoire des temps. <em>Elle dit qu'elle viendra</em> (pas *viendrait)."),
    ],
    "summary": [
        "Verbe intro au <strong>présent</strong> → les temps ne changent pas.",
        "Verbe intro au <strong>passé</strong> → Présent→Imparfait; PC→PQP; Futur→Conditionnel.",
        "Questions yes/no → <strong>si</strong>; mots interrogatifs → conservés; que/quoi → <strong>ce que/ce qui</strong>.",
        "Impératif → <strong>de + infinitif</strong>.",
        "Déictiques changent : ici→là, maintenant→alors, demain→le lendemain.",
    ],
    "ex1": {
        "q": "Il a dit : «Je viendrai demain.» → Il a dit qu'il ___ le lendemain.",
        "opts": ["viendrait", "viendrais", "viendra", "est venu"],
        "ans": "viendrait",
        "exp": "Verbe introducteur au passé (a dit) → futur → conditionnel présent (viendrait). 'Demain' → 'le lendemain'. 'Viendra' serait correct si 'dit' était au présent.",
    },
    "ex2": {
        "q": "Transformez en discours indirect : 'Viens ici !' (Il a dit à Marie…)",
        "ans": "il a dit à marie de venir",
        "exp": "L'impératif 'Viens' devient 'de + infinitif' : Il a dit à Marie de venir. 'Ici' → 'là' si on adapte les déictiques.",
        "accept": ["il a dit à marie de venir", "il a dit à marie de venir.", "de venir", "il lui a dit de venir"],
    },
    "ex3": {
        "q": "Elle a demandé : «Qu'est-ce que tu veux ?» → Elle a demandé ___",
        "opts": [
            "ce que je voulais.",
            "que je voulais.",
            "ce qui je voulais.",
            "qu'est-ce que je voulais.",
        ],
        "ans": "ce que je voulais.",
        "exp": "'Qu'est-ce que' (objet direct) → 'ce que' au discours indirect. Pas d'inversion. 'Que je voulais' est incorrect (on ne garde pas le 'que' seul). 'Ce qui' est pour le sujet.",
    },
    "game_desc": "Discours indirect — concordance des temps et transformations",
    "items": [
        ("di-def", "Le discours indirect", "Façon de rapporter les paroles de quelqu'un sans les citer directement", "rapporter sans guillemets", "Il dit qu'il est fatigué.", "rapporter les paroles de qqn", "rapporter sans guillemets"),
        ("di-present", "Verbe intro au présent", "Si le verbe introducteur est au présent, pas de changement de temps", "présent → mêmes temps", "Elle dit qu'elle viendra.", "pas de changement si verbe au présent", "présent → mêmes temps"),
        ("di-passe-imp", "Présent → Imparfait", "Concordance : présent direct → imparfait indirect (verbe intro au passé)", "présent → imparfait", "Il a dit qu'il était fatigué.", "présent direct = imparfait indirect", "présent → imparfait"),
        ("di-futur-cond", "Futur → Conditionnel", "Concordance : futur direct → conditionnel présent indirect (verbe intro au passé)", "futur → conditionnel présent", "Elle a dit qu'elle viendrait.", "futur direct = conditionnel indirect", "futur → conditionnel présent"),
        ("di-si", "Questions oui/non → si", "Les questions oui/non au discours indirect sont introduites par 'si'", "question oui/non = si", "Il a demandé si tu venais.", "si pour les questions oui/non", "question oui/non = si"),
        ("di-ce-que", "Ce que / Ce qui", "Que/Qu'est-ce que → ce que; Qu'est-ce qui → ce qui au discours indirect", "que → ce que; qui → ce qui", "Il a demandé ce que tu voulais.", "ce que (objet) / ce qui (sujet)", "que → ce que; qui → ce qui"),
        ("di-imperatif", "Impératif → de + infinitif", "L'impératif direct devient 'dire à qqn de + infinitif' au discours indirect", "impératif → de + infinitif", "Il a dit à Paul de partir.", "impératif = de + inf. indirect", "impératif → de + infinitif"),
        ("di-deictic", "Changements déictiques", "Ici→là, maintenant→alors, aujourd'hui→ce jour-là, demain→le lendemain, hier→la veille", "adaptation des expressions de temps/lieu", "Il a dit que demain → le lendemain.", "déictiques changent au passé", "adaptation des expressions de temps/lieu"),
    ],
},

"les-verbes-impersonnels": {
    "level": "b1",
    "section": "grammaire",
    "num": "G08",
    "short": "Les Verbes Impersonnels",
    "title": "Les Verbes Impersonnels",
    "subtitle": "Il faut, il s'agit de, il vaut mieux…",
    "slides": [
        ("Qu'est-ce qu'un verbe impersonnel ?",
         "Un verbe impersonnel s'emploie uniquement à la 3e personne du singulier avec le sujet <em>il</em> grammatical (pas de référent réel). La liste inclut des verbes météo, des expressions de nécessité/opinion, et des constructions avec d'autres verbes."),
        ("Météo et existence",
         "<em>il pleut, il neige, il fait chaud/froid/beau/mauvais, il y a, il vente</em>.<br>Ces verbes n'ont pas d'autre sujet possible : *'il' est toujours le sujet."),
        ("Nécessité et obligation",
         "<em>il faut</em> + infinitif : <em>Il faut partir maintenant.</em><br><em>il faut que</em> + subjonctif : <em>Il faut que tu viennes.</em><br><em>il est nécessaire de</em> + inf. · <em>il est indispensable de</em> + inf."),
        ("Opinion et probabilité",
         "<em>il semble que</em> + subjonctif : <em>Il semble qu'il soit absent.</em><br><em>il paraît que</em> + indicatif : <em>Il paraît qu'il est malade.</em><br><em>il est possible que</em> + subjonctif · <em>il est probable que</em> + indicatif · <em>il est évident que</em> + indicatif."),
        ("<em>Il s'agit de</em> et <em>il vaut mieux</em>",
         "<em>Il s'agit de</em> + nom/inf. : <em>Il s'agit d'un problème grave. / Il s'agit de trouver une solution.</em><br><em>Il vaut mieux</em> + inf. : <em>Il vaut mieux partir tôt.</em><br><em>Il vaut mieux que</em> + subjonctif : <em>Il vaut mieux qu'il parte.</em>"),
        ("Constructions impersonnelles avec d'autres verbes",
         "Tout verbe peut devenir impersonnel avec construction passive/neutre :<br><em>Il se passe quelque chose d'étrange.</em><br><em>Il existe plusieurs solutions.</em><br><em>Il reste deux places.</em><br><em>Il manque un détail.</em>"),
    ],
    "traps": [
        ("<em>Il paraît que</em> vs <em>il semble que</em>", "'Il paraît que' + indicatif (information entendue). 'Il semble que' + subjonctif (impression personnelle)."),
        ("<em>Il est probable</em> vs <em>il est possible</em>", "'Il est probable que' + indicatif (forte probabilité). 'Il est possible que' + subjonctif (simple possibilité)."),
        ("<em>Il faut</em> sans que vs avec que", "'Il faut partir' (sujet de la principale et de l'infinitif identique ou indéterminé). 'Il faut que tu partes' (nécessité pour un sujet spécifique → subjonctif)."),
        ("Il reste / Il manque", "Ces constructions impersonnelles ont un sujet logique postposé : <em>Il reste deux billets</em> (= deux billets restent). L'accord du verbe est toujours avec 'il' (3e sg)."),
    ],
    "summary": [
        "<strong>Météo :</strong> il pleut, il neige, il fait beau/chaud/froid.",
        "<strong>Nécessité :</strong> il faut + inf. / il faut que + subjonctif.",
        "<strong>Opinion :</strong> il semble que + subj.; il paraît que + ind.; il est possible que + subj.",
        "<strong>Il s'agit de</strong> + nom/inf.; <strong>il vaut mieux</strong> + inf.",
        "Constructions neutres : il existe, il reste, il manque + nom.",
    ],
    "ex1": {
        "q": "Il ___ que vous connaissiez cette règle. (nécessité)",
        "opts": ["faut", "paraît", "semble", "est probable"],
        "ans": "faut",
        "exp": "'Il faut que' + subjonctif exprime la nécessité. 'Il paraît que' + indicatif. 'Il semble que' + subjonctif mais exprime une impression. 'Il est probable que' + indicatif.",
    },
    "ex2": {
        "q": "Complétez : 'Il ___ d'un malentendu.' (concerne / s'agit)",
        "ans": "s'agit",
        "exp": "'Il s'agit de' exprime le sujet ou la nature de quelque chose. Il s'agit d'un malentendu.",
        "accept": ["s'agit", "il s'agit", "s'agit de"],
    },
    "ex3": {
        "q": "Quelle phrase est correcte ?",
        "opts": [
            "Il paraît qu'il est malade.",
            "Il paraît qu'il soit malade.",
            "Il semble qu'il est malade.",
            "Il vaut mieux que tu pars.",
        ],
        "ans": "Il paraît qu'il est malade.",
        "exp": "'Il paraît que' prend l'indicatif (est). 'Il semble que' prend le subjonctif (soit, pas est). 'Il vaut mieux que' prend le subjonctif (partes, pas pars).",
    },
    "game_desc": "Verbes impersonnels — nécessité, probabilité, opinion",
    "items": [
        ("vi-def", "Verbe impersonnel", "Verbe toujours à la 3e personne du singulier avec 'il' grammatical", "il + verbe 3e personne sg", "Il pleut. Il faut partir.", "il + verbe sans sujet réel", "il + verbe 3e personne sg"),
        ("vi-meteo", "Météo impersonnelle", "Il pleut, il neige, il fait beau/chaud/froid/mauvais, il vente", "il fait + adjectif météo", "Il fait froid ce matin.", "expressions météo impersonnelles", "il fait + adjectif météo"),
        ("vi-faut-inf", "Il faut + inf.", "Exprimer une obligation générale ou sans sujet précis", "il faut + infinitif", "Il faut manger pour vivre.", "obligation générale = il faut + inf.", "il faut + infinitif"),
        ("vi-faut-que", "Il faut que + subj.", "Obligation pour un sujet précis → subjonctif obligatoire", "il faut que + subjonctif", "Il faut que tu viennes.", "obligation spécifique = il faut que + subj.", "il faut que + subjonctif"),
        ("vi-semble", "Il semble que + subj.", "Impression personnelle incertaine → subjonctif", "il semble que + subjonctif", "Il semble qu'il soit absent.", "impression = il semble que + subj.", "il semble que + subjonctif"),
        ("vi-parait", "Il paraît que + ind.", "Information entendue/rapportée → indicatif", "il paraît que + indicatif", "Il paraît qu'il démissionne.", "info entendue = il paraît que + ind.", "il paraît que + indicatif"),
        ("vi-sagit", "Il s'agit de", "Exprimer le sujet ou la nature de quelque chose", "il s'agit de + nom/inf.", "Il s'agit d'un problème technique.", "il s'agit de = it's about", "il s'agit de + nom/inf."),
        ("vi-vaut-mieux", "Il vaut mieux", "Exprimer une préférence ou un conseil général", "il vaut mieux + inf./que + subj.", "Il vaut mieux partir tôt.", "préférence = il vaut mieux", "il vaut mieux + inf./que + subj."),
    ],
},

}
