"""Français A2 — Vocabulaire batch 1: V01–V04."""

CHAPTERS = {

# ── V01 Le Travail ─────────────────────────────────────────────────────────
'le-travail': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V01',
    'short':   'Le Travail',
    'title':   'Le Travail — Les Professions et le Bureau',
    'subtitle': 'Les métiers courants et le vocabulaire du monde professionnel',
    'game_desc': 'Apprenez le vocabulaire du travail en français !',
    'words': [
        {'word': 'le médecin',      'ipa': '/lə me.dsɛ̃/',   'def': 'the doctor',               'ex': 'Le médecin m\'a donné une ordonnance.'},
        {'word': 'l\'infirmier/ière','ipa': '/lɛ̃.fiʁ.mje/', 'def': 'the nurse',                'ex': 'L\'infirmière prend soin des malades.'},
        {'word': 'le professeur',   'ipa': '/lə pʁo.fɛ.sœʁ/','def': 'the teacher / professor', 'ex': 'Mon professeur de français est très patient.'},
        {'word': 'l\'avocat(e)',    'ipa': '/la.vɔ.ka/',     'def': 'the lawyer',               'ex': 'Mon avocat a gagné le procès.'},
        {'word': 'l\'ingénieur',    'ipa': '/lɛ̃.ʒe.njœʁ/', 'def': 'the engineer',             'ex': 'Elle est ingénieure en informatique.'},
        {'word': 'le/la chef',      'ipa': '/lə ʃɛf/',       'def': 'the boss / chef',          'ex': 'Mon chef est très exigeant.'},
        {'word': 'le collègue',     'ipa': '/lə kɔ.lɛg/',   'def': 'the colleague',            'ex': 'Mes collègues sont sympa.'},
        {'word': 'le bureau',       'ipa': '/lə by.ʁo/',     'def': 'the office / desk',        'ex': 'Je travaille dans un bureau au centre-ville.'},
        {'word': 'la réunion',      'ipa': '/la ʁe.y.njɔ̃/', 'def': 'the meeting',              'ex': 'Nous avons une réunion à 14 h.'},
        {'word': 'le salaire',      'ipa': '/lə sa.lɛʁ/',    'def': 'the salary / wage',        'ex': 'Mon salaire a augmenté cette année.'},
        {'word': 'travailler',      'ipa': '/tʁa.va.je/',    'def': 'to work',                  'ex': 'Je travaille de 9 h à 17 h.'},
        {'word': 'chercher un emploi','ipa': '/ʃɛʁ.ʃe œ̃n ɑ̃.plwa/', 'def': 'to look for a job','ex': 'Elle cherche un emploi depuis deux mois.'},
        {'word': 'le contrat',      'ipa': '/lə kɔ̃.tʁa/',   'def': 'the contract',             'ex': 'J\'ai signé un contrat à durée indéterminée.'},
        {'word': 'les congés',      'ipa': '/le kɔ̃.ʒe/',    'def': 'the holidays / leave',     'ex': 'Je prends mes congés en août.'},
        {'word': 'être en chômage', 'ipa': '/ɛtʁ ɑ̃ ʃo.maʒ/','def': 'to be unemployed',        'ex': 'Il est en chômage depuis six mois.'},
    ],
    'items': [
        ('trav-01', 'le médecin',    'the doctor',       'métier',   'Le médecin m\'a donné une ordonnance.', 'Le ___ m\'a donné une ordonnance.',     'médecin'),
        ('trav-02', 'le professeur', 'the teacher',      'métier',   'Mon professeur est très patient.',       'Mon ___ est très patient.',              'professeur'),
        ('trav-03', 'le collègue',   'the colleague',    'travail',  'Mes collègues sont sympa.',              'Mes ___ sont sympa.',                    'collègues'),
        ('trav-04', 'la réunion',    'the meeting',      'bureau',   'Nous avons une réunion à 14 h.',         'Nous avons une ___ à 14 h.',             'réunion'),
        ('trav-05', 'le salaire',    'the salary',       'travail',  'Mon salaire a augmenté cette année.',    'Mon ___ a augmenté cette année.',        'salaire'),
        ('trav-06', 'le bureau',     'the office',       'lieu',     'Je travaille dans un bureau au centre.',  'Je travaille dans un ___ au centre.',    'bureau'),
        ('trav-07', 'les congés',    'the holidays/leave','travail', 'Je prends mes congés en août.',          'Je prends mes ___ en août.',             'congés'),
        ('trav-08', 'chercher un emploi','to look for a job','action','Elle cherche un emploi depuis deux mois.','Elle ___ un emploi depuis deux mois.',  'cherche'),
    ],
},

# ── V02 Les Loisirs ────────────────────────────────────────────────────────
'les-loisirs': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V02',
    'short':   'Les Loisirs',
    'title':   'Les Loisirs — Sport, Culture et Détente',
    'subtitle': 'Les activités de loisir et les verbes pour en parler',
    'game_desc': 'Apprenez le vocabulaire des loisirs en français !',
    'words': [
        {'word': 'faire du sport',  'ipa': '/fɛʁ dy spɔʁ/',  'def': 'to do sport',              'ex': 'Je fais du sport trois fois par semaine.'},
        {'word': 'nager',           'ipa': '/na.ʒe/',         'def': 'to swim',                  'ex': 'Elle nage tous les matins à la piscine.'},
        {'word': 'courir',          'ipa': '/ku.ʁiʁ/',        'def': 'to run',                   'ex': 'Il court dix kilomètres chaque week-end.'},
        {'word': 'jouer à',         'ipa': '/ʒwe a/',         'def': 'to play (sport/game)',      'ex': 'Nous jouons au tennis le samedi.'},
        {'word': 'faire de la randonnée','ipa': '/fɛʁ də la ʁɑ̃.dɔ.ne/','def': 'to go hiking',  'ex': 'On fait de la randonnée en montagne.'},
        {'word': 'lire',            'ipa': '/liʁ/',           'def': 'to read',                  'ex': 'J\'aime lire des romans policiers.'},
        {'word': 'regarder un film','ipa': '/ʁə.ɡaʁ.de œ̃ film/','def': 'to watch a film',      'ex': 'On regarde un film le vendredi soir.'},
        {'word': 'écouter de la musique','ipa': '/e.ku.te/','def': 'to listen to music',         'ex': 'J\'écoute de la musique en faisant le ménage.'},
        {'word': 'cuisiner',        'ipa': '/kɥi.zi.ne/',     'def': 'to cook',                  'ex': 'Il adore cuisiner des plats exotiques.'},
        {'word': 'voyager',         'ipa': '/vwa.ja.ʒe/',     'def': 'to travel',                'ex': 'Nous adorons voyager en train.'},
        {'word': 'le cinéma',       'ipa': '/lə si.ne.ma/',   'def': 'the cinema',               'ex': 'On va souvent au cinéma le week-end.'},
        {'word': 'le théâtre',      'ipa': '/lə te.atʁ/',     'def': 'the theatre',              'ex': 'Elle préfère le théâtre au cinéma.'},
        {'word': 'la piscine',      'ipa': '/la pi.sin/',     'def': 'the swimming pool',        'ex': 'Je vais à la piscine deux fois par semaine.'},
        {'word': 'le week-end',     'ipa': '/lə wi.kɛnd/',    'def': 'the weekend',              'ex': 'Ce week-end, on va à la plage.'},
        {'word': 'se détendre',     'ipa': '/sə de.tɑ̃dʁ/',   'def': 'to relax',                 'ex': 'Le week-end, j\'aime me détendre à la maison.'},
    ],
    'items': [
        ('lois-01', 'faire du sport', 'to do sport',     'loisir',  'Je fais du sport trois fois par semaine.', 'Je ___ sport trois fois par semaine.',  'fais du'),
        ('lois-02', 'jouer à',       'to play (sport)',  'loisir',  'Nous jouons au tennis le samedi.',          'Nous ___ tennis le samedi.',             'jouons au'),
        ('lois-03', 'lire',          'to read',          'culture', 'J\'aime lire des romans policiers.',        'J\'aime ___ des romans policiers.',      'lire'),
        ('lois-04', 'voyager',       'to travel',        'loisir',  'Nous adorons voyager en train.',            'Nous adorons ___ en train.',             'voyager'),
        ('lois-05', 'le cinéma',     'the cinema',       'culture', 'On va souvent au cinéma le week-end.',      'On va souvent au ___ le week-end.',      'cinéma'),
        ('lois-06', 'cuisiner',      'to cook',          'loisir',  'Il adore cuisiner des plats exotiques.',    'Il adore ___ des plats exotiques.',      'cuisiner'),
        ('lois-07', 'se détendre',   'to relax',         'loisir',  'J\'aime me détendre à la maison.',          'J\'aime me ___ à la maison.',            'détendre'),
        ('lois-08', 'la piscine',    'the swimming pool','sport',   'Je vais à la piscine deux fois par semaine.','Je vais à la ___ deux fois par semaine.','piscine'),
    ],
},

# ── V03 La Santé ───────────────────────────────────────────────────────────
'la-sante': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V03',
    'short':   'La Santé',
    'title':   'La Santé — Chez le Médecin',
    'subtitle': 'Le vocabulaire médical pour décrire les symptômes et consulter un médecin',
    'game_desc': 'Apprenez le vocabulaire de la santé en français !',
    'words': [
        {'word': 'la fièvre',       'ipa': '/la fjɛvʁ/',      'def': 'the fever',                'ex': 'J\'ai de la fièvre depuis hier soir.'},
        {'word': 'la toux',         'ipa': '/la tu/',          'def': 'the cough',                'ex': 'Il a une mauvaise toux depuis une semaine.'},
        {'word': 'le rhume',        'ipa': '/lə ʁym/',         'def': 'the cold (illness)',       'ex': 'J\'ai attrapé un rhume ce week-end.'},
        {'word': 'la grippe',       'ipa': '/la ɡʁip/',        'def': 'the flu',                  'ex': 'Elle a la grippe et doit rester au lit.'},
        {'word': 'avoir mal à',     'ipa': '/a.vwaʁ mal a/',  'def': 'to have pain in',          'ex': 'J\'ai mal à la gorge depuis deux jours.'},
        {'word': 'se sentir bien/mal','ipa': '/sə sɑ̃.tiʁ/','def': 'to feel well/unwell',        'ex': 'Je ne me sens pas bien aujourd\'hui.'},
        {'word': 'l\'ordonnance',   'ipa': '/lɔʁ.dɔ.nɑ̃s/',  'def': 'the prescription',         'ex': 'Le médecin m\'a donné une ordonnance.'},
        {'word': 'le médicament',   'ipa': '/lə me.di.ka.mɑ̃/','def': 'the medicine / medication','ex': 'Je prends ces médicaments trois fois par jour.'},
        {'word': 'la pharmacie',    'ipa': '/la faʁ.ma.si/',  'def': 'the pharmacy',             'ex': 'Je vais à la pharmacie chercher mes médicaments.'},
        {'word': 'prendre rendez-vous','ipa': '/pʁɑ̃dʁ ʁɑ̃.de.vu/','def': 'to make an appointment','ex': 'J\'ai pris rendez-vous chez le médecin.'},
        {'word': 'être allergique à','ipa': '/ɛtʁ a.lɛʁ.ʒik a/','def': 'to be allergic to',    'ex': 'Je suis allergique aux arachides.'},
        {'word': 'se blesser',      'ipa': '/sə blɛ.se/',     'def': 'to injure oneself',        'ex': 'Il s\'est blessé au genou pendant le match.'},
        {'word': 'l\'urgence',      'ipa': '/lyʁ.ʒɑ̃s/',      'def': 'the emergency',            'ex': 'On l\'a emmené aux urgences.'},
        {'word': 'guérir',          'ipa': '/ɡe.ʁiʁ/',        'def': 'to recover / to heal',     'ex': 'Il a guéri rapidement grâce aux antibiotiques.'},
        {'word': 'se reposer',      'ipa': '/sə ʁə.po.ze/',   'def': 'to rest',                  'ex': 'Le médecin m\'a dit de me reposer.'},
    ],
    'items': [
        ('sant-01', 'la fièvre',    'the fever',      'symptôme', 'J\'ai de la fièvre depuis hier soir.',     'J\'ai de la ___ depuis hier soir.',       'fièvre'),
        ('sant-02', 'le rhume',     'the cold',       'maladie',  'J\'ai attrapé un rhume ce week-end.',      'J\'ai attrapé un ___ ce week-end.',        'rhume'),
        ('sant-03', 'avoir mal à',  'to have pain in','symptôme', 'J\'ai mal à la gorge depuis deux jours.',  'J\'ai ___ à la gorge depuis deux jours.',  'mal'),
        ('sant-04', 'l\'ordonnance','the prescription','médecin',  'Le médecin m\'a donné une ordonnance.',    'Le médecin m\'a donné une ___.',           'ordonnance'),
        ('sant-05', 'le médicament','the medicine',   'traitement','Je prends ces médicaments trois fois par jour.','Je prends ces ___ trois fois par jour.','médicaments'),
        ('sant-06', 'prendre rendez-vous','make an appt','action', 'J\'ai pris rendez-vous chez le médecin.', 'J\'ai pris ___ chez le médecin.',          'rendez-vous'),
        ('sant-07', 'se reposer',   'to rest',        'conseil',  'Le médecin m\'a dit de me reposer.',       'Le médecin m\'a dit de me ___.',           'reposer'),
        ('sant-08', 'guérir',       'to recover',     'résultat', 'Il a guéri grâce aux antibiotiques.',      'Il a ___ grâce aux antibiotiques.',        'guéri'),
    ],
},

# ── V04 La Ville ───────────────────────────────────────────────────────────
'la-ville': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V04',
    'short':   'La Ville',
    'title':   'La Ville — Les Commerces et Les Lieux',
    'subtitle': 'Se repérer en ville, faire des courses et décrire son quartier',
    'game_desc': 'Apprenez le vocabulaire de la ville en français !',
    'words': [
        {'word': 'la boulangerie',  'ipa': '/la bu.lɑ̃.ʒʁi/', 'def': 'the bakery',               'ex': 'J\'achète mon pain à la boulangerie du coin.'},
        {'word': 'la boucherie',    'ipa': '/la buʃ.ʁi/',     'def': 'the butcher\'s',            'ex': 'La boucherie est fermée le dimanche.'},
        {'word': 'le supermarché',  'ipa': '/lə sy.pɛʁ.maʁ.ʃe/','def': 'the supermarket',       'ex': 'Je fais mes courses au supermarché le samedi.'},
        {'word': 'la pharmacie',    'ipa': '/la faʁ.ma.si/',  'def': 'the pharmacy / chemist\'s','ex': 'La pharmacie est à côté de la mairie.'},
        {'word': 'la mairie',       'ipa': '/la mɛ.ʁi/',      'def': 'the town hall',            'ex': 'Je dois aller à la mairie pour une carte d\'identité.'},
        {'word': 'la bibliothèque', 'ipa': '/la bi.bli.o.tɛk/','def': 'the library',             'ex': 'J\'emprunte des livres à la bibliothèque.'},
        {'word': 'le marché',       'ipa': '/lə maʁ.ʃe/',     'def': 'the market',               'ex': 'Le marché a lieu tous les dimanches matin.'},
        {'word': 'la poste',        'ipa': '/la pɔst/',        'def': 'the post office',          'ex': 'Je dois envoyer un colis à la poste.'},
        {'word': 'la banque',       'ipa': '/la bɑ̃k/',        'def': 'the bank',                 'ex': 'Je vais retirer de l\'argent à la banque.'},
        {'word': 'la place',        'ipa': '/la plas/',        'def': 'the square / plaza',       'ex': 'On se retrouve sur la place du marché à midi.'},
        {'word': 'le quartier',     'ipa': '/lə kaʁ.tje/',    'def': 'the neighbourhood / district','ex': 'J\'habite dans un quartier tranquille.'},
        {'word': 'l\'église',       'ipa': '/le.ɡliz/',       'def': 'the church',               'ex': 'L\'église est au centre de la ville.'},
        {'word': 'faire les courses','ipa': '/fɛʁ le kuʁs/',  'def': 'to do the shopping',       'ex': 'Je fais les courses tous les vendredis.'},
        {'word': 'le centre-ville', 'ipa': '/lə sɑ̃tʁ vil/',  'def': 'the town/city centre',     'ex': 'Il habite en centre-ville, près de tout.'},
        {'word': 'le parking',      'ipa': '/lə paʁ.kiŋ/',    'def': 'the car park',             'ex': 'Il y a un parking gratuit derrière le supermarché.'},
    ],
    'items': [
        ('ville-01', 'la boulangerie','the bakery',     'commerce', 'J\'achète mon pain à la boulangerie du coin.','J\'achète mon pain à la ___ du coin.','boulangerie'),
        ('ville-02', 'le supermarché','the supermarket','commerce', 'Je fais mes courses au supermarché.',          'Je fais mes courses au ___.',          'supermarché'),
        ('ville-03', 'la mairie',    'the town hall',  'lieu',     'Je dois aller à la mairie pour une carte.',     'Je dois aller à la ___ pour une carte.','mairie'),
        ('ville-04', 'le marché',    'the market',     'commerce', 'Le marché a lieu tous les dimanches matin.',    'Le ___ a lieu tous les dimanches matin.','marché'),
        ('ville-05', 'la poste',     'the post office','service',  'Je dois envoyer un colis à la poste.',          'Je dois envoyer un colis à la ___.',   'poste'),
        ('ville-06', 'faire les courses','to shop',    'action',   'Je fais les courses tous les vendredis.',        'Je ___ les courses tous les vendredis.','fais'),
        ('ville-07', 'le quartier',  'the neighbourhood','lieu',   'J\'habite dans un quartier tranquille.',         'J\'habite dans un ___ tranquille.',    'quartier'),
        ('ville-08', 'le centre-ville','the city centre','lieu',   'Il habite en centre-ville, près de tout.',       'Il habite en ___, près de tout.',      'centre-ville'),
    ],
},

}
