CHAPTERS = {
    "l-education": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V01",
        "short": "l-education",
        "title": "L'Éducation",
        "subtitle": "School, university, subjects, exams, and teachers",
        "words": [
            ("une matière", "/yn ma.tjɛʁ/", "a subject (school)", "Ma matière préférée est les mathématiques."),
            ("un cours magistral", "/œ̃ kuʁ ma.ʒis.tʁal/", "a lecture", "Le cours magistral durait deux heures."),
            ("un diplôme", "/œ̃ di.plom/", "a degree / diploma", "Elle a obtenu son diplôme en juin dernier."),
            ("s'inscrire", "/sɛ̃s.kʁiʁ/", "to enrol / register", "Je dois m'inscrire avant la fin du mois."),
            ("une bourse", "/yn buʁs/", "a scholarship / grant", "Il a reçu une bourse pour financer ses études."),
            ("un stage", "/œ̃ staʒ/", "an internship / work placement", "Elle fait un stage dans une entreprise à Lyon."),
            ("réviser", "/ʁe.vi.ze/", "to revise / to study for an exam", "Il faut réviser régulièrement pour réussir."),
            ("échouer à un examen", "/e.ʃwe a œ̃ ɛɡ.za.mɛ̃/", "to fail an exam", "Il a échoué à son examen de chimie."),
            ("un mémoire", "/œ̃ me.mwaʁ/", "a dissertation / thesis", "Elle rédige son mémoire sur le changement climatique."),
            ("une note", "/yn nɔt/", "a mark / grade", "J'ai eu une très bonne note en histoire."),
            ("un amphithéâtre", "/œ̃ ɑ̃.fi.te.atʁ/", "a lecture hall", "L'amphithéâtre était plein d'étudiants."),
            ("approfondir", "/a.pʁɔ.fɔ̃.diʁ/", "to deepen / develop (knowledge)", "Ce cours permet d'approfondir ses connaissances."),
            ("une filière", "/yn fi.ljɛʁ/", "a course of study / track", "Il a choisi la filière scientifique."),
            ("le baccalauréat", "/lə ba.ka.lɔ.ʁe.a/", "the baccalaureate (French school-leaving exam)", "Elle a passé le baccalauréat avec mention."),
            ("un atelier", "/œ̃ na.tə.lje/", "a workshop / seminar", "Nous avons participé à un atelier de créative écriture."),
            ("une conférence", "/yn kɔ̃.fe.ʁɑ̃s/", "a lecture / conference (public talk)", "Le professeur a donné une conférence sur la littérature."),
        ],
        "game_desc": "Master French vocabulary for school and university life",
        "items": [
            ("edu1", "une matière", "a school subject", "subject", "Sa ___ préférée est la biologie.", "Sa matière préférée est la biologie.", "matière"),
            ("edu2", "un diplôme", "a degree or diploma", "qualification", "Elle a obtenu son ___ après trois ans d'études.", "Elle a obtenu son diplôme après trois ans d'études.", "diplôme"),
            ("edu3", "réviser", "to revise for an exam", "to study", "Il faut ___ tous les soirs avant l'examen.", "Il faut réviser tous les soirs avant l'examen.", "réviser"),
            ("edu4", "une bourse", "a scholarship", "grant", "Elle a reçu une ___ pour étudier à Paris.", "Elle a reçu une bourse pour étudier à Paris.", "bourse"),
            ("edu5", "un stage", "an internship", "placement", "Je fais un ___ dans une école primaire ce mois-ci.", "Je fais un stage dans une école primaire ce mois-ci.", "stage"),
            ("edu6", "s'inscrire", "to enrol", "to register", "Tu dois ___ avant le 30 septembre.", "Tu dois t'inscrire avant le 30 septembre.", "inscrire"),
            ("edu7", "un mémoire", "a dissertation", "thesis", "Elle écrit son ___ sur l'immigration en France.", "Elle écrit son mémoire sur l'immigration en France.", "mémoire"),
            ("edu8", "une filière", "a course of study", "track", "Il a choisi la ___ littéraire au lycée.", "Il a choisi la filière littéraire au lycée.", "filière"),
        ],
    },
    "les-medias": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V02",
        "short": "les-medias",
        "title": "Les Médias",
        "subtitle": "Social media, TV, internet, journalism, and news",
        "words": [
            ("un réseau social", "/œ̃ ʁe.zo sɔ.sjal/", "a social network", "Elle passe trop de temps sur les réseaux sociaux."),
            ("un journal télévisé", "/œ̃ ʒuʁ.nal te.le.vi.ze/", "a TV news broadcast", "Nous regardons le journal télévisé chaque soir."),
            ("une émission", "/yn e.mi.sjɔ̃/", "a (TV/radio) programme / show", "Cette émission traite des problèmes sociaux."),
            ("un abonnement", "/œ̃ na.bɔn.mɑ̃/", "a subscription", "J'ai un abonnement mensuel à cette plateforme."),
            ("diffuser", "/di.fy.ze/", "to broadcast / stream", "La chaîne diffuse les matchs en direct."),
            ("une source fiable", "/yn suʁs fjabl/", "a reliable source", "Il est important de vérifier les sources fiables."),
            ("les fake news", "/le fɛk njuz/", "fake news / misinformation", "Les fake news se propagent rapidement en ligne."),
            ("un influenceur", "/œ̃ ɛ̃.fly.ɑ̃.sœʁ/", "an influencer", "Cet influenceur a des millions d'abonnés."),
            ("la presse écrite", "/la pʁɛs e.kʁit/", "the print press", "La presse écrite perd des lecteurs chaque année."),
            ("un podcast", "/œ̃ pɔd.kast/", "a podcast", "J'écoute un podcast sur l'histoire de France."),
            ("partager", "/paʁ.ta.ʒe/", "to share (online)", "Elle a partagé un article intéressant sur son profil."),
            ("la liberté de la presse", "/la li.bɛʁ.te də la pʁɛs/", "freedom of the press", "La liberté de la presse est essentielle en démocratie."),
            ("un commentaire", "/œ̃ kɔ.mɑ̃.tɛʁ/", "a comment (online)", "Il a laissé un commentaire négatif sous la vidéo."),
            ("en direct", "/ɑ̃ di.ʁɛkt/", "live / in real time", "L'événement est retransmis en direct à la télé."),
            ("un article de fond", "/œ̃ naʁ.tikl də fɔ̃/", "an in-depth article", "Elle a écrit un article de fond sur la corruption."),
        ],
        "game_desc": "Master French vocabulary for media, news, and online life",
        "items": [
            ("med1", "un réseau social", "a social network", "social media", "Elle publie des photos sur les ___ ___.", "Elle publie des photos sur les réseaux sociaux.", "réseaux sociaux"),
            ("med2", "diffuser", "to broadcast", "to stream", "La radio va ___ le discours en direct.", "La radio va diffuser le discours en direct.", "diffuser"),
            ("med3", "une source fiable", "a reliable source", "trusted source", "Cherche toujours une ___ ___ avant de partager.", "Cherche toujours une source fiable avant de partager.", "source fiable"),
            ("med4", "un abonnement", "a subscription", "membership", "J'ai pris un ___ annuel à ce journal en ligne.", "J'ai pris un abonnement annuel à ce journal en ligne.", "abonnement"),
            ("med5", "les fake news", "fake news", "misinformation", "Il ne faut pas croire toutes les ___ ___.", "Il ne faut pas croire toutes les fake news.", "fake news"),
            ("med6", "partager", "to share online", "to post", "Tu peux ___ cet article avec tes amis.", "Tu peux partager cet article avec tes amis.", "partager"),
            ("med7", "en direct", "live", "real-time", "Le match est retransmis ___ ___ sur la chaîne.", "Le match est retransmis en direct sur la chaîne.", "en direct"),
            ("med8", "un influenceur", "an influencer", "content creator", "Cet ___ a influencé l'opinion de milliers de jeunes.", "Cet influenceur a influencé l'opinion de milliers de jeunes.", "influenceur"),
        ],
    },
    "l-environnement": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V03",
        "short": "l-environnement",
        "title": "L'Environnement",
        "subtitle": "Ecology, pollution, climate, recycling, and sustainability",
        "words": [
            ("le réchauffement climatique", "/lə ʁe.ʃɔf.mɑ̃ kli.ma.tik/", "global warming", "Le réchauffement climatique menace de nombreuses espèces."),
            ("les énergies renouvelables", "/le ze.nɛʁ.ʒi ʁə.nu.vlabl/", "renewable energies", "Le pays investit dans les énergies renouvelables."),
            ("la pollution", "/la pɔ.ly.sjɔ̃/", "pollution", "La pollution de l'air est un grave problème en ville."),
            ("recycler", "/ʁə.si.kle/", "to recycle", "Il faut recycler le papier et le verre."),
            ("une empreinte carbone", "/yn ɑ̃.pʁɛ̃t kaʁ.bɔn/", "a carbon footprint", "Je cherche à réduire mon empreinte carbone."),
            ("la déforestation", "/la de.fɔ.ʁɛs.ta.sjɔ̃/", "deforestation", "La déforestation détruit l'habitat de nombreux animaux."),
            ("durable", "/dy.ʁabl/", "sustainable", "Nous devons adopter un mode de vie plus durable."),
            ("une espèce menacée", "/yn ɛs.pɛs mə.na.se/", "an endangered species", "Le panda est une espèce menacée."),
            ("les déchets", "/le de.ʃɛ/", "waste / rubbish", "Il faut trier les déchets pour les recycler."),
            ("la biodiversité", "/la bi.ɔ.di.vɛʁ.si.te/", "biodiversity", "La biodiversité est essentielle à l'équilibre de la planète."),
            ("une centrale solaire", "/yn sɑ̃.tʁal sɔ.lɛʁ/", "a solar power plant", "Une centrale solaire a été construite dans le désert."),
            ("protéger", "/pʁɔ.te.ʒe/", "to protect", "Nous devons protéger les forêts tropicales."),
            ("la sécheresse", "/la se.ʃʁɛs/", "drought", "La sécheresse a ravagé les récoltes cette année."),
            ("une inondation", "/yn i.nɔ̃.da.sjɔ̃/", "a flood", "De nombreuses villes ont subi des inondations ce printemps."),
        ],
        "game_desc": "Master French vocabulary for the environment and climate",
        "items": [
            ("env1", "le réchauffement climatique", "global warming", "climate change", "Le ___ ___ est l'un des défis majeurs du siècle.", "Le réchauffement climatique est l'un des défis majeurs du siècle.", "réchauffement climatique"),
            ("env2", "recycler", "to recycle", "to sort waste", "Il est important de ___ le plastique et le verre.", "Il est important de recycler le plastique et le verre.", "recycler"),
            ("env3", "durable", "sustainable", "eco-friendly", "Nous devons choisir un mode de vie plus ___.", "Nous devons choisir un mode de vie plus durable.", "durable"),
            ("env4", "une empreinte carbone", "a carbon footprint", "CO2 footprint", "Prendre le train réduit ton ___ ___.", "Prendre le train réduit ton empreinte carbone.", "empreinte carbone"),
            ("env5", "la déforestation", "deforestation", "forest loss", "La ___ détruit des millions d'hectares de forêt chaque an.", "La déforestation détruit des millions d'hectares de forêt chaque an.", "déforestation"),
            ("env6", "les déchets", "waste / rubbish", "trash", "Il faut trier les ___ pour protéger l'environnement.", "Il faut trier les déchets pour protéger l'environnement.", "déchets"),
            ("env7", "une espèce menacée", "an endangered species", "threatened species", "Le tigre est une ___ ___ à cause de la chasse.", "Le tigre est une espèce menacée à cause de la chasse.", "espèce menacée"),
            ("env8", "les énergies renouvelables", "renewable energies", "green energy", "Les ___ ___ remplacent peu à peu le pétrole.", "Les énergies renouvelables remplacent peu à peu le pétrole.", "énergies renouvelables"),
        ],
    },
    "le-travail": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V04",
        "short": "le-travail",
        "title": "Le Monde du Travail",
        "subtitle": "Employment, job roles, office life, salary, and career",
        "words": [
            ("un entretien d'embauche", "/œ̃ nɑ̃.tʁə.tjɛ̃ dɑ̃.boʃ/", "a job interview", "Elle s'est bien préparée pour son entretien d'embauche."),
            ("un contrat à durée indéterminée", "/œ̃ kɔ̃.tʁa a dy.ʁe ɛ̃.de.tɛʁ.mi.ne/", "a permanent contract (CDI)", "Il a finalement obtenu un contrat à durée indéterminée."),
            ("le salaire", "/lə sa.lɛʁ/", "salary / wage", "Son salaire a augmenté après deux ans dans l'entreprise."),
            ("une réunion", "/yn ʁe.y.njɔ̃/", "a meeting", "Nous avons une réunion d'équipe ce lundi matin."),
            ("postuler", "/pɔs.ty.le/", "to apply (for a job)", "J'ai postulé pour un poste dans cette société."),
            ("un congé", "/œ̃ kɔ̃.ʒe/", "leave / holiday (from work)", "Elle prend un congé maternité à partir du mois prochain."),
            ("télétravail", "/te.le.tʁa.vaj/", "remote working / working from home", "Le télétravail est devenu courant depuis la pandémie."),
            ("une promotion", "/yn pʁɔ.mɔ.sjɔ̃/", "a promotion", "Il espère obtenir une promotion avant la fin de l'année."),
            ("licencier", "/li.sɑ̃.sje/", "to lay off / dismiss (an employee)", "L'entreprise a licencié cinquante employés cette année."),
            ("un syndicat", "/œ̃ sɛ̃.di.ka/", "a trade union", "Elle est membre d'un syndicat depuis dix ans."),
            ("les avantages", "/le za.vɑ̃.taʒ/", "benefits / perks", "Ce poste offre de nombreux avantages en nature."),
            ("un CV", "/œ̃ se.ve/", "a CV / résumé", "Il a mis à jour son CV avant de postuler."),
            ("la grève", "/la ɡʁɛv/", "a strike", "Les transports sont perturbés à cause d'une grève."),
            ("un chef de projet", "/œ̃ ʃɛf də pʁɔ.ʒɛ/", "a project manager", "Elle travaille comme chef de projet dans une startup."),
            ("la retraite", "/la ʁə.tʁɛt/", "retirement", "Mon père partira à la retraite l'année prochaine."),
        ],
        "game_desc": "Master French vocabulary for the world of work and careers",
        "items": [
            ("trav1", "un entretien d'embauche", "a job interview", "interview", "Elle a réussi son ___ ___ et a obtenu le poste.", "Elle a réussi son entretien d'embauche et a obtenu le poste.", "entretien d'embauche"),
            ("trav2", "postuler", "to apply for a job", "to submit an application", "J'ai décidé de ___ pour ce poste de comptable.", "J'ai décidé de postuler pour ce poste de comptable.", "postuler"),
            ("trav3", "le salaire", "salary", "wage", "Son ___ a augmenté de dix pour cent cette année.", "Son salaire a augmenté de dix pour cent cette année.", "salaire"),
            ("trav4", "le télétravail", "remote working", "working from home", "Le ___ lui permet d'éviter les transports en commun.", "Le télétravail lui permet d'éviter les transports en commun.", "télétravail"),
            ("trav5", "une promotion", "a promotion", "advancement", "Elle a reçu une ___ après son excellent travail.", "Elle a reçu une promotion après son excellent travail.", "promotion"),
            ("trav6", "licencier", "to lay off", "to dismiss", "L'usine a dû ___ de nombreux ouvriers.", "L'usine a dû licencier de nombreux ouvriers.", "licencier"),
            ("trav7", "un congé", "leave from work", "holiday", "Il prend un ___ de deux semaines en août.", "Il prend un congé de deux semaines en août.", "congé"),
            ("trav8", "un syndicat", "a trade union", "workers union", "Le ___ a négocié de meilleures conditions de travail.", "Le syndicat a négocié de meilleures conditions de travail.", "syndicat"),
        ],
    },
    "la-politique": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V05",
        "short": "la-politique",
        "title": "La Politique et la Société",
        "subtitle": "Elections, government, rights, laws, and democracy",
        "words": [
            ("une élection", "/yn e.lɛk.sjɔ̃/", "an election", "Les élections présidentielles ont lieu tous les cinq ans."),
            ("voter", "/vɔ.te/", "to vote", "Tout citoyen a le droit de voter à dix-huit ans."),
            ("un parti politique", "/œ̃ paʁ.ti pɔ.li.tik/", "a political party", "Elle a rejoint un parti politique pour défendre ses idées."),
            ("la démocratie", "/la de.mɔ.kʁa.si/", "democracy", "La démocratie repose sur le suffrage universel."),
            ("une loi", "/yn lwa/", "a law", "Le parlement a adopté une nouvelle loi sur le travail."),
            ("les droits de l'homme", "/le dʁwa də lɔm/", "human rights", "Nous devons défendre les droits de l'homme partout."),
            ("un débat", "/œ̃ de.ba/", "a debate", "Les candidats ont participé à un débat télévisé."),
            ("un référendum", "/œ̃ ʁe.fe.ʁɑ̃.dɔm/", "a referendum", "Le gouvernement a organisé un référendum sur la Constitution."),
            ("la citoyenneté", "/la si.twa.jɛn.te/", "citizenship", "Elle a obtenu la citoyenneté française après cinq ans."),
            ("l'égalité", "/le.ɡa.li.te/", "equality", "L'égalité hommes-femmes est un principe fondamental."),
            ("une manifestation", "/yn ma.ni.fɛs.ta.sjɔ̃/", "a demonstration / protest", "Des milliers de personnes ont participé à la manifestation."),
            ("le gouvernement", "/lə ɡu.vɛʁ.nə.mɑ̃/", "the government", "Le gouvernement a annoncé de nouvelles mesures économiques."),
            ("la corruption", "/la kɔ.ʁyp.sjɔ̃/", "corruption", "Un scandale de corruption a éclaté au sein du ministère."),
            ("l'immigration", "/li.mi.ɡʁa.sjɔ̃/", "immigration", "L'immigration est un sujet de débat politique important."),
        ],
        "game_desc": "Master French vocabulary for politics and society",
        "items": [
            ("pol1", "une élection", "an election", "vote", "La prochaine ___ présidentielle aura lieu en mai.", "La prochaine élection présidentielle aura lieu en mai.", "élection"),
            ("pol2", "la démocratie", "democracy", "democratic system", "La ___ garantit le droit de vote à tous les citoyens.", "La démocratie garantit le droit de vote à tous les citoyens.", "démocratie"),
            ("pol3", "une loi", "a law", "legislation", "Le parlement a voté une nouvelle ___ sur l'environnement.", "Le parlement a voté une nouvelle loi sur l'environnement.", "loi"),
            ("pol4", "les droits de l'homme", "human rights", "civil rights", "Il faut protéger les ___ ___ ___ dans le monde entier.", "Il faut protéger les droits de l'homme dans le monde entier.", "droits de l'homme"),
            ("pol5", "une manifestation", "a protest", "demonstration", "Des étudiants ont organisé une ___ contre la réforme.", "Des étudiants ont organisé une manifestation contre la réforme.", "manifestation"),
            ("pol6", "voter", "to vote", "to cast a ballot", "Chaque citoyen doit ___ pour choisir ses représentants.", "Chaque citoyen doit voter pour choisir ses représentants.", "voter"),
            ("pol7", "un référendum", "a referendum", "public vote", "Le pays a organisé un ___ sur l'indépendance.", "Le pays a organisé un référendum sur l'indépendance.", "référendum"),
            ("pol8", "la corruption", "corruption", "bribery", "Le juge enquête sur un scandale de ___ au gouvernement.", "Le juge enquête sur un scandale de corruption au gouvernement.", "corruption"),
        ],
    },
    "les-relations": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V06",
        "short": "les-relations",
        "title": "Les Relations Humaines",
        "subtitle": "Friendship, love, conflict, communication, and family dynamics",
        "words": [
            ("la confiance", "/la kɔ̃.fjɑ̃s/", "trust / confidence", "La confiance est la base d'une bonne amitié."),
            ("se disputer", "/sə dis.py.te/", "to argue / quarrel", "Ils se disputent souvent à propos d'argent."),
            ("se réconcilier", "/sə ʁe.kɔ̃.si.lje/", "to make up / reconcile", "Ils se sont réconciliés après une longue dispute."),
            ("soutenir", "/su.tə.niʁ/", "to support / back up", "Elle soutient ses amis dans les moments difficiles."),
            ("un malentendu", "/œ̃ ma.lɑ̃.tɑ̃.dy/", "a misunderstanding", "Ce conflit est dû à un simple malentendu."),
            ("faire confiance à", "/fɛʁ kɔ̃.fjɑ̃s a/", "to trust someone", "Je fais entièrement confiance à mon meilleur ami."),
            ("la jalousie", "/la ʒa.lu.zi/", "jealousy", "La jalousie peut détruire une relation amoureuse."),
            ("s'entendre avec", "/sɑ̃.tɑ̃dʁ a.vɛk/", "to get along with", "Je m'entends très bien avec mes collègues."),
            ("rompre avec", "/ʁɔ̃pʁ a.vɛk/", "to break up with", "Elle a décidé de rompre avec son petit ami."),
            ("un soutien moral", "/œ̃ su.tjɛ̃ mɔ.ʁal/", "moral support", "Ses amis lui ont apporté un soutien moral pendant sa maladie."),
            ("la loyauté", "/la lwa.jo.te/", "loyalty", "La loyauté est une qualité indispensable en amitié."),
            ("communiquer", "/kɔ.my.ni.ke/", "to communicate", "Il est essentiel de bien communiquer dans un couple."),
            ("une rupture", "/yn ʁyp.tyʁ/", "a break-up", "La rupture a été difficile pour les deux partenaires."),
            ("le respect mutuel", "/lə ʁɛs.pɛ myt.yɛl/", "mutual respect", "Le respect mutuel est fondamental dans toute relation."),
        ],
        "game_desc": "Master French vocabulary for relationships and communication",
        "items": [
            ("rel1", "la confiance", "trust", "confidence", "Sans ___, une relation amoureuse ne peut pas durer.", "Sans confiance, une relation amoureuse ne peut pas durer.", "confiance"),
            ("rel2", "se disputer", "to argue", "to quarrel", "Ils commencent à ___ dès qu'ils parlent d'argent.", "Ils commencent à se disputer dès qu'ils parlent d'argent.", "se disputer"),
            ("rel3", "se réconcilier", "to make up", "to reconcile", "Après une semaine de silence, ils ont fini par ___.", "Après une semaine de silence, ils ont fini par se réconcilier.", "se réconcilier"),
            ("rel4", "un malentendu", "a misunderstanding", "miscommunication", "Ce conflit n'est qu'un simple ___.", "Ce conflit n'est qu'un simple malentendu.", "malentendu"),
            ("rel5", "la jalousie", "jealousy", "envy", "La ___ peut empoisonner une amitié.", "La jalousie peut empoisonner une amitié.", "jalousie"),
            ("rel6", "s'entendre avec", "to get along with", "to get on with", "Je ___ très bien ___ ma belle-mère.", "Je m'entends très bien avec ma belle-mère.", "m'entends"),
            ("rel7", "la loyauté", "loyalty", "faithfulness", "Sa ___ envers ses amis est admirable.", "Sa loyauté envers ses amis est admirable.", "loyauté"),
            ("rel8", "communiquer", "to communicate", "to talk openly", "Il est essentiel de bien ___ pour éviter les conflits.", "Il est essentiel de bien communiquer pour éviter les conflits.", "communiquer"),
        ],
    },
    "les-voyages": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V07",
        "short": "les-voyages",
        "title": "Les Voyages et le Tourisme",
        "subtitle": "Airports, hotels, cultural visits, packing, and booking",
        "words": [
            ("réserver", "/ʁe.zɛʁ.ve/", "to book / reserve", "J'ai réservé une chambre d'hôtel pour trois nuits."),
            ("un vol", "/œ̃ vɔl/", "a flight", "Mon vol part à six heures du matin."),
            ("la douane", "/la dwan/", "customs", "Nous avons dû passer par la douane à l'aéroport."),
            ("un passeport", "/œ̃ pas.pɔʁ/", "a passport", "N'oublie pas ton passeport avant de partir."),
            ("faire ses bagages", "/fɛʁ se ba.ɡaʒ/", "to pack one's bags", "Je fais mes bagages la veille du départ."),
            ("un office de tourisme", "/œ̃ nɔ.fis də tuʁ.ism/", "a tourist information office", "Nous sommes allés à l'office de tourisme pour des conseils."),
            ("un hébergement", "/œ̃ ne.bɛʁ.ʒə.mɑ̃/", "accommodation", "Il cherche un hébergement pas trop cher en centre-ville."),
            ("annuler", "/a.ny.le/", "to cancel", "Elle a dû annuler sa réservation à cause d'une urgence."),
            ("une escale", "/yn ɛs.kal/", "a stopover / layover", "Il y a une escale de deux heures à Amsterdam."),
            ("le décalage horaire", "/lə de.ka.laʒ ɔ.ʁɛʁ/", "jet lag / time difference", "J'ai souffert du décalage horaire pendant trois jours."),
            ("un circuit touristique", "/œ̃ siʁ.kwi tuʁ.is.tik/", "a tourist circuit / guided tour", "Nous avons suivi un circuit touristique en Provence."),
            ("la carte d'embarquement", "/la kaʁt dɑ̃.baʁ.kə.mɑ̃/", "a boarding pass", "N'oublie pas ta carte d'embarquement au moment d'embarquer."),
            ("dépayser", "/de.pe.i.ze/", "to give a change of scenery", "Ce voyage nous a complètement dépaysés."),
            ("un guide touristique", "/œ̃ ɡid tuʁ.is.tik/", "a travel guide / tour guide", "Elle a acheté un guide touristique sur le Maroc."),
            ("les transports en commun", "/le tʁɑ̃s.pɔʁ ɑ̃ kɔ.mɛ̃/", "public transport", "On peut visiter la ville grâce aux transports en commun."),
        ],
        "game_desc": "Master French vocabulary for travel and tourism",
        "items": [
            ("voy1", "réserver", "to book", "to reserve", "Je vais ___ une chambre dans cet hôtel pour ce week-end.", "Je vais réserver une chambre dans cet hôtel pour ce week-end.", "réserver"),
            ("voy2", "la douane", "customs", "border control", "Nous avons dû déclarer nos achats à la ___.", "Nous avons dû déclarer nos achats à la douane.", "douane"),
            ("voy3", "faire ses bagages", "to pack", "to pack one's luggage", "Je dois ___ ___ ___ avant minuit ce soir.", "Je dois faire mes bagages avant minuit ce soir.", "faire mes bagages"),
            ("voy4", "une escale", "a stopover", "layover", "Il y a une ___ d'une heure à Madrid.", "Il y a une escale d'une heure à Madrid.", "escale"),
            ("voy5", "le décalage horaire", "jet lag", "time difference", "Le ___ ___ m'a empêché de dormir pendant deux nuits.", "Le décalage horaire m'a empêché de dormir pendant deux nuits.", "décalage horaire"),
            ("voy6", "un hébergement", "accommodation", "lodging", "Elle recherche un ___ économique près du centre.", "Elle recherche un hébergement économique près du centre.", "hébergement"),
            ("voy7", "annuler", "to cancel", "to call off", "Il a fallu ___ le voyage à cause d'une grève.", "Il a fallu annuler le voyage à cause d'une grève.", "annuler"),
            ("voy8", "la carte d'embarquement", "a boarding pass", "boarding card", "Montre ta ___ ___ à l'agent avant de monter dans l'avion.", "Montre ta carte d'embarquement à l'agent avant de monter dans l'avion.", "carte d'embarquement"),
        ],
    },
    "la-sante-mode-de-vie": {
        "level": "b1",
        "section": "vocabulary",
        "num": "V08",
        "short": "la-sante-mode-de-vie",
        "title": "La Santé et le Mode de Vie",
        "subtitle": "Diet, exercise, stress, wellbeing, and lifestyle habits",
        "words": [
            ("l'alimentation", "/la.li.mɑ̃.ta.sjɔ̃/", "diet / eating habits / food intake", "Une bonne alimentation contribue à une bonne santé."),
            ("faire de l'exercice", "/fɛʁ də lɛɡ.zɛʁ.sis/", "to exercise", "Il est conseillé de faire de l'exercice trois fois par semaine."),
            ("le bien-être", "/lə bjɛ̃.nɛtʁ/", "wellbeing", "Le yoga contribue à mon bien-être mental et physique."),
            ("le stress", "/lə stʁɛs/", "stress", "Le stress au travail peut nuire à la santé."),
            ("équilibré", "/e.ki.li.bʁe/", "balanced", "Il est important d'avoir un régime alimentaire équilibré."),
            ("une habitude", "/yn a.bi.tyd/", "a habit", "Il a pris l'habitude de marcher trente minutes chaque matin."),
            ("la méditation", "/la me.di.ta.sjɔ̃/", "meditation", "La méditation l'aide à gérer son stress quotidien."),
            ("éviter", "/e.vi.te/", "to avoid", "Elle essaie d'éviter les aliments trop gras ou sucrés."),
            ("un bilan de santé", "/œ̃ bi.lɑ̃ də sɑ̃.te/", "a health check-up", "Son médecin lui a recommandé un bilan de santé annuel."),
            ("le sommeil", "/lə sɔ.mɛj/", "sleep", "Un bon sommeil est indispensable pour récupérer."),
            ("les matières grasses", "/le ma.tjɛʁ ɡʁas/", "fats / fatty substances", "Il faut limiter les matières grasses dans son alimentation."),
            ("une ordonnance", "/yn ɔʁ.dɔ.nɑ̃s/", "a prescription", "Le médecin lui a donné une ordonnance pour des antibiotiques."),
            ("se remettre de", "/sə ʁə.mɛtʁ də/", "to recover from", "Il met du temps à se remettre de son opération."),
            ("prévenir", "/pʁe.və.niʁ/", "to prevent", "Il vaut mieux prévenir que guérir.", ),
            ("la santé mentale", "/la sɑ̃.te mɑ̃.tal/", "mental health", "La santé mentale est aussi importante que la santé physique."),
        ],
        "game_desc": "Master French vocabulary for health and lifestyle",
        "items": [
            ("san1", "l'alimentation", "diet / eating habits", "nutrition", "Une ___ variée est essentielle pour rester en bonne santé.", "Une alimentation variée est essentielle pour rester en bonne santé.", "alimentation"),
            ("san2", "faire de l'exercice", "to exercise", "to work out", "Il faut ___ ___ ___ régulièrement pour garder la forme.", "Il faut faire de l'exercice régulièrement pour garder la forme.", "faire de l'exercice"),
            ("san3", "le bien-être", "wellbeing", "wellness", "Le sport contribue à son ___ ___ au quotidien.", "Le sport contribue à son bien-être au quotidien.", "bien-être"),
            ("san4", "le stress", "stress", "anxiety", "Trop de ___ peut provoquer des problèmes de santé graves.", "Trop de stress peut provoquer des problèmes de santé graves.", "stress"),
            ("san5", "une habitude", "a habit", "routine", "Il a pris une bonne ___ : il court chaque matin.", "Il a pris une bonne habitude : il court chaque matin.", "habitude"),
            ("san6", "le sommeil", "sleep", "rest", "Un manque de ___ peut affecter la concentration.", "Un manque de sommeil peut affecter la concentration.", "sommeil"),
            ("san7", "se remettre de", "to recover from", "to get over", "Elle met plusieurs semaines à ___ ___ sa grippe.", "Elle met plusieurs semaines à se remettre de sa grippe.", "se remettre de"),
            ("san8", "prévenir", "to prevent", "to avoid illness", "Il vaut mieux ___ les maladies que les traiter.", "Il vaut mieux prévenir les maladies que les traiter.", "prévenir"),
        ],
    },
}
