"""Français A2 — Vocabulaire batch 2: V05–V08."""

CHAPTERS = {

# ── V05 Les Sentiments ─────────────────────────────────────────────────────
'les-sentiments': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V05',
    'short':   'Les Sentiments',
    'title':   'Les Sentiments — Exprimer ses Émotions',
    'subtitle': 'Le vocabulaire des émotions et des états d\'esprit en français',
    'game_desc': 'Apprenez à exprimer vos émotions en français !',
    'words': [
        {'word': 'heureux/heureuse', 'ipa': '/øʁø/ /øʁøz/',  'def': 'happy',                    'ex': 'Je suis heureux de te voir !'},
        {'word': 'triste',          'ipa': '/tʁist/',         'def': 'sad',                      'ex': 'Elle est triste depuis la nouvelle.'},
        {'word': 'en colère',       'ipa': '/ɑ̃ kɔ.lɛʁ/',    'def': 'angry',                    'ex': 'Il est en colère contre son patron.'},
        {'word': 'inquiet/inquiète','ipa': '/ɛ̃.kjɛ/ /ɛ̃.kjɛt/','def': 'worried',               'ex': 'Je suis inquiète pour mon examen.'},
        {'word': 'surpris(e)',      'ipa': '/syʁ.pʁi/ /syʁ.pʁiz/','def': 'surprised',          'ex': 'Elle était vraiment surprise par le cadeau.'},
        {'word': 'content(e)',      'ipa': '/kɔ̃.tɑ̃/ /kɔ̃.tɑ̃t/','def': 'pleased / happy',      'ex': 'Je suis contente de mes résultats.'},
        {'word': 'fatigué(e)',      'ipa': '/fa.ti.ɡe/',      'def': 'tired',                    'ex': 'Je suis très fatigué après cette semaine.'},
        {'word': 'stressé(e)',      'ipa': '/stʁɛ.se/',       'def': 'stressed',                 'ex': 'Elle est stressée avant sa présentation.'},
        {'word': 'déçu(e)',         'ipa': '/de.sy/',          'def': 'disappointed',             'ex': 'Il est déçu par le résultat du match.'},
        {'word': 'fier/fière',      'ipa': '/fjɛʁ/',          'def': 'proud',                    'ex': 'Ses parents sont fiers de lui.'},
        {'word': 'avoir peur',      'ipa': '/a.vwaʁ pœʁ/',    'def': 'to be afraid / to fear',   'ex': 'Elle a peur des araignées.'},
        {'word': 'se sentir',       'ipa': '/sə sɑ̃.tiʁ/',    'def': 'to feel',                  'ex': 'Comment tu te sens aujourd\'hui ?'},
        {'word': 'l\'amour',        'ipa': '/la.muʁ/',        'def': 'love',                     'ex': 'L\'amour rend la vie belle.'},
        {'word': 'la joie',         'ipa': '/la ʒwa/',         'def': 'joy',                      'ex': 'Les enfants sautaient de joie.'},
        {'word': 'la tristesse',    'ipa': '/la tʁis.tɛs/',   'def': 'sadness',                  'ex': 'Elle n\'arrivait pas à cacher sa tristesse.'},
    ],
    'items': [
        ('sent-01', 'heureux/heureuse','happy',       'émotion', 'Je suis heureux de te voir !',            'Je suis ___ de te voir ! (m.)',        'heureux'),
        ('sent-02', 'triste',        'sad',            'émotion', 'Elle est triste depuis la nouvelle.',      'Elle est ___ depuis la nouvelle.',     'triste'),
        ('sent-03', 'en colère',     'angry',          'émotion', 'Il est en colère contre son patron.',      'Il est ___ contre son patron.',        'en colère'),
        ('sent-04', 'inquiet(e)',    'worried',        'émotion', 'Je suis inquiète pour mon examen.',        'Je suis ___ pour mon examen. (f.)',    'inquiète'),
        ('sent-05', 'déçu(e)',       'disappointed',   'émotion', 'Il est déçu par le résultat du match.',    'Il est ___ par le résultat.',          'déçu'),
        ('sent-06', 'avoir peur',    'to be afraid',   'émotion', 'Elle a peur des araignées.',               'Elle a ___ des araignées.',            'peur'),
        ('sent-07', 'fier/fière',    'proud',          'émotion', 'Ses parents sont fiers de lui.',            'Ses parents sont ___ de lui.',         'fiers'),
        ('sent-08', 'se sentir',     'to feel',        'verbe',   'Comment tu te sens aujourd\'hui ?',         'Comment tu te ___ aujourd\'hui ?',     'sens'),
    ],
},

# ── V06 La Nourriture et les Restaurants ──────────────────────────────────
'au-restaurant': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V06',
    'short':   'Au Restaurant',
    'title':   'Au Restaurant — Commander et Apprécier',
    'subtitle': 'Le vocabulaire du restaurant : commander, décrire et régler l\'addition',
    'game_desc': 'Apprenez à commander au restaurant en français !',
    'words': [
        {'word': 'la carte / le menu','ipa': '/la kaʁt/ /lə me.ny/','def': 'the à-la-carte menu / set menu','ex': 'Je prends le menu à 15 euros.'},
        {'word': 'l\'entrée',        'ipa': '/lɑ̃.tʁe/',       'def': 'the starter',              'ex': 'Comme entrée, je prends la soupe.'},
        {'word': 'le plat principal','ipa': '/lə pla pʁɛ̃.si.pal/','def': 'the main course',     'ex': 'Comme plat principal, je voudrais le poulet.'},
        {'word': 'le dessert',       'ipa': '/lə de.sɛʁ/',     'def': 'the dessert',              'ex': 'Je voudrais une tarte aux pommes comme dessert.'},
        {'word': 'commander',        'ipa': '/kɔ.mɑ̃.de/',     'def': 'to order',                 'ex': 'Vous êtes prêts à commander ?'},
        {'word': 'l\'addition',      'ipa': '/la.di.sjɔ̃/',    'def': 'the bill',                 'ex': 'L\'addition, s\'il vous plaît !'},
        {'word': 'le pourboire',     'ipa': '/lə puʁ.bwaʁ/',   'def': 'the tip',                  'ex': 'On laisse un pourboire de 10 %.'},
        {'word': 'délicieux/délicieuse','ipa': '/de.li.sjø/ /de.li.sjøz/','def': 'delicious',   'ex': 'Ce plat est vraiment délicieux !'},
        {'word': 'avoir faim',       'ipa': '/a.vwaʁ fɛ̃/',    'def': 'to be hungry',             'ex': 'J\'ai très faim ce soir !'},
        {'word': 'avoir soif',       'ipa': '/a.vwaʁ swaf/',   'def': 'to be thirsty',            'ex': 'Tu as soif ? Je commande de l\'eau.'},
        {'word': 'le serveur/la serveuse','ipa': '/sɛʁ.vœʁ/ /sɛʁ.vøz/','def': 'the waiter/waitress','ex': 'Le serveur nous a apporté la carte.'},
        {'word': 'réserver une table','ipa': '/ʁe.zɛʁ.ve/','def': 'to book a table',            'ex': 'J\'ai réservé une table pour deux personnes.'},
        {'word': 'végétarien(ne)',   'ipa': '/ve.ʒe.ta.ʁjɛ̃/', 'def': 'vegetarian',              'ex': 'Je suis végétarien, pas de viande pour moi.'},
        {'word': 'sans gluten',      'ipa': '/sɑ̃ ɡly.tɛn/',   'def': 'gluten-free',              'ex': 'Avez-vous des plats sans gluten ?'},
        {'word': 'payer',            'ipa': '/pe.je/',          'def': 'to pay',                   'ex': 'On paie ensemble ou chacun paie sa part ?'},
    ],
    'items': [
        ('rest-01', 'l\'entrée',     'the starter',    'repas',   'Comme entrée, je prends la soupe.',         'Comme ___, je prends la soupe.',       'entrée'),
        ('rest-02', 'le plat principal','the main course','repas', 'Je voudrais le poulet comme plat principal.','Je voudrais le poulet comme ___ principal.','plat'),
        ('rest-03', 'commander',     'to order',       'action',  'Vous êtes prêts à commander ?',              'Vous êtes prêts à ___ ?',              'commander'),
        ('rest-04', 'l\'addition',   'the bill',       'paiement','L\'addition, s\'il vous plaît !',            'L\'___, s\'il vous plaît !',           'addition'),
        ('rest-05', 'délicieux',     'delicious',      'qualité', 'Ce plat est vraiment délicieux !',           'Ce plat est vraiment ___ !',           'délicieux'),
        ('rest-06', 'avoir faim',    'to be hungry',   'état',    'J\'ai très faim ce soir !',                  'J\'ai très ___ ce soir !',             'faim'),
        ('rest-07', 'réserver',      'to book',        'action',  'J\'ai réservé une table pour deux.',         'J\'ai ___ une table pour deux.',       'réservé'),
        ('rest-08', 'payer',         'to pay',         'action',  'On paie ensemble ou chacun paie sa part ?',  'On ___ ensemble ?',                    'paie'),
    ],
},

# ── V07 Les Voyages ────────────────────────────────────────────────────────
'les-voyages': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V07',
    'short':   'Les Voyages',
    'title':   'Les Voyages — Partir et Découvrir',
    'subtitle': 'Le vocabulaire pour organiser et décrire un voyage en français',
    'game_desc': 'Apprenez le vocabulaire des voyages en français !',
    'words': [
        {'word': 'réserver',        'ipa': '/ʁe.zɛʁ.ve/',    'def': 'to book / to reserve',     'ex': 'J\'ai réservé un hôtel pour trois nuits.'},
        {'word': 'l\'hôtel',        'ipa': '/lo.tɛl/',        'def': 'the hotel',                'ex': 'Notre hôtel est à deux pas de la plage.'},
        {'word': 'la chambre',      'ipa': '/la ʃɑ̃bʁ/',     'def': 'the room (hotel)',         'ex': 'Je voudrais une chambre double, s\'il vous plaît.'},
        {'word': 'le vol',          'ipa': '/lə vɔl/',         'def': 'the flight',               'ex': 'Notre vol part à 6 h du matin.'},
        {'word': 'le passeport',    'ipa': '/lə pas.pɔʁ/',    'def': 'the passport',             'ex': 'N\'oublie pas ton passeport !'},
        {'word': 'la valise',       'ipa': '/la va.liz/',     'def': 'the suitcase',             'ex': 'J\'ai fait ma valise la veille du départ.'},
        {'word': 'l\'office de tourisme','ipa': '/lɔ.fis də tu.ʁism/','def': 'the tourist office','ex': 'L\'office de tourisme donne des cartes gratuites.'},
        {'word': 'visiter',         'ipa': '/vi.zi.te/',      'def': 'to visit (a place)',       'ex': 'On a visité le Louvre ce matin.'},
        {'word': 'la plage',        'ipa': '/la plaʒ/',        'def': 'the beach',                'ex': 'On passe la journée à la plage.'},
        {'word': 'la montagne',     'ipa': '/la mɔ̃.taɲ/',    'def': 'the mountain',             'ex': 'Ils adorent skier en montagne.'},
        {'word': 'le départ',       'ipa': '/lə de.paʁ/',     'def': 'the departure',            'ex': 'Notre départ est prévu pour 8 h.'},
        {'word': 'l\'arrivée',      'ipa': '/la.ʁi.ve/',      'def': 'the arrival',              'ex': 'Quelle est l\'heure d\'arrivée ?'},
        {'word': 'faire du tourisme','ipa': '/fɛʁ dy tu.ʁism/','def': 'to go sightseeing',      'ex': 'On a fait du tourisme pendant quatre jours.'},
        {'word': 'un souvenir',     'ipa': '/œ̃ su.və.niʁ/',  'def': 'a souvenir',               'ex': 'J\'ai acheté des souvenirs pour ma famille.'},
        {'word': 'la carte postale','ipa': '/la kaʁt pɔs.tal/','def': 'the postcard',           'ex': 'J\'envoie une carte postale à mes amis.'},
    ],
    'items': [
        ('voy-01', 'réserver',      'to book',         'action',  'J\'ai réservé un hôtel pour trois nuits.',   'J\'ai ___ un hôtel pour trois nuits.',  'réservé'),
        ('voy-02', 'le vol',        'the flight',      'transport','Notre vol part à 6 h du matin.',            'Notre ___ part à 6 h du matin.',        'vol'),
        ('voy-03', 'la valise',     'the suitcase',    'objet',   'J\'ai fait ma valise la veille du départ.',  'J\'ai fait ma ___ la veille du départ.','valise'),
        ('voy-04', 'visiter',       'to visit',        'action',  'On a visité le Louvre ce matin.',            'On a ___ le Louvre ce matin.',          'visité'),
        ('voy-05', 'la plage',      'the beach',       'lieu',    'On passe la journée à la plage.',            'On passe la journée à la ___.',         'plage'),
        ('voy-06', 'le départ',     'the departure',   'voyage',  'Notre départ est prévu pour 8 h.',            'Notre ___ est prévu pour 8 h.',         'départ'),
        ('voy-07', 'un souvenir',   'a souvenir',      'achat',   'J\'ai acheté des souvenirs pour ma famille.', 'J\'ai acheté des ___ pour ma famille.',  'souvenirs'),
        ('voy-08', 'la carte postale','the postcard',  'objet',   'J\'envoie une carte postale à mes amis.',    'J\'envoie une ___ à mes amis.',         'carte postale'),
    ],
},

# ── V08 La Maison et le Quotidien ──────────────────────────────────────────
'la-vie-quotidienne': {
    'level':   'a2',
    'section': 'vocabulaire',
    'num':     'V08',
    'short':   'La Vie Quotidienne',
    'title':   'La Vie Quotidienne — Les Tâches et les Routines',
    'subtitle': 'Le vocabulaire de la vie de tous les jours : ménage, courses et routines',
    'game_desc': 'Apprenez le vocabulaire de la vie quotidienne en français !',
    'words': [
        {'word': 'faire le ménage', 'ipa': '/fɛʁ lə me.naʒ/', 'def': 'to do the housework',     'ex': 'Je fais le ménage chaque samedi matin.'},
        {'word': 'passer l\'aspirateur','ipa': '/pa.se las.pi.ʁa.tœʁ/','def': 'to vacuum',      'ex': 'Il passe l\'aspirateur dans le salon.'},
        {'word': 'faire la vaisselle','ipa': '/fɛʁ la vɛ.sɛl/','def': 'to do the dishes',       'ex': 'C\'est ton tour de faire la vaisselle !'},
        {'word': 'faire la lessive', 'ipa': '/fɛʁ la lɛ.siv/','def': 'to do the laundry',       'ex': 'Je fais la lessive deux fois par semaine.'},
        {'word': 'ranger',          'ipa': '/ʁɑ̃.ʒe/',         'def': 'to tidy (up)',             'ex': 'Range ta chambre avant de sortir !'},
        {'word': 'se lever tôt/tard','ipa': '/sə lə.ve to/taʁ/','def': 'to get up early/late',  'ex': 'Je me lève tôt en semaine, tard le week-end.'},
        {'word': 'le petit déjeuner','ipa': '/lə pə.ti de.ʒœ.ne/','def': 'breakfast',           'ex': 'Je prends mon petit déjeuner à 7 h.'},
        {'word': 'le déjeuner',     'ipa': '/lə de.ʒœ.ne/',   'def': 'lunch',                    'ex': 'Je déjeune à la cantine avec mes collègues.'},
        {'word': 'le dîner',        'ipa': '/lə di.ne/',       'def': 'dinner / supper',          'ex': 'On dîne en famille à 19 h 30.'},
        {'word': 'se coucher',      'ipa': '/sə ku.ʃe/',       'def': 'to go to bed',             'ex': 'Je me couche généralement à 23 h.'},
        {'word': 'les courses',     'ipa': '/le kuʁs/',        'def': 'the shopping',             'ex': 'Je fais les courses le mercredi soir.'},
        {'word': 'le loyer',        'ipa': '/lə lwa.je/',      'def': 'the rent',                 'ex': 'Mon loyer est de 800 euros par mois.'},
        {'word': 'les factures',    'ipa': '/le fak.tyʁ/',     'def': 'the bills',                'ex': 'Je paie mes factures en ligne.'},
        {'word': 'sortir les poubelles','ipa': '/sɔʁ.tiʁ le pu.bɛl/','def': 'to take out the bins','ex': 'C\'est qui qui sort les poubelles ce soir ?'},
        {'word': 'emménager',       'ipa': '/ɑ.me.na.ʒe/',    'def': 'to move in',               'ex': 'On a emménagé dans notre nouvel appartement.'},
    ],
    'items': [
        ('quot-01', 'faire le ménage','to do housework','action', 'Je fais le ménage chaque samedi matin.',     'Je ___ le ménage chaque samedi matin.',  'fais'),
        ('quot-02', 'faire la vaisselle','do the dishes','action','C\'est ton tour de faire la vaisselle !',     'C\'est ton tour de ___ la vaisselle !',  'faire'),
        ('quot-03', 'ranger',        'to tidy up',     'action',  'Range ta chambre avant de sortir !',          'Range ta ___ avant de sortir !',         'chambre'),
        ('quot-04', 'le petit déjeuner','breakfast',   'repas',   'Je prends mon petit déjeuner à 7 h.',         'Je prends mon ___ à 7 h.',               'petit déjeuner'),
        ('quot-05', 'le dîner',      'dinner',         'repas',   'On dîne en famille à 19 h 30.',               'On ___ en famille à 19 h 30.',           'dîne'),
        ('quot-06', 'le loyer',      'the rent',       'logement','Mon loyer est de 800 euros par mois.',         'Mon ___ est de 800 euros par mois.',     'loyer'),
        ('quot-07', 'les factures',  'the bills',      'logement','Je paie mes factures en ligne.',               'Je paie mes ___ en ligne.',              'factures'),
        ('quot-08', 'emménager',     'to move in',     'action',  'On a emménagé dans notre nouvel appartement.','On a ___ dans notre nouvel appartement.','emménagé'),
    ],
},

}
