"""
francais/b1 — Vocabulaire B1 — batch 1 (V01–V04)
"""

CHAPTERS = {

"la-societe": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V01",
    "short": "La Société",
    "title": "La Société",
    "subtitle": "Vie sociale, égalité, droits et citoyenneté",
    "words": [
        {"word": "la société", "ipa": "/la sɔ.sje.te/", "def": "l'ensemble des personnes vivant dans une communauté organisée", "ex": "La société française valorise la liberté."},
        {"word": "le citoyen", "ipa": "/lə si.twa.jɛ̃/", "def": "personne ayant les droits et devoirs d'un pays", "ex": "Chaque citoyen a le droit de voter."},
        {"word": "l'égalité", "ipa": "/le.ɡa.li.te/", "def": "fait d'avoir les mêmes droits que les autres", "ex": "L'égalité entre les hommes et les femmes est fondamentale."},
        {"word": "la liberté", "ipa": "/la li.bɛʁ.te/", "def": "droit de faire ce que l'on veut dans le respect des lois", "ex": "La liberté de la presse est protégée."},
        {"word": "les droits", "ipa": "/le dʁwa/", "def": "ce que la loi vous permet de faire ou d'avoir", "ex": "Tout le monde a des droits fondamentaux."},
        {"word": "le devoir", "ipa": "/lə də.vwaʁ/", "def": "obligation légale ou morale", "ex": "Le devoir de chaque citoyen est de voter."},
        {"word": "la loi", "ipa": "/la lwa/", "def": "règle établie par l'État qui s'applique à tous", "ex": "Cette loi interdit de fumer dans les lieux publics."},
        {"word": "le gouvernement", "ipa": "/lə ɡu.vɛʁ.nə.mɑ̃/", "def": "ensemble des ministres qui dirigent un pays", "ex": "Le gouvernement a adopté une nouvelle politique."},
        {"word": "la démocratie", "ipa": "/la de.mɔ.kʁa.si/", "def": "système politique où les citoyens élisent leurs représentants", "ex": "La France est une démocratie républicaine."},
        {"word": "le vote", "ipa": "/lə vɔt/", "def": "action d'exprimer son choix lors d'une élection", "ex": "Le vote est un droit et un devoir civique."},
        {"word": "l'inégalité", "ipa": "/li.ne.ɡa.li.te/", "def": "différence injuste dans le traitement des personnes", "ex": "Les inégalités sociales restent un problème majeur."},
        {"word": "la solidarité", "ipa": "/la sɔ.li.da.ʁi.te/", "def": "aide mutuelle entre les membres d'une communauté", "ex": "La solidarité est une valeur fondamentale en France."},
        {"word": "l'intégration", "ipa": "/lɛ̃.te.ɡʁa.sjɔ̃/", "def": "processus par lequel une personne devient membre d'une société", "ex": "L'intégration des nouveaux arrivants prend du temps."},
        {"word": "la discrimination", "ipa": "/la dis.kʁi.mi.na.sjɔ̃/", "def": "traitement inégal basé sur la race, le sexe ou l'origine", "ex": "La discrimination au travail est illégale."},
        {"word": "le bénévolat", "ipa": "/lə be.ne.vɔ.la/", "def": "travail volontaire et non rémunéré pour une cause", "ex": "Elle fait du bénévolat dans une association caritative."},
    ],
    "game_desc": "La Société — vocabulaire civique et social",
    "items": [
        ("soc-citoyen", "le citoyen", "personne avec droits et devoirs dans un pays", "habitant avec droits civiques", "Chaque citoyen a le droit de voter.", "citoyen = habitant avec droits civiques", "habitant avec droits civiques"),
        ("soc-egalite", "l'égalité", "même traitement et mêmes droits pour tous", "même droits pour tous", "L'égalité est une valeur républicaine.", "égalité = même droits pour tous", "même droits pour tous"),
        ("soc-loi", "la loi", "règle de l'État qui s'applique à tous", "règle juridique obligatoire", "Cette loi protège les travailleurs.", "loi = règle obligatoire de l'État", "règle juridique obligatoire"),
        ("soc-democratie", "la démocratie", "système où les citoyens choisissent leurs gouvernants", "gouvernement élu par le peuple", "La démocratie repose sur le vote.", "démocratie = gouvernement élu", "gouvernement élu par le peuple"),
        ("soc-inegalite", "l'inégalité", "différence injuste dans les droits ou les conditions de vie", "traitement différent et injuste", "Les inégalités sociales sont importantes.", "inégalité = traitement injuste", "traitement différent et injuste"),
        ("soc-solidarite", "la solidarité", "aide mutuelle au sein d'une communauté", "entraide entre membres d'un groupe", "La solidarité aide les plus vulnérables.", "solidarité = entraide", "entraide entre membres d'un groupe"),
        ("soc-discrimination", "la discrimination", "traitement inégal basé sur des caractéristiques personnelles", "traitement injuste selon origine ou sexe", "La discrimination est illégale.", "discrimination = traitement inégal injuste", "traitement injuste selon origine ou sexe"),
        ("soc-benevolat", "le bénévolat", "travail volontaire non rémunéré pour une cause", "travail gratuit pour aider les autres", "Il fait du bénévolat chaque weekend.", "bénévolat = travail volontaire gratuit", "travail gratuit pour aider les autres"),
    ],
},

"l-economie": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V02",
    "short": "L'Économie",
    "title": "L'Économie",
    "subtitle": "Finance, travail, commerce et consommation",
    "words": [
        {"word": "l'économie", "ipa": "/le.kɔ.nɔ.mi/", "def": "ensemble des activités de production et d'échange d'un pays", "ex": "L'économie française est la septième du monde."},
        {"word": "le budget", "ipa": "/lə by.dʒɛ/", "def": "plan de recettes et de dépenses pour une période donnée", "ex": "Elle gère son budget avec soin."},
        {"word": "le salaire", "ipa": "/lə sa.lɛʁ/", "def": "rémunération reçue pour un travail", "ex": "Son salaire a augmenté de 5%."},
        {"word": "l'impôt", "ipa": "/lɛ̃.po/", "def": "somme versée à l'État par les citoyens", "ex": "Les impôts financent les services publics."},
        {"word": "la dépense", "ipa": "/la de.pɑ̃s/", "def": "argent utilisé pour acheter quelque chose", "ex": "Il faut réduire les dépenses du ménage."},
        {"word": "l'investissement", "ipa": "/lɛ̃.vɛs.tis.mɑ̃/", "def": "placement d'argent pour obtenir un bénéfice futur", "ex": "L'investissement dans l'éducation est essentiel."},
        {"word": "la croissance", "ipa": "/la kʁwa.sɑ̃s/", "def": "augmentation de la production économique d'un pays", "ex": "La croissance économique est de 2% cette année."},
        {"word": "le chômage", "ipa": "/lə ʃo.maʒ/", "def": "situation des personnes sans emploi qui en cherchent un", "ex": "Le taux de chômage a baissé."},
        {"word": "l'inflation", "ipa": "/lɛ̃.fla.sjɔ̃/", "def": "hausse généralisée des prix", "ex": "L'inflation rend la vie plus chère."},
        {"word": "la dette", "ipa": "/la dɛt/", "def": "somme d'argent qu'on doit rembourser", "ex": "La dette nationale a augmenté."},
        {"word": "le commerce", "ipa": "/lə kɔ.mɛʁs/", "def": "échange de marchandises ou de services contre de l'argent", "ex": "Le commerce international crée des emplois."},
        {"word": "la concurrence", "ipa": "/la kɔ̃.ky.ʁɑ̃s/", "def": "rivalité entre entreprises sur un même marché", "ex": "La concurrence maintient les prix bas."},
        {"word": "le consommateur", "ipa": "/lə kɔ̃.sɔ.ma.tœʁ/", "def": "personne qui achète des biens ou des services", "ex": "Les consommateurs exigent des produits de qualité."},
        {"word": "la mondialisation", "ipa": "/la mɔ̃.dja.li.za.sjɔ̃/", "def": "intégration croissante des économies du monde entier", "ex": "La mondialisation a transformé le commerce."},
        {"word": "le développement durable", "ipa": "/lə de.vɛ.lɔp.mɑ̃ dy.ʁabl/", "def": "développement économique respectueux de l'environnement", "ex": "Le développement durable est une priorité mondiale."},
    ],
    "game_desc": "L'Économie — vocabulaire financier et commercial",
    "items": [
        ("eco-budget", "le budget", "plan de recettes et dépenses", "plan financier personnel ou d'État", "Elle respecte son budget mensuel.", "budget = plan financier", "plan financier personnel ou d'État"),
        ("eco-chomage", "le chômage", "situation des personnes sans emploi cherchant du travail", "sans emploi + cherche travail", "Le chômage touche les jeunes.", "chômage = sans emploi", "sans emploi + cherche travail"),
        ("eco-inflation", "l'inflation", "hausse générale des prix", "prix qui montent", "L'inflation érode le pouvoir d'achat.", "inflation = hausse des prix", "prix qui montent"),
        ("eco-croissance", "la croissance", "augmentation de la production économique", "économie qui grandit", "La croissance crée des emplois.", "croissance = économie qui grandit", "économie qui grandit"),
        ("eco-investissement", "l'investissement", "placement d'argent pour un bénéfice futur", "mettre de l'argent pour gagner plus tard", "L'investissement dans la tech est risqué.", "investissement = placer pour gagner", "mettre de l'argent pour gagner plus tard"),
        ("eco-concurrence", "la concurrence", "rivalité entre entreprises pour attirer les clients", "compétition entre entreprises", "La concurrence baisse les prix.", "concurrence = compétition commerciale", "compétition entre entreprises"),
        ("eco-mondialisation", "la mondialisation", "intégration des économies mondiales", "économies du monde reliées", "La mondialisation profite à certains.", "mondialisation = économies mondiales reliées", "économies du monde reliées"),
        ("eco-dev-durable", "le développement durable", "croissance économique respectant l'environnement", "croissance + respect de l'environnement", "Le développement durable est nécessaire.", "dév. durable = croissance + environnement", "croissance + respect de l'environnement"),
    ],
},

"la-culture-et-les-arts": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V03",
    "short": "La Culture et les Arts",
    "title": "La Culture et les Arts",
    "subtitle": "Musique, littérature, cinéma et patrimoine",
    "words": [
        {"word": "le patrimoine", "ipa": "/lə pa.tʁi.mwan/", "def": "ensemble des biens culturels et historiques d'un pays", "ex": "Le patrimoine architectural de Paris est exceptionnel."},
        {"word": "l'œuvre", "ipa": "/lœvʁ/", "def": "création artistique ou littéraire", "ex": "Cette œuvre de Picasso vaut des millions."},
        {"word": "l'exposition", "ipa": "/lɛks.po.zi.sjɔ̃/", "def": "présentation publique d'objets ou d'œuvres d'art", "ex": "Nous allons voir l'exposition au Louvre."},
        {"word": "le chef-d'œuvre", "ipa": "/lə ʃɛ.dœvʁ/", "def": "œuvre d'art considérée comme la meilleure de son genre", "ex": "La Joconde est un chef-d'œuvre de la peinture."},
        {"word": "la représentation", "ipa": "/la ʁe.pʁe.zɑ̃.ta.sjɔ̃/", "def": "spectacle joué devant un public (théâtre, danse…)", "ex": "La représentation commence à 20h."},
        {"word": "le réalisateur", "ipa": "/lə ʁe.a.li.za.tœʁ/", "def": "personne qui dirige la création d'un film", "ex": "François Truffaut est un célèbre réalisateur français."},
        {"word": "le scénario", "ipa": "/lə se.na.ʁjo/", "def": "texte qui décrit les scènes et dialogues d'un film", "ex": "Le scénario de ce film est très bien écrit."},
        {"word": "l'auteur", "ipa": "/lo.tœʁ/", "def": "personne qui crée une œuvre écrite ou artistique", "ex": "Victor Hugo est un auteur du XIXe siècle."},
        {"word": "la peinture", "ipa": "/la pɛ̃.tyʁ/", "def": "art de créer des images avec des couleurs; l'image créée", "ex": "Cette peinture représente un paysage provençal."},
        {"word": "la sculpture", "ipa": "/la skyl.pyʁ/", "def": "art de créer des formes en trois dimensions", "ex": "La sculpture de Rodin est exposée à Paris."},
        {"word": "la musique classique", "ipa": "/la my.zik kla.sik/", "def": "musique composée selon des formes traditionnelles occidentales", "ex": "J'adore la musique classique de Mozart."},
        {"word": "le roman", "ipa": "/lə ʁɔ.mɑ̃/", "def": "long récit de fiction en prose", "ex": "Elle lit un roman policier."},
        {"word": "la critique", "ipa": "/la kʁi.tik/", "def": "analyse et jugement d'une œuvre par un expert", "ex": "La critique du film était très positive."},
        {"word": "le festival", "ipa": "/lə fɛs.ti.val/", "def": "événement culturel qui réunit artistes et public sur plusieurs jours", "ex": "Le festival de Cannes est célèbre dans le monde entier."},
        {"word": "l'héritage culturel", "ipa": "/le.ʁi.taʒ kyl.ty.ʁɛl/", "def": "ensemble des traditions et valeurs transmises par les générations passées", "ex": "L'héritage culturel français est riche et varié."},
    ],
    "game_desc": "La Culture et les Arts — vocabulaire artistique et culturel",
    "items": [
        ("art-patrimoine", "le patrimoine", "biens culturels et historiques d'une nation", "trésors culturels nationaux", "Le patrimoine de Lyon est classé UNESCO.", "patrimoine = trésors culturels", "trésors culturels nationaux"),
        ("art-oeuvre", "l'œuvre", "création artistique ou littéraire", "production artistique", "Cette œuvre est magnifique.", "œuvre = création artistique", "production artistique"),
        ("art-exposition", "l'exposition", "présentation publique d'œuvres d'art", "événement pour voir des œuvres", "L'exposition dure trois mois.", "exposition = montrer des œuvres au public", "événement pour voir des œuvres"),
        ("art-realisateur", "le réalisateur", "personne qui dirige un film", "directeur d'un film", "Ce réalisateur a gagné un César.", "réalisateur = dirige un film", "directeur d'un film"),
        ("art-roman", "le roman", "long récit de fiction en prose", "livre de fiction long", "J'ai lu un roman de Flaubert.", "roman = long livre de fiction", "livre de fiction long"),
        ("art-critique", "la critique", "analyse et jugement d'une œuvre", "opinion d'un expert sur une œuvre", "La critique du roman est excellente.", "critique = analyse d'une œuvre", "opinion d'un expert sur une œuvre"),
        ("art-festival", "le festival", "événement culturel de plusieurs jours", "grand événement artistique", "Le festival d'Avignon attire des milliers.", "festival = grand événement culturel", "grand événement artistique"),
        ("art-heritage", "l'héritage culturel", "traditions transmises par les générations passées", "traditions et valeurs reçues du passé", "L'héritage culturel unit les peuples.", "héritage culturel = traditions du passé", "traditions et valeurs reçues du passé"),
    ],
},

"l-environnement": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V04",
    "short": "L'Environnement",
    "title": "L'Environnement",
    "subtitle": "Nature, écologie, pollution et changement climatique",
    "words": [
        {"word": "l'environnement", "ipa": "/lɑ̃.vi.ʁɔ.nə.mɑ̃/", "def": "milieu naturel dans lequel vivent les êtres vivants", "ex": "Nous devons protéger l'environnement."},
        {"word": "le changement climatique", "ipa": "/lə ʃɑ̃ʒ.mɑ̃ kli.ma.tik/", "def": "modification à long terme des conditions météorologiques", "ex": "Le changement climatique menace la planète."},
        {"word": "la pollution", "ipa": "/la pɔ.ly.sjɔ̃/", "def": "contamination de l'air, de l'eau ou du sol", "ex": "La pollution de l'air est un problème urbain majeur."},
        {"word": "le réchauffement", "ipa": "/lə ʁe.ʃo.fə.mɑ̃/", "def": "augmentation de la température de la Terre", "ex": "Le réchauffement climatique est une réalité scientifique."},
        {"word": "les énergies renouvelables", "ipa": "/le.ze.nɛʁ.ʒi ʁə.nu.vɛlabl/", "def": "sources d'énergie qui se régénèrent naturellement (soleil, vent…)", "ex": "Les énergies renouvelables réduisent la pollution."},
        {"word": "l'empreinte carbone", "ipa": "/lɑ̃.pʁɛ̃t kaʁ.bɔn/", "def": "quantité de CO₂ émise par une activité ou une personne", "ex": "Il faut réduire notre empreinte carbone."},
        {"word": "le recyclage", "ipa": "/lə ʁə.si.klaʒ/", "def": "transformation des déchets pour les réutiliser", "ex": "Le recyclage du plastique est essentiel."},
        {"word": "la biodiversité", "ipa": "/la bjɔ.di.vɛʁ.si.te/", "def": "variété des espèces vivantes dans un écosystème", "ex": "La biodiversité est menacée par la déforestation."},
        {"word": "la déforestation", "ipa": "/la de.fɔ.ʁɛs.ta.sjɔ̃/", "def": "destruction massive des forêts", "ex": "La déforestation détruit les habitats naturels."},
        {"word": "l'écologie", "ipa": "/le.kɔ.lɔ.ʒi/", "def": "science des relations entre les êtres vivants et leur milieu", "ex": "L'écologie est devenue une priorité politique."},
        {"word": "durable", "ipa": "/dy.ʁabl/", "def": "qui peut se maintenir sans épuiser les ressources naturelles", "ex": "Nous avons besoin d'une agriculture durable."},
        {"word": "la canicule", "ipa": "/la ka.ni.kyl/", "def": "période de chaleur extrême", "ex": "La canicule de 2003 a été très meurtrière."},
        {"word": "les inondations", "ipa": "/le.z‿i.nɔ̃.da.sjɔ̃/", "def": "débordement d'eau couvrant des zones normalement sèches", "ex": "Les inondations ont détruit des centaines de maisons."},
        {"word": "l'espèce menacée", "ipa": "/lɛs.pɛs mə.na.se/", "def": "espèce animale ou végétale en danger d'extinction", "ex": "Le panda est une espèce menacée."},
        {"word": "le tri sélectif", "ipa": "/lə tʁi se.lɛk.tif/", "def": "séparation des déchets en différentes catégories pour le recyclage", "ex": "Le tri sélectif est obligatoire dans beaucoup de villes."},
    ],
    "game_desc": "L'Environnement — écologie et changement climatique",
    "items": [
        ("env-changement", "le changement climatique", "modification à long terme des conditions météorologiques", "températures et météo qui changent durablement", "Le changement climatique cause des sécheresses.", "changement climatique = météo durablement modifiée", "températures et météo qui changent durablement"),
        ("env-pollution", "la pollution", "contamination de l'air, de l'eau ou du sol", "substances nocives dans l'environnement", "La pollution de l'eau nuit à la santé.", "pollution = contamination de la nature", "substances nocives dans l'environnement"),
        ("env-energies", "les énergies renouvelables", "sources d'énergie naturellement régénérées", "énergie du soleil, du vent, de l'eau", "Le solaire est une énergie renouvelable.", "renouvelable = énergie naturelle et inépuisable", "énergie du soleil, du vent, de l'eau"),
        ("env-empreinte", "l'empreinte carbone", "quantité de CO₂ émise par une activité", "CO₂ produit par nos activités", "Mon empreinte carbone est trop élevée.", "empreinte carbone = CO₂ émis", "CO₂ produit par nos activités"),
        ("env-recyclage", "le recyclage", "transformation des déchets pour les réutiliser", "recycler = transformer les déchets", "Le recyclage réduit les déchets.", "recyclage = transformer les déchets", "recycler = transformer les déchets"),
        ("env-biodiversite", "la biodiversité", "variété des espèces vivantes d'un écosystème", "diversité des êtres vivants", "La biodiversité est en danger.", "biodiversité = diversité du vivant", "diversité des êtres vivants"),
        ("env-deforestation", "la déforestation", "destruction massive des forêts", "coupe des arbres à grande échelle", "La déforestation de l'Amazonie est alarmante.", "déforestation = destruction des forêts", "coupe des arbres à grande échelle"),
        ("env-tri", "le tri sélectif", "séparation des déchets par catégorie pour le recyclage", "séparer les poubelles pour recycler", "Le tri sélectif est obligatoire.", "tri sélectif = séparer les déchets", "séparer les poubelles pour recycler"),
    ],
},

}
