"""
francais_c2_g1.py — French C2 Grammar chapters G01–G06
G01 Le Subjonctif Plus-que-parfait et la Concordance Absolue
G02 L'Inversion Stylistique et l'Hyperbate
G03 La Phrase Nominale et l'Ellipse Avancée
G04 La Syntaxe Périodique et le Style Oratoire
G05 Les Constructions Détachées et l'Apposition
G06 La Modalisation Épistémique et le Conditionnel Journalistique
"""

CHAPTERS = {

# ── G01 Le Subjonctif PQP et concordance absolue ─────────────────────────
"le-subjonctif-plus-que-parfait": {
    "level": "c2",
    "section": "grammaire",
    "num": "G01",
    "short": "Subjonctif plus-que-parfait",
    "title": "Le Subjonctif Plus-que-parfait",
    "subtitle": "Concordance absolue des temps et registre littéraire de haut niveau",
    "slides": [
        ("Formation du subjonctif plus-que-parfait", "Auxiliaire au subjonctif imparfait + participe passé. Avoir : que j'eusse parlé, que tu eusses parlé, qu'il eût parlé, que nous eussions parlé, que vous eussiez parlé, qu'ils eussent parlé. Être : que je fusse venu(e), que tu fusses venu(e), qu'il fût venu, que nous fussions venu(e)s."),
        ("Valeur et emploi", "Exprime une action passée, antérieure à un verbe principal au passé (subjonctif), dans un registre strictement littéraire ou solennel. Il est la contrepartie du subjonctif parfait dans la concordance des temps lorsque le verbe principal est lui-même à un temps du passé."),
        ("Concordance absolue des temps au subjonctif", "Registre écrit soigné : VP présent → subj. présent / subj. parfait. VP passé ou conditionnel → subj. imparfait / subj. PQP. Ex. : Je veux qu'il vienne (présent). Je voulais qu'il vînt (imparfait). J'ai voulu qu'il vînt (imparfait). Je voulais qu'il fût venu avant midi (PQP — antériorité)."),
        ("Subjonctif PQP = conditionnel passé 2e forme", "La forme 'qu'il eût parlé' est homophone du conditionnel passé 2e forme (= conditionnel passé 1re forme soutenu, appelé aussi 'le conditionnel littéraire'). Contexte seul distingue les deux : après un verbe de volonté/sentiment → subj. PQP ; dans une hypothèse irréelle du passé → conditionnel."),
        ("Exemples littéraires classiques", "Flaubert : « Il aurait voulu qu'elle fût restée. » (subj. PQP après conditionnel VP). Racine : « Plût au ciel que vous eussiez su… » (plût = subj. imparfait de plaire ; eussiez su = subj. PQP). Ces formes signalent un niveau de langue supérieur, attendu dans les commentaires de texte et les dissertations de très haut niveau."),
        ("Subjonctif PQP dans les complétives temporelles", "Après avant que, bien que, pour que, à moins que, de crainte que, quoique — si le VP est au passé : « Il sortit avant qu'elle fût revenue. » / « Bien qu'il eût tout perdu, il gardait sa dignité. » Ces formes sont rares à l'oral contemporain mais obligatoires en style soutenu écrit."),
        ("Distinctions finales : subj. parfait vs PQP", "Subj. parfait (ait parlé) = antériorité relative à un VP présent ou futur : « Je doute qu'il ait déjà fini. » Subj. PQP (eût parlé) = antériorité relative à un VP passé : « Je doutais qu'il eût déjà fini. » Le choix dépend entièrement du temps du VP, non du sens de l'action."),
        ("Registre et fréquence", "Le subjonctif PQP est absent de l'oral standard et de l'écrit courant. On le rencontre dans : romans du XIXe siècle, textes académiques de très haut niveau, concours d'agrégation, certains discours politiques formels. À C2, le reconnaître et le produire activement est attendu en expression écrite soutenue."),
        ("Pièges courants", "Confondre subj. PQP et subj. imparfait : après un VP au passé + antériorité → PQP obligatoire ('fût venu', non 'vînt'). Confondre avec le conditionnel passé 2e forme (même morphologie, rôle différent). Oublier l'accent circonflexe à la 3e personne du singulier : il eût (non *il eut)."),
        ("Résumé paradigme complet (avoir)", "Subj. imparfait : que j'eusse, que tu eusses, qu'il eût, que nous eussions, que vous eussiez, qu'ils eussent. Subj. PQP : que j'eusse eu, que tu eusses eu, qu'il eût eu… — toujours reconnaissable par l'auxiliaire au subj. imparfait."),
    ],
    "traps": [
        ("Confondre subj. PQP et subj. imparfait", "Après un VP au passé, si l'action de la subordonnée est antérieure → subj. PQP obligatoire ('je doutais qu'il fût déjà parti', non *'qu'il partît'). Le subj. imparfait exprime la simultanéité/postériorité par rapport au VP passé, pas l'antériorité."),
        ("Oublier l'accent circonflexe à la 3e pers. sg.", "'qu'il eût', 'qu'il fût' : l'accent distingue le subj. imparfait de l'indicatif passé simple ('il eut', 'il fut'). L'omettre est une faute d'orthographe grave dans un texte soutenu."),
        ("Généraliser le subj. PQP à l'oral", "Ces formes sont exclusivement de registre écrit ou oratoire formel. Les employer à l'oral spontané crée un effet d'affectation comique. À C2, savoir où les placer est aussi important que savoir les former."),
        ("Confondre la concordance avec une règle mécanique", "La concordance des temps n'est pas une règle absolue en français moderne : beaucoup de locuteurs cultivés emploient le subj. présent après un VP passé. La concordance stricte est une marque stylistique de soin, pas une obligation grammaticale en dehors du registre académique."),
    ],
    "summary": [
        "Subj. PQP = auxiliaire (eûsse/fusse) au subj. imparfait + participe passé.",
        "Emploi : antériorité par rapport à un VP passé, registre littéraire/académique.",
        "Concordance : VP présent → subj. présent/parfait ; VP passé → subj. imparfait/PQP.",
        "Homophone du conditionnel passé 2e forme : seul le contexte distingue les deux.",
        "Accent circonflexe obligatoire : il eût, il fût — jamais *il eut, *il fut dans ce contexte.",
    ],
    "ex1": {
        "q": "Dans quelle phrase le subjonctif plus-que-parfait est-il correctement employé ?",
        "opts": [
            "Je veux qu'il eût fini avant demain.",
            "Il était parti avant qu'elle fût revenue.",
            "Bien qu'il parte tôt, il arriva en retard.",
            "Je doutais qu'il vînt à temps.",
        ],
        "ans": "Il était parti avant qu'elle fût revenue.",
        "exp": "Le subj. PQP 'fût revenue' exprime une antériorité par rapport à 'il était parti' (VP au passé). 'Vînt' (subj. imparfait) exprime la simultanéité/postériorité, non l'antériorité. 'Veux' (présent) exige le subj. présent ou parfait, non PQP.",
    },
    "ex2": {
        "q": "Mettez à la concordance des temps soutenue : Je doute qu'il ait compris. → Hier, je doutais que…",
        "ans": "Hier, je doutais qu'il eût compris.",
        "exp": "Le VP passe de présent (doute) à passé (doutais). La subordonnée passe du subj. parfait (ait compris) au subj. PQP (eût compris) pour exprimer la même antériorité relative au VP passé.",
        "accept": ["eût compris", "il eût compris"],
    },
    "ex3": {
        "q": "Quel temps du subjonctif exprime la simultanéité par rapport à un verbe principal au passé ?",
        "opts": [
            "Le subjonctif présent",
            "Le subjonctif parfait",
            "Le subjonctif imparfait",
            "Le subjonctif plus-que-parfait",
        ],
        "ans": "Le subjonctif imparfait",
        "exp": "Concordance des temps soutenue : VP passé + simultanéité/postériorité → subj. imparfait ('Je voulais qu'il vînt'). VP passé + antériorité → subj. PQP ('Je voulais qu'il fût venu'). Le subj. présent s'emploie avec un VP au présent ou au futur.",
    },
    "game_desc": "Maîtrisez le subjonctif plus-que-parfait et la concordance absolue",
    "items": [
        ("g1-subj-pqp", "le subjonctif plus-que-parfait", "temps du subjonctif exprimant l'antériorité par rapport à un verbe principal au passé", "eût parlé · fût venu · concordance du passé", "Je doutais qu'il eût déjà fini avant notre arrivée — subj. PQP après VP passé.", "subjonctif PQP = auxiliaire au subj. imparfait + participe passé", "temps exprimant l'antériorité par rapport à un verbe principal au passé"),
        ("g1-concordance", "la concordance des temps", "règle ajustant le temps du verbe subordonné selon le temps du verbe principal", "l'ajustement temporel · l'accord des temps · la succession verbale", "VP présent → subj. présent ; VP passé → subj. imparfait (concordance soutenue).", "concordance des temps = ajustement du verbe subordonné selon le VP", "règle ajustant le temps du verbe subordonné selon le verbe principal"),
        ("g1-eut-fut", "il eût / il fût (accent obligatoire)", "formes du subj. imparfait à la 3e pers. sg., distinguées par l'accent des formes du passé simple", "l'accent circonflexe · eût vs eut · fût vs fut", "Il eût voulu (subj. imp.) ≠ il eut voulu (ind. passé antérieur) — l'accent est distinctif.", "il eût / fût = 3e pers. sg. subj. imparfait, accent obligatoire", "formes du subj. imparfait 3e pers. sg. avec accent distinctif"),
        ("g1-cond-passe-2", "le conditionnel passé 2e forme", "forme identique au subj. PQP employée dans les hypothèses irréelles du passé en registre soutenu", "l'autre conditionnel passé · eût parlé dans si… · le conditionnel littéraire", "S'il eût su, il ne fût pas venu — conditionnel 2e forme dans une hypothèse irréelle.", "conditionnel passé 2e forme = subj. PQP dans les hypothèses irréelles du passé", "forme identique au subj. PQP dans les hypothèses irréelles du passé"),
        ("g1-subj-imparfait", "le subjonctif imparfait", "temps du subjonctif exprimant la simultanéité/postériorité par rapport à un VP au passé", "vînt · parlât · finît · concordance des temps soutenue", "Je voulais qu'il vînt — subj. imparfait pour simultanéité après VP passé.", "subjonctif imparfait = simultanéité/postériorité après VP passé", "simultanéité ou postériorité par rapport à un verbe principal au passé"),
        ("g1-subj-parfait", "le subjonctif parfait", "temps du subjonctif exprimant l'antériorité par rapport à un VP au présent ou futur", "ait parlé · soit venu · antériorité présent · subj. composé", "Je doute qu'il ait déjà compris — subj. parfait pour antériorité après VP présent.", "subjonctif parfait = antériorité par rapport à un VP présent ou futur", "antériorité par rapport à un verbe principal au présent ou au futur"),
        ("g1-avant-que", "avant que + subj. PQP", "conjonction de subordination temporelle exigeant le subj. PQP après VP au passé", "avant que fût · subordination temporelle · antériorité conjonctive", "Il sortit avant qu'elle fût revenue — avant que + subj. PQP après VP passé.", "avant que + VP passé → subjonctif PQP", "avant que exige le subj. PQP quand le verbe principal est au passé"),
        ("g1-bien-que-pqp", "bien que + subj. PQP", "conjonction concessive exigeant le subj. PQP pour exprimer une antériorité concessée", "bien qu'il eût · quoiqu'il fût · concession au passé", "Bien qu'il eût tout perdu, il gardait sa sérénité — subj. PQP après bien que + VP passé.", "bien que + VP passé → subjonctif PQP", "bien que exige le subj. PQP pour exprimer une antériorité concessée"),
    ],
},

# ── G02 L'Inversion Stylistique et l'Hyperbate ────────────────────────────
"l-inversion-stylistique-et-hyperbate": {
    "level": "c2",
    "section": "grammaire",
    "num": "G02",
    "short": "Inversion stylistique",
    "title": "L'Inversion Stylistique et l'Hyperbate",
    "subtitle": "Procédés de dislocation syntaxique pour l'effet stylistique en prose soutenue",
    "slides": [
        ("L'inversion dans la proposition incise", "Discours rapporté : 'dit-il', 'reprit-elle', 's'exclama-t-il'. Obligatoire après les guillemets/tiret dans le dialogue littéraire. Règle : sujet nominal → inversion nominale : 'dit le docteur' (non *'le docteur dit'). Verbe introducteur après la citation."),
        ("L'inversion après certains adverbes", "Aussi, ainsi, à peine, sans doute, peut-être, encore, du moins — en tête de phrase → inversion du sujet. Ex. : 'Aussi décida-t-il de partir.' / 'À peine était-il entré que le téléphone sonna.' / 'Peut-être viendra-t-il.' L'inversion est obligatoire après à peine et aussi (≠ aussi = de même, qui ne l'exige pas)."),
        ("L'inversion dans les subordonnées hypothétiques sans si", "Registre soutenu : remplacement de 'si' par l'inversion du sujet + subjonctif ou conditionnel. Ex. : 'Fût-il venu, nous aurions résolu le problème.' (= Si elle était venue…). 'Eût-il su, il n'aurait pas agi ainsi.' (= S'il avait su…). Très littéraire, marque d'un niveau stylistique exceptionnel."),
        ("L'inversion dans la phrase exclamative et interrogative", "Interrogation directe en registre soutenu : 'Où êtes-vous allé ?' (non *'Vous êtes allé où ?'). Exclamation : 'Qu'il était beau, ce temps !' Formules figées : 'Ainsi soit-il.' / 'Soit !'. L'inversion du pronom est obligatoire dans les questions de registre standard à soutenu."),
        ("L'hyperbate : définition et fonction", "Ajout d'un élément syntaxique APRÈS la clôture logique de la phrase, créant un effet de suspension puis de chute. Ex. : 'Il avait tout perdu, son argent, ses amis, sa santé.' L'hyperbate crée une emphase sur l'élément détaché, comme si la pensée continuait au-delà de sa fin naturelle."),
        ("Types d'hyperbate", "Accumulation terminale : ajout d'une liste après le point logique ('Il était seul, totalement, irrémédiablement.'). Apposition détachée finale : 'Elle entra, tremblante.' Complément circonstanciel déplacé : 'Il le comprit enfin, trop tard.' Chaque variante produit un rythme différent."),
        ("Inversion stylistique et chiasme", "L'inversion peut créer un chiasme syntaxique : 'Pierre aime Marie — Marie, elle l'aime aussi.' La dislocation à gauche (Marie, elle) est un type d'inversion thématique fréquent en français contemporain. Le chiasme crée une symétrie qui met en relief l'opposition ou la réciprocité."),
        ("L'inversion dans les comparatives et consécutives soutenues", "Telle est sa force qu'on ne peut… / Rares sont ceux qui… / Grande est ma joie de… Ces constructions attribut + être inversé sont des marques de style oratoire. 'Rares sont ceux' = registre soutenu de 'il y en a peu qui'."),
        ("Hyperbate et anacoluthe", "Anacoluthe : rupture syntaxique volontaire, le début de phrase ne se poursuit pas logiquement ('Moi, mes amis, je les aime' — sujet repris par pronom). Différence : l'hyperbate AJOUTE après la clôture ; l'anacoluthe CHANGE de construction en cours de phrase. Les deux sont des procédés stylistiques, non des fautes à C2."),
        ("Effets et usages", "Inversion = solennité, distanciation, style classique. Hyperbate = emphase, suspension, effet dramatique. À C2, les identifier dans un texte et les produire intentionnellement est attendu. Les employer hors contexte (dans un email professionnel) crée un effet de pédanterie."),
    ],
    "traps": [
        ("Inversion obligatoire vs optionnelle", "Après 'à peine' et 'aussi (= c'est pourquoi)', l'inversion est OBLIGATOIRE en registre soutenu : 'À peine était-il arrivé' (non *'À peine il était arrivé'). Après 'peut-être' et 'sans doute', l'inversion est recommandée mais que + subj. est admis : 'Peut-être qu'il viendra' (courant) vs 'Peut-être viendra-t-il' (soutenu)."),
        ("Confondre hyperbate et simple apposition", "L'apposition est une relation de reformulation intégrée syntaxiquement : 'Paris, capitale de la France, est…'. L'hyperbate est un AJOUT après la clôture logique : 'Il était seul. Absolument.' L'hyperbate crée une cassure ; l'apposition est fluide."),
        ("Oublier le tiret euphonique", "'Viendra-t-il ?' et non *'Viendra-il ?' Le -t- euphonique s'insère entre un verbe terminé par une voyelle et il/elle/on à l'interrogatif ou dans l'incise : 'dit-il', 'reviendra-t-on'."),
        ("Inversion dans les hypothétiques sans si", "Les constructions 'Fût-il venu, Eût-il su…' sont réservées au registre littéraire ou soutenu très formel. Les employer dans un essai courant crée un effet d'archaïsme. Elles sont à produire uniquement dans un commentaire de texte ou une dissertation de très haut niveau."),
    ],
    "summary": [
        "Inversion obligatoire après : à peine, aussi (= c'est pourquoi), dans les incises du dialogue.",
        "Inversion optionnelle mais soutenue après : peut-être, sans doute, du moins.",
        "Hypothétiques sans si : Fût-il venu… / Eût-il su… — registre strictement littéraire.",
        "Hyperbate : ajout stylistique après la clôture logique pour emphase et suspension.",
        "Tiret euphonique : -t- entre verbe en voyelle et il/elle/on (viendra-t-il).",
    ],
    "ex1": {
        "q": "Quelle phrase illustre correctement l'inversion obligatoire après 'à peine' ?",
        "opts": [
            "À peine il était entré que le téléphone sonna.",
            "À peine était-il entré que le téléphone sonna.",
            "À peine qu'il fut entré, le téléphone sonna.",
            "À peine, il entra et le téléphone sonna.",
        ],
        "ans": "À peine était-il entré que le téléphone sonna.",
        "exp": "'À peine' en tête de proposition exige l'inversion du sujet en registre soutenu : était-il (et non il était). La construction 'à peine… que' est une corrélative temporelle ; 'que' introduit la conséquence immédiate. Les autres options sont incorrectes syntaxiquement ou stylistiquement insuffisantes.",
    },
    "ex2": {
        "q": "Transformez en construction hypothétique sans 'si' (registre soutenu) : 'Si elle avait été présente, tout aurait changé.'",
        "ans": "Eût-elle été présente, tout aurait changé.",
        "exp": "Remplacement de 'si + plus-que-parfait' par inversion du sujet + subjonctif PQP (conditionnel passé 2e forme). 'Si elle avait été' → 'Eût-elle été'. La principale conserve le conditionnel passé standard. Cette construction est strictement littéraire.",
        "accept": ["eût-elle été", "fût-elle", "eût elle été"],
    },
    "ex3": {
        "q": "Lequel des exemples suivants est un exemple d'hyperbate ?",
        "opts": [
            "Paris, capitale de la France, est une métropole mondiale.",
            "Il avait tout perdu — son argent, ses amis, sa raison.",
            "Peut-être viendra-t-il demain.",
            "Ainsi décida-t-il de repartir à zéro.",
        ],
        "ans": "Il avait tout perdu — son argent, ses amis, sa raison.",
        "exp": "L'hyperbate ajoute un élément ('son argent, ses amis, sa raison') après la clôture logique de la phrase ('il avait tout perdu'). L'énumération finale crée un effet de suspension et d'emphase progressive. Les autres exemples illustrent l'apposition (Paris, capitale…), l'inversion après peut-être, et l'inversion après ainsi.",
    },
    "game_desc": "Maîtrisez l'inversion stylistique et l'hyperbate au niveau C2",
    "items": [
        ("g2-inversion-adv", "l'inversion après adverbe initiaux", "inversion du sujet obligatoire ou recommandée après certains adverbes en tête de proposition", "aussi · à peine · sans doute · peut-être", "À peine était-il arrivé que la réunion commença — inversion obligatoire après 'à peine'.", "inversion après adverbe = sujet inversé après aussi/à peine/peut-être en tête", "inversion du sujet après certains adverbes placés en tête de proposition"),
        ("g2-hyp-sans-si", "l'hypothétique sans si", "construction soutenue remplaçant si + PQP par inversion + subj. PQP", "eût-il su · fût-elle venue · le conditionnel littéraire", "Eût-il su la vérité, il aurait agi autrement — hypothétique sans si.", "hypothétique sans si = inversion + subj. PQP en lieu de si + PQP", "inversion + subjonctif PQP remplaçant si + plus-que-parfait"),
        ("g2-hyperbate", "l'hyperbate", "ajout stylistique après la clôture logique d'une phrase pour créer emphase et suspension", "l'accumulation terminale · l'ajout après la clôture · l'emphase", "Il avait tout perdu — son argent, ses amis, sa sérénité. (hyperbate avec énumération terminale)", "hyperbate = ajout après la clôture logique de la phrase", "ajout après la clôture logique d'une phrase pour emphase et suspension"),
        ("g2-tiret-eupho", "le tiret euphonique -t-", "insertion de -t- entre un verbe en voyelle et il/elle/on dans une inversion", "viendra-t-il · dit-il · -t- euphonique · liaison graphique", "Viendra-t-il ? / dit-il — le -t- est obligatoire pour faciliter la prononciation.", "tiret euphonique = -t- entre verbe en voyelle et il/elle/on inversé", "insertion de -t- entre verbe en voyelle et il/elle/on dans l'inversion"),
        ("g2-inversion-incise", "l'inversion dans l'incise", "ordre verbe + sujet dans les propositions intercalées du dialogue littéraire", "dit-il · reprit-elle · s'exclama le narrateur", "'Je viendrai demain', dit-il en souriant — inversion obligatoire dans l'incise.", "inversion dans l'incise = verbe + sujet dans le discours rapporté littéraire", "ordre verbe + sujet dans les propositions intercalées du dialogue"),
        ("g2-anacoluthe", "l'anacoluthe", "rupture syntaxique volontaire : début de phrase ne se prolongeant pas selon la construction attendue", "la rupture syntaxique · la dislocation · la phrase brisée", "Moi, mes amis, je les aime — le sujet nominal est repris par un pronom (anacoluthe par dislocation).", "anacoluthe = rupture syntaxique volontaire en cours de phrase", "rupture syntaxique volontaire changeant la construction en cours de phrase"),
        ("g2-inversion-attribut", "l'inversion attribut + être", "construction soutenue plaçant l'attribut en tête : Grande est ma joie", "rares sont ceux qui · telle est ma conviction · style oratoire", "Rares sont ceux qui osent contredire — inversion attribut + être en style oratoire.", "inversion attribut + être = attribut en tête de phrase (registre soutenu)", "construction soutenue plaçant l'attribut avant être en tête de phrase"),
        ("g2-aussi-inversion", "aussi (= c'est pourquoi) + inversion", "emploi de aussi en tête de proposition causale-conclusive exigeant l'inversion du sujet", "aussi décida-t-il · aussi est-il · donc soutenu", "Aussi décida-t-il de changer de stratégie — aussi (conclusif) exige l'inversion.", "aussi conclusif + inversion = aussi (donc) en tête exige l'inversion", "aussi en sens conclusif en tête de proposition exige l'inversion du sujet"),
    ],
},

# ── G03 La Phrase Nominale et l'Ellipse Avancée ──────────────────────────
"la-phrase-nominale-et-ellipse": {
    "level": "c2",
    "section": "grammaire",
    "num": "G03",
    "short": "Phrase nominale et ellipse",
    "title": "La Phrase Nominale et l'Ellipse Avancée",
    "subtitle": "Procédés de condensation syntaxique pour la densité stylistique",
    "slides": [
        ("La phrase nominale : définition", "Phrase sans verbe conjugué, organisée autour d'un nom, d'un groupe nominal ou d'un adjectif. Ex. : 'Silence total.' / 'Étrange rencontre.' / 'Personne en vue.' Elle condense l'information, crée un rythme brisé et produit un effet d'immédiateté ou d'urgence."),
        ("Fonctions stylistiques de la phrase nominale", "Titre et sous-titre (journaux, ouvrages). Didascalies théâtrales. Descriptions impressionnistes. Notations rapides (carnets, journaux). Appel à l'attention ('Attention ! Danger !'). Dans le roman ou l'essai, elle crée un contraste de rythme avec les phrases verbales longues."),
        ("Types de phrases nominales", "Nominale pure : 'Nuit noire.' Participiale sans sujet propre : 'Ce faisant, il révèle…' (= en faisant ceci). Infinitive injonctive : 'Ne pas fumer.' / 'Défense d'entrer.' Présentative : 'Voilà mon problème.' Exclamative nominale : 'Quelle beauté !'"),
        ("L'ellipse : définition", "Suppression d'un ou plusieurs éléments syntaxiques récupérables par le contexte. Ex. : 'Il viendra demain et elle [viendra] après-demain.' L'ellipse allège le style, évite les répétitions et crée une impression de fluidité ou de lacune volontaire."),
        ("Ellipse du verbe (zeugme elliptique)", "Ellipse du verbe répété dans une coordination. Ex. : 'Pierre lit un roman, Marie [lit] un journal.' Variante sophistiquée : 'Il prenait le vin et moi [prenais] l'eau.' Le lecteur complète mentalement. Le zeugme stylistique unit intentionnellement des éléments incompatibles : 'Il prit congé et son chapeau.'"),
        ("Ellipse du sujet et du pronom", "En registre soutenu ou poétique, le sujet peut être omis quand il est récupérable : 'Vint à passer un mendiant. [Il] tendit la main.' / 'Entré, [il] s'assit sans un mot.' Ce procédé mimétique accélère le récit ou crée une focalisation impersonnelle."),
        ("L'aposiopèse", "Ellipse en fin de phrase laissant une idée délibérément inachevée pour suggérer l'indicible, la honte ou l'émotion. Marquée par points de suspension : 'Si tu savais ce que j'ai vécu…' / 'Il allait dire… mais non.' Effet : impliquer le lecteur, créer du mystère ou de la retenue."),
        ("Parallélisme et ellipse", "L'ellipse est souvent combinée avec le parallélisme pour créer un rythme binaire ou ternaire élégant. Ex. : 'Veni, vidi, vici.' (César) — trois infinitifs parallèles avec ellipse du sujet. En français : 'Entrer, voir, vaincre.' La combinaison donne une prose lapidaire et mémorable."),
        ("Nominalisations comme procédé d'ellipse", "La nominalisation condensed une phrase entière en un GN. 'La décision de partir fut difficile' = 'Décider de partir fut difficile' condensé. Les nominalisations sont fréquentes dans le style académique et journalistique pour la densité : 'la reprise économique', 'le renforcement du contrôle'."),
        ("Pièges à éviter", "Phrase nominale sans effet intentionnel : liste de noms sans rythme ni sens produit un style télégraphique maladroit. Ellipse ambiguë : supprimer un élément qui ne peut pas être récupéré par le contexte ('Il aime et elle aussi' — que fait-elle aussi ?). Aposiopèse artificielle : points de suspension non justifiés par l'émotion ou l'indicible."),
    ],
    "traps": [
        ("Confondre phrase nominale et phrase à copule zéro", "La phrase nominale n'a PAS de verbe conjugué sous-jacent. 'Quelle belle journée !' est une exclamative nominale. 'C'est une belle journée' est une phrase verbale à copule. Ne pas analyser 'Magnifique !' comme une ellipse de 'c'est magnifique' — ce sont deux constructions distinctes."),
        ("Ellipse ambiguë", "Supprimer un élément non récupérable : '*Il étudie le droit, et elle la médecine.' est ambigu si 'étudie' peut s'appliquer différemment. L'ellipse n'est stylistiquement correcte que si le lecteur peut retrouver sans effort l'élément omis."),
        ("Abuser de l'aposiopèse", "Les points de suspension répétés affaiblissent le style au lieu de créer du mystère. À C2, une ou deux aposiopèses par page maximale ; au-delà, l'effet est dilué et le style paraît hésitant."),
        ("Confondre ellipse et anacoluthe", "L'anacoluthe change de construction syntaxique en cours de phrase ('Lui, ses enfants l'aiment'). L'ellipse SUPPRIME un élément récupérable ('Pierre rit et Marie [rit] aussi'). Les deux sont des procédés distincts avec des effets différents."),
    ],
    "summary": [
        "Phrase nominale : sans verbe conjugué — immédiate, percutante, rythmiquement contrastée.",
        "Ellipse : suppression d'un élément récupérable par le contexte pour fluidité et concision.",
        "Aposiopèse : inachèvement délibéré (…) pour suggérer l'indicible ou l'émotion.",
        "Zeugme : ellipse du verbe en coordination ; zeugme stylistique : union d'éléments incompatibles.",
        "Nominalisation : condensation d'une proposition entière en groupe nominal (style académique).",
    ],
    "ex1": {
        "q": "Quelle est la fonction principale de la phrase nominale dans un texte littéraire ?",
        "opts": [
            "Introduire un commentaire sur l'auteur",
            "Créer un contraste rythmique et un effet d'immédiateté",
            "Remplacer systématiquement les phrases longues",
            "Signaler un changement de narrateur",
        ],
        "ans": "Créer un contraste rythmique et un effet d'immédiateté",
        "exp": "La phrase nominale, dépourvue de verbe conjugué, se distingue nettement des phrases verbales longues et crée une rupture de rythme qui attire l'attention. Elle produit un effet d'immédiateté, de notation rapide ou de choc émotionnel selon le contexte.",
    },
    "ex2": {
        "q": "Identifiez l'ellipse dans : 'Pierre lit Proust et Marie, Zola.'",
        "ans": "Le verbe 'lit' est ellipsé dans la deuxième partie : 'Marie [lit] Zola.' L'ellipse verbale évite la répétition et crée un parallélisme élégant.",
        "exp": "L'ellipse du verbe en coordination est l'un des procédés de condensation les plus courants. Le lecteur récupère 'lit' par le contexte immédiat. La virgule après 'Marie' marque la pause qui signale l'ellipse.",
        "accept": ["lit est ellipsé", "ellipse du verbe", "lit sous-entendu", "ellipse de lit"],
    },
    "ex3": {
        "q": "Quel procédé consiste à laisser une phrase délibérément inachevée avec des points de suspension ?",
        "opts": [
            "L'hyperbate",
            "L'aposiopèse",
            "La zeugme",
            "L'anacoluthe",
        ],
        "ans": "L'aposiopèse",
        "exp": "L'aposiopèse est l'interruption délibérée d'une phrase, signalée par des points de suspension, pour suggérer l'indicible, l'émotion ou le non-dit. 'Si tu savais ce que j'ai traversé…' L'hyperbate ajoute après la clôture ; le zeugme unit des éléments incompatibles ; l'anacoluthe change de construction.",
    },
    "game_desc": "Maîtrisez la phrase nominale et l'ellipse avancée au niveau C2",
    "items": [
        ("g3-phr-nom", "la phrase nominale", "phrase sans verbe conjugué organisée autour d'un nom ou d'un adjectif", "la phrase sans verbe · la phrase averbale · le style nominal", "'Nuit profonde. Silence total.' — deux phrases nominales créant une atmosphère par accumulation.", "phrase nominale = phrase sans verbe conjugué", "phrase sans verbe conjugué organisée autour d'un nom ou adjectif"),
        ("g3-ellipse", "l'ellipse syntaxique", "suppression d'un élément récupérable par le contexte pour alléger et fluidifier le style", "la suppression d'élément · la compression syntaxique · l'implicite", "'Pierre lit Proust et Marie, Zola.' — 'lit' est ellipsé dans la deuxième partie.", "ellipse = suppression d'un élément récupérable par le contexte", "suppression d'un élément syntaxique récupérable par le contexte"),
        ("g3-aposiopese", "l'aposiopèse", "interruption délibérée d'une phrase laissée inachevée, signalée par des points de suspension", "les points de suspension · l'inachèvement · le silence éloquent", "'Si tu savais ce que j'ai vécu…' — l'aposiopèse suggère l'indicible.", "aposiopèse = phrase délibérément inachevée signalée par ...", "interruption délibérée d'une phrase laissée inachevée (...)"),
        ("g3-zeugme", "le zeugme stylistique", "union d'un seul verbe à deux compléments sémantiquement incompatibles pour un effet comique ou poétique", "le zeugme · l'attelage · la coordination hétéroclite", "'Il prit congé et son chapeau.' — zeugme : un seul verbe unit des compléments incompatibles.", "zeugme = un verbe + deux compléments sémantiquement incompatibles", "union d'un verbe à deux compléments sémantiquement incompatibles"),
        ("g3-nominalisation", "la nominalisation", "transformation d'une proposition ou d'un verbe en groupe nominal pour condenser l'information", "le substantif déverbal · la condensation nominale · le style académique", "'La reprise économique' condense 'l'économie reprend' — nominalisation typique du style académique.", "nominalisation = transformation d'une proposition en groupe nominal", "transformation d'une proposition ou d'un verbe en groupe nominal"),
        ("g3-parallelisme", "le parallélisme avec ellipse", "répétition d'une structure syntaxique avec suppression des éléments communs pour un rythme élégant", "la structure parallèle · l'isocolon · la répétition structurelle", "Veni, vidi, vici — trois éléments parallèles avec ellipse du sujet pour une prose lapidaire.", "parallélisme + ellipse = structure répétée avec omission des éléments communs", "répétition d'une structure avec suppression des éléments communs"),
        ("g3-infinitive-injone", "la phrase infinitive injonctive", "type de phrase nominale sans sujet exprimé, à l'infinitif, exprimant un ordre ou une interdiction", "l'infinitif d'ordre · Ne pas fumer · Défense d'entrer", "'Ne pas fumer.' / 'Appuyer sur le bouton.' — infinitive injonctive sans sujet.", "infinitive injonctive = infinitif sans sujet exprimant un ordre ou interdiction", "phrase à l'infinitif sans sujet exprimant un ordre ou une interdiction"),
        ("g3-ellipse-sujet", "l'ellipse du sujet", "omission du sujet dans un registre soutenu ou poétique quand il est récupérable par le contexte", "le sujet omis · la narration sans je · la focalisation impersonnelle", "'Entra, s'assit sans mot dire.' — sujet ellipsé, récupérable par le contexte narratif.", "ellipse du sujet = omission du sujet récupérable par le contexte", "omission du sujet quand il est récupérable par le contexte"),
    ],
},

# ── G04 La Syntaxe Périodique et le Style Oratoire ────────────────────────
"la-syntaxe-periodique-et-style-oratoire": {
    "level": "c2",
    "section": "grammaire",
    "num": "G04",
    "short": "Syntaxe périodique",
    "title": "La Syntaxe Périodique et le Style Oratoire",
    "subtitle": "Construire des périodes longues, des climax et des anaphores pour l'éloquence",
    "slides": [
        ("Qu'est-ce que la période ?", "La période est une longue phrase construite en plusieurs membres (ou propositions) qui s'enchaînent vers une conclusion attendue et rhythmiquement satisfaisante. Elle est le signe du style classique et oratoire. Elle diffère de la phrase simple par son architecture interne : protase (tension) + apodose (résolution)."),
        ("Protase et apodose", "Protase : membres subordonnés ou conditionnels en début de période, créant une attente. Apodose : proposition principale qui résout la tension. Ex. : 'Si l'on considère les multiples obstacles surmontés, les sacrifices consentis, et la ténacité dont ils ont fait preuve [protase], il faut reconnaître que leur succès est mérité [apodose].'"),
        ("Le climax et l'anticlimax", "Climax (gradation ascendante) : accumulation d'éléments d'intensité croissante. Ex. : 'Il est venu, il a vu, il a vaincu.' Anticlimax (gradation descendante + chute) : tension puis déception ou ironie. Ex. : 'Il avait tout préparé, tout organisé, tout planifié — et oublia la date.' L'anticlimax crée l'effet comique ou pathétique."),
        ("L'anaphore oratoire", "Répétition d'un mot ou d'un groupe en tête de plusieurs propositions ou phrases. Ex. : 'Nous nous battrons sur les plages, nous nous battrons sur les terrains d'atterrissage, nous nous battrons dans les champs et dans les rues…' (Churchill). Effet : intensification, progression émotionnelle, rythme incantatoire."),
        ("L'épiphore et le symploque", "Épiphore : répétition en FIN de propositions. Ex. : 'Je l'ai voulu, je l'ai cherché, je l'ai obtenu.' Symploque : anaphore + épiphore combinées (début et fin identiques). Ex. : 'La liberté est mon droit, l'égalité est mon droit, la fraternité est mon droit.' Ces procédés créent une structure très rythmée."),
        ("La tricolon et la structure ternaire", "Groupement de trois éléments de longueur similaire : 'Veni, vidi, vici.' / 'Liberté, égalité, fraternité.' Le ternaire est la structure rythmique la plus puissante dans l'éloquence française. Le troisième terme porte l'emphase maximale et est souvent le plus long (loi des membres croissants)."),
        ("La question rhétorique", "Question posée sans attente de réponse, pour affirmer l'évidence ou impliquer l'auditoire. Ex. : 'Est-il possible d'ignorer ces faits ?' (= On ne peut les ignorer). 'Qui de nous ne ressent pas cette injustice ?' (= Nous la ressentons tous). Effet : interpeller, persuader, créer une connivence."),
        ("L'accumulation et l'asyndète oratoire", "Accumulation sans conjonctions (asyndète) pour un rythme précipité : 'Il aima, souffrit, combattit, mourut.' Avec polysyndète (répétition de et) pour insistance : 'Et il aima, et il souffrit, et il combattit, et il mourut.' L'asyndète crée l'urgence ; la polysyndète, la solennité ou l'émotion."),
        ("Le style coupé vs le style périodique", "Style coupé (style court) : phrases brèves, rythme haché, nerveux — Pascal, Voltaire. Style périodique (style long) : phrases longues et architecturées — Bossuet, Chateaubriand, Proust. À C2, savoir les distinguer dans un texte et les produire intentionnellement est attendu."),
        ("Reconnaître et produire le style oratoire", "Traits distinctifs : anaphores, questions rhétoriques, tricolon, périodes avec protase/apodose, inversion stylistique, vocabulaire solennel. Ex. de période oratoire modèle : 'Quand l'histoire nous jugera, quand nos enfants nous interrogeront, quand le silence des archives parlera plus fort que nos discours, que pourrons-nous répondre ?'"),
    ],
    "traps": [
        ("Période sans résolution (apodose manquante)", "Accumuler des subordonnées sans jamais arriver à la proposition principale : la phrase devient interminable et incompréhensible. Toute protase doit être résolue par une apodose claire."),
        ("Anaphore mécanique sans progression", "Répéter un mot en tête de chaque phrase sans que la succession d'idées progresse ou s'intensifie. L'anaphore doit accompagner une montée en intensité ou une énumération significative."),
        ("Question rhétorique banale", "Poser une question dont la réponse est trop évidente pour être intéressante : 'Est-ce que la santé est importante ?' L'efficacité de la question rhétorique dépend d'un certain paradoxe ou d'un renversement attendu."),
        ("Tricolon déséquilibré", "Grouper trois éléments de longueurs très inégales brise le rythme ternaire. La loi des membres croissants recommande que le troisième terme soit le plus développé. '*La liberté, l'égalité, la fraternité, la solidarité et l'équité' n'est plus un tricolon mais une liste."),
    ],
    "summary": [
        "Période = protase (tension) + apodose (résolution) — architecture de la phrase soutenue.",
        "Climax = gradation ascendante ; anticlimax = chute après tension.",
        "Anaphore = répétition en tête de propositions ; épiphore = répétition en fin.",
        "Tricolon = trois membres de force croissante — la structure oratoire la plus puissante.",
        "Style coupé (court, nerveux) vs style périodique (long, architecturé).",
    ],
    "ex1": {
        "q": "Dans la période 'Si les faits sont avérés, si les témoins sont fiables, si les preuves sont concordantes, alors la culpabilité ne fait aucun doute', quelle est la protase ?",
        "opts": [
            "Alors la culpabilité ne fait aucun doute",
            "Si les faits sont avérés, si les témoins sont fiables, si les preuves sont concordantes",
            "La culpabilité ne fait aucun doute",
            "Les preuves sont concordantes",
        ],
        "ans": "Si les faits sont avérés, si les témoins sont fiables, si les preuves sont concordantes",
        "exp": "La protase est l'ensemble des propositions subordonnées qui créent la tension et l'attente en début de période. L'apodose 'alors la culpabilité ne fait aucun doute' résout cette tension. Les trois 'si' forment également une anaphore qui renforce la progression.",
    },
    "ex2": {
        "q": "Rédigez un tricolon (gradation ascendante) sur le thème de la résistance.",
        "ans": "Il résista, il persévéra, il triompha de tout ce que la fortune avait accumulé contre lui.",
        "exp": "Le tricolon unit trois membres de force croissante : l'action simple (résista), la durée (persévéra) et la victoire finale amplifiée (triompha de tout…). Le troisième membre est le plus développé, conformément à la loi des membres croissants.",
        "accept": ["trois éléments", "gradation", "croissant", "membres croissants", "tricolon"],
    },
    "ex3": {
        "q": "Quel est le procédé stylistique qui consiste à répéter un mot ou un groupe en tête de plusieurs propositions pour créer un rythme incantatoire ?",
        "opts": [
            "L'épiphore",
            "L'anaphore",
            "Le zeugme",
            "L'hyperbate",
        ],
        "ans": "L'anaphore",
        "exp": "L'anaphore répète un élément en tête (ἀναφορά = porter en avant). L'épiphore répète en fin de propositions. 'Nous nous battrons… nous nous battrons… nous nous battrons…' (Churchill) est l'exemple canonique d'anaphore oratoire à visée de progression émotionnelle.",
    },
    "game_desc": "Maîtrisez la syntaxe périodique et le style oratoire au C2",
    "items": [
        ("g4-periode", "la période", "longue phrase architecturée en protase (tension) + apodose (résolution)", "la phrase périodique · la phrase longue · l'architecture oratoire", "Si l'on considère… [protase], force est de reconnaître… [apodose] — période classique.", "période = protase (tension) + apodose (résolution)", "longue phrase avec protase créant l'attente et apodose la résolvant"),
        ("g4-anaphore", "l'anaphore", "répétition d'un mot ou d'un groupe en tête de plusieurs propositions consécutives", "la répétition initiale · le retour en tête · le rythme incantatoire", "Nous lutterons sur les plages, nous lutterons dans les rues… — anaphore de 'nous lutterons'.", "anaphore = répétition en tête de propositions consécutives", "répétition d'un mot ou groupe en tête de propositions consécutives"),
        ("g4-climax", "le climax", "gradation ascendante : accumulation d'éléments d'intensité croissante", "la gradation · l'intensification · la montée en puissance", "Il vint, il vit, il vainquit — trois étapes de force croissante (climax ternaire).", "climax = gradation ascendante d'éléments d'intensité croissante", "accumulation d'éléments d'intensité croissante vers un sommet"),
        ("g4-tricolon", "le tricolon", "structure rhétorique groupant trois éléments parallèles de force croissante", "le ternaire · les trois membres · la structure en trois temps", "Liberté, égalité, fraternité — tricolon révolutionnaire à trois membres équilibrés.", "tricolon = trois éléments parallèles de force croissante", "structure groupant trois éléments parallèles de force croissante"),
        ("g4-question-rhet", "la question rhétorique", "question posée sans attente de réponse, pour affirmer ou impliquer l'auditoire", "la question de rhétorique · l'interrogation oratoire · l'interpellation", "'Qui de nous ne ressent pas cette injustice ?' — question rhétorique affirmant le ressenti universel.", "question rhétorique = question sans réponse attendue pour affirmer ou impliquer", "question posée sans attente de réponse pour affirmer ou impliquer"),
        ("g4-anticlimax", "l'anticlimax", "gradation descendante suivie d'une chute bathétique pour l'effet comique ou pathétique", "la chute · le bathétique · la gradation descendante", "Il avait tout planifié, tout organisé — et oublia la date. (anticlimax comique)", "anticlimax = tension + chute bathétique pour effet comique ou pathétique", "gradation descendante suivie d'une chute inattendue"),
        ("g4-epiphore", "l'épiphore", "répétition d'un mot ou d'un groupe en fin de plusieurs propositions consécutives", "la répétition finale · l'épistrophe · la clôture répétée", "'Je l'ai voulu, je l'ai cherché, je l'ai obtenu.' — épiphore de 'je l'ai + verbe'.", "épiphore = répétition en fin de propositions consécutives", "répétition d'un mot ou groupe en fin de propositions consécutives"),
        ("g4-style-coupe", "le style coupé vs périodique", "opposition entre phrases courtes et nerveuses (coupé) et phrases longues architecturées (périodique)", "le style court · le style bref · Pascal vs Bossuet", "Pascal : style coupé — phrases lapidaires. Bossuet : style périodique — phrases longues solennelles.", "style coupé (court, nerveux) vs périodique (long, architecturé)", "opposition entre phrases brèves nerveuses et phrases longues architecturées"),
    ],
},

# ── G05 Les Constructions Détachées et l'Apposition ──────────────────────
"les-constructions-detachees-et-apposition": {
    "level": "c2",
    "section": "grammaire",
    "num": "G05",
    "short": "Constructions détachées",
    "title": "Les Constructions Détachées et l'Apposition",
    "subtitle": "Syntaxe du détachement pour la nuance, l'emphase et la densité informative",
    "slides": [
        ("Qu'est-ce qu'une construction détachée ?", "Groupe nominal, adjectival, participial ou adverbial séparé du reste de la phrase par une virgule et n'étant pas relié par une conjonction. Fonction : apporter une information supplémentaire (attribut, circonstance, qualification) sans la subordonner syntaxiquement."),
        ("L'apposition", "GN placé à côté d'un autre GN auquel il se réfère, séparé par une virgule ou non. Ex. : 'Camus, écrivain algérien, a reçu le Nobel.' (apposition intercalée) / 'Un génie, Proust !' (apposition en tête ou en finale). Elle précise, reformule ou classe."),
        ("Apposition vs attribut", "Attribut = lié par un verbe d'état : 'Il est médecin.' Apposition = sans verbe : 'Médecin, il comprit immédiatement.' L'apposition détachée en tête crée un effet de mise en relief du trait caractéristique avant toute prédication."),
        ("Le participe passé détaché", "Participe passé ou présent séparé par une virgule, se référant au sujet ou à un autre nom. Ex. : 'Épuisé par la marche, il s'assit.' / 'La tempête venue, ils renoncèrent.' Le participe détaché équivaut à une subordonnée circonstancielle (causale, temporelle, concessive selon le sens)."),
        ("La participiale absolue (rappel C1 + C2)", "Participe avec son propre sujet : 'Le soleil se couchant, les oiseaux se turent.' Différence avec le participe détaché : la participiale a un sujet différent du sujet principal. À C2, l'employer activement en production écrite est attendu."),
        ("L'adjectif détaché", "Adjectif ou groupe adjectival séparé par une virgule, épithète détachée. Ex. : 'Silencieuse et grave, elle entra.' / 'Il la regarda, stupéfait.' L'adjectif détaché en tête a une valeur causale ou de cadrage ; en finale, il a une valeur resultative ou descriptive."),
        ("La dislocation à gauche et à droite", "Gauche : élément thématisé en tête, repris par un pronom : 'Ce roman, je l'adore.' Droite : élément rhématisé en finale, annoncé par un pronom : 'Je l'adore, ce roman.' La dislocation met en relief l'élément thème ou rhème. Fréquente en français oral, mais aussi en prose soutenue pour l'emphase."),
        ("L'incise et l'incidente", "Incise : proposition parenthétique indiquant qui parle ('dit-il') ou comment ('crut-il'). Incidente : proposition parenthétique non verbale ou brève ajoutant une précision : 'Ce phénomène — les chercheurs l'ont confirmé — est en progression.' Les tirets cadratins ou virgules signalent les deux."),
        ("Fonctions sémantiques du détachement", "Cadrage : l'élément détaché établit le cadre (temporel, spatial, conditionnel) de la proposition principale. Ex. : 'Quant aux résultats, ils sont encourageants.' Thématisation : mettre en saillance un élément en le détachant. Évaluation : ajouter un commentaire marginal."),
        ("Pièges : le dangling participle", "Participe détaché dont le référent implicite n'est pas le sujet de la principale : *'Arrivé à la gare, le train était parti.' (qui est arrivé à la gare ? le train ?) → 'Arrivé à la gare, il constata que le train était parti.' Le sujet implicite du participe détaché DOIT être le sujet de la principale."),
    ],
    "traps": [
        ("Dangling participle (participe sans référent)", "*'Traversant la rue, une voiture le frôla.' — qui traverse ? La voiture ? Le participe détaché doit avoir le même référent que le sujet de la principale : 'Traversant la rue, il faillit être renversé.'"),
        ("Apposition sans virgule", "L'apposition intercalée exige des virgules des deux côtés : 'Camus, écrivain algérien, a reçu le Nobel.' Sans les virgules, la relation syntaxique est ambiguë et l'effet stylistique est perdu."),
        ("Dislocation informelle dans un écrit soutenu", "'Ce résultat, on ne s'y attendait pas' est correct en registre courant ou oral. Dans un essai académique, préférer une formulation pleinement intégrée : 'Ce résultat était imprévu' — à moins que la dislocation soit intentionnelle pour l'emphase."),
        ("Confondre incise et incidente", "L'incise indique le locuteur ou le mode de parole ('dit-il', 'susurra-t-elle'). L'incidente est une parenthèse explicative ('les chiffres le confirment') sans lien avec le discours rapporté. Ne pas les confondre dans l'analyse stylistique."),
    ],
    "summary": [
        "Apposition : GN séparé par virgule reformulant ou précisant un autre GN.",
        "Participe détaché : équivalent d'une circonstancielle (cause, temps, concession).",
        "Participiale absolue : participe avec son propre sujet, différent du sujet principal.",
        "Adjectif détaché en tête = cadrage/cause ; en finale = résultat/description.",
        "Dangling participle : le participe détaché doit coréférer au sujet de la principale.",
    ],
    "ex1": {
        "q": "Quelle phrase contient un participe détaché grammaticalement correct ?",
        "opts": [
            "Arrivant à la gare, le train était déjà parti.",
            "Arrivant à la gare, elle constata que le train était déjà parti.",
            "Arrivant à la gare, les bagages étaient lourds.",
            "Arrivant à la gare, la pluie commença à tomber.",
        ],
        "ans": "Arrivant à la gare, elle constata que le train était déjà parti.",
        "exp": "'Elle' est le sujet de la principale et c'est bien elle qui arrive à la gare — le participe détaché est correctement référencé. Dans les autres options, le référent du participe (train, bagages, pluie) n'est pas celui qui arrive à la gare, créant un dangling participle.",
    },
    "ex2": {
        "q": "Transformez en apposition détachée : 'Parce qu'il était fatigué, il refusa l'invitation.'",
        "ans": "Fatigué, il refusa l'invitation.",
        "exp": "L'adjectif détaché en tête ('Fatigué,') exprime la cause en remplaçant la subordonnée causale. Le sujet de 'fatigué' et de 'refusa' est le même (il), ce qui rend la construction correcte. Cette compression nominale est une marque de densité stylistique au niveau C2.",
        "accept": ["fatigué, il", "adjectif détaché", "construction détachée", "épithète détachée"],
    },
    "ex3": {
        "q": "Quelle est la différence entre une apposition et un attribut du sujet ?",
        "opts": [
            "L'apposition utilise 'est' ; l'attribut n'a pas de verbe.",
            "L'attribut est lié au sujet par un verbe d'état ; l'apposition n'a pas de verbe.",
            "L'apposition est toujours placée à la fin de la phrase.",
            "L'attribut est une figure de style ; l'apposition est une faute de grammaire.",
        ],
        "ans": "L'attribut est lié au sujet par un verbe d'état ; l'apposition n'a pas de verbe.",
        "exp": "L'attribut nécessite un verbe d'état (être, devenir, paraître…) : 'Il est médecin.' L'apposition est un groupe nominal ou adjectival juxtaposé sans verbe : 'Médecin, il comprit immédiatement.' La virgule de séparation est caractéristique de l'apposition détachée.",
    },
    "game_desc": "Maîtrisez les constructions détachées et l'apposition au niveau C2",
    "items": [
        ("g5-apposition", "l'apposition", "groupe nominal séparé par virgule se référant à un autre GN pour le préciser ou reformuler", "la reformulation nominale · le GN juxtaposé · la précision sans verbe", "'Camus, écrivain algérien, a reçu le Nobel.' — apposition intercalée.", "apposition = GN séparé par virgule précisant ou reformulant un autre GN", "groupe nominal séparé par virgule précisant ou reformulant un autre GN"),
        ("g5-participe-detache", "le participe détaché", "participe (présent ou passé) séparé par virgule équivalant à une circonstancielle", "l'épithète détachée participiale · la subordonnée condensée · le participe en apposition", "'Épuisé par la marche, il s'assit.' — participe passé détaché à valeur causale.", "participe détaché = participe séparé équivalant à une circonstancielle", "participe séparé par virgule équivalant à une subordonnée circonstancielle"),
        ("g5-participiale-abs", "la participiale absolue", "participe avec son propre sujet différent du sujet principal de la phrase", "la proposition participiale · le sujet propre · la construction absolue", "'Le soleil se couchant, les oiseaux se turent.' — sujet du participe = le soleil ≠ les oiseaux.", "participiale absolue = participe avec sujet propre différent du sujet principal", "participe avec son propre sujet différent du sujet principal"),
        ("g5-dislocation", "la dislocation (gauche et droite)", "mise en relief d'un élément en le détachant en tête (gauche) ou en finale (droite) avec reprise pronominale", "la topicalisation · la mise en saillance · thème/rhème", "'Ce roman, je l'adore.' (gauche) / 'Je l'adore, ce roman.' (droite) — dislocation pour emphase.", "dislocation = élément détaché en tête ou finale avec reprise pronominale", "mise en relief par détachement en tête ou finale avec reprise pronominale"),
        ("g5-adj-detache", "l'adjectif détaché", "adjectif séparé par virgule, en tête (cadrage/cause) ou en finale (résultat/description)", "l'épithète détachée · l'adjectif prédicatif détaché · la valeur circonstancielle", "'Silencieuse, elle entra.' (cause/état) vs 'Elle entra, silencieuse.' (résultat/description).", "adjectif détaché = adjectif en apposition exprimant cause (tête) ou résultat (finale)", "adjectif séparé par virgule exprimant cause en tête ou résultat en finale"),
        ("g5-dangling", "le dangling participle", "erreur : participe détaché dont le référent implicite n'est pas le sujet de la principale", "le participe sans référent · la mauvaise coréférence · l'erreur de détachement", "*'Arrivé à la gare, le train était parti.' — 'arrivé' réfère à qui ? Faute de coréférence.", "dangling participle = participe détaché sans coréférence au sujet principal", "participe dont le référent implicite n'est pas le sujet de la principale"),
        ("g5-incise", "l'incise", "proposition parenthétique indiquant le locuteur ou le mode d'énonciation dans le discours rapporté", "dit-il · reprit-elle · la proposition intercalée", "'Je partirai demain, dit-il, sans se retourner.' — incise indiquant locuteur et mode.", "incise = proposition parenthétique indiquant locuteur ou mode dans le discours rapporté", "proposition parenthétique indiquant le locuteur ou le mode d'énonciation"),
        ("g5-incidente", "l'incidente", "proposition parenthétique ajoutant une précision explicative, sans rapport avec le discours rapporté", "la parenthèse explicative · les tirets cadratins · la précision intercalée", "Ce phénomène — les chercheurs l'ont confirmé — est en progression. (incidente entre tirets)", "incidente = parenthèse explicative intercalée sans rapport avec le discours rapporté", "proposition parenthétique ajoutant une précision explicative"),
    ],
},

# ── G06 La Modalisation Épistémique et le Conditionnel Journalistique ─────
"la-modalisation-epistemique-avancee": {
    "level": "c2",
    "section": "grammaire",
    "num": "G06",
    "short": "Modalisation épistémique",
    "title": "La Modalisation Épistémique Avancée",
    "subtitle": "Nuancer le degré de certitude en prose soutenue et en discours journalistique",
    "slides": [
        ("Rappel : modalité épistémique", "Exprime le degré de certitude du locuteur par rapport à son énoncé. À C2, il s'agit de maîtriser une gamme complète allant de la certitude absolue à la conjecture prudente, en employant les formes morphosyntaxiques et lexicales appropriées au registre."),
        ("La gradation de la certitude", "Certitude absolue : 'Il est établi que…' / 'Il est prouvé que…' + indicatif. Haute probabilité : 'Il est très probable que…' + indicatif / 'Il semble que…' + subj. ou ind. Probabilité moyenne : 'Il se peut que…' + subj. / 'Il est possible que…' + subj. Faible probabilité : 'Il est peu probable que…' + subj. Impossibilité : 'Il est exclu que…' + subj."),
        ("Le conditionnel journalistique", "Conditionnel présent ou passé pour rapporter une information non confirmée, en prenant ses distances : 'Le premier ministre aurait démissionné.' / 'L'entreprise serait en difficulté.' Signifie : 'selon nos sources, mais nous ne garantissons pas'. Obligatoire dans la presse pour les informations non vérifiées."),
        ("Distinction conditionnel journalistique / conditionnel hypothétique", "Journalistique : exprime la prise de distance épistémique sur un fait présenté. Ex. : 'Trois personnes auraient été blessées.' Hypothétique : exprime la conséquence d'une condition non réalisée. Ex. : 'Si j'avais su, je serais venu.' Contexte et sens permettent de les distinguer."),
        ("Les adverbes modalisateurs", "Certitude : 'assurément', 'indéniablement', 'sans conteste'. Probabilité : 'vraisemblablement', 'apparemment', 'sans doute', 'il est à supposer que'. Possibilité : 'peut-être', 'éventuellement', 'le cas échéant'. Doute : 'apparemment', 'prétendument', 'soi-disant'. Chacun module finement le degré de certitude."),
        ("Les verbes modalisateurs", "Affirmer vs prétendre : affirmer = engagement du locuteur ; prétendre = distanciation ('il prétend être innocent' = je n'y crois pas nécessairement). Sembler vs paraître : sembler = impression subjective ; paraître = apparence observable. Supposer, présumer, conjecturer, estimer — nuances croissantes de réserve."),
        ("La modalisation par la mise en scène du discours", "Introduire une information comme opinion d'un tiers : 'Selon X…' / 'D'après Y…' / 'Aux dires de…' / 'Il appert que…'. Ces formules signalent que la responsabilité énonciative appartient à la source, non au locuteur. Elles sont essentielles dans la presse, les rapports et les notes de synthèse."),
        ("Le subjonctif comme modalisation", "Après des expressions de doute, possibilité, nécessité : subjonctif. Ex. : 'Il est possible qu'il vienne' (doute) vs 'Il est certain qu'il vient' (certitude + indicatif). La distinction indicatif / subjonctif après certaines expressions est elle-même une marque de modalisation épistémique."),
        ("La pseudo-clivée et la focalisation épistémique", "La mise en relief par pseudo-clivée ('Ce qui est certain, c'est que…' / 'Ce qu'on ne peut nier, c'est que…') est un procédé de focalisation épistémique : elle souligne ce que le locuteur tient pour établi parmi un ensemble plus large d'incertitudes."),
        ("Risques du sur-emploi de la modalisation", "Trop de modalisateurs affaiblissent le discours : 'Il semblerait peut-être possible que…' crée une impression d'hésitation maladive. À C2, la modalisation doit être précise et intentionnelle : employer le bon degré de certitude selon ce qu'on sait réellement."),
    ],
    "traps": [
        ("Confondre conditionnel journalistique et conditionnel hypothétique", "'Le suspect aurait avoué' = conditionnel journalistique (source non confirmée). 'Il aurait avoué si on l'avait interrogé différemment' = conditionnel hypothétique (conséquence d'une condition). Le contexte (discours sur un fait d'actualité vs hypothèse) distingue les deux."),
        ("'Il semble que' + indicatif ou subjonctif ?", "Il semble que + indicatif : l'apparence est forte et le locuteur est presque convaincu. Il semble que + subjonctif : l'apparence est incertaine et le locuteur se distancie davantage. Les deux sont corrects, mais expriment des degrés de certitude différents."),
        ("Confondre 'prétendre' et 'affirmer'", "Affirmer = s'engager sur la vérité de l'énoncé. Prétendre = rapporter sans s'engager, avec une nuance de scepticisme implicite. '*Il prétend que la Terre est ronde' suggère qu'on en doute — formule incorrecte pour un fait établi."),
        ("Sur-modalisation", "Accumuler trop de modalisateurs : 'Il semblerait peut-être possible que vraisemblablement…' Choisir UN modalisateur précis et l'employer seul. La précision est la vertu cardinale du registre académique et journalistique.",),
    ],
    "summary": [
        "Certitude absolue → indicatif ; possibilité/doute → subjonctif (après expressions modales).",
        "Conditionnel journalistique : fait non confirmé rapporté avec prise de distance ('aurait démissionné').",
        "Adverbes : vraisemblablement, apparemment, prétendument, assurément — gradation de certitude.",
        "Verbes : affirmer (engagement) vs prétendre (distanciation) vs sembler (apparence).",
        "Pseudo-clivée épistémique : 'Ce qui est certain, c'est que…' pour focaliser ce qu'on sait.",
    ],
    "ex1": {
        "q": "Quelle phrase illustre correctement le conditionnel journalistique ?",
        "opts": [
            "Si le directeur avait su, il serait intervenu.",
            "Le directeur serait sur le point de démissionner, selon des sources proches du dossier.",
            "Il est certain que le directeur démissionnera demain.",
            "Le directeur aurait dû démissionner plus tôt.",
        ],
        "ans": "Le directeur serait sur le point de démissionner, selon des sources proches du dossier.",
        "exp": "Le conditionnel journalistique ('serait') + attribution à une source ('selon des sources') signalent que l'information n'est pas vérifiée. La première option est un conditionnel hypothétique (après si). La troisième est une certitude (indicatif futur). La quatrième exprime un regret ou un reproche moral.",
    },
    "ex2": {
        "q": "Quelle est la différence modale entre 'il affirme être innocent' et 'il prétend être innocent' ?",
        "ans": "'Affirmer' engage la responsabilité du locuteur et présente la proposition comme vraie. 'Prétendre' signale une prise de distance implicite : le locuteur rapporte sans garantir la vérité, avec une nuance de scepticisme.",
        "exp": "Le choix du verbe introducteur module le degré d'engagement épistémique du locuteur. 'Affirmer' = je m'engage. 'Prétendre' = je rapporte sans m'engager, parfois avec scepticisme. Ce choix est crucial dans la presse et les écrits académiques.",
        "accept": ["affirmer = engagement", "prétendre = distanciation", "prétendre = scepticisme", "affirmer s'engage", "prétendre sans garantie"],
    },
    "ex3": {
        "q": "Après quelle expression emploie-t-on l'indicatif plutôt que le subjonctif pour exprimer la certitude ?",
        "opts": [
            "Il est possible que",
            "Il est probable que",
            "Il est certain que",
            "Il est douteux que",
        ],
        "ans": "Il est certain que",
        "exp": "La certitude ('il est certain que', 'il est évident que', 'il est sûr que') gouverne l'indicatif, car le locuteur présente le fait comme établi. Les expressions de possibilité, probabilité et doute gouvernent le subjonctif, car elles marquent une distance épistémique entre le locuteur et le contenu de la proposition.",
    },
    "game_desc": "Maîtrisez la modalisation épistémique avancée au niveau C2",
    "items": [
        ("g6-certitude-ind", "certitude + indicatif", "les expressions de certitude gouvernent l'indicatif dans la subordonnée", "il est certain que + ind · il est évident que · il est prouvé que", "'Il est certain qu'il viendra' — certitude → indicatif dans la complétive.", "certitude = il est certain/prouvé que + indicatif", "les expressions de certitude gouvernent l'indicatif dans la subordonnée"),
        ("g6-cond-journa", "le conditionnel journalistique", "conditionnel employé pour rapporter une information non confirmée avec prise de distance", "aurait démissionné · serait en fuite · la précaution journalistique", "'Le premier ministre aurait démissionné' — conditionnel journalistique pour information non vérifiée.", "conditionnel journalistique = conditionnel pour info non confirmée", "conditionnel pour rapporter une information non confirmée avec prise de distance"),
        ("g6-pretendre", "prétendre (vs affirmer)", "verbe introducteur signalant une distanciation implicite du locuteur par rapport à la vérité de l'énoncé", "la distanciation · le scepticisme implicite · vs affirmer", "'Il prétend être innocent' — le locuteur ne garantit pas la vérité, contrairement à 'il affirme'.", "prétendre = rapporter avec distanciation implicite (vs affirmer = s'engager)", "verbe introducteur signalant la distanciation par rapport à la vérité"),
        ("g6-vraisemblablement", "vraisemblablement", "adverbe modalisateur indiquant une haute probabilité sans certitude absolue", "sans doute · apparemment · probablement · haute probabilité", "'Il viendra vraisemblablement demain.' — haute probabilité, sans certitude absolue.", "vraisemblablement = haute probabilité sans certitude absolue", "adverbe indiquant une haute probabilité sans certitude absolue"),
        ("g6-selon", "selon / d'après (attribution de source)", "formules signalant que la responsabilité énonciative appartient à la source citée, non au locuteur", "selon X · d'après Y · aux dires de · attribution de source", "'Selon nos sources, l'accord serait imminent.' — attribution de la responsabilité énonciative.", "selon/d'après = attribution de la responsabilité énonciative à une source", "formules attribuant la responsabilité énonciative à une source citée"),
        ("g6-sembler-subj", "il semble que + subjonctif", "expression de probabilité affaiblie gouvernant le subjonctif pour marquer la réserve du locuteur", "il semble que · il paraît que · la probabilité modérée", "'Il semble qu'il soit parti sans laisser d'adresse.' — doute modéré → subjonctif.", "il semble que + subjonctif = probabilité affaiblie avec réserve", "expression de probabilité affaiblie gouvernant le subjonctif"),
        ("g6-pseudo-clivee", "la pseudo-clivée épistémique", "construction 'Ce qui est certain, c'est que…' focalisant ce que le locuteur tient pour établi", "ce qui est sûr c'est que · focalisation épistémique · mise en relief", "'Ce qui est certain, c'est qu'il reviendra.' — pseudo-clivée focalisant la certitude.", "pseudo-clivée épistémique = ce qui est certain, c'est que + indicatif", "construction focalisant ce que le locuteur tient pour établi parmi les incertitudes"),
        ("g6-sur-modalisation", "le risque de sur-modalisation", "accumulation de modalisateurs affaiblissant le propos au lieu de le nuancer", "trop de nuances · hésitation maladive · il semblerait peut-être possible", "'Il semblerait peut-être possible que…' — sur-modalisation : un seul modalisateur suffit.", "sur-modalisation = accumulation de modalisateurs affaiblissant le propos", "accumulation de modalisateurs créant une impression d'hésitation excessive"),
    ],
},

}
