"""
francais_c1_r1.py — French C1 Writing chapters R01–R04
R01 Le Commentaire de Texte
R02 L'Essai Argumentatif
R03 L'Écriture Littéraire
R04 La Note de Synthèse et le Rapport
"""

CHAPTERS = {

# ── R01 Le Commentaire de Texte ──────────────────────────────────────────
"le-commentaire-de-texte": {
    "level": "c1",
    "section": "redaction",
    "num": "R01",
    "short": "Commentaire de texte",
    "title": "Le Commentaire de Texte",
    "subtitle": "Analyser, interpréter et commenter un texte littéraire ou argumentatif",
    "slides": [
        ("Qu'est-ce que le commentaire de texte ?", "Exercice académique qui analyse un texte pour en dégager le sens, les procédés et la portée. Il ne résume pas — il explique COMMENT le texte produit son effet et POURQUOI."),
        ("Structure en trois parties", "Introduction (accroche + situer le texte + problématique + annonce du plan) · Développement (2–3 parties thématiques, chacune avec sous-parties = observation + analyse + interprétation) · Conclusion (bilan + ouverture)."),
        ("L'introduction en détail", "Accroche : fait culturel ou citation en lien · Présentation de l'auteur, du contexte et de l'œuvre · Résumé en 2 phrases · Problématique : « En quoi ce texte… ? » · Annonce du plan en termes thématiques, jamais 'premièrement/deuxièmement'."),
        ("La problématique", "Question centrale qui oriente l'analyse. Elle doit être non-triviale : éviter « Quel est le thème ? » — préférer « Comment l'auteur construit-il une vision tragique de l'exil ? ». La problématique unit toutes vos parties."),
        ("Observation → analyse → interprétation", "Pour chaque procédé : (1) Citez le texte (guillemets + ligne) · (2) Nommez le procédé (métaphore filée, rythme ternaire, champ lexical de la mort…) · (3) Interprétez son effet sur le sens et le lecteur. Ne citez jamais sans analyser."),
        ("Procédés stylistiques au C1", "Niveau lexical : champ lexical, registre soutenu/populaire, connotations · Niveau syntaxique : phrase nominale, accumulation, chiasme, asyndète, hyperbate · Niveau phonique : allitération, assonance, rythme, coupe · Niveau rhétorique : ironie, antiphrase, prétérition, oxymore."),
        ("Repérer le registre", "Lyrique (émotion, 1re pers., exclamations) · Épique (amplification, collectif, grandeur) · Ironique (décalage entre dit et sous-entendu) · Tragique (fatalité, ton solennel) · Comique (inversion des valeurs, quiproquo). Le registre traverse tout le texte."),
        ("Citations et intégration", "Courte (<5 mots) : intégrer dans la phrase avec guillemets. Longue : isoler en bloc indenté. Toujours citer précisément (ligne). Ne jamais paraphraser quand la citation suffit. Tout passage cité DOIT être suivi d'une analyse."),
        ("Les transitions", "Entre sous-parties : « Cependant, cette violence lexicale se double d'un registre ironique… » Entre parties : bilan de la partie précédente + annonce de la suivante en une phrase. Les connecteurs logiques montrent la progression : certes… mais… or… ainsi…"),
        ("La conclusion", "Bilan : réponse synthétique à la problématique (3–4 phrases). Ouverture : mise en perspective — autre œuvre du même auteur, mouvement littéraire, questionnement contemporain. Ne pas introduire une idée nouvelle. Ne jamais conclure par 'En conclusion,'."),
        ("Pièges fréquents à éviter", "Paraphrase : résumer l'action sans analyser les procédés. Catalogue : lister des figures sans les interpréter. Hors-texte : évoquer d'autres œuvres sans ancrage dans le texte. Plan chronologique : découper le texte ligne par ligne au lieu de thématiser."),
        ("Formules utiles au commentaire", "« Ce champ lexical de X souligne… » · « La structure en chiasme met en relief… » · « L'usage du subjonctif imparfait confère au texte un ton… » · « Par cette antiphrase, l'auteur suggère… » · « La rupture syntaxique en ligne N traduit… »"),
    ],
    "traps": [
        ("Paraphraser au lieu d'analyser", "Décrire ce qui se passe (« le personnage est triste ») sans montrer COMMENT le texte le construit (« le champ lexical de l'obscurité — 'ténèbres', 'nuit', 'abîme' — traduit la détresse intérieure »)."),
        ("Faire un plan chronologique", "Découper le texte en 'premier paragraphe', 'deuxième paragraphe' : le plan doit être thématique (registre, thèmes, procédés), non linéaire."),
        ("Oublier la problématique", "Lancer des analyses disparates sans fil directeur. Chaque partie doit répondre à un aspect de la problématique et y revenir en conclusion de partie."),
        ("Citer sans analyser", "Multiplier les citations sans les commenter : « Comme le dit l'auteur : '…' » puis passer à autre chose. Toute citation exige (1) nomination du procédé et (2) interprétation de l'effet."),
    ],
    "summary": [
        "Commentaire = analyse + interprétation des procédés, jamais résumé.",
        "Structure : introduction (accroche → situer → problématique → plan) + développement thématique + conclusion (bilan → ouverture).",
        "Pour chaque procédé : citez → nommez → interprétez l'effet sur le sens.",
        "Problématique en 'En quoi…?' ou 'Comment…?' — question non-triviale qui unit toutes les parties.",
        "Pièges : paraphrase, plan chronologique, catalogue de figures, citations sans analyse.",
    ],
    "ex1": {
        "q": "Quelle est la structure correcte d'une sous-partie dans un commentaire de texte ?",
        "opts": [
            "Résumé du passage + citation + transition",
            "Observation du procédé + citation + analyse + interprétation",
            "Présentation de l'auteur + contexte historique + avis personnel",
            "Citation + traduction en langue courante + exemple personnel",
        ],
        "ans": "Observation du procédé + citation + analyse + interprétation",
        "exp": "La sous-partie suit la progression : repérer un procédé → citer le texte → nommer le procédé → interpréter son effet sur le sens. Résumer ou donner son avis personnel n'est pas du commentaire.",
    },
    "ex2": {
        "q": "Transformez cette paraphrase en analyse : « Le personnage ressent une grande tristesse. »",
        "ans": "Le champ lexical de l'obscurité ('ténèbres', 'nuit', 'abîme') construit l'état intérieur du personnage en assimilant sa tristesse à une perte de lumière.",
        "exp": "L'analyse nomme le procédé (champ lexical), cite des mots précis du texte et interprète l'effet produit (assimiler la tristesse à une perte de lumière). La paraphrase se contentait de reformuler le contenu.",
        "accept": ["champ lexical", "lexique", "vocabulaire de la tristesse", "procédé stylistique"],
    },
    "ex3": {
        "q": "Quel est le rôle de l'ouverture à la fin d'un commentaire de texte ?",
        "opts": [
            "Présenter un résumé complet du texte étudié",
            "Introduire de nouveaux arguments non développés",
            "Mettre le texte en perspective avec une question connexe ou une autre œuvre",
            "Répéter la problématique mot à mot pour la mémorisation",
        ],
        "ans": "Mettre le texte en perspective avec une question connexe ou une autre œuvre",
        "exp": "L'ouverture clôture le commentaire en élargissant la réflexion : elle peut évoquer une autre œuvre du même auteur, un mouvement littéraire ou un enjeu contemporain. Elle ne résume pas et n'introduit aucune idée nouvelle développée.",
    },
    "game_desc": "Maîtrisez les techniques du commentaire de texte",
    "items": [
        ("red-problematique", "la problématique", "question centrale qui oriente toute l'analyse du texte", "le fil directeur · la question centrale · l'angle d'analyse", "La problématique 'Comment l'auteur construit-il une vision tragique ?' guide tout le commentaire.", "problématique = question centrale qui oriente l'analyse", "question centrale qui oriente toute l'analyse"),
        ("red-observation", "observation → analyse → interprétation", "progression obligatoire pour commenter un procédé stylistique", "repérer → nommer → interpréter · la méthode OAI · l'analyse stylistique", "Observer le procédé, l'analyser puis l'interpréter : c'est la colonne vertébrale du commentaire.", "observation → analyse → interprétation = méthode pour commenter un procédé", "progression obligatoire : observer, analyser, interpréter"),
        ("red-paraphrase", "la paraphrase", "reformulation du contenu sans analyse des procédés — erreur capitale au commentaire", "le résumé · la reformulation · l'erreur du commentaire", "Écrire 'le personnage est triste' sans analyser les procédés est une paraphrase à éviter.", "paraphrase = reformulation sans analyse des procédés", "reformulation du contenu sans analyse des procédés"),
        ("red-registre", "le registre littéraire", "tonalité dominante d'un texte : lyrique, épique, ironique, tragique ou comique", "la tonalité · le ton dominant · la coloration affective", "Identifier le registre ironique permet d'analyser le décalage entre le dit et le sous-entendu.", "registre littéraire = tonalité dominante du texte", "tonalité dominante d'un texte littéraire"),
        ("red-accroche", "l'accroche", "phrase d'ouverture de l'introduction qui suscite l'intérêt du lecteur", "l'entrée en matière · le début de l'introduction · la mise en contexte", "Une accroche réussie lie un fait culturel pertinent au texte étudié.", "accroche = phrase d'ouverture qui suscite l'intérêt", "phrase d'ouverture de l'introduction qui suscite l'intérêt"),
        ("red-plan-thematique", "le plan thématique", "organisation du développement par thèmes ou procédés, non par ordre chronologique du texte", "l'organisation thématique · le plan analytique · la structure non-linéaire", "Un plan thématique regroupe les observations par thèmes à travers tout le texte.", "plan thématique = organisation par thèmes, non par ordre du texte", "organisation du développement par thèmes ou procédés"),
        ("red-ouverture", "l'ouverture", "phrase finale de la conclusion qui met le texte en perspective", "la mise en perspective · la clôture · l'élargissement", "L'ouverture peut citer une autre œuvre du même auteur ou soulever un enjeu contemporain.", "ouverture = phrase finale qui met le texte en perspective", "phrase finale de la conclusion qui met le texte en perspective"),
        ("red-champ-lexical", "le champ lexical", "ensemble de mots d'un texte appartenant à un même domaine sémantique", "le réseau lexical · le vocabulaire thématique · la constellation de mots", "Le champ lexical de la mort — 'tombeau', 'linceul', 'agonie' — construit l'atmosphère funèbre.", "champ lexical = ensemble de mots d'un même domaine sémantique", "ensemble de mots appartenant à un même domaine sémantique"),
    ],
},

# ── R02 L'Essai Argumentatif ─────────────────────────────────────────────
"l-essai-argumentatif": {
    "level": "c1",
    "section": "redaction",
    "num": "R02",
    "short": "Essai argumentatif",
    "title": "L'Essai Argumentatif",
    "subtitle": "Construire une argumentation rigoureuse et nuancée en français soutenu",
    "slides": [
        ("L'essai argumentatif : définition", "Texte qui défend une thèse sur une question débattue. Il diffère de la dissertation dialectique (thèse-antithèse-synthèse) : l'essai peut adopter un plan analytique ou critique tout en restant défensif d'une position claire."),
        ("Plans possibles de l'essai C1", "Plan dialectique : thèse → antithèse → dépassement (TAS). Plan analytique : 3 aspects ou arguments en faveur de la thèse. Plan critique : thèse reçue → limites → dépassement. Choisir selon le sujet : 'Discutez' → dialectique ; 'Dans quelle mesure' → critique."),
        ("La thèse et l'antithèse", "Thèse : position que vous défendez, annoncée clairement dès l'introduction. Antithèse : contre-arguments que vous devez présenter honnêtement avant de les réfuter ou de les nuancer. Une thèse sans antithèse est un plaidoyer, non un essai."),
        ("Structure d'un paragraphe argumentatif", "Affirmation (topic sentence) → Argument → Exemple (fait, chiffre, citation d'auteur, cas) → Explication du lien argument-thèse → Transition vers le paragraphe suivant. Acronyme : AAEX (Affirmation, Argument, EXemple, eXplication)."),
        ("Types de preuves au niveau C1", "Exemples historiques ou actuels · Citations d'autorité (philosophes, sociologues, auteurs) · Données statistiques avec source · Analogies soigneusement argumentées · Cas hypothétiques ou expériences de pensée. Hiérarchiser : les faits vérifiables > les analogies."),
        ("Concession et réfutation", "Certes, il est vrai que… / On peut admettre que… [concession] + Cependant / Néanmoins / Or / Pourtant [pivot] + réfutation ou nuance. La concession montre que vous avez considéré les contre-arguments — c'est une marque de rigueur intellectuelle."),
        ("Registre et style soutenu", "Éviter : 'je pense que', 'c'est clair', 'de nos jours', 'tout le monde sait'. Préférer : 'il apparaît que', 'force est de constater', 'il convient de souligner', 'en définitive', 'quoi qu'il en soit'. Phrases longues mais claires, subjonctif maîtrisé, vocabulaire précis."),
        ("Connecteurs logiques essentiels", "Cause : car, en effet, puisque, étant donné que · Conséquence : donc, ainsi, c'est pourquoi, de sorte que · Opposition : or, cependant, toutefois, néanmoins · Concession : certes, il est vrai que, bien que (+subj.) · Exemplification : ainsi, c'est le cas de, à titre d'exemple."),
        ("L'introduction de l'essai", "Accroche (fait actuel, citation, paradoxe) → Contexte et définition des termes du sujet → Problématique (question débattue, reformulée) → Annonce du plan. L'introduction = 10–15% du total. Ne pas prendre position dans l'introduction d'un plan dialectique."),
        ("La conclusion de l'essai", "Bilan des arguments principaux (ne pas répéter mot à mot) → Réponse nette à la problématique → Ouverture vers une question connexe ou un enjeu plus large. Éviter 'Pour conclure,'. Longueur : 5–8% du total."),
        ("Nuance et dépassement", "Le dépassement (synthèse) dépasse la simple addition thèse+antithèse : il propose une position plus fine qui intègre la complexité. Ex. : 'Si la mondialisation génère des inégalités, elle offre aussi des opportunités que les politiques peuvent orienter équitablement.'"),
        ("Formules de dépassement et de nuance", "« S'il est vrai que X, il n'en demeure pas moins que Y » · « La réalité est plus complexe : X et Y coexistent » · « Sans nier X, il convient d'insister sur Y » · « Le véritable enjeu n'est pas X mais Y » · « Il faudrait distinguer X de Y pour clarifier le débat. »"),
    ],
    "traps": [
        ("Plan 'pour et contre' sans dépassement", "Lister des arguments pro et des arguments con sans jamais prendre position ni proposer une synthèse. Un essai se conclut sur une réponse nuancée mais tranchée."),
        ("Exemples sans explication", "Citer Kant ou donner une statistique sans expliquer EN QUOI cet exemple soutient votre argument. L'exemple illustre — l'explication argumentative fait le lien avec la thèse."),
        ("Registre oral ou familier", "Employer 'je pense', 'c'est évident', 'de nos jours', 'vraiment'. Ces formules affaiblissent la crédibilité de l'essai. Utilisez le registre soutenu attendu à C1."),
        ("Ignorer les contre-arguments", "Présenter uniquement votre thèse sans accorder de place à l'antithèse : l'essai paraît naïf. La concession honnête puis bien réfutée est une marque de maturité intellectuelle."),
    ],
    "summary": [
        "Essai C1 : défendre une thèse avec rigueur, nuance et style soutenu.",
        "Structure AAEX pour chaque paragraphe : Affirmation → Argument → Exemple → eXplication.",
        "Concession + réfutation : montrer qu'on a pesé les contre-arguments avant de les nuancer.",
        "Dépassement : position finale plus fine qui intègre la complexité du sujet.",
        "Registre : bannir les formules orales ; employer les connecteurs logiques avec précision.",
    ],
    "ex1": {
        "q": "Quelle structure de paragraphe argumentatif est correcte au niveau C1 ?",
        "opts": [
            "Opinion personnelle → exemple vécu → conclusion morale",
            "Affirmation → argument → exemple → explication du lien",
            "Citation d'auteur → résumé du sujet → transition",
            "Contre-argument → concession → répétition de la thèse",
        ],
        "ans": "Affirmation → argument → exemple → explication du lien",
        "exp": "La structure AAEX (Affirmation, Argument, EXemple, eXplication) est le modèle canonique du paragraphe argumentatif C1. L'explication du lien entre l'exemple et la thèse est indispensable : l'exemple sans explication ne prouve rien.",
    },
    "ex2": {
        "q": "Réécrivez en registre soutenu : « Je pense que tout le monde sait que le changement climatique est vraiment grave. »",
        "ans": "Force est de constater que le changement climatique constitue un défi majeur, comme en témoignent les rapports successifs du GIEC.",
        "exp": "Le registre soutenu supprime 'je pense', 'tout le monde sait', 'vraiment'. Il substitue une formule impersonnelle distancée ('force est de constater'), un vocabulaire précis ('constitue un défi majeur') et appuie l'affirmation sur une source d'autorité.",
        "accept": ["force est de constater", "il apparaît que", "il convient de souligner", "comme le montrent", "les données indiquent"],
    },
    "ex3": {
        "q": "Quelle formule convient pour introduire un dépassement dans un essai dialectique ?",
        "opts": [
            "Premièrement, nous allons voir que…",
            "S'il est vrai que X, il n'en demeure pas moins que Y",
            "Pour conclure, on peut dire que…",
            "D'un côté X, de l'autre côté Y",
        ],
        "ans": "S'il est vrai que X, il n'en demeure pas moins que Y",
        "exp": "Le dépassement articule la concession ('s'il est vrai que') et la nuance ('il n'en demeure pas moins que') pour proposer une position plus fine. Les formules 'premièrement' et 'pour conclure' sont des marqueurs trop scolaires au niveau C1.",
    },
    "game_desc": "Maîtrisez les techniques de l'essai argumentatif C1",
    "items": [
        ("ess-these", "la thèse", "position que l'on défend et qu'on soutient tout au long de l'essai", "la position défendue · l'argument central · la prise de position", "La thèse doit être annoncée clairement dès l'introduction et défendue dans chaque partie.", "thèse = position centrale défendue tout au long de l'essai", "position défendue et soutenue tout au long de l'essai"),
        ("ess-antithese", "l'antithèse", "ensemble des arguments contraires à la thèse, à présenter honnêtement avant réfutation", "le contre-argument · l'argument adverse · l'opposition", "Une antithèse bien présentée puis réfutée renforce la crédibilité de l'essai.", "antithèse = arguments contraires présentés avant réfutation", "arguments contraires à présenter honnêtement avant réfutation"),
        ("ess-concession", "la concession rhétorique", "reconnaissance partielle d'un contre-argument avant de le réfuter ou le nuancer", "l'accord partiel · certes/cependant · la nuance", "Certes, la mondialisation crée des emplois ; cependant, elle fragilise aussi les travailleurs peu qualifiés.", "concession = reconnaissance partielle d'un contre-argument", "reconnaissance partielle d'un contre-argument avant réfutation"),
        ("ess-depassement", "le dépassement", "position finale plus nuancée qui intègre la thèse et l'antithèse dans une synthèse supérieure", "la synthèse · la position nuancée · l'Aufhebung", "Le dépassement n'est pas une moyenne entre thèse et antithèse mais une position plus fine.", "dépassement = synthèse qui intègre thèse et antithèse dans une position supérieure", "position finale nuancée qui intègre thèse et antithèse"),
        ("ess-AAEX", "la structure AAEX", "modèle de paragraphe : Affirmation → Argument → Exemple → eXplication", "le paragraphe argumentatif · la structure du §  · argument + exemple", "Chaque paragraphe suit AAEX : affirmer, argumenter, exemplifier, expliquer le lien.", "AAEX = Affirmation + Argument + Exemple + eXplication du lien", "structure du paragraphe : Affirmation, Argument, Exemple, eXplication"),
        ("ess-registre-soutenu", "le registre soutenu", "niveau de langue formel attendu dans les écrits académiques et littéraires C1", "le style académique · la langue soutenue · le registre littéraire", "À C1, le registre soutenu évite les formules familières et emploie les connecteurs logiques précis.", "registre soutenu = niveau de langue formel des écrits académiques", "niveau de langue formel attendu dans les écrits académiques"),
        ("ess-connecteurs", "les connecteurs logiques", "mots et locutions qui marquent les relations logiques entre les arguments", "les articulateurs logiques · les liens logiques · les transitions", "Les connecteurs 'or', 'certes', 'néanmoins', 'de sorte que' structurent la logique de l'essai.", "connecteurs logiques = mots marquant les relations entre arguments", "mots qui marquent les relations logiques entre les arguments"),
        ("ess-problematique", "la problématique de l'essai", "reformulation du sujet en une question ouverte qui révèle l'enjeu du débat", "la question centrale · le fil directeur · l'enjeu du sujet", "La problématique 'Dans quelle mesure la liberté d'expression a-t-elle des limites légitimes ?' oriente tout l'essai.", "problématique de l'essai = question ouverte qui révèle l'enjeu du débat", "reformulation du sujet en question ouverte révélant l'enjeu"),
    ],
},

# ── R03 L'Écriture Littéraire ────────────────────────────────────────────
"l-ecriture-litteraire": {
    "level": "c1",
    "section": "redaction",
    "num": "R03",
    "short": "Écriture littéraire",
    "title": "L'Écriture Littéraire",
    "subtitle": "Maîtriser la prose narrative et poétique en registre littéraire soutenu",
    "slides": [
        ("L'écriture littéraire au niveau C1", "Produire un texte de création qui maîtrise les temps du récit (passé simple, imparfait, plus-que-parfait), les registres, les figures de style et la cohérence narrative. On évalue la richesse lexicale, la maîtrise syntaxique et l'effet produit sur le lecteur."),
        ("Les temps du récit littéraire", "Passé simple : actions ponctuelles, successives, en avant-plan. Imparfait : descriptions, arrière-plan, habitudes, état mental. Plus-que-parfait : antériorité. Présent de narration : effet de vivacité (à utiliser avec cohérence). Ne jamais mélanger PS et PC dans le même récit littéraire."),
        ("Les modes de narration", "Narrateur interne (je, voix du personnage, accès subjectif) · Narrateur externe (il/elle, observateur, distance) · Omniscient (accès à tous les personnages). Le style indirect libre (SIL) permet de fusionner voix narrateur + pensée personnage sans guillemets."),
        ("Le style indirect libre", "Imparfait + conditionnel + exclamations + interrogations maintenues = voix du personnage sans guillemets. Ex. : « Il était las. À quoi bon continuer ? La route serait longue encore, et ses jambes ne répondaient plus. » C'est LA marque du récit littéraire C1."),
        ("La description littéraire", "Ancrage sensoriel (5 sens) · Point de vue focalisé (ce que VOIT le personnage) · Champs lexicaux cohérents · Métaphores filées · Personnification du décor · Rythme de la phrase (longue pour l'étendue, courte pour le choc). La description révèle un état d'âme."),
        ("Les figures de style au service du récit", "Métaphore filée : image cohérente sur plusieurs phrases. Anaphore : répétition en tête de phrase pour créer rythme et insistance. Asyndète : accumulation sans conjonctions pour un rythme haletant. Hyperbole : amplification de l'émotion. Litote : dire moins pour suggérer plus."),
        ("La progression narrative", "Situation initiale → Perturbation → Péripéties (tension montante) → Climax → Résolution (ou absence délibérée). Au C1, la perturbation peut être subtile (un regard, une lettre, un son) et la résolution peut rester ouverte pour créer une ambiguïté volontaire."),
        ("Le dialogue au style direct", "Guidons français (« ») obligatoires. Tiret cadratin (—) pour les répliques suivantes. Verbes introducteurs variés : murmura, s'exclama, rétorqua, susurra, trancha. Jamais 'dit-il' répété : alterner ou supprimer. Le dialogue révèle le caractère par le style parlé de chaque voix."),
        ("Créer une atmosphère", "Lexique cohérent avec l'état d'âme · Météo et décor symboliques (pathétique fallacy) · Rythme de la phrase (haché = urgence, ample = mélancolie) · Sons (allitérations en s = sifflement, en r = rugosité) · Temporalité (crépuscule, aube = transitions symboliques)."),
        ("La clôture du texte littéraire", "Finale ouverte (laisse le lecteur interpréter) · Finale circulaire (reprise d'un élément du début) · Finale coup de théâtre · Finale symbolique (image qui résume tout). Éviter la morale explicite : laisser le sens émerger des procédés plutôt que de l'énoncer."),
        ("Erreurs à éviter en écriture littéraire", "Registre familier ('il était trop fatigué', 'ça l'a choqué'). Adverbes-béquilles ('vraiment', 'tellement'). Répétitions lexicales sans intention stylistique. Confusion PS/imparfait. Absence de figures de style. Narration en 'je' sans intériorité psychologique réelle."),
        ("Enrichir son vocabulaire littéraire", "Verbes de mouvement précis : chanceler, se tapir, surgir, s'élancer · Adjectifs sensoriels : âcre, vaporeux, tamisé, feutré · Noms abstraits pour l'intériorité : affliction, accablement, effroi, béatitude · Verbes de perception : discerner, percevoir, flairer, deviner."),
    ],
    "traps": [
        ("Confondre passé simple et imparfait", "Écrire 'il était entré' quand on veut un geste ponctuel (→ il entra) ou 'il entra dans une pièce où la lumière tremblait' avec une confusion des plans narratifs. PS = avant-plan/action ; imparfait = arrière-plan/description/état."),
        ("Registre familier dans le récit", "Employer 'il était super fatigué', 'elle l'a regardé bizarrement', 'ça l'a choqué' dans un récit littéraire C1. Chaque mot doit être choisi : 'il était épuisé jusqu'aux os', 'elle darda sur lui un regard chargé d'étonnement'."),
        ("Description sans ancrage sensoriel", "Décrire un lieu de manière abstraite ('c'était beau et calme') sans mobiliser les 5 sens ni révéler l'état intérieur du personnage. La description littéraire fait ressentir, pas seulement voir."),
        ("Morale explicite en fin de texte", "Conclure par 'Cela nous montre que l'amitié est importante' ou 'Il comprit alors la valeur de la vie'. Laisser le sens émerger des images et des procédés — le lecteur tire lui-même la leçon."),
    ],
    "summary": [
        "Récit littéraire C1 : PS (avant-plan) + imparfait (arrière-plan) + SIL (pensées sans guillemets).",
        "Description : 5 sens + champ lexical cohérent + métaphore filée + rythme de la phrase.",
        "Figures clés : anaphore, asyndète, hyperbole, litote, métaphore filée.",
        "Dialogue : guillemets français + tiret cadratin + verbes introducteurs variés.",
        "Finale : ouverte ou symbolique — jamais de morale explicite.",
    ],
    "ex1": {
        "q": "Quel temps du récit décrit l'arrière-plan et les états mentaux dans le roman français ?",
        "opts": [
            "Le passé simple",
            "Le présent de l'indicatif",
            "L'imparfait",
            "Le conditionnel passé",
        ],
        "ans": "L'imparfait",
        "exp": "L'imparfait est le temps de l'arrière-plan narratif : descriptions, états durables, habitudes, état mental et décor. Le passé simple est réservé aux actions ponctuelles en avant-plan. Les mélanger sans intention crée des incohérences narratives.",
    },
    "ex2": {
        "q": "Transformez en style indirect libre : Il pensa : 'Je ne la reverrai jamais. Pourquoi était-il venu ?'",
        "ans": "Il ne la reverrait jamais. Pourquoi était-il venu ? La question tournait en lui, lourde et sans réponse.",
        "exp": "Le SIL supprime les guillemets et le verbe introducteur. Les pronoms passent à la 3e personne (Je → il), le futur devient conditionnel (reverrai → reverrait), mais les interrogations et exclamations sont maintenues. L'imparfait narrateur encadre.",
        "accept": ["ne la reverrait jamais", "conditionnel", "supprime les guillemets", "3e personne", "imparfait"],
    },
    "ex3": {
        "q": "Quel procédé caractérise le style indirect libre dans un roman ?",
        "opts": [
            "L'emploi de guillemets français pour toutes les pensées",
            "La fusion de la voix du narrateur et des pensées du personnage sans guillemets, à l'imparfait",
            "Le discours direct avec tiret cadratin et verbe introducteur",
            "La narration à la première personne avec guillemets internes",
        ],
        "ans": "La fusion de la voix du narrateur et des pensées du personnage sans guillemets, à l'imparfait",
        "exp": "Le style indirect libre (SIL) supprime les guillemets et le verbe introducteur. Les pensées du personnage s'expriment à l'imparfait et au conditionnel, maintenant exclamations et interrogations, mais sans marque graphique de discours direct.",
    },
    "game_desc": "Maîtrisez les techniques de l'écriture littéraire avancée",
    "items": [
        ("lit-sil", "le style indirect libre", "technique narrative fusionnant voix du narrateur et pensée du personnage sans guillemets", "SIL · la voix intérieure · la pensée narrée", "Il ne la reverrait jamais. Pourquoi était-il venu ? — voix du personnage sans guillemets.", "style indirect libre = fusion narrateur + personnage sans guillemets", "technique fusionnant voix du narrateur et pensée du personnage sans guillemets"),
        ("lit-ps", "le passé simple narratif", "temps des actions ponctuelles en avant-plan dans le récit littéraire", "le temps du roman · PS · l'action ponctuelle", "Il entra, posa son chapeau et se retourna vers elle — trois gestes au passé simple.", "passé simple = actions ponctuelles en avant-plan du récit", "temps des actions ponctuelles en avant-plan du récit"),
        ("lit-imparfait", "l'imparfait descriptif", "temps de l'arrière-plan, des descriptions et des états durables dans le récit", "le temps de la description · l'état continu · l'imparfait de durée", "La pluie tombait depuis des heures ; les rues brillaient sous les réverbères.", "imparfait = arrière-plan, descriptions et états durables", "temps de l'arrière-plan, des descriptions et états durables"),
        ("lit-ancrage-sensoriel", "l'ancrage sensoriel", "mobilisation des 5 sens dans la description pour créer une présence concrète", "les 5 sens · la description sensorielle · le détail concret", "L'odeur de résine mêlée de terre humide annonçait l'orage — ancrage olfactif et tactile.", "ancrage sensoriel = mobilisation des 5 sens dans la description", "mobilisation des 5 sens pour créer une présence concrète"),
        ("lit-metaphore-filee", "la métaphore filée", "image développée de manière cohérente sur plusieurs phrases ou tout un texte", "la métaphore étendue · l'image filée · la cohérence métaphorique", "La métaphore de la mer pour désigner la foule : flots, déferlement, houle — filée sur un paragraphe.", "métaphore filée = image développée de manière cohérente sur plusieurs phrases", "image développée cohérente sur plusieurs phrases ou un texte"),
        ("lit-asyndete", "l'asyndète narrative", "enchaînement d'éléments sans conjonction pour créer un rythme haletant", "la parataxe · l'accumulation sans liaison · le rythme brisé", "Il courut, trébucha, se releva, repartit — l'asyndète mime l'essoufflement.", "asyndète = accumulation sans conjonctions pour rythme haletant", "enchaînement sans conjonctions créant un rythme haletant"),
        ("lit-pathetic-fallacy", "le pathétique fallacy", "attribution d'un état d'âme humain au décor ou à la nature", "la nature miroir · le décor symbolique · la projection affective", "Le ciel se couvrit au moment précis où il apprit la nouvelle — pathétique fallacy.", "pathétique fallacy = décor qui reflète l'état d'âme du personnage", "attribution d'un état d'âme humain au décor ou à la nature"),
        ("lit-finale-ouverte", "la finale ouverte", "clôture du récit qui laisse l'interprétation au lecteur sans résolution explicite", "la fin ambiguë · le sens suspendu · la clôture implicite", "Terminer par une image symbolique plutôt qu'une morale explicite : la finale ouverte engage le lecteur.", "finale ouverte = clôture laissant l'interprétation au lecteur", "clôture laissant l'interprétation au lecteur sans résolution explicite"),
    ],
},

# ── R04 La Note de Synthèse et le Rapport ────────────────────────────────
"la-note-de-synthese-et-rapport": {
    "level": "c1",
    "section": "redaction",
    "num": "R04",
    "short": "Note de synthèse",
    "title": "La Note de Synthèse et le Rapport",
    "subtitle": "Produire des écrits professionnels et académiques structurés",
    "slides": [
        ("La note de synthèse : définition", "Document professionnel ou académique qui présente, de manière objective et organisée, les informations essentielles issues de plusieurs sources. Elle ne commente pas et n'exprime pas d'opinion personnelle : elle synthétise en restant neutre."),
        ("Différence note de synthèse / rapport", "Note de synthèse : présentation neutre de l'information issue de sources multiples. Rapport : analyse + recommandations destinées à un décideur. Les deux partagent un plan structuré et un registre professionnel formel, mais le rapport inclut une conclusion opérationnelle."),
        ("Structure de la note de synthèse", "En-tête (À : / De : / Objet : / Date :) → Introduction (contexte + objectif de la synthèse) → Développement thématique (plan par thèmes, non par source) → Conclusion (bilan des points clés, sans avis personnel). Jamais de 'je pense' ou 'd'après moi'."),
        ("Plan thématique obligatoire", "La note de synthèse organise l'information par THÈMES, pas source par source. Ex. : 3 sources sur le télétravail → Part. 1 : avantages organisationnels · Part. 2 : défis managériaux · Part. 3 : cadre réglementaire. Citer les sources entre parenthèses : (Doc. 1), (Doc. 2)."),
        ("Formules de renvoi aux sources", "(Selon le document 1…) / (D'après l'auteur X…) / (Le document 2 indique que…) / (Ces données sont confirmées par Doc. 3). Ne jamais citer mot à mot sans guillemets. Reformuler en paraphrase fidèle et citer la source entre parenthèses."),
        ("Le registre professionnel", "Phrases nominales fréquentes : 'Analyse de la situation / Proposition de mesures.' Formules passives : 'Il est préconisé de… / Des mesures ont été adoptées.' Verbes de rapportage neutres : souligner, indiquer, mentionner, préciser, signaler. Bannir les jugements de valeur."),
        ("Structure du rapport", "Page de garde (titre, destinataire, auteur, date) → Sommaire (si long) → Introduction → Développement (description + analyse + recommandations) → Conclusion + recommandations numérotées → Annexes (optionnel). La conclusion du rapport est prescriptive."),
        ("Les recommandations dans le rapport", "Formulées à l'infinitif ou au conditionnel : 'Il conviendrait de… / Il est recommandé de… / Nous proposons de…'. Numérotées et hiérarchisées par priorité. Chaque recommandation découle d'un problème identifié dans le développement."),
        ("La lisibilité dans les écrits professionnels", "Titres et sous-titres numérotés (1., 1.1, 1.2) · Phrases courtes et directes · Bullet points pour les listes (jamais dans une note de synthèse académique) · Paragraphes d'un seul thème · Pas d'acronymes sans définition. Clarté > style."),
        ("L'objectivité de ton", "Éviter : 'malheureusement', 'évidemment', 'il est regrettable que'. Préférer : 'or', 'néanmoins', 'il ressort de cette analyse que'. Signaler une contradiction entre sources : 'Si le document 1 affirme X, le document 3 nuance ce constat en soulignant Y.'"),
        ("La conclusion de la note", "Résumer les points clés sans en ajouter de nouveaux. Signaler les limites ou zones d'incertitude si pertinent. Ne jamais terminer par une formule littéraire. Formules : 'Cette analyse met en lumière…' / 'Les éléments rassemblés indiquent que…'"),
        ("Pièges fréquents", "Résumer source par source (plan chronologique des sources) au lieu de thématiser. Exprimer un avis personnel ('je pense que'). Copier-coller sans paraphrase. Oublier l'en-tête professionnel. Utiliser des formules littéraires dans un rapport ('au fil des pages', 'ainsi donc')."),
    ],
    "traps": [
        ("Plan source par source", "Traiter chaque document séparément ('Document 1 dit X, document 2 dit Y, document 3 dit Z') au lieu de regrouper par thème. La note de synthèse exige un plan thématique qui croise les sources."),
        ("Opinion personnelle", "Écrire 'd'après moi', 'je pense', 'il est regrettable que' dans une note de synthèse. Ces écrits professionnels exigent une neutralité totale de ton."),
        ("Copie sans paraphrase", "Recopier des phrases entières des documents sources sans guillemets : c'est du plagiat. Toujours reformuler fidèlement en propres mots + référence entre parenthèses."),
        ("Conclusion prescriptive dans la note de synthèse", "Formuler des recommandations dans une note de synthèse (elles appartiennent au rapport). La note conclut sur les points clés sans prescrire d'actions."),
    ],
    "summary": [
        "Note de synthèse : plan thématique + neutralité totale + renvois aux sources entre parenthèses.",
        "Rapport : description + analyse + recommandations numérotées et prescriptives.",
        "Registre professionnel : passives, verbes de rapportage neutres, titres numérotés.",
        "Jamais de plan source par source : toujours thématiser et croiser les documents.",
        "Objectivité : bannir les jugements de valeur et les opinions personnelles.",
    ],
    "ex1": {
        "q": "Quelle est la différence principale entre une note de synthèse et un rapport ?",
        "opts": [
            "La note est plus courte ; le rapport est plus long.",
            "La note présente des informations de manière neutre ; le rapport inclut des recommandations.",
            "La note est destinée aux étudiants ; le rapport, aux professionnels.",
            "La note utilise des tableaux ; le rapport, des paragraphes.",
        ],
        "ans": "La note présente des informations de manière neutre ; le rapport inclut des recommandations.",
        "exp": "La différence fondamentale est fonctionnelle : la note de synthèse informe objectivement à partir de sources multiples sans exprimer de position, tandis que le rapport analyse et prescrit des actions à un décideur. Les deux partagent un registre professionnel, mais le rapport a une conclusion opérationnelle.",
    },
    "ex2": {
        "q": "Réécrivez en style professionnel neutre : 'Je pense que l'entreprise devrait vraiment investir dans la formation, c'est évident.'",
        "ans": "Les éléments analysés indiquent qu'un investissement dans la formation constituerait une réponse appropriée aux déficits de compétences identifiés.",
        "exp": "Le registre professionnel supprime 'je pense', 'vraiment', 'c'est évident'. Il emploie une formule impersonnelle ('les éléments analysés indiquent'), un conditionnel prescriptif ('constituerait') et un vocabulaire technique précis ('déficits de compétences identifiés').",
        "accept": ["il conviendrait", "il ressort", "il est recommandé", "les données indiquent", "la formulation impersonnelle"],
    },
    "ex3": {
        "q": "Quelle formule convient pour signaler une contradiction entre deux documents sources ?",
        "opts": [
            "Les deux documents affirment que…",
            "Je pense que le document 1 a tort…",
            "Si le document 1 soutient X, le document 3 nuance ce constat en soulignant Y",
            "Le document 1 et le document 2 disent pareil…",
        ],
        "ans": "Si le document 1 soutient X, le document 3 nuance ce constat en soulignant Y",
        "exp": "Signaler une contradiction entre sources exige une formule neutre et contrastive. 'Si… nuance ce constat en soulignant' présente les deux positions sans jugement de valeur et utilise le registre professionnel requis.",
    },
    "game_desc": "Maîtrisez la note de synthèse et le rapport professionnel",
    "items": [
        ("syn-plan-thematique", "le plan thématique", "organisation de la note de synthèse par thèmes en croisant plusieurs sources", "le croisement des sources · l'organisation thématique · le plan analytique", "La note organise 3 documents par thèmes : avantages / défis / cadre réglementaire.", "plan thématique = organisation par thèmes en croisant les sources", "organisation par thèmes en croisant plusieurs sources"),
        ("syn-neutralite", "la neutralité de ton", "absence totale d'opinion personnelle dans une note de synthèse ou un rapport", "l'objectivité · le ton neutre · l'impartialité", "Dans une note de synthèse, on ne dit jamais 'je pense' ou 'il est regrettable que'.", "neutralité de ton = absence d'opinion personnelle", "absence totale d'opinion personnelle dans la note ou le rapport"),
        ("syn-paraphrase", "la paraphrase fidèle", "reformulation en propres mots d'un passage source, avec citation de la référence", "la reformulation · la restitution · le résumé fidèle", "Paraphrase : (Doc. 2) indique que la productivité a augmenté de 12% en télétravail.", "paraphrase fidèle = reformulation + référence entre parenthèses", "reformulation en propres mots avec citation de la référence"),
        ("syn-recommandation", "la recommandation", "prescription d'une action à un décideur, formulée à l'infinitif ou au conditionnel", "la préconisation · la proposition d'action · la mesure prescriptive", "Il est recommandé de déployer un système de mentorat pour les nouvelles recrues.", "recommandation = prescription d'action à l'infinitif ou au conditionnel", "prescription d'une action formulée à l'infinitif ou au conditionnel"),
        ("syn-en-tete", "l'en-tête professionnel", "bloc introductif d'une note formelle : À / De / Objet / Date", "le bloc en-tête · les informations de présentation · le format formel", "Toute note professionnelle commence par : À : / De : / Objet : / Date :", "en-tête = bloc À / De / Objet / Date en début de note", "bloc introductif À / De / Objet / Date d'une note formelle"),
        ("syn-renvoi", "le renvoi aux sources", "indication entre parenthèses de la source d'une information dans la note de synthèse", "la citation de source · la référence · (Doc. 1)", "Chaque information est suivie de sa source : (Document 1) ou (Auteur, page).", "renvoi aux sources = indication entre parenthèses de la source", "indication entre parenthèses de la source d'une information"),
        ("syn-objectivite", "l'objectivité rédactionnelle", "qualité d'un texte professionnel qui présente les faits sans jugement de valeur ni biais", "la neutralité · l'impartialité · le registre professionnel", "Signaler une contradiction entre sources sans la commenter : 'Si Doc. 1 affirme X, Doc. 3 nuance en soulignant Y.'", "objectivité rédactionnelle = faits sans jugement de valeur", "présentation des faits sans jugement de valeur ni biais"),
        ("syn-registre-professionnel", "le registre professionnel", "niveau de langue formel caractérisé par les passives, les nominalisations et le vocabulaire technique", "le style professionnel · la langue formelle · l'écriture de travail", "Le registre professionnel emploie 'il est préconisé', 'des mesures ont été adoptées', 'il ressort de cette analyse'.", "registre professionnel = passives + nominalisations + vocabulaire technique", "niveau de langue formel avec passives, nominalisations et vocabulaire technique"),
    ],
},

}
