"""
francais/b1 — Vocabulaire B1 — batch 2 (V05–V08)
"""

CHAPTERS = {

"la-technologie": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V05",
    "short": "La Technologie",
    "title": "La Technologie",
    "subtitle": "Internet, numérique, innovations et intelligence artificielle",
    "words": [
        {"word": "la technologie", "ipa": "/la tɛk.nɔ.lɔ.ʒi/", "def": "ensemble des techniques et outils développés par la science", "ex": "La technologie transforme notre façon de vivre."},
        {"word": "le numérique", "ipa": "/lə ny.me.ʁik/", "def": "qui fonctionne avec des données codées en chiffres (bits)", "ex": "La transformation numérique touche toutes les entreprises."},
        {"word": "l'intelligence artificielle", "ipa": "/lɛ̃.tɛ.li.ʒɑ̃s aʁ.ti.fi.sjɛl/", "def": "simulation de l'intelligence humaine par des machines", "ex": "L'intelligence artificielle révolutionne la médecine."},
        {"word": "le réseau social", "ipa": "/lə ʁe.zo sɔ.sjal/", "def": "plateforme en ligne permettant de partager du contenu avec d'autres", "ex": "Elle passe trop de temps sur les réseaux sociaux."},
        {"word": "la cybersécurité", "ipa": "/la si.bɛʁ.se.ky.ʁi.te/", "def": "protection des systèmes informatiques contre les attaques", "ex": "La cybersécurité est cruciale pour les entreprises."},
        {"word": "le logiciel", "ipa": "/lə lɔ.ʒi.sjɛl/", "def": "programme informatique exécuté sur un ordinateur", "ex": "Ce logiciel de traduction est très précis."},
        {"word": "la base de données", "ipa": "/la baz də don.ne/", "def": "ensemble structuré d'informations stockées sur un ordinateur", "ex": "La base de données client est très large."},
        {"word": "le cloud", "ipa": "/lə klawd/", "def": "stockage et traitement des données sur Internet", "ex": "Mes fichiers sont sauvegardés dans le cloud."},
        {"word": "l'algorithme", "ipa": "/la.lgɔ.ʁitm/", "def": "suite d'instructions permettant de résoudre un problème", "ex": "L'algorithme de YouTube choisit les vidéos recommandées."},
        {"word": "l'application", "ipa": "/la.pli.ka.sjɔ̃/", "def": "logiciel conçu pour un usage spécifique sur mobile ou ordinateur", "ex": "J'utilise une application pour apprendre le français."},
        {"word": "le pirate informatique", "ipa": "/lə pi.ʁat ɛ̃.fɔʁ.ma.tik/", "def": "personne qui s'introduit illégalement dans des systèmes informatiques", "ex": "Un pirate informatique a volé des données."},
        {"word": "la vie privée", "ipa": "/la vi pʁi.ve/", "def": "droit à garder certaines informations personnelles confidentielles", "ex": "Les réseaux sociaux menacent la vie privée."},
        {"word": "le streaming", "ipa": "/lə stʁi.miŋ/", "def": "lecture de contenu audio ou vidéo en ligne sans téléchargement", "ex": "Je regarde des films en streaming."},
        {"word": "l'innovation", "ipa": "/li.nɔ.va.sjɔ̃/", "def": "introduction d'une nouveauté technique ou commerciale", "ex": "L'innovation est au cœur de la croissance."},
        {"word": "les données personnelles", "ipa": "/le dɔ.ne pɛʁ.sɔ.nɛl/", "def": "informations relatives à une personne identifiable", "ex": "Les données personnelles sont protégées par la loi."},
    ],
    "game_desc": "La Technologie — vocabulaire numérique et informatique",
    "items": [
        ("tech-numerique", "le numérique", "technologie basée sur des données codées en chiffres", "données en format digital", "La révolution numérique est mondiale.", "numérique = technologie digitale", "données en format digital"),
        ("tech-ia", "l'intelligence artificielle", "simulation de l'intelligence humaine par des machines", "machine qui pense comme un humain", "L'IA analyse des millions de données.", "IA = machine qui simule l'intelligence", "machine qui pense comme un humain"),
        ("tech-reseau", "le réseau social", "plateforme en ligne pour partager et communiquer", "site pour partager avec des amis en ligne", "Je suis sur plusieurs réseaux sociaux.", "réseau social = partager en ligne", "site pour partager avec des amis en ligne"),
        ("tech-cybersecurite", "la cybersécurité", "protection contre les attaques informatiques", "défense des systèmes informatiques", "La cybersécurité est une priorité.", "cybersécurité = défense informatique", "défense des systèmes informatiques"),
        ("tech-algorithme", "l'algorithme", "suite d'instructions pour résoudre un problème automatiquement", "recette logique pour un ordinateur", "L'algorithme trie les résultats.", "algorithme = instructions automatiques", "recette logique pour un ordinateur"),
        ("tech-vie-privee", "la vie privée", "droit à la confidentialité des informations personnelles", "droit de garder des infos secrètes", "Protégez votre vie privée en ligne.", "vie privée = confidentialité personnelle", "droit de garder des infos secrètes"),
        ("tech-innovation", "l'innovation", "introduction d'une nouveauté technique ou commerciale", "idée nouvelle qui améliore quelque chose", "L'innovation drive l'économie.", "innovation = nouveauté qui améliore", "idée nouvelle qui améliore quelque chose"),
        ("tech-donnees", "les données personnelles", "informations liées à une personne identifiable", "infos privées sur une personne", "Les données personnelles valent de l'or.", "données personnelles = infos privées", "infos privées sur une personne"),
    ],
},

"la-sante-et-le-bien-etre": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V06",
    "short": "La Santé et le Bien-être",
    "title": "La Santé et le Bien-être",
    "subtitle": "Médecine, mode de vie et santé mentale",
    "words": [
        {"word": "la santé mentale", "ipa": "/la sɑ̃.te mɑ̃.tal/", "def": "état de bien-être psychologique et émotionnel d'une personne", "ex": "La santé mentale est aussi importante que la santé physique."},
        {"word": "le stress", "ipa": "/lə stʁɛs/", "def": "état de tension causé par des pressions ou des difficultés", "ex": "Le stress au travail peut causer des maladies."},
        {"word": "le bien-être", "ipa": "/lə bjɛ̃.nɛtʁ/", "def": "état de satisfaction physique et psychologique", "ex": "Le yoga contribue à mon bien-être."},
        {"word": "la prévention", "ipa": "/la pʁe.vɑ̃.sjɔ̃/", "def": "ensemble de mesures visant à éviter une maladie", "ex": "La prévention est plus efficace que le traitement."},
        {"word": "le traitement", "ipa": "/lə tʁɛt.mɑ̃/", "def": "ensemble des soins médicaux pour guérir une maladie", "ex": "Ce traitement dure six semaines."},
        {"word": "l'alimentation", "ipa": "/la.li.mɑ̃.ta.sjɔ̃/", "def": "manière de se nourrir; les aliments consommés", "ex": "Une alimentation équilibrée est essentielle."},
        {"word": "chronique", "ipa": "/kʁɔ.nik/", "def": "qui dure longtemps ou qui revient régulièrement", "ex": "Il souffre d'une maladie chronique."},
        {"word": "l'épidémie", "ipa": "/le.pi.de.mi/", "def": "propagation rapide d'une maladie dans une population", "ex": "L'épidémie de grippe touche des milliers."},
        {"word": "la dépression", "ipa": "/la de.pʁɛ.sjɔ̃/", "def": "trouble mental caractérisé par une tristesse profonde et prolongée", "ex": "La dépression est une maladie sérieuse."},
        {"word": "l'activité physique", "ipa": "/lak.ti.vi.te fi.zik/", "def": "mouvement corporel qui dépense de l'énergie", "ex": "L'activité physique régulière protège la santé."},
        {"word": "le diagnostic", "ipa": "/lə dja.ɡnɔs.tik/", "def": "identification d'une maladie par un médecin", "ex": "Le diagnostic a été confirmé par des analyses."},
        {"word": "la vaccination", "ipa": "/la vak.si.na.sjɔ̃/", "def": "injection d'un vaccin pour protéger contre une maladie", "ex": "La vaccination a éliminé la polio."},
        {"word": "l'obésité", "ipa": "/lɔ.be.zi.te/", "def": "excès de poids important pouvant nuire à la santé", "ex": "L'obésité est un problème de santé publique."},
        {"word": "le système immunitaire", "ipa": "/lə sis.tɛm i.my.ni.tɛʁ/", "def": "ensemble des mécanismes de défense naturels du corps", "ex": "Le sport renforce le système immunitaire."},
        {"word": "la thérapie", "ipa": "/la te.ʁa.pi/", "def": "traitement d'une maladie physique ou mentale", "ex": "Elle suit une thérapie pour gérer son anxiété."},
    ],
    "game_desc": "La Santé et le Bien-être — vocabulaire médical et psychologique",
    "items": [
        ("sante-mentale", "la santé mentale", "état de bien-être psychologique et émotionnel", "bien-être de l'esprit", "La santé mentale mérite attention.", "santé mentale = bien-être psychologique", "bien-être de l'esprit"),
        ("sante-stress", "le stress", "tension causée par des pressions ou difficultés", "pression qui fatigue mentalement", "Le stress chronique nuit à la santé.", "stress = tension mentale et physique", "pression qui fatigue mentalement"),
        ("sante-prevention", "la prévention", "mesures pour éviter une maladie avant qu'elle survienne", "agir avant la maladie", "La prévention coûte moins cher.", "prévention = éviter la maladie avant", "agir avant la maladie"),
        ("sante-traitement", "le traitement", "soins médicaux pour guérir une maladie", "soins pour guérir", "Ce traitement est efficace.", "traitement = soins médicaux", "soins pour guérir"),
        ("sante-chronique", "chronique", "qui dure longtemps ou revient régulièrement", "persistant, de longue durée", "Il souffre d'une maladie chronique.", "chronique = qui dure longtemps", "persistant, de longue durée"),
        ("sante-epidemie", "l'épidémie", "propagation rapide d'une maladie dans une population", "maladie qui se répand vite", "L'épidémie a touché toute la région.", "épidémie = maladie qui se propage", "maladie qui se répand vite"),
        ("sante-vaccination", "la vaccination", "injection d'un vaccin pour prévenir une maladie", "vaccin pour se protéger", "La vaccination sauve des millions.", "vaccination = vaccin pour prévenir", "vaccin pour se protéger"),
        ("sante-therapie", "la thérapie", "traitement d'une maladie physique ou mentale", "soin pour un problème médical ou psych.", "La thérapie l'aide à gérer son anxiété.", "thérapie = traitement médical ou psy", "soin pour un problème médical ou psych."),
    ],
},

"l-education": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V07",
    "short": "L'Éducation",
    "title": "L'Éducation",
    "subtitle": "École, université, apprentissage et formation",
    "words": [
        {"word": "l'enseignement", "ipa": "/lɑ̃.sɛɲ.mɑ̃/", "def": "transmission du savoir par un professeur à des élèves", "ex": "L'enseignement des langues est essentiel."},
        {"word": "l'apprentissage", "ipa": "/la.pʁɑ̃.ti.saʒ/", "def": "processus d'acquisition de nouvelles connaissances ou compétences", "ex": "L'apprentissage en ligne est en plein essor."},
        {"word": "la formation", "ipa": "/la fɔʁ.ma.sjɔ̃/", "def": "programme d'enseignement pour acquérir des compétences professionnelles", "ex": "Il suit une formation en informatique."},
        {"word": "le diplôme", "ipa": "/lə di.plom/", "def": "titre officiel attestant des études ou une qualification", "ex": "Elle a obtenu son diplôme de médecine."},
        {"word": "la bourse", "ipa": "/la buʁs/", "def": "aide financière accordée à un étudiant pour ses études", "ex": "Il a reçu une bourse pour étudier à l'étranger."},
        {"word": "l'orientation", "ipa": "/lɔ.ʁjɑ̃.ta.sjɔ̃/", "def": "choix de la filière ou du domaine d'études pour un élève", "ex": "L'orientation professionnelle l'a aidée."},
        {"word": "la compétence", "ipa": "/la kɔ̃.pe.tɑ̃s/", "def": "capacité à réaliser une tâche avec efficacité", "ex": "Il a les compétences nécessaires pour ce poste."},
        {"word": "le cursus", "ipa": "/lə kyʁ.sys/", "def": "parcours d'études suivi dans un établissement", "ex": "Son cursus universitaire dure cinq ans."},
        {"word": "la réussite", "ipa": "/la ʁe.y.sit/", "def": "fait d'obtenir de bons résultats ou d'atteindre un objectif", "ex": "La réussite scolaire demande du travail."},
        {"word": "l'échec", "ipa": "/le.ʃɛk/", "def": "fait de ne pas réussir, de ne pas atteindre un objectif", "ex": "L'échec à l'examen l'a beaucoup déçu."},
        {"word": "le concours", "ipa": "/lə kɔ̃.kuʁ/", "def": "examen sélectif avec un nombre limité de places", "ex": "Il a réussi le concours d'entrée aux grandes écoles."},
        {"word": "la recherche", "ipa": "/la ʁə.ʃɛʁʃ/", "def": "travail intellectuel visant à produire de nouvelles connaissances", "ex": "Elle fait de la recherche en biologie."},
        {"word": "le stage", "ipa": "/lə staʒ/", "def": "période de travail en entreprise pour acquérir de l'expérience", "ex": "Il fait un stage dans une grande entreprise."},
        {"word": "l'alphabétisation", "ipa": "/lal.fa.be.ti.za.sjɔ̃/", "def": "apprentissage de la lecture et de l'écriture pour des adultes", "ex": "Les cours d'alphabétisation sont gratuits."},
        {"word": "l'autonomie", "ipa": "/lo.tɔ.nɔ.mi/", "def": "capacité à prendre des décisions et agir seul", "ex": "L'autonomie est une qualité appréciée des employeurs."},
    ],
    "game_desc": "L'Éducation — apprentissage et parcours scolaire",
    "items": [
        ("edu-enseignement", "l'enseignement", "transmission du savoir par un professeur", "apprendre aux élèves", "L'enseignement public est gratuit.", "enseignement = enseigner aux élèves", "apprendre aux élèves"),
        ("edu-apprentissage", "l'apprentissage", "processus d'acquisition de nouvelles connaissances", "apprendre quelque chose de nouveau", "L'apprentissage d'une langue prend du temps.", "apprentissage = processus d'apprendre", "apprendre quelque chose de nouveau"),
        ("edu-diplome", "le diplôme", "titre officiel attestant des études réussies", "titre à la fin des études", "Elle a son diplôme en poche.", "diplôme = titre de fin d'études", "titre à la fin des études"),
        ("edu-bourse", "la bourse", "aide financière pour les études", "argent pour payer les études", "La bourse couvre les frais d'inscription.", "bourse = aide financière pour étudier", "argent pour payer les études"),
        ("edu-competence", "la compétence", "capacité à effectuer une tâche efficacement", "savoir-faire dans un domaine", "Les compétences numériques sont requises.", "compétence = capacité à faire qqch bien", "savoir-faire dans un domaine"),
        ("edu-reussite", "la réussite", "fait d'atteindre ses objectifs avec succès", "succès dans les études ou le travail", "La réussite demande de la persévérance.", "réussite = succès", "succès dans les études ou le travail"),
        ("edu-concours", "le concours", "examen compétitif avec nombre limité de places", "examen très sélectif", "Le concours est difficile.", "concours = examen sélectif", "examen très sélectif"),
        ("edu-stage", "le stage", "période de travail en entreprise pour apprendre", "expérience professionnelle temporaire", "Son stage dure trois mois.", "stage = expérience en entreprise", "expérience professionnelle temporaire"),
    ],
},

"les-medias-et-la-communication": {
    "level": "b1",
    "section": "vocabulaire",
    "num": "V08",
    "short": "Les Médias et la Communication",
    "title": "Les Médias et la Communication",
    "subtitle": "Presse, télévision, liberté d'expression et désinformation",
    "words": [
        {"word": "les médias", "ipa": "/le me.dja/", "def": "moyens de communication de masse (presse, télé, internet)", "ex": "Les médias influencent l'opinion publique."},
        {"word": "la presse", "ipa": "/la pʁɛs/", "def": "ensemble des journaux et magazines imprimés ou en ligne", "ex": "Elle lit la presse tous les matins."},
        {"word": "le journaliste", "ipa": "/lə ʒuʁ.na.list/", "def": "professionnel qui collecte et diffuse des informations", "ex": "Le journaliste a enquêté pendant six mois."},
        {"word": "l'information", "ipa": "/lɛ̃.fɔʁ.ma.sjɔ̃/", "def": "nouvelle ou renseignement transmis au public", "ex": "L'information circule très rapidement."},
        {"word": "la liberté d'expression", "ipa": "/la li.bɛʁ.te dɛks.pʁɛ.sjɔ̃/", "def": "droit de s'exprimer librement sans censure", "ex": "La liberté d'expression est fondamentale."},
        {"word": "la désinformation", "ipa": "/la de.zɛ̃.fɔʁ.ma.sjɔ̃/", "def": "diffusion intentionnelle de fausses informations", "ex": "La désinformation est dangereuse pour la démocratie."},
        {"word": "les fake news", "ipa": "/le fɛk njuz/", "def": "fausses informations diffusées comme si elles étaient vraies", "ex": "Les fake news se répandent rapidement sur les réseaux."},
        {"word": "l'opinion publique", "ipa": "/lɔ.pi.njɔ̃ py.blik/", "def": "ensemble des opinions partagées par la majorité d'une société", "ex": "L'opinion publique est favorable à cette mesure."},
        {"word": "le reportage", "ipa": "/lə ʁə.pɔʁ.taʒ/", "def": "enquête journalistique sur un événement ou un sujet", "ex": "Ce reportage sur la pauvreté est bouleversant."},
        {"word": "la censure", "ipa": "/la sɑ̃.syʁ/", "def": "contrôle et suppression de certaines informations par une autorité", "ex": "La censure limite la liberté de la presse."},
        {"word": "l'audience", "ipa": "/lo.djɑ̃s/", "def": "nombre de personnes qui regardent ou écoutent un média", "ex": "L'audience de cette émission est en hausse."},
        {"word": "la publicité", "ipa": "/la py.bli.si.te/", "def": "message commercial destiné à promouvoir un produit", "ex": "La publicité télévisée coûte très cher."},
        {"word": "le débat", "ipa": "/lə de.ba/", "def": "discussion organisée entre plusieurs personnes sur un sujet", "ex": "Le débat politique a été très animé."},
        {"word": "le fact-checking", "ipa": "/lə fakt tʃɛ.kiŋ/", "def": "vérification de l'exactitude des informations publiées", "ex": "Le fact-checking est crucial pour la démocratie."},
        {"word": "le podcast", "ipa": "/lə pɔd.kast/", "def": "émission audio disponible en ligne à écouter à la demande", "ex": "J'écoute un podcast d'actualité chaque matin."},
    ],
    "game_desc": "Les Médias — vocabulaire de la presse et de la communication",
    "items": [
        ("med-presse", "la presse", "ensemble des journaux et magazines", "journaux et magazines", "La presse écrite est en déclin.", "presse = journaux et magazines", "journaux et magazines"),
        ("med-journaliste", "le journaliste", "professionnel qui collecte et diffuse des informations", "personne qui rapporte les nouvelles", "Le journaliste enquête sur cette affaire.", "journaliste = rapporte les nouvelles", "personne qui rapporte les nouvelles"),
        ("med-desinformation", "la désinformation", "diffusion intentionnelle de fausses informations", "mensonges diffusés comme des vérités", "La désinformation divise la société.", "désinformation = fausses infos voulues", "mensonges diffusés comme des vérités"),
        ("med-liberte", "la liberté d'expression", "droit de s'exprimer sans censure", "pouvoir dire ce qu'on pense", "La liberté d'expression est protégée.", "liberté d'expression = parler librement", "pouvoir dire ce qu'on pense"),
        ("med-opinion", "l'opinion publique", "ensemble des opinions de la majorité d'une société", "ce que les gens pensent en général", "L'opinion publique a changé.", "opinion publique = avis général de la société", "ce que les gens pensent en général"),
        ("med-censure", "la censure", "suppression de certaines informations par une autorité", "interdire des informations", "La censure tue la liberté de la presse.", "censure = interdire des infos", "interdire des informations"),
        ("med-fake-news", "les fake news", "fausses informations présentées comme vraies", "informations fausses et trompeuses", "Vérifiez les sources avant de partager.", "fake news = fausses infos", "informations fausses et trompeuses"),
        ("med-fact-checking", "le fact-checking", "vérification de l'exactitude des informations", "vérifier si une info est vraie", "Le fact-checking révèle les mensonges.", "fact-checking = vérifier les infos", "vérifier si une info est vraie"),
    ],
},

}
