"""francais C1 vocabulaire — V01–V04"""

CHAPTERS = {
    "la-rhetorique": {
        "level": "c1",
        "section": "vocabulaire",
        "num": "V01",
        "short": "La Rhétorique",
        "title": "La Rhétorique",
        "subtitle": "Vocab — argumentation, figures et persuasion",
        "game_desc": "Maîtrisez le vocabulaire de la rhétorique et de l'argumentation",
        "words": [
            {"word": "le syllogisme", "ipa": "/si.lɔ.ʒism/", "def": "raisonnement déductif à trois propositions menant à une conclusion", "ex": "Tous les hommes sont mortels ; Socrate est un homme ; donc Socrate est mortel — c'est un syllogisme."},
            {"word": "l'enthymème (m)", "ipa": "/ɑ̃.ti.mɛm/", "def": "syllogisme dont une prémisse est implicite", "ex": "Il est courageux, donc il réussira — enthymème omettant la prémisse 'les courageux réussissent'."},
            {"word": "la concession rhétorique", "ipa": "/kɔ̃.sɛ.sjɔ̃ʁe.tɔ.ʁik/", "def": "accord apparent avec l'adversaire pour mieux réfuter ensuite", "ex": "Certes, cet argument a du mérite, mais il omet un point essentiel — concession rhétorique."},
            {"word": "l'ad hominem (m)", "ipa": "/ad ɔ.mi.nɛm/", "def": "argument qui attaque la personne plutôt que l'idée", "ex": "Lui faire confiance serait absurde vu son passé — c'est un argument ad hominem."},
            {"word": "la pétition de principe", "ipa": "/pe.ti.sjɔ̃ də pʁɛ̃.sip/", "def": "raisonnement circulaire qui suppose dans la prémisse ce qu'il faudrait démontrer", "ex": "La Bible est vraie car c'est la parole de Dieu, et Dieu existe car la Bible le dit — pétition de principe."},
            {"word": "l'analogie (f)", "ipa": "/a.na.lɔ.ʒi/", "def": "comparaison entre deux situations similaires pour étayer un argument", "ex": "Comme le corps a besoin de sport, l'esprit a besoin de lecture — analogie argumentative."},
            {"word": "la réfutation", "ipa": "/ʁe.fy.ta.sjɔ̃/", "def": "démonstration de la fausseté ou de la faiblesse d'un argument adverse", "ex": "La réfutation de sa thèse a convaincu l'auditoire."},
            {"word": "l'épichérème (m)", "ipa": "/e.pi.ke.ʁɛm/", "def": "syllogisme dont les prémisses sont accompagnées d'une justification", "ex": "L'épichérème renforce le syllogisme en justifiant chaque prémisse."},
            {"word": "le lieu commun", "ipa": "/ljø kɔ.mɛ̃/", "def": "argument ou idée vague et généralement admis, utilisé dans les discours", "ex": "Il a eu recours à des lieux communs sur la solidarité sans arguments concrets."},
            {"word": "l'ethos (m)", "ipa": "/e.tɔs/", "def": "crédibilité et autorité morale de l'orateur qui renforce son argumentation", "ex": "Son ethos de médecin renforçait la portée de son discours sur la santé."},
            {"word": "le pathos (m)", "ipa": "/pa.tɔs/", "def": "appel aux émotions du public pour le convaincre", "ex": "Son discours jouait sur le pathos en évoquant les victimes de la catastrophe."},
            {"word": "le logos (m)", "ipa": "/lɔ.gɔs/", "def": "argumentation rationnelle et logique s'appuyant sur des preuves", "ex": "Le logos de son exposé était irréfutable, fondé sur des statistiques solides."},
            {"word": "la parabase", "ipa": "/pa.ʁa.baz/", "def": "digression où l'auteur ou l'orateur s'adresse directement au public", "ex": "Dans son discours, il fit une parabase pour interpeller directement les élus."},
            {"word": "l'apostrophe (f)", "ipa": "/a.pɔs.tʁɔf/", "def": "figure par laquelle on s'adresse directement à une personne ou à une entité absente", "ex": "'Ô liberté, que de crimes on commet en ton nom !' — apostrophe rhétorique."},
            {"word": "la dialectique argumentative", "ipa": "/dja.lɛk.tik aʁ.ɡy.mɑ̃.ta.tiv/", "def": "méthode consistant à confronter des thèses opposées pour dégager une vérité", "ex": "La dialectique argumentative du débat a permis de clarifier les enjeux."},
        ],
        "items": [
            ("c1v01-syllogisme", "le syllogisme", "raisonnement déductif en trois propositions", "prémisse · conclusion · déduction", "Tous les hommes sont mortels ; Socrate est un homme ; donc il est mortel — syllogisme.", "syllogisme = raisonnement en trois propositions", "raisonnement déductif à trois propositions"),
            ("c1v01-ethos", "l'ethos", "crédibilité de l'orateur renforçant son argumentation", "autorité · crédibilité · orateur", "Son ethos de spécialiste a renforcé la portée de ses arguments.", "ethos = crédibilité de l'orateur", "crédibilité et autorité morale de l'orateur"),
            ("c1v01-pathos", "le pathos", "appel aux émotions du public", "émotion · public · persuasion", "Son discours jouait sur le pathos en évoquant les souffrances des victimes.", "pathos = appel aux émotions", "appel aux émotions du public pour convaincre"),
            ("c1v01-logos", "le logos", "argumentation rationnelle fondée sur des preuves", "logique · preuves · raison", "Le logos de sa démonstration s'appuyait sur des données vérifiables.", "logos = argumentation rationnelle", "argumentation rationnelle et logique"),
            ("c1v01-refutation", "la réfutation", "démonstration de la fausseté d'un argument adverse", "contrer · répondre · invalider", "La réfutation de l'argument adverse a retourné l'opinion du jury.", "réfutation = invalider un argument adverse", "démonstration de la fausseté d'un argument"),
            ("c1v01-concession", "la concession rhétorique", "accord apparent pour mieux réfuter ensuite", "certes · mais · nuance", "Certes, cet argument est recevable, mais il passe sous silence un fait capital.", "concession rhet. = accord apparent + réfutation", "accord apparent avec l'adversaire pour mieux réfuter"),
            ("c1v01-analogie", "l'analogie", "comparaison entre deux situations similaires pour argumenter", "comparaison · similaire · étayer", "L'analogie entre le corps et la société est un classique de la rhétorique.", "analogie = comparaison argumentative", "comparaison entre deux situations pour étayer un argument"),
            ("c1v01-ad-hominem", "l'ad hominem", "attaque de la personne plutôt que de l'idée", "sophisme · personne · erreur", "L'argument ad hominem est un sophisme qui évite de répondre sur le fond.", "ad hominem = attaquer la personne, pas l'idée", "argument attaquant la personne plutôt que l'argument"),
        ],
    },

    "la-linguistique": {
        "level": "c1",
        "section": "vocabulaire",
        "num": "V02",
        "short": "La Linguistique",
        "title": "La Linguistique",
        "subtitle": "Vocab — langue, discours et analyse linguistique",
        "game_desc": "Maîtrisez le vocabulaire de la linguistique",
        "words": [
            {"word": "le signifiant", "ipa": "/si.ɲi.fjɑ̃/", "def": "image acoustique ou graphique du signe linguistique", "ex": "Le signifiant du mot 'arbre' est la séquence sonore /aʁbʁ/."},
            {"word": "le signifié", "ipa": "/si.ɲi.fje/", "def": "concept ou contenu mental associé au signifiant", "ex": "Le signifié de 'arbre' est le concept mental de végétal à tronc et branches."},
            {"word": "la pragmatique", "ipa": "/pʁag.ma.tik/", "def": "étude du sens des énoncés en contexte, au-delà de leur sens littéral", "ex": "La pragmatique explique pourquoi 'Peux-tu me passer le sel ?' est une requête et non une question."},
            {"word": "l'acte de langage (m)", "ipa": "/akt də lɑ̃.ɡaʒ/", "def": "action accomplie par la parole (promettre, ordonner, féliciter)", "ex": "Austin a théorisé les actes de langage comme des actions sociales."},
            {"word": "la deixis", "ipa": "/dɛk.sis/", "def": "ensemble des éléments linguistiques dont le sens dépend du contexte d'énonciation", "ex": "Ici, maintenant, je — exemples de deixis spatiale, temporelle et personnelle."},
            {"word": "la présupposition", "ipa": "/pʁe.sy.po.zi.sjɔ̃/", "def": "information implicitement admise dans un énoncé sans être affirmée", "ex": "'Il a cessé de fumer' présuppose qu'il fumait avant."},
            {"word": "le discours", "ipa": "/dis.kuʁ/", "def": "ensemble d'énoncés produits dans une situation de communication", "ex": "L'analyse du discours étudie comment le contexte influence le sens des énoncés."},
            {"word": "la polysémie", "ipa": "/pɔ.li.se.mi/", "def": "propriété d'un mot d'avoir plusieurs sens liés", "ex": "'Vol' a plusieurs sens liés : vol d'avion, vol de document — polysémie."},
            {"word": "l'homonymie (f)", "ipa": "/ɔ.mɔ.ni.mi/", "def": "identité formelle entre mots de sens complètement différents", "ex": "'Voler' (dans les airs) et 'voler' (dérober) sont deux mots homonymes distincts."},
            {"word": "la syntagme (m)", "ipa": "/sɛ̃.taɡm/", "def": "groupe de mots formant une unité syntaxique (nominal, verbal, etc.)", "ex": "Dans 'le chat noir', le syntagme nominal est 'le chat noir'."},
            {"word": "le morphème", "ipa": "/mɔʁ.fɛm/", "def": "plus petite unité de sens dans une langue", "ex": "'Inacceptable' contient trois morphèmes : in- + accept- + -able."},
            {"word": "l'ellipse linguistique (f)", "ipa": "/e.lips lɛ̃.ɡɥis.tik/", "def": "omission d'un ou plusieurs éléments récupérables dans le contexte", "ex": "A : 'Tu viens ?' B : 'Non, [je ne viens pas].' — ellipse linguistique."},
            {"word": "la cohérence textuelle", "ipa": "/ko.e.ʁɑ̃s tɛks.tɥɛl/", "def": "logique d'ensemble assurant la bonne compréhension d'un texte", "ex": "La cohérence textuelle repose sur la progression thématique et les connecteurs logiques."},
            {"word": "l'énonciation (f)", "ipa": "/e.nɔ̃.sja.sjɔ̃/", "def": "acte de production d'un énoncé par un énonciateur dans une situation donnée", "ex": "L'étude de l'énonciation analyse qui parle, à qui, où et quand."},
            {"word": "la valence verbale", "ipa": "/va.lɑ̃s vɛʁ.bal/", "def": "nombre d'arguments qu'un verbe requiert ou admet", "ex": "'Donner' a une valence de 3 (sujet, COD, COI) ; 'pleuvoir' a une valence de 0."},
        ],
        "items": [
            ("c1v02-signifiant", "le signifiant", "image acoustique ou graphique du signe linguistique", "signe · son · forme", "Le signifiant de 'chien' est la séquence sonore et graphique du mot.", "signifiant = image acoustique du signe linguistique", "image acoustique ou graphique du signe linguistique"),
            ("c1v02-signifie", "le signifié", "concept mental associé au signifiant", "concept · sens · mental", "Le signifié de 'chien' est le concept d'animal domestique quadrupède.", "signifié = concept mental associé au signe", "concept ou contenu mental associé au signifiant"),
            ("c1v02-pragmatique", "la pragmatique", "étude du sens en contexte, au-delà du sens littéral", "contexte · acte · implicite", "La pragmatique explique les actes de langage et les implicites de la communication.", "pragmatique = sens en contexte", "étude du sens des énoncés en contexte réel"),
            ("c1v02-acte-langage", "l'acte de langage", "action accomplie par la parole", "promettre · ordonner · Austin", "Promettre est un acte de langage qui crée une obligation.", "acte de langage = action accomplie par parole", "action sociale accomplie par le biais du langage"),
            ("c1v02-presupposition", "la présupposition", "information implicitement admise dans un énoncé", "implicite · admis · présupposé", "'Il a arrêté de mentir' présuppose qu'il mentait avant.", "présupposition = information implicite dans l'énoncé", "information implicitement admise dans un énoncé"),
            ("c1v02-polysemie", "la polysémie", "un même mot ayant plusieurs sens liés", "sens multiple · mot · lié", "'Table' a plusieurs sens liés : meuble, table de données, table des matières.", "polysémie = un mot, plusieurs sens liés", "propriété d'un mot d'avoir plusieurs sens liés"),
            ("c1v02-morpheme", "le morphème", "plus petite unité significative d'une langue", "unité · sens · minimal", "In- + accept- + -able = trois morphèmes dans 'inacceptable'.", "morphème = plus petite unité de sens", "plus petite unité de sens dans une langue"),
            ("c1v02-enonciation", "l'énonciation", "acte de production d'un énoncé dans une situation", "énonciateur · contexte · situation", "Étudier l'énonciation, c'est analyser qui parle à qui, où et quand.", "énonciation = acte de produire un énoncé", "acte de production d'un énoncé par un énonciateur"),
        ],
    },

    "les-arts-et-esthetique": {
        "level": "c1",
        "section": "vocabulaire",
        "num": "V03",
        "short": "Les Arts et l'Esthétique",
        "title": "Les Arts et l'Esthétique",
        "subtitle": "Vocab — beaux-arts, critique et théorie esthétique",
        "game_desc": "Maîtrisez le vocabulaire des arts et de l'esthétique",
        "words": [
            {"word": "l'esthétique (f)", "ipa": "/ɛs.te.tik/", "def": "branche de la philosophie qui étudie le beau et le goût artistique", "ex": "L'esthétique de Kant distingue le beau, le sublime et l'agréable."},
            {"word": "la mimèsis", "ipa": "/mi.me.sis/", "def": "imitation de la réalité dans l'art — concept d'Aristote", "ex": "La théorie aristotélicienne de la mimèsis voit l'art comme imitation de la nature."},
            {"word": "le sublime", "ipa": "/sy.blim/", "def": "sentiment d'effroi et d'admiration devant quelque chose de grandiose ou de démesuré", "ex": "Les paysages alpins inspiraient aux romantiques un sentiment de sublime."},
            {"word": "l'avant-garde (f)", "ipa": "/a.vɑ̃ ɡaʁd/", "def": "mouvement artistique innovant qui rompt avec les conventions établies", "ex": "Le surréalisme et le dadaïsme étaient les avant-gardes du début du XXe siècle."},
            {"word": "le kitsch", "ipa": "/kitʃ/", "def": "style caractérisé par l'excès, le mauvais goût ou l'imitation de l'art populaire", "ex": "Les collections de bibelots en plastique sont souvent qualifiées de kitsch."},
            {"word": "l'ekphrasis (f)", "ipa": "/ɛk.fʁa.sis/", "def": "description littéraire détaillée d'une œuvre d'art visuelle", "ex": "La description du bouclier d'Achille dans l'Iliade est un exemple célèbre d'ekphrasis."},
            {"word": "l'œuvre totale (f)", "ipa": "/œvʁ tɔ.tal/", "def": "Gesamtkunstwerk — œuvre qui fusionne toutes les formes d'art", "ex": "Wagner aspirait à l'œuvre totale en fusionnant musique, texte, scène et décor."},
            {"word": "la catégorie esthétique", "ipa": "/ka.te.ɡɔ.ʁi ɛs.te.tik/", "def": "concept permettant de classer et d'évaluer l'expérience artistique", "ex": "Le beau, le laid, le grotesque et le sublime sont des catégories esthétiques."},
            {"word": "la réception", "ipa": "/ʁe.sɛp.sjɔ̃/", "def": "façon dont une œuvre est perçue, interprétée et évaluée par ses destinataires", "ex": "L'esthétique de la réception s'intéresse aux lecteurs, non à l'auteur."},
            {"word": "l'herméneutique (f)", "ipa": "/ɛʁ.me.nø.tik/", "def": "théorie et pratique de l'interprétation des textes et des œuvres", "ex": "L'herméneutique de Gadamer analyse le dialogue entre le texte et l'interprète."},
            {"word": "la déconstruction", "ipa": "/de.kɔ̃s.tʁyk.sjɔ̃/", "def": "méthode d'analyse philosophique remettant en cause les fondements des textes", "ex": "La déconstruction de Derrida interroge les oppositions binaires dans la philosophie occidentale."},
            {"word": "le canon esthétique", "ipa": "/ka.nɔ̃ ɛs.te.tik/", "def": "ensemble des œuvres ou des critères servant de référence dans une culture", "ex": "Le canon littéraire occidental est dominé par des auteurs européens masculins blancs."},
            {"word": "la sensibilité artistique", "ipa": "/sɑ̃.si.bi.li.te aʁ.tis.tik/", "def": "capacité à percevoir et à apprécier les valeurs esthétiques des œuvres", "ex": "Sa sensibilité artistique lui permettait de saisir les nuances imperceptibles d'une composition."},
            {"word": "l'intertextualité artistique (f)", "ipa": "/ɛ̃.tɛʁ.tɛks.tɥa.li.te aʁ.tis.tik/", "def": "dialogue entre une œuvre et des œuvres antérieures par allusion ou reprise", "ex": "Le tableau de Picasso dialogue avec Vélasquez — intertextualité artistique."},
            {"word": "la postmodernité", "ipa": "/pɔst.mɔ.dɛʁ.ni.te/", "def": "mouvement culturel questionnant les grands récits de la modernité", "ex": "La postmodernité se caractérise par l'ironie, le métissage et le refus des hiérarchies culturelles."},
        ],
        "items": [
            ("c1v03-esthetique", "l'esthétique", "philosophie du beau et du goût artistique", "beau · goût · philosophie", "L'esthétique de Kant distingue le beau (universel) de l'agréable (subjectif).", "esthétique = philosophie du beau", "branche de la philosophie étudiant le beau et le goût"),
            ("c1v03-mimesis", "la mimèsis", "imitation de la réalité dans l'art (Aristote)", "imitation · Aristote · nature", "La mimèsis aristotélicienne voit la tragédie comme imitation d'une action noble.", "mimèsis = imitation de la réalité dans l'art", "imitation de la réalité dans l'art — concept aristotélicien"),
            ("c1v03-sublime", "le sublime", "sentiment d'effroi et d'admiration devant le grandiose", "admiration · effroi · romantisme", "Face à la tempête, le peintre romantique ressent le sublime de la nature.", "sublime = effroi + admiration devant le grandiose", "sentiment mêlant effroi et admiration devant le grandiose"),
            ("c1v03-avant-garde", "l'avant-garde", "mouvement artistique innovant rupture avec les conventions", "innovation · rupture · surréalisme", "Le dadaïsme était une avant-garde radicale de la première moitié du XXe siècle.", "avant-garde = art innovant brisant les conventions", "mouvement artistique innovant qui rompt avec les conventions"),
            ("c1v03-reception", "la réception", "façon dont une œuvre est perçue par ses destinataires", "lecteur · interprétation · public", "L'esthétique de la réception déplace l'analyse de l'auteur vers le lecteur.", "réception = perception de l'œuvre par ses destinataires", "façon dont une œuvre est perçue et interprétée"),
            ("c1v03-hermeneutique", "l'herméneutique", "théorie de l'interprétation des textes et des œuvres", "interprétation · Gadamer · texte", "L'herméneutique interroge le sens produit par la rencontre entre texte et lecteur.", "herméneutique = théorie de l'interprétation", "théorie et pratique de l'interprétation des œuvres"),
            ("c1v03-canon", "le canon esthétique", "ensemble des œuvres servant de référence culturelle", "référence · classiques · culture", "Le canon littéraire est contesté par les études postcoloniales et féministes.", "canon esthétique = œuvres de référence culturelle", "ensemble des œuvres ou critères servant de référence"),
            ("c1v03-postmodernite", "la postmodernité", "courant culturel questionnant les grands récits de la modernité", "ironie · métissage · relativisme", "La postmodernité valorise l'ironie, la fragmentation et le mélange des genres.", "postmodernité = remise en cause des grands récits", "mouvement questionnant les certitudes de la modernité"),
        ],
    },

    "l-histoire-et-memoire": {
        "level": "c1",
        "section": "vocabulaire",
        "num": "V04",
        "short": "L'Histoire et la Mémoire",
        "title": "L'Histoire et la Mémoire",
        "subtitle": "Vocab — historiographie, mémoire collective et patrimoine",
        "game_desc": "Maîtrisez le vocabulaire de l'histoire et de la mémoire",
        "words": [
            {"word": "l'historiographie (f)", "ipa": "/is.tɔ.ʁjɔ.ɡʁa.fi/", "def": "étude des méthodes et des approches utilisées par les historiens", "ex": "L'historiographie des Annales a révolutionné la façon d'écrire l'histoire en France."},
            {"word": "la mémoire collective", "ipa": "/me.mwaʁ kɔ.lɛk.tiv/", "def": "ensemble des souvenirs partagés par un groupe social ou une nation", "ex": "La mémoire collective de la Shoah est transmise par les commémorations et les témoignages."},
            {"word": "le devoir de mémoire", "ipa": "/də.vwaʁ də me.mwaʁ/", "def": "obligation morale de ne pas oublier les crimes historiques majeurs", "ex": "Le devoir de mémoire envers les victimes de l'esclavage est inscrit dans la loi Taubira."},
            {"word": "la révision historique", "ipa": "/ʁe.vi.zjɔ̃ is.tɔ.ʁik/", "def": "réexamen légitime des faits historiques à la lumière de nouveaux documents", "ex": "La révision historique saine s'appuie sur des archives, contrairement au négationnisme."},
            {"word": "le négationnisme", "ipa": "/ne.ɡa.sjɔ.nism/", "def": "négation de faits historiques établis, notamment des génocides", "ex": "Le négationnisme de la Shoah est un délit en France depuis la loi Gayssot de 1990."},
            {"word": "le lieu de mémoire", "ipa": "/ljø də me.mwaʁ/", "def": "site symbolique où se cristallise la mémoire d'une communauté (Pierre Nora)", "ex": "Verdun, le Mémorial de la Shoah, le Mont-Saint-Michel sont des lieux de mémoire français."},
            {"word": "la commémoration", "ipa": "/kɔ.me.mɔ.ʁa.sjɔ̃/", "def": "cérémonie officielle rappelant un événement historique", "ex": "La commémoration du 8 mai réunit chaque année anciens combattants et représentants de l'État."},
            {"word": "l'anachronisme historique (m)", "ipa": "/a.na.kʁɔ.nism is.tɔ.ʁik/", "def": "erreur consistant à appliquer des catégories actuelles à des situations passées", "ex": "Parler de 'droits de l'homme' au Moyen Âge serait un anachronisme historique."},
            {"word": "la longue durée", "ipa": "/lɔ̃ɡ dy.ʁe/", "def": "concept de l'école des Annales désignant les structures historiques lentes", "ex": "Fernand Braudel a théorisé la longue durée pour décrire les permanences géographiques et économiques."},
            {"word": "le témoignage", "ipa": "/te.mwa.ɲaʒ/", "def": "récit personnel d'un événement vécu, source première de l'histoire orale", "ex": "Les témoignages des survivants constituent une source irremplaçable pour les historiens."},
            {"word": "la patrimonialisation", "ipa": "/pat.ʁi.mɔ.nja.li.za.sjɔ̃/", "def": "processus par lequel un objet culturel ou naturel est reconnu comme patrimoine", "ex": "La patrimonialisation du centre historique de Lyon lui a valu l'inscription à l'UNESCO."},
            {"word": "la prosopographie", "ipa": "/pʁɔ.sɔ.pɔ.ɡʁa.fi/", "def": "méthode historique étudiant les caractéristiques d'un groupe d'individus du passé", "ex": "La prosopographie des sénateurs romains a permis d'établir leur profil social."},
            {"word": "le présentisme", "ipa": "/pʁe.zɑ̃.tism/", "def": "tendance à interpréter le passé avec des valeurs et catégories du présent", "ex": "Juger les pères fondateurs à l'aune des valeurs actuelles relève du présentisme."},
            {"word": "la rupture épistémologique", "ipa": "/ʁyp.tyʁ e.pis.te.mɔ.lɔ.ʒik/", "def": "changement radical de paradigme dans la manière de produire le savoir", "ex": "La révolution copernicienne est une rupture épistémologique majeure de la science moderne."},
            {"word": "l'histoire des mentalités (f)", "ipa": "/is.twaʁ de mɑ̃.ta.li.te/", "def": "étude des représentations, croyances et valeurs collectives d'une époque", "ex": "L'histoire des mentalités s'intéresse aux peurs, aux croyances et aux valeurs du passé."},
        ],
        "items": [
            ("c1v04-historiographie", "l'historiographie", "étude des méthodes et approches des historiens", "méthode · Annales · histoire", "L'historiographie des Annales a mis fin à l'histoire évènementielle pure.", "historiographie = étude des méthodes historiques", "étude des méthodes et approches utilisées par les historiens"),
            ("c1v04-memoire-coll", "la mémoire collective", "souvenirs partagés par un groupe ou une nation", "nation · partage · transmission", "La mémoire collective de la Résistance est centrale dans l'identité française.", "mémoire collective = souvenirs partagés d'un groupe", "ensemble des souvenirs partagés par un groupe social"),
            ("c1v04-devoir-memoire", "le devoir de mémoire", "obligation morale de ne pas oublier les crimes historiques", "obligation · Shoah · commémoration", "Le devoir de mémoire envers les victimes de l'esclavage est reconnu par la loi.", "devoir de mémoire = obligation de ne pas oublier", "obligation morale de ne pas oublier les crimes historiques"),
            ("c1v04-lieu-memoire", "le lieu de mémoire", "site symbolique cristallisant la mémoire d'une communauté", "symbole · Pierre Nora · commémoration", "Verdun est un puissant lieu de mémoire de la Première Guerre mondiale.", "lieu de mémoire = site symbolique de la mémoire collective", "site symbolique où se cristallise la mémoire d'une communauté"),
            ("c1v04-negation", "le négationnisme", "négation de faits historiques établis comme les génocides", "génocide · crime · loi Gayssot", "Le négationnisme de la Shoah est un délit passible de poursuites en France.", "négationnisme = nier des faits historiques établis", "négation de faits historiques établis, notamment des génocides"),
            ("c1v04-longue-duree", "la longue durée", "structures historiques lentes sur plusieurs siècles", "Braudel · Annales · permanences", "Braudel a étudié la Méditerranée sur la longue durée, au-delà des événements.", "longue durée = structures historiques lentes", "concept des Annales désignant les structures historiques lentes"),
            ("c1v04-presentisme", "le présentisme", "interpréter le passé avec des valeurs actuelles", "anachronisme · valeurs · jugement", "Le présentisme juge les acteurs historiques selon des normes qui n'existaient pas encore.", "présentisme = juger le passé selon le présent", "tendance à interpréter le passé avec des catégories actuelles"),
            ("c1v04-temoignage", "le témoignage", "récit personnel d'un événement vécu — source orale", "survivant · source · histoire orale", "Les témoignages des survivants de la Shoah constituent une source historique irremplaçable.", "témoignage = récit personnel d'un événement vécu", "récit personnel d'un événement vécu, source de l'histoire orale"),
        ],
    },
}
