CHAPTERS = {
    "la-mondialisation": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V01",
        "short": "la-mondialisation",
        "title": "La Mondialisation",
        "subtitle": "Globalisation, trade, migration and international relations",
        "words": [
            ("la mondialisation", "/la mɔ̃djalizasjɔ̃/", "globalisation", "La mondialisation a transformé les échanges commerciaux entre les pays."),
            ("le libre-échange", "/lə libʁ‿eʃɑ̃ʒ/", "free trade", "L'accord de libre-échange a supprimé les droits de douane entre les deux nations."),
            ("le flux migratoire", "/lə fly miɡʁatwaʁ/", "migratory flow", "Les flux migratoires vers l'Europe ont augmenté au cours de la dernière décennie."),
            ("l'entreprise multinationale", "/lɑ̃tʁəpʁiz myltinasjɔnal/", "multinational company", "Cette entreprise multinationale emploie des milliers de personnes dans trente pays."),
            ("la diversité culturelle", "/la divɛʁsite kyltɥʁɛl/", "cultural diversity", "La diversité culturelle enrichit nos sociétés mais peut aussi engendrer des tensions."),
            ("la diplomatie", "/la diplɔmasi/", "diplomacy", "La diplomatie reste le meilleur outil pour résoudre les conflits internationaux."),
            ("le protectionnisme", "/lə pʁɔtɛksjɔnism/", "protectionism", "Le protectionnisme vise à protéger l'économie nationale de la concurrence étrangère."),
            ("l'ONG", "/lɔ‿ɛn‿ʒe/", "NGO (non-governmental organisation)", "Cette ONG humanitaire intervient dans les zones de conflit armé."),
            ("la délocalisation", "/la delɔkalizasjɔ̃/", "offshoring / relocation of production", "La délocalisation des usines a entraîné des pertes d'emplois massives dans la région."),
            ("la frontière", "/la fʁɔ̃tjɛʁ/", "border", "L'ouverture des frontières a facilité la circulation des personnes et des marchandises."),
            ("la coopération internationale", "/la kɔɔpeʁasjɔ̃ ɛ̃tɛʁnasjɔnal/", "international cooperation", "La coopération internationale est indispensable pour lutter contre le changement climatique."),
            ("les inégalités", "/lez‿ineɡalite/", "inequalities", "La mondialisation a creusé les inégalités entre les pays riches et les pays pauvres."),
            ("le marché mondial", "/lə maʁʃe mɔ̃djal/", "global market", "Les entreprises doivent s'adapter aux exigences du marché mondial pour rester compétitives."),
            ("le traité", "/lə tʁɛte/", "treaty", "Ce traité commercial a été signé après des années de négociations complexes."),
            ("la souveraineté", "/la suvʁɛnte/", "sovereignty", "Certains États craignent que les accords mondiaux n'empiètent sur leur souveraineté nationale."),
        ],
        "game_desc": "Key vocabulary for discussing globalisation, international trade and cross-border relations",
        "items": [
            ("mondialisation", "la mondialisation", "globalisation", "globalisation worldwide", "La ___ a profondément modifié les relations économiques entre les nations.", "mondialisation", "mondialisation"),
            ("libre-echange", "le libre-échange", "free trade", "open trade", "L'accord de ___ a permis de réduire considérablement les barrières douanières.", "libre-échange", "libre-échange"),
            ("flux-migratoire", "le flux migratoire", "migratory flow", "migration wave", "Les ___ en provenance des zones de conflit ont mis à l'épreuve les politiques d'accueil européennes.", "flux migratoires", "flux migratoires"),
            ("delocali­sation", "la délocalisation", "offshoring", "outsourcing abroad", "La ___ de la production vers des pays à bas salaires a provoqué des débats politiques intenses.", "délocalisation", "délocalisation"),
            ("protectionnisme", "le protectionnisme", "protectionism", "trade barriers policy", "Le ___ peut sembler attrayant à court terme, mais il nuit aux échanges mondiaux.", "protectionnisme", "protectionnisme"),
            ("cooperation", "la coopération internationale", "international cooperation", "global collaboration", "Sans une véritable ___, il sera impossible de résoudre les crises mondiales actuelles.", "coopération internationale", "coopération internationale"),
            ("inegalites", "les inégalités", "inequalities", "disparities", "La mondialisation a accentué les ___ entre les pays développés et les pays en voie de développement.", "inégalités", "inégalités"),
            ("souverainete", "la souveraineté", "sovereignty", "national autonomy", "Certains gouvernements défendent leur ___ face aux pressions des organisations internationales.", "souveraineté", "souveraineté"),
        ],
    },

    "les-sciences-technologie": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V02",
        "short": "les-sciences-technologie",
        "title": "Les Sciences et la Technologie",
        "subtitle": "Research, innovation, AI, biotech and digital ethics",
        "words": [
            ("l'intelligence artificielle", "/lɛ̃tɛliʒɑ̃s‿aʁtifisjɛl/", "artificial intelligence", "L'intelligence artificielle révolutionne des secteurs aussi variés que la médecine et les transports."),
            ("l'algorithme", "/lalɡɔʁitm/", "algorithm", "Cet algorithme analyse des millions de données en quelques secondes pour personnaliser les résultats."),
            ("la biotechnologie", "/la bjɔtɛknɔlɔʒi/", "biotechnology", "Les biotechnologies offrent des perspectives prometteuses pour soigner des maladies génétiques."),
            ("la recherche fondamentale", "/la ʁəʃɛʁʃ fɔ̃damɑ̃tal/", "basic / fundamental research", "La recherche fondamentale ne produit pas de résultats immédiats, mais elle est essentielle au progrès."),
            ("le brevet", "/lə bʁəvɛ/", "patent", "L'entreprise a déposé un brevet pour protéger son innovation contre la concurrence."),
            ("la robotique", "/la ʁɔbɔtik/", "robotics", "La robotique industrielle permet d'automatiser des tâches dangereuses ou répétitives."),
            ("l'éthique", "/letik/", "ethics", "L'éthique de l'intelligence artificielle soulève des questions fondamentales sur la responsabilité."),
            ("les données personnelles", "/le dɔne pɛʁsɔnɛl/", "personal data", "La protection des données personnelles est un enjeu majeur à l'ère numérique."),
            ("la cyberattaque", "/la sibɛʁatak/", "cyberattack", "Cette cyberattaque a paralysé les infrastructures informatiques de plusieurs hôpitaux."),
            ("la nanotechnologie", "/la nanɔtɛknɔlɔʒi/", "nanotechnology", "La nanotechnologie pourrait transformer la fabrication de médicaments ciblés."),
            ("la génétique", "/la ʒenetik/", "genetics", "Les avancées en génétique permettent désormais de dépister certaines maladies avant la naissance."),
            ("la source d'énergie", "/la suʁs denɛʁʒi/", "energy source", "Les chercheurs explorent de nouvelles sources d'énergie pour remplacer les combustibles fossiles."),
            ("l'innovation disruptive", "/linɔvasjɔ̃ disʁyptiv/", "disruptive innovation", "L'innovation disruptive remet en cause les modèles économiques traditionnels."),
            ("la réalité virtuelle", "/la ʁealite viʁtyɛl/", "virtual reality", "La réalité virtuelle est de plus en plus utilisée dans la formation professionnelle."),
            ("l'ingénierie", "/lɛ̃ʒenjʁi/", "engineering", "L'ingénierie génétique ouvre des possibilités fascinantes mais suscite aussi des craintes éthiques."),
        ],
        "game_desc": "Essential vocabulary for talking about science, technology and digital ethics at B2 level",
        "items": [
            ("ia", "l'intelligence artificielle", "artificial intelligence", "machine learning system", "L'___ est capable de battre les meilleurs joueurs d'échecs au monde.", "intelligence artificielle", "intelligence artificielle"),
            ("algorithme", "l'algorithme", "algorithm", "computational procedure", "Le réseau social utilise un ___ complexe pour déterminer quels contenus vous montrer en priorité.", "algorithme", "algorithme"),
            ("brevet", "le brevet", "patent", "intellectual property right", "Sans ___, une invention peut être copiée librement par n'importe quelle entreprise concurrente.", "brevet", "brevet"),
            ("ethique", "l'éthique", "ethics", "moral framework", "L'___ encadre les recherches sur le génome humain afin d'éviter les dérives.", "éthique", "éthique"),
            ("donnees-personnelles", "les données personnelles", "personal data", "private user data", "Les entreprises sont légalement tenues de protéger les ___ de leurs clients.", "données personnelles", "données personnelles"),
            ("cyberattaque", "la cyberattaque", "cyberattack", "digital assault", "La ___ contre le ministère a compromis des milliers de fichiers confidentiels.", "cyberattaque", "cyberattaque"),
            ("innovation-disruptive", "l'innovation disruptive", "disruptive innovation", "game-changing breakthrough", "L'___ dans le secteur des transports a bouleversé les habitudes de déplacement urbain.", "innovation disruptive", "innovation disruptive"),
            ("realite-virtuelle", "la réalité virtuelle", "virtual reality", "immersive simulation", "La ___ est désormais utilisée pour simuler des opérations chirurgicales complexes.", "réalité virtuelle", "réalité virtuelle"),
        ],
    },

    "la-culture-arts": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V03",
        "short": "la-culture-arts",
        "title": "La Culture et les Arts",
        "subtitle": "Cinema, literature, museums, artistic expression and criticism",
        "words": [
            ("le patrimoine culturel", "/lə patʁimwan kyltɥʁɛl/", "cultural heritage", "La préservation du patrimoine culturel est une responsabilité collective envers les générations futures."),
            ("l'exposition", "/lɛkspɔzisjɔ̃/", "exhibition", "Cette exposition rétrospective rassemble plus de deux cents œuvres du peintre catalan."),
            ("le chef-d'œuvre", "/lə ʃɛ dœvʁ/", "masterpiece", "La Joconde est sans doute le chef-d'œuvre le plus célèbre de la Renaissance italienne."),
            ("le dramaturge", "/lə dʁamatyʁʒ/", "playwright", "Ce dramaturge contemporain aborde des thèmes sociaux avec une langue provocante et précise."),
            ("le réalisateur", "/lə ʁealizatœʁ/", "film director", "Le réalisateur a choisi de tourner entièrement en décors naturels pour renforcer le réalisme."),
            ("la critique littéraire", "/la kʁitik litɛʁɛʁ/", "literary criticism", "La critique littéraire a salué ce roman pour sa profondeur psychologique et son style épuré."),
            ("l'avant-garde", "/lavɑ̃ɡaʁd/", "avant-garde", "Ce mouvement d'avant-garde a rompu avec les conventions esthétiques de l'époque."),
            ("le mécénat", "/lə mesena/", "patronage (of the arts)", "Le mécénat d'entreprise permet de financer des projets culturels ambitieux sans dépendre de l'État."),
            ("le musée", "/lə myze/", "museum", "Ce musée national accueille chaque année plus d'un million de visiteurs du monde entier."),
            ("l'œuvre d'art", "/lœvʁ‿daʁ/", "work of art", "Cette œuvre d'art a été vendue aux enchères pour un prix record de vingt millions d'euros."),
            ("l'interprétation", "/lɛ̃tɛʁpʁetasjɔ̃/", "interpretation / performance", "L'interprétation de cette sonate par la pianiste a reçu une ovation debout."),
            ("la subvention", "/la sybvɑ̃sjɔ̃/", "subsidy / grant", "Sans les subventions de l'État, de nombreux théâtres régionaux fermeraient leurs portes."),
            ("le festival", "/lə fɛstival/", "festival", "Le festival de Cannes récompense chaque année les meilleures productions cinématographiques mondiales."),
            ("l'adaptation", "/ladaptasjɔ̃/", "adaptation", "Cette adaptation cinématographique du roman a déçu les lecteurs les plus fidèles."),
            ("la censure", "/la sɑ̃syʁ/", "censorship", "La censure des œuvres artistiques est souvent le signe d'un régime autoritaire."),
        ],
        "game_desc": "Vocabulary for discussing art, culture, cinema and artistic criticism in French",
        "items": [
            ("patrimoine", "le patrimoine culturel", "cultural heritage", "cultural legacy", "Le ___ de cette ville médiévale est inscrit au patrimoine mondial de l'UNESCO.", "patrimoine culturel", "patrimoine culturel"),
            ("chef-doeuvre", "le chef-d'œuvre", "masterpiece", "greatest work", "Cette cathédrale gothique est considérée comme le ___ de l'architecture médiévale française.", "chef-d'œuvre", "chef-d'œuvre"),
            ("avant-garde", "l'avant-garde", "avant-garde", "experimental movement", "L'___ artistique du début du XXe siècle a radicalement transformé notre conception de l'art.", "avant-garde", "avant-garde"),
            ("mecenat", "le mécénat", "patronage", "arts sponsorship", "Le ___ culturel bénéficie d'avantages fiscaux importants pour encourager les entreprises à financer les arts.", "mécénat", "mécénat"),
            ("subvention", "la subvention", "subsidy", "public funding", "La ___ accordée à ce cinéma d'art et d'essai lui a permis de proposer des tarifs accessibles.", "subvention", "subvention"),
            ("censure", "la censure", "censorship", "suppression of expression", "La ___ de ce film a provoqué une vive polémique sur la liberté d'expression artistique.", "censure", "censure"),
            ("interpretation", "l'interprétation", "interpretation / performance", "artistic reading", "L'___ de ce rôle par l'actrice principale est unanimement saluée par la critique.", "interprétation", "interprétation"),
            ("adaptation", "l'adaptation", "adaptation", "screen version", "L'___ théâtrale de ce roman policier a rencontré un immense succès auprès du public.", "adaptation", "adaptation"),
        ],
    },

    "l-economie": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V04",
        "short": "l-economie",
        "title": "L'Économie",
        "subtitle": "Markets, recession, finance, enterprise and economic policy",
        "words": [
            ("la récession", "/la ʁesɛsjɔ̃/", "recession", "Le pays traverse sa pire récession depuis la crise financière de 2008."),
            ("la croissance économique", "/la kʁwasɑ̃s ekɔnɔmik/", "economic growth", "La croissance économique de ce pays émergent atteint cinq pour cent par an."),
            ("le taux d'intérêt", "/lə to dɛ̃teʁɛ/", "interest rate", "La banque centrale a relevé les taux d'intérêt pour freiner l'inflation."),
            ("la dette publique", "/la dɛt pyblik/", "public debt", "La dette publique représente désormais plus de cent pour cent du PIB national."),
            ("l'inflation", "/lɛ̃flasjɔ̃/", "inflation", "L'inflation galopante a érodé le pouvoir d'achat des ménages les plus modestes."),
            ("la bourse", "/la buʁs/", "stock exchange", "Les marchés boursiers ont chuté brutalement suite à l'annonce des mauvais résultats trimestriels."),
            ("l'actionnaire", "/laksjonaʁ/", "shareholder", "Les actionnaires ont voté en faveur d'une augmentation du dividende annuel."),
            ("le budget", "/lə bydʒɛ/", "budget", "Le gouvernement a présenté un budget d'austérité pour réduire le déficit public."),
            ("l'entreprise", "/lɑ̃tʁəpʁiz/", "company / enterprise", "Cette entreprise familiale a réussi à s'imposer face aux grandes multinationales."),
            ("le déficit", "/lə defisi/", "deficit", "Le déficit budgétaire s'est creusé en raison de la hausse des dépenses sociales."),
            ("l'investissement", "/lɛ̃vɛstismɑ̃/", "investment", "L'investissement étranger direct a contribué au développement économique de la région."),
            ("le PIB", "/lə pe‿i‿be/", "GDP (Gross Domestic Product)", "Le PIB de ce pays a reculé de deux pour cent au premier trimestre."),
            ("la privatisation", "/la pʁivatizasjɔ̃/", "privatisation", "La privatisation des entreprises publiques est souvent controversée sur le plan social."),
            ("la taxe", "/la taks/", "tax", "Le gouvernement a instauré une nouvelle taxe sur les transactions financières."),
            ("le commerce équitable", "/lə kɔmɛʁs‿ekitabl/", "fair trade", "Le commerce équitable garantit un prix juste aux producteurs des pays en développement."),
        ],
        "game_desc": "Core economic vocabulary for discussing finance, markets and policy at B2 level",
        "items": [
            ("recession", "la récession", "recession", "economic downturn", "La ___ a entraîné une hausse significative du chômage dans tous les secteurs d'activité.", "récession", "récession"),
            ("croissance", "la croissance économique", "economic growth", "GDP expansion", "La ___ a ralenti à cause des tensions commerciales entre les grandes puissances.", "croissance économique", "croissance économique"),
            ("taux-interet", "le taux d'intérêt", "interest rate", "borrowing rate", "Une hausse du ___ rend les emprunts plus coûteux pour les ménages et les entreprises.", "taux d'intérêt", "taux d'intérêt"),
            ("inflation", "l'inflation", "inflation", "price rise", "L'___ a atteint un niveau record, obligeant les banques centrales à réagir rapidement.", "inflation", "inflation"),
            ("deficit", "le déficit", "deficit", "budget shortfall", "Le ___ commercial du pays s'est aggravé en raison d'une baisse des exportations.", "déficit", "déficit"),
            ("PIB", "le PIB", "GDP", "gross domestic product", "La croissance du ___ est souvent utilisée comme indicateur principal de la santé économique d'un pays.", "PIB", "PIB"),
            ("privatisation", "la privatisation", "privatisation", "selling off state assets", "La ___ du réseau ferroviaire a suscité une vive opposition de la part des syndicats.", "privatisation", "privatisation"),
            ("commerce-equitable", "le commerce équitable", "fair trade", "ethical trade", "Acheter des produits issus du ___ permet de soutenir les petits producteurs du monde entier.", "commerce équitable", "commerce équitable"),
        ],
    },

    "les-droits-humains": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V05",
        "short": "les-droits-humains",
        "title": "Les Droits Humains",
        "subtitle": "Equality, discrimination, activism, justice and fundamental rights",
        "words": [
            ("la discrimination", "/la diskʁiminasjɔ̃/", "discrimination", "La discrimination fondée sur l'origine ethnique est illégale dans tous les États membres de l'UE."),
            ("l'égalité des chances", "/leɡalite de ʃɑ̃s/", "equality of opportunity", "L'égalité des chances reste un idéal difficile à atteindre dans de nombreuses sociétés."),
            ("le militantisme", "/lə militɑ̃tism/", "activism", "Le militantisme en faveur des droits civiques a transformé les sociétés américaine et européenne."),
            ("les droits fondamentaux", "/le dʁwa fɔ̃damɑ̃to/", "fundamental rights", "La protection des droits fondamentaux est une obligation pour tout État démocratique."),
            ("la liberté d'expression", "/la libɛʁte dɛkspʁɛsjɔ̃/", "freedom of expression", "La liberté d'expression ne saurait justifier les discours haineux ou incitant à la violence."),
            ("l'oppression", "/lɔpʁɛsjɔ̃/", "oppression", "Ce régime autoritaire maintient sa population dans l'oppression depuis des décennies."),
            ("le tribunal", "/lə tʁibynɑl/", "court / tribunal", "La victime a porté l'affaire devant le tribunal international des droits de l'homme."),
            ("le réfugié", "/lə ʁefyʒje/", "refugee", "Des milliers de réfugiés fuient les zones de conflit en risquant leur vie."),
            ("l'asile politique", "/lazil pɔlitik/", "political asylum", "Cet opposant a demandé l'asile politique après avoir été emprisonné dans son pays natal."),
            ("l'impunité", "/lɛ̃pynite/", "impunity", "L'impunité dont bénéficient certains dirigeants encourage la poursuite des violations des droits humains."),
            ("la laïcité", "/la laisite/", "secularism / laïcité", "La laïcité garantit la séparation des religions et de l'État dans la République française."),
            ("la minorité", "/la minɔʁite/", "minority", "Les droits des minorités doivent être garantis par la loi dans toute démocratie pluraliste."),
            ("le mouvement social", "/lə muvmɑ̃ sɔsjal/", "social movement", "Ce mouvement social a réuni des millions de personnes dans les rues pour réclamer des réformes."),
            ("la solidarité", "/la sɔlidarite/", "solidarity", "La solidarité internationale est essentielle pour venir en aide aux populations les plus vulnérables."),
            ("l'injustice", "/lɛ̃ʒystis/", "injustice", "Ce documentaire dénonce avec force les injustices subies par les populations autochtones."),
        ],
        "game_desc": "Vocabulary for discussing human rights, activism, equality and justice in French",
        "items": [
            ("discrimination", "la discrimination", "discrimination", "unfair treatment", "La ___ à l'embauche est un délit passible de sanctions pénales sévères.", "discrimination", "discrimination"),
            ("egalite-chances", "l'égalité des chances", "equality of opportunity", "level playing field", "L'___ ne peut être garantie sans des politiques publiques volontaristes en matière d'éducation.", "égalité des chances", "égalité des chances"),
            ("droits-fondamentaux", "les droits fondamentaux", "fundamental rights", "basic rights", "La Constitution garantit les ___ de tous les citoyens, sans distinction de race ou de religion.", "droits fondamentaux", "droits fondamentaux"),
            ("liberte-expression", "la liberté d'expression", "freedom of expression", "free speech", "La ___ est un pilier des démocraties libérales, mais elle s'accompagne aussi de responsabilités.", "liberté d'expression", "liberté d'expression"),
            ("refugie", "le réfugié", "refugee", "displaced person", "La Convention de Genève définit les droits du ___ et les obligations des États d'accueil.", "réfugié", "réfugié"),
            ("impunite", "l'impunité", "impunity", "freedom from punishment", "La Cour pénale internationale a été créée pour mettre fin à l'___ des auteurs de crimes de guerre.", "impunité", "impunité"),
            ("laicite", "la laïcité", "secularism", "separation of church and state", "La ___ est un principe constitutionnel fondamental en France, souvent mal compris à l'étranger.", "laïcité", "laïcité"),
            ("solidarite", "la solidarité", "solidarity", "mutual support", "La ___ entre les peuples est un moteur puissant des grands changements sociaux de l'Histoire.", "solidarité", "solidarité"),
        ],
    },

    "l-urbanisme": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V06",
        "short": "l-urbanisme",
        "title": "L'Urbanisme et l'Architecture",
        "subtitle": "Cities, planning, infrastructure, housing and smart cities",
        "words": [
            ("l'urbanisme", "/lyʁbanism/", "urban planning", "Un urbanisme mal pensé peut aggraver les inégalités sociales au sein d'une ville."),
            ("l'infrastructure", "/lɛ̃fʁastʁyktyʁ/", "infrastructure", "Des infrastructures de transport modernes sont indispensables à la compétitivité économique d'une région."),
            ("la densité urbaine", "/la dɑ̃site yʁbɛn/", "urban density", "Une forte densité urbaine permet de réduire les déplacements et d'optimiser les services publics."),
            ("l'étalement urbain", "/letalmɑ̃ yʁbɛ̃/", "urban sprawl", "L'étalement urbain détruit les terres agricoles et augmente la dépendance à la voiture individuelle."),
            ("le logement social", "/lə lɔʒmɑ̃ sɔsjal/", "social housing", "Le manque de logements sociaux aggrave la crise immobilière dans les grandes métropoles."),
            ("la rénovation", "/la ʁenɔvasjɔ̃/", "renovation", "La rénovation du vieux quartier a permis de préserver le patrimoine architectural tout en modernisant les logements."),
            ("les espaces verts", "/lez‿ɛspas vɛʁ/", "green spaces", "Les espaces verts en ville améliorent la qualité de vie et contribuent à réduire les îlots de chaleur."),
            ("la mobilité", "/la mɔbilite/", "mobility", "La mobilité douce, vélo et marche, est au cœur des nouvelles politiques urbaines."),
            ("le quartier", "/lə kaʁtje/", "neighbourhood / district", "Ce quartier historique a su conserver son identité tout en accueillant de nouveaux habitants."),
            ("le plan d'urbanisme", "/lə plɑ̃ dyʁbanism/", "urban development plan", "Le plan d'urbanisme de la ville prévoit la création de cinq nouveaux écoquartiers d'ici 2030."),
            ("la gentrification", "/la ʒɑ̃tʁifikasjɔ̃/", "gentrification", "La gentrification de ce quartier populaire a chassé les habitants les plus modestes vers la périphérie."),
            ("la smart city", "/la smaʁt siti/", "smart city", "La smart city utilise les données numériques pour améliorer la gestion des services urbains."),
            ("le bâtiment durable", "/lə batimɑ̃ dyʁabl/", "sustainable building", "Les bâtiments durables consomment moins d'énergie et réduisent l'empreinte carbone du secteur immobilier."),
            ("l'aménagement", "/lamenaʒmɑ̃/", "planning / development", "L'aménagement du territoire doit concilier développement économique et préservation de l'environnement."),
            ("le transport en commun", "/lə tʁɑ̃spɔʁ ɑ̃ kɔmœ̃/", "public transport", "Investir dans les transports en commun réduit la congestion routière et les émissions de CO₂."),
        ],
        "game_desc": "Vocabulary for discussing cities, urban planning, housing and sustainable architecture",
        "items": [
            ("urbanisme", "l'urbanisme", "urban planning", "city planning", "Un ___ cohérent est essentiel pour éviter la ségrégation sociale dans les grandes métropoles.", "urbanisme", "urbanisme"),
            ("etalement-urbain", "l'étalement urbain", "urban sprawl", "suburban expansion", "L'___ consomme des espaces naturels précieux et rend les villes totalement dépendantes de l'automobile.", "étalement urbain", "étalement urbain"),
            ("logement-social", "le logement social", "social housing", "affordable housing", "Le manque de ___ oblige de nombreuses familles à s'éloigner des centres-villes pour trouver un toit abordable.", "logement social", "logement social"),
            ("gentrification", "la gentrification", "gentrification", "upmarket transformation", "La ___ rapide de ce quartier a profondément modifié sa composition sociale et culturelle.", "gentrification", "gentrification"),
            ("smart-city", "la smart city", "smart city", "digital city", "La ___ ambitionne d'utiliser les données en temps réel pour optimiser la gestion des déchets et de l'énergie.", "smart city", "smart city"),
            ("batiment-durable", "le bâtiment durable", "sustainable building", "green building", "La construction de ___ est encouragée par des aides fiscales et des normes environnementales strictes.", "bâtiments durables", "bâtiments durables"),
            ("transport-commun", "le transport en commun", "public transport", "mass transit", "Un réseau de ___ efficace réduit considérablement la pollution atmosphérique en milieu urbain.", "transport en commun", "transport en commun"),
            ("espaces-verts", "les espaces verts", "green spaces", "parks and gardens", "La multiplication des ___ en ville est devenue une priorité pour lutter contre les effets des canicules.", "espaces verts", "espaces verts"),
        ],
    },

    "la-communication": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V07",
        "short": "la-communication",
        "title": "La Communication et le Langage",
        "subtitle": "Rhetoric, persuasion, media literacy and language registers",
        "words": [
            ("la rhétorique", "/la ʁetɔʁik/", "rhetoric", "La rhétorique est l'art de convaincre par la parole, maîtrisée par tous les grands orateurs."),
            ("l'argumentation", "/laʁɡymɑ̃tasjɔ̃/", "argumentation", "Une argumentation solide repose sur des preuves vérifiables et une logique irréfutable."),
            ("le registre de langue", "/lə ʁəʒistʁ də lɑ̃ɡ/", "language register", "Il est essentiel d'adapter son registre de langue au contexte et à son interlocuteur."),
            ("le discours", "/lə diskuʁ/", "speech / discourse", "Ce discours présidentiel a marqué les esprits par son éloquence et sa portée historique."),
            ("le biais cognitif", "/lə bjɛ kɔɡnitif/", "cognitive bias", "Le biais de confirmation nous pousse à ne retenir que les informations qui confortent nos croyances."),
            ("la désinformation", "/la dezɛ̃fɔʁmasjɔ̃/", "disinformation", "La désinformation se propage à une vitesse alarmante sur les réseaux sociaux."),
            ("la source fiable", "/la suʁs fjabl/", "reliable source", "Il est indispensable de vérifier ses sources fiables avant de partager une information en ligne."),
            ("l'esprit critique", "/lɛspʁi kʁitik/", "critical thinking", "L'esprit critique est une compétence fondamentale pour naviguer dans un monde saturé d'informations."),
            ("la manipulation", "/la manipylasjɔ̃/", "manipulation", "La manipulation de l'opinion publique est une pratique courante dans les régimes autoritaires."),
            ("la communication non verbale", "/la kɔmynikasjɔ̃ nɔ̃ vɛʁbal/", "non-verbal communication", "La communication non verbale — gestes, posture, regard — révèle souvent plus que les mots."),
            ("le langage soutenu", "/lə lɑ̃ɡaʒ sutny/", "formal language register", "Le langage soutenu est attendu dans les écrits académiques et les discours officiels."),
            ("l'euphémisme", "/løfemism/", "euphemism", "L'euphémisme permet d'aborder des sujets sensibles avec plus de délicatesse."),
            ("l'hyperbole", "/lipɛʁbɔl/", "hyperbole", "L'hyperbole est une figure de style qui exagère la réalité pour produire un effet marquant."),
            ("l'image de marque", "/limaʒ də maʁk/", "brand image", "L'image de marque d'une entreprise dépend autant de sa communication que de la qualité de ses produits."),
            ("le narratif", "/lə naʁatif/", "narrative", "Ce gouvernement a construit un narratif politique fondé sur la peur et la méfiance envers l'autre."),
        ],
        "game_desc": "Vocabulary for analysing communication, rhetoric, media and language use at B2 level",
        "items": [
            ("rhetorique", "la rhétorique", "rhetoric", "art of persuasion", "La ___ politique fait souvent appel aux émotions plutôt qu'à des arguments rationnels.", "rhétorique", "rhétorique"),
            ("argumentation", "l'argumentation", "argumentation", "line of reasoning", "Une ___ efficace doit s'appuyer sur des faits vérifiés et présenter les contrarguments avec honnêteté.", "argumentation", "argumentation"),
            ("registre-langue", "le registre de langue", "language register", "language level", "En milieu professionnel, il faut adopter un ___ formel et éviter les expressions familières.", "registre de langue", "registre de langue"),
            ("biais-cognitif", "le biais cognitif", "cognitive bias", "thinking error", "Le ___ de disponibilité nous amène à surestimer la probabilité des événements qui nous viennent facilement à l'esprit.", "biais cognitif", "biais cognitif"),
            ("desinformation", "la désinformation", "disinformation", "fake news", "La ___ en ligne représente une menace sérieuse pour la démocratie et la cohésion sociale.", "désinformation", "désinformation"),
            ("esprit-critique", "l'esprit critique", "critical thinking", "analytical mindset", "Développer son ___ est la meilleure protection contre la manipulation et les fausses informations.", "esprit critique", "esprit critique"),
            ("euphemisme", "l'euphémisme", "euphemism", "softened expression", "L'usage de l'___ dans les bulletins de santé officiels peut parfois induire le public en erreur.", "euphémisme", "euphémisme"),
            ("narratif", "le narratif", "narrative", "dominant story", "Le ___ médiatique autour de la crise économique a fortement influencé le comportement des électeurs.", "narratif", "narratif"),
        ],
    },

    "les-enjeux-mondiaux": {
        "level": "b2",
        "section": "vocabulary",
        "num": "V08",
        "short": "les-enjeux-mondiaux",
        "title": "Les Enjeux Mondiaux",
        "subtitle": "Climate crisis, geopolitics, energy, population and global challenges",
        "words": [
            ("l'enjeu mondial", "/lɑ̃ʒø mɔ̃djal/", "global challenge / global issue", "La lutte contre la pauvreté est l'un des enjeux mondiaux les plus urgents de notre siècle."),
            ("la crise climatique", "/la kʁiz klimatik/", "climate crisis", "La crise climatique exige des mesures radicales et immédiates de la part de tous les gouvernements."),
            ("la géopolitique", "/la ʒeɔpɔlitik/", "geopolitics", "La géopolitique mondiale est de plus en plus marquée par la rivalité entre les grandes puissances."),
            ("la sécurité alimentaire", "/la sekyʁite alimɑ̃tɛʁ/", "food security", "La sécurité alimentaire de millions de personnes est menacée par les sécheresses à répétition."),
            ("la transition énergétique", "/la tʁɑ̃zisjɔ̃ enɛʁʒetik/", "energy transition", "La transition énergétique vers les renouvelables nécessite des investissements colossaux."),
            ("la surpopulation", "/la syʁpɔpylasjɔ̃/", "overpopulation", "La surpopulation dans certaines mégapoles entraîne une pression insoutenable sur les ressources."),
            ("le conflit armé", "/lə kɔ̃fli‿aʁme/", "armed conflict", "Les conflits armés déplacent chaque année des millions de personnes à travers le monde."),
            ("l'accord international", "/lakɔʁ‿ɛ̃tɛʁnasjɔnal/", "international agreement", "L'accord international sur le climat a fixé des objectifs ambitieux de réduction des émissions."),
            ("la ressource naturelle", "/la ʁəsuʁs natyʁɛl/", "natural resource", "La gestion durable des ressources naturelles est un défi majeur pour les générations à venir."),
            ("la catastrophe humanitaire", "/la katastʁɔf ymanitɛʁ/", "humanitarian catastrophe", "La catastrophe humanitaire provoquée par la sécheresse a nécessité une aide internationale urgente."),
            ("le développement durable", "/lə devlɔpmɑ̃ dyʁabl/", "sustainable development", "Le développement durable cherche à concilier croissance économique et respect de l'environnement."),
            ("la neutralité carbone", "/la nøtʁalite kaʁbɔn/", "carbon neutrality", "L'Union européenne s'est engagée à atteindre la neutralité carbone d'ici 2050."),
            ("la biodiversité", "/la bjɔdivɛʁsite/", "biodiversity", "La perte de biodiversité est une menace aussi grave que le changement climatique pour la vie sur Terre."),
            ("l'État fragile", "/leta fʁaʒil/", "fragile state", "Les États fragiles peinent à assurer la sécurité et les services de base à leurs populations."),
            ("l'aide humanitaire", "/lɛd ymanitɛʁ/", "humanitarian aid", "L'acheminement de l'aide humanitaire est souvent entravé par les combats dans les zones de guerre."),
        ],
        "game_desc": "Essential vocabulary for discussing global issues, the climate crisis and international relations",
        "items": [
            ("crise-climatique", "la crise climatique", "climate crisis", "climate emergency", "La ___ oblige les États à repenser en profondeur leurs modèles de production et de consommation.", "crise climatique", "crise climatique"),
            ("geopolitique", "la géopolitique", "geopolitics", "global power dynamics", "La ___ de la région est devenue extrêmement instable depuis l'effondrement des accords de paix.", "géopolitique", "géopolitique"),
            ("securite-alimentaire", "la sécurité alimentaire", "food security", "access to food", "La ___ de millions d'habitants dépend désormais des importations de céréales en provenance d'Ukraine.", "sécurité alimentaire", "sécurité alimentaire"),
            ("transition-energetique", "la transition énergétique", "energy transition", "shift to renewables", "La ___ implique de sortir progressivement des énergies fossiles au profit des énergies renouvelables.", "transition énergétique", "transition énergétique"),
            ("developpement-durable", "le développement durable", "sustainable development", "green development", "Le ___ repose sur trois piliers indissociables : l'économie, le social et l'environnement.", "développement durable", "développement durable"),
            ("neutralite-carbone", "la neutralité carbone", "carbon neutrality", "net zero emissions", "Atteindre la ___ d'ici 2050 exige une transformation radicale de nos systèmes énergétiques et industriels.", "neutralité carbone", "neutralité carbone"),
            ("biodiversite", "la biodiversité", "biodiversity", "variety of life forms", "La destruction des forêts tropicales entraîne une perte irréversible de ___ à une échelle alarmante.", "biodiversité", "biodiversité"),
            ("aide-humanitaire", "l'aide humanitaire", "humanitarian aid", "emergency relief", "L'___ acheminée vers les zones sinistrées a permis de sauver des milliers de vies en quelques semaines.", "aide humanitaire", "aide humanitaire"),
        ],
    },
}
