"""Français C2 — Rédaction R01–R04"""

CHAPTERS = {
    "la-dissertation-litteraire": {
        "level": "c2",
        "section": "redaction",
        "num": "R01",
        "short": "Dissertation Littéraire",
        "title": "La Dissertation Littéraire",
        "subtitle": "Construire une argumentation littéraire rigoureuse au niveau DALF C2",
        "slides": [
            ("Qu'est-ce que la dissertation littéraire ?",
             "La dissertation littéraire est un exercice académique qui demande d'analyser une proposition portant sur la littérature ou les arts, en mobilisant des exemples précis et une argumentation structurée. Elle se distingue de la simple récitation par sa démarche dialectique : thèse, antithèse, synthèse."),
            ("La problématique",
             "La problématique transforme le sujet en une question genuine. Elle doit être ouverte (plusieurs réponses possibles), pertinente (ancrée dans le sujet) et productive (permet de générer des arguments). Exemple : « Dans quelle mesure la fiction peut-elle être un instrument de connaissance du réel ? » est une problématique ; « La fiction est-elle utile ? » est trop vague."),
            ("Le plan dialectique",
             "Le plan en trois parties suit la structure thèse–antithèse–synthèse. La thèse répond positivement au sujet, l'antithèse le nuance ou le contredit, la synthèse dépasse la contradiction en ouvrant de nouvelles perspectives. Chaque partie comprend deux ou trois sous-parties avec au moins un exemple littéraire précis."),
            ("L'introduction",
             "L'introduction comporte quatre mouvements : (1) une accroche contextualisant le sujet, (2) la présentation du sujet et sa définition des termes clés, (3) la problématique explicitement formulée, (4) l'annonce du plan. L'accroche peut être une citation d'auteur, un paradoxe ou un fait culturel — jamais une généralité vague (« Depuis la nuit des temps… »)."),
            ("Rédiger une sous-partie",
             "Chaque sous-partie suit la structure AAEE : Affirmation (idée directrice), Argument (justification logique), Exemple (texte précis, auteur, œuvre), Explication (lien entre l'exemple et l'idée). La sous-partie est un paragraphe d'environ 150 mots. La transition annonce la sous-partie suivante et marque la progression logique."),
            ("La synthèse et la conclusion",
             "La synthèse ne tranche pas entre thèse et antithèse : elle les dépasse en formulant une idée nouvelle. La conclusion récapitule brièvement le parcours argumentatif, rappelle la réponse à la problématique, puis ouvre sur une perspective plus large — une question connexe, un autre domaine artistique ou une dimension philosophique."),
            ("Langue et style",
             "Le registre est soutenu sans être pompeux. Employer des verbes d'analyse (« attester », « révéler », « illustrer », « mettre en lumière »), des connecteurs logiques précis (« or », « certes », « néanmoins », « partant »), des formules de distanciation (« il semblerait que », « l'on peut dès lors se demander »). Éviter le je, les tournures familières et les superlatifs non justifiés."),
            ("Pièges fréquents",
             "Paraphrase : résumer l'œuvre sans analyser. Hors-sujet partiel : traiter un aspect du sujet en oubliant d'autres termes clés. Plan catalogue : juxtaposer des exemples sans fil conducteur. Conclusion bâclée : terminer par « En conclusion, nous avons vu que… » sans synthèse. Oublier de citer précisément : titre, auteur, date sont indispensables."),
        ],
        "traps": [
            ("Paraphrase", "Résumer le texte au lieu d'analyser — chaque exemple doit être interprété et relié à l'argument."),
            ("Problématique fermée", "Une question à laquelle on répond simplement oui ou non ne génère pas de dialectique."),
            ("Plan déséquilibré", "La thèse ou l'antithèse trop courte fragilise la dialectique — chaque partie doit avoir un poids comparable."),
            ("Style relâché", "Les expressions familières (« vraiment », « super », « ça ») et le je personnel sont proscrits en dissertation."),
        ],
        "summary": [
            "La dissertation littéraire analyse une proposition par une démarche dialectique (thèse–antithèse–synthèse).",
            "La problématique doit être ouverte, pertinente et productive.",
            "Chaque sous-partie suit la structure AAEE : Affirmation, Argument, Exemple, Explication.",
            "L'introduction comporte accroche, définition, problématique et annonce du plan.",
            "La synthèse dépasse la contradiction pour formuler une idée nouvelle.",
            "Le registre est soutenu, analytique et impersonnel.",
        ],
        "ex1": {
            "q": "Quel est le rôle de la synthèse dans une dissertation littéraire ?",
            "opts": [
                "Résumer la thèse et l'antithèse sans les dépasser",
                "Choisir entre la thèse et l'antithèse la plus convaincante",
                "Dépasser la contradiction pour formuler une idée nouvelle",
                "Ouvrir le sujet vers d'autres disciplines sans lien avec le sujet",
            ],
            "ans": "Dépasser la contradiction pour formuler une idée nouvelle",
            "exp": "La synthèse ne tranche pas et ne résume pas : elle produit une idée qui transcende les deux positions précédentes.",
        },
        "ex2": {
            "q": "Transformez ce sujet en problématique : « La poésie et la réalité ».",
            "ans": "Dans quelle mesure la poésie transforme-t-elle notre perception de la réalité ?",
            "exp": "Une bonne problématique reformule le sujet en question ouverte et productive qui oriente l'argumentation.",
            "accept": [
                "En quoi la poésie offre-t-elle une vision différente de la réalité ?",
                "La poésie peut-elle nous faire voir la réalité autrement ?",
                "Comment la poésie redéfinit-elle notre rapport au réel ?",
            ],
        },
        "ex3": {
            "q": "Dans la structure AAEE d'une sous-partie, que signifie la lettre E finale ?",
            "opts": [
                "Étude (analyse grammaticale du texte)",
                "Explication (lien entre l'exemple et l'argument)",
                "Extension (ouverture vers une autre œuvre)",
                "Énonciation (reformulation de l'idée directrice)",
            ],
            "ans": "Explication (lien entre l'exemple et l'argument)",
            "exp": "Après avoir cité l'exemple précis, l'explication montre en quoi cet exemple illustre et renforce l'argument avancé.",
        },
        "game_desc": "Maîtrisez l'art de la dissertation littéraire de niveau C2",
        "items": [
            ("dissertation", "dissertation littéraire", "analyse dialectique d'une proposition sur la littérature", "essai académique", "Sa dissertation sur Proust a obtenu la mention très bien au DALF.", "dissertation = analyse dialectique d'une proposition littéraire", "dissertation"),
            ("problematique", "problématique", "question ouverte et productive qui oriente l'argumentation", "questionnement central", "La problématique bien formulée guide toute la réflexion.", "problématique = question ouverte et productive", "problématique"),
            ("dialectique", "dialectique", "progression thèse–antithèse–synthèse", "raisonnement par contradictions", "La démarche dialectique permet de nuancer les positions.", "dialectique = progression thèse–antithèse–synthèse", "dialectique"),
            ("these", "thèse", "première position affirmant une réponse au sujet", "affirmation initiale", "La thèse soutient que la fiction est un outil de connaissance.", "thèse = première position affirmant une réponse", "thèse"),
            ("antithese", "antithèse", "position contraire qui nuance ou contredit la thèse", "contre-argument", "L'antithèse montre les limites de la thèse initiale.", "antithèse = position contraire qui nuance la thèse", "antithèse"),
            ("accroche", "accroche", "phrase d'ouverture contextualisant le sujet", "entrée en matière", "L'accroche peut être une citation ou un paradoxe percutant.", "accroche = phrase d'ouverture contextualisant le sujet", "accroche"),
            ("paraphrase", "paraphrase", "résumé du texte sans analyse ni interprétation", "reformulation stérile", "La paraphrase est le piège majeur de la dissertation.", "paraphrase = résumé sans analyse — à éviter", "paraphrase"),
            ("synthese", "synthèse", "dépassement dialectique qui formule une idée nouvelle", "dépassement", "La synthèse va au-delà de la contradiction pour ouvrir de nouvelles perspectives.", "synthèse = dépassement dialectique qui formule une idée nouvelle", "synthèse"),
        ],
    },

    "l-epreuve-de-synthese": {
        "level": "c2",
        "section": "redaction",
        "num": "R02",
        "short": "Épreuve de Synthèse",
        "title": "L'Épreuve de Synthèse",
        "subtitle": "Synthétiser plusieurs documents en un texte cohérent et objectif",
        "slides": [
            ("Définition et enjeux",
             "L'épreuve de synthèse demande de croiser plusieurs documents (articles, extraits, graphiques) portant sur un même thème, pour en dégager les enjeux communs dans un texte cohérent et objectif. Elle évalue la capacité à lire activement, à identifier les idées clés et à les reformuler sans plagiat ni opinion personnelle."),
            ("Lire et annoter les documents",
             "Première étape : lire chaque document en notant sa nature (article journalistique, texte littéraire, données statistiques), son angle (pour ou contre, nuancé), ses idées principales et ses exemples clés. Utiliser des couleurs ou des symboles pour relier les idées communes entre documents. Identifier les convergences, divergences et complémentarités."),
            ("Construire le plan de la synthèse",
             "Le plan de la synthèse n'est pas chronologique (document 1, puis document 2…) mais thématique : les grandes idées se dégagent des documents croisés. Généralement deux ou trois parties, chacune traitant un aspect du thème. Chaque sous-partie intègre des informations de plusieurs documents — c'est le croisement qui définit la synthèse."),
            ("Rédiger : reformulation et croisement",
             "La reformulation évite le plagiat : paraphraser les idées avec ses propres mots tout en conservant le sens exact. Le croisement montre les liens : « Si le document A affirme X, le document B nuance en précisant Y. » Les sources sont citées par leur numéro (doc. 1, doc. 2) ou par le nom de l'auteur. Ne jamais citer de longues phrases directes."),
            ("Objectivité et neutralité",
             "La synthèse est un exercice de neutralité absolue : l'opinion personnelle est interdite. Utiliser des verbes de discours (« selon l'auteur », « le document indique », « il ressort de »), éviter les jugements de valeur, et présenter les divergences entre documents sans trancher. Les formules d'engagement personnel (« je pense », « à mon avis ») sont proscrites."),
            ("Introduction et conclusion",
             "L'introduction présente le thème global, précise la nature des documents et annonce le plan. La conclusion synthétise les grandes lignes en une ou deux phrases et peut indiquer des limites ou des questions non résolues — mais sans opinion personnelle. L'introduction et la conclusion sont brèves (trois à quatre phrases chacune)."),
            ("Pièges et erreurs fréquentes",
             "Plan document par document : erreur fondamentale — la synthèse doit croiser. Paraphrase directe : copier des phrases entières est considéré comme un plagiat. Opinion personnelle : la première personne et les jugements de valeur annulent la neutralité requise. Oubli d'un document : tous les documents doivent être exploités de manière équilibrée."),
            ("Longueur et présentation",
             "La synthèse au DALF C2 fait généralement 220 à 250 mots. La présentation est soignée : paragraphes distincts, pas de tirets ni de listes. Le titre du texte produit reprend le thème général. Le registre est neutre et soutenu : ni familier, ni excessivement technique."),
        ],
        "traps": [
            ("Plan chronologique", "Traiter les documents un par un au lieu de croiser les idées par thèmes — erreur fondamentale."),
            ("Plagiat", "Copier des phrases entières des documents sans reformuler — pénalisé au DALF."),
            ("Opinion personnelle", "Inclure « je pense » ou des jugements de valeur — interdit dans la synthèse."),
            ("Déséquilibre documentaire", "Exploiter un seul document en profondeur et ignorer les autres."),
        ],
        "summary": [
            "La synthèse croise plusieurs documents pour en dégager les enjeux communs de façon objective.",
            "Le plan est thématique, pas chronologique — les documents sont croisés dans chaque partie.",
            "Reformuler sans plagier, citer les sources par numéro ou auteur.",
            "L'opinion personnelle est strictement interdite.",
            "Introduction et conclusion sont brèves (3–4 phrases), sans jugement de valeur.",
            "Longueur cible au DALF C2 : 220–250 mots.",
        ],
        "ex1": {
            "q": "Pourquoi le plan « document par document » est-il interdit dans la synthèse ?",
            "opts": [
                "Parce qu'il est trop long et dépasse la limite de mots",
                "Parce qu'il ne permet pas de croiser les idées des documents entre eux",
                "Parce qu'il oblige à paraphraser chaque document en entier",
                "Parce qu'il révèle l'opinion personnelle du rédacteur",
            ],
            "ans": "Parce qu'il ne permet pas de croiser les idées des documents entre eux",
            "exp": "La synthèse se définit par le croisement des documents autour de thèmes communs — un plan chronologique juxtapose au lieu de synthétiser.",
        },
        "ex2": {
            "q": "Reformulez cette phrase sans plagiat : « La mondialisation a profondément transformé les échanges culturels. »",
            "ans": "Les échanges culturels ont été radicalement modifiés par le phénomène de mondialisation.",
            "exp": "La reformulation conserve le sens en changeant la structure syntaxique et en variant le lexique.",
            "accept": [
                "La mondialisation a bouleversé les interactions entre cultures.",
                "Les pratiques culturelles ont été profondément affectées par la mondialisation.",
                "Le phénomène mondialiste a reconfiguré les échanges entre cultures.",
            ],
        },
        "ex3": {
            "q": "Quelle formule convient à la synthèse pour introduire une divergence entre documents ?",
            "opts": [
                "« Je pense que le document 1 a tort car… »",
                "« Tandis que le document 1 affirme X, le document 2 nuance en précisant Y »",
                "« Le document 2 est plus intéressant que le document 1 »",
                "« En conclusion, les deux documents sont d'accord sur tout »",
            ],
            "ans": "« Tandis que le document 1 affirme X, le document 2 nuance en précisant Y »",
            "exp": "Cette formule croise les documents, présente leur divergence de façon neutre et objective, sans introduire d'opinion personnelle.",
        },
        "game_desc": "Maîtrisez la synthèse de documents de niveau C2",
        "items": [
            ("synthese", "synthèse de documents", "texte objectif croisant plusieurs sources autour d'un thème", "compte-rendu thématique", "La synthèse requiert de croiser les documents sans exprimer d'opinion.", "synthèse = texte objectif croisant plusieurs sources", "synthèse"),
            ("croisement", "croisement documentaire", "mise en relation des idées de plusieurs documents dans une même partie", "intégration thématique", "Le croisement est le cœur de la synthèse réussie.", "croisement = mise en relation des idées de plusieurs documents", "croisement"),
            ("reformulation", "reformulation", "réécriture d'une idée avec ses propres mots sans en changer le sens", "paraphrase non plagiaire", "La reformulation évite le plagiat tout en conservant le sens original.", "reformulation = réécriture sans plagiat", "reformulation"),
            ("neutralite", "neutralité", "absence de jugement de valeur ou d'opinion personnelle", "objectivité", "La neutralité absolue est exigée dans la synthèse de documents.", "neutralité = absence de jugement personnel", "neutralité"),
            ("convergence", "convergence", "accord entre les positions de plusieurs documents", "point commun", "Les documents convergent sur l'importance du développement durable.", "convergence = accord entre documents", "convergence"),
            ("divergence", "divergence", "désaccord ou nuance entre les positions de documents différents", "point de désaccord", "La divergence entre les deux textes enrichit l'analyse.", "divergence = désaccord entre documents", "divergence"),
            ("plagiat", "plagiat", "copie de phrases entières sans reformulation ni guillemets", "copie non signalée", "Le plagiat est sanctionné au DALF même sans intention.", "plagiat = copie sans reformulation — à éviter", "plagiat"),
            ("plan-thematique", "plan thématique", "organisation de la synthèse par idées transversales plutôt que par document", "plan par enjeux", "Un plan thématique croise les documents et révèle les enjeux communs.", "plan thématique = organisation par idées transversales", "plan thématique"),
        ],
    },

    "l-ecriture-d-invention": {
        "level": "c2",
        "section": "redaction",
        "num": "R03",
        "short": "Écriture d'Invention",
        "title": "L'Écriture d'Invention",
        "subtitle": "Créer un texte littéraire ou rhétorique en maîtrisant les registres et les genres",
        "slides": [
            ("Définition et genres",
             "L'écriture d'invention consiste à produire un texte en respectant un genre et un registre précis : poème en prose, monologue intérieur, discours délibératif, pastiche, dialogue philosophique, lettre ouverte, apologue. Chaque genre possède des codes formels (longueur des phrases, type de narration, figures de style attendues) qu'il faut maîtriser."),
            ("Lire le sujet avec précision",
             "Le sujet d'écriture d'invention précise toujours : le genre ou la forme (monologue, lettre, discours), le registre ou le ton (pathétique, ironique, satirique), la situation d'énonciation (qui parle, à qui, dans quel contexte). Il faut répondre à toutes ces contraintes. Négliger un paramètre — écrire en registre familier quand on demande du soutenu — est une faute de genre."),
            ("Le pastiche",
             "Le pastiche imite le style d'un auteur ou d'une époque sans le parodier. Il exige d'identifier les traits stylistiques caractéristiques : longueur et structure des phrases, champ lexical dominant, figures récurrentes (métaphores, personnifications), temps verbaux. Un pastiche de Flaubert mobilisera le style indirect libre, la précision du détail et l'ironie froide."),
            ("Le monologue intérieur",
             "Le monologue intérieur reproduit le flux de la pensée d'un personnage : syntaxe fragmentée, associations d'idées, ruptures temporelles, présent de conscience. Il peut être libre (sans ponctuation régulière, comme Joyce) ou structuré (comme Proust). L'enjeu est de montrer la complexité psychologique du personnage sans l'expliquer de l'extérieur."),
            ("Le discours argumentatif",
             "Le discours délibératif ou épidictique mobilise les ressources rhétoriques : apostrophe au destinataire, gradation, anaphore, question rhétorique, hypotypose. Il suppose une situation d'énonciation précise (éloge funèbre, plaidoyer, manifeste littéraire). Le registre oratoire use de périodes longues et de rythmes ternaires."),
            ("Travail stylistique",
             "L'écriture d'invention au niveau C2 est jugée sur la maîtrise stylistique : variété des structures syntaxiques, richesse lexicale (sans préciosité inutile), cohérence du registre, originalité des images. Éviter les clichés (« les yeux comme des étoiles », « le cœur lourd »), préférer des images inédites construites avec précision."),
            ("Relecture et révision",
             "Après rédaction, relire en cherchant : les ruptures de registre (passage involontaire au familier), les répétitions lexicales, les clichés, les incohérences de point de vue (changement de narrateur non justifié). Au DALF C2, quelques fautes d'orthographe graves (accord du participe passé, conjugaison du subjonctif imparfait) peuvent pénaliser une copie sinon remarquable."),
            ("Exemples de sujets",
             "« Vous écrirez le monologue intérieur d'un personnage qui attend un résultat décisif. » — « Rédigez une lettre ouverte à la manière de Zola en défense d'une cause contemporaine. » — « Composez un apologue sur le thème de la mémoire collective. » Chaque sujet impose un genre, un registre et une contrainte thématique à respecter."),
        ],
        "traps": [
            ("Ignorer les contraintes de genre", "Écrire librement sans respecter les codes du genre demandé (pastiche, monologue, discours) — faute fondamentale."),
            ("Clichés stylistiques", "Utiliser des images usées (« nuit noire comme l'encre », « larmes de joie ») au lieu d'images originales."),
            ("Rupture de registre", "Passer du registre soutenu au familier sans intention stylistique — signe d'un manque de maîtrise."),
            ("Confusion pastiche/parodie", "Le pastiche imite sérieusement le style ; la parodie l'exagère pour faire rire — ne pas confondre."),
        ],
        "summary": [
            "L'écriture d'invention respecte un genre précis (pastiche, monologue, discours, apologue) et ses codes formels.",
            "Lire le sujet attentivement : genre, registre, situation d'énonciation sont tous contraignants.",
            "Le pastiche imite un style sans parodier — identifier les traits stylistiques caractéristiques.",
            "Le monologue intérieur reproduit le flux de pensée avec une syntaxe fragmentée.",
            "Le discours mobilise les ressources rhétoriques : apostrophe, anaphore, gradation.",
            "Relire pour corriger ruptures de registre, répétitions, clichés et fautes d'accord.",
        ],
        "ex1": {
            "q": "Quelle est la différence entre le pastiche et la parodie ?",
            "opts": [
                "Le pastiche est plus long que la parodie",
                "Le pastiche imite sérieusement un style ; la parodie l'exagère pour faire rire",
                "La parodie est réservée à la poésie ; le pastiche à la prose",
                "Le pastiche change le registre ; la parodie conserve le registre original",
            ],
            "ans": "Le pastiche imite sérieusement un style ; la parodie l'exagère pour faire rire",
            "exp": "Le pastiche vise à reproduire fidèlement les traits stylistiques d'un auteur ou d'une époque ; la parodie les amplifie à des fins comiques ou critiques.",
        },
        "ex2": {
            "q": "Citez deux traits stylistiques caractéristiques du monologue intérieur.",
            "ans": "Syntaxe fragmentée et associations d'idées libres / flux de conscience",
            "exp": "Le monologue intérieur reproduit la pensée en cours : phrases inachevées, ruptures, associations, présent de conscience.",
            "accept": [
                "Phrases inachevées et ruptures temporelles",
                "Flux de conscience sans ponctuation régulière",
                "Associations d'idées libres et présent de conscience",
                "Syntaxe brisée et changements brusques de sujet",
            ],
        },
        "ex3": {
            "q": "Dans un discours épidictique, quelle figure de style organise souvent la montée émotionnelle vers le climax ?",
            "opts": [
                "L'euphémisme",
                "La litote",
                "La gradation",
                "L'anacoluthe",
            ],
            "ans": "La gradation",
            "exp": "La gradation organise les éléments en ordre croissant d'intensité, créant un effet de montée émotionnelle caractéristique du style oratoire.",
        },
        "game_desc": "Maîtrisez l'écriture d'invention littéraire au niveau C2",
        "items": [
            ("invention", "écriture d'invention", "production d'un texte littéraire respectant un genre et un registre imposés", "création contrainte", "L'écriture d'invention exige la maîtrise des codes génériques.", "écriture d'invention = production littéraire contrainte par un genre", "écriture d'invention"),
            ("pastiche", "pastiche", "imitation sérieuse du style d'un auteur ou d'une époque", "imitation stylistique", "Son pastiche de Proust reproduisait le style indirect libre avec précision.", "pastiche = imitation sérieuse d'un style", "pastiche"),
            ("monologue-interieur", "monologue intérieur", "reproduction du flux de pensée d'un personnage avec une syntaxe fragmentée", "stream of consciousness", "Le monologue intérieur révèle la psychologie du personnage de l'intérieur.", "monologue intérieur = flux de pensée à syntaxe fragmentée", "monologue intérieur"),
            ("registre", "registre de langue", "niveau de langue adapté à la situation et au genre (soutenu, courant, familier)", "niveau stylistique", "La cohérence du registre est essentielle dans l'écriture d'invention.", "registre = niveau de langue adapté au genre", "registre"),
            ("parodie", "parodie", "imitation exagérée d'un style à des fins comiques ou critiques", "détournement comique", "La parodie amplifie les traits stylistiques pour produire un effet comique.", "parodie = imitation exagérée à fin comique", "parodie"),
            ("apologue", "apologue", "court récit allégorique portant une leçon morale", "fable moderne", "L'apologue de La Fontaine dissimule une leçon morale derrière l'histoire animale.", "apologue = récit allégorique avec leçon morale", "apologue"),
            ("cliche", "cliché", "image ou expression usée par l'usage excessif", "lieu commun stylistique", "Les clichés affaiblissent le style — les éviter au C2.", "cliché = image usée à éviter", "cliché"),
            ("epidictique", "discours épidictique", "discours d'éloge ou de blâme visant à susciter l'admiration ou l'indignation", "éloge oratoire", "Le discours épidictique mobilise gradations, anaphores et apostrophes.", "épidictique = discours d'éloge ou de blâme", "épidictique"),
        ],
    },

    "la-traduction-et-commentaire-de-texte": {
        "level": "c2",
        "section": "redaction",
        "num": "R04",
        "short": "Traduction et Commentaire",
        "title": "La Traduction et le Commentaire de Texte",
        "subtitle": "Analyser un texte littéraire et rendre compte de ses enjeux stylistiques au niveau DALF C2",
        "slides": [
            ("Le commentaire de texte : définition",
             "Le commentaire de texte est une analyse linéaire ou thématique d'un extrait littéraire. Il vise à montrer comment le texte fonctionne — quels procédés stylistiques il emploie et quels effets ils produisent. Le commentaire n'est ni un résumé ni une dissertation : il suit le texte de près tout en dégageant des axes d'interprétation."),
            ("Lire et annoter le texte",
             "Première lecture globale : genre, époque, registre, ton général. Deuxième lecture analytique : noter les champs lexicaux, les figures de style (métaphore, hyperbole, ironie, anaphore), les temps verbaux et leur valeur, le rythme des phrases (parataxe/hypotaxe), les effets sonores (allitération, assonance). Troisième lecture : dégager deux ou trois axes d'interprétation."),
            ("Construire le plan du commentaire",
             "Plan thématique (le plus courant) : deux ou trois parties, chacune développant un axe interprétatif. Exemples d'axes : « un tableau de la désillusion » + « une critique implicite de la société » + « un style qui mime le désordre intérieur ». Chaque axe est développé en deux à trois sous-parties avec des citations précises du texte."),
            ("Citer et analyser",
             "Chaque affirmation sur le texte doit être prouvée par une citation entre guillemets, suivie d'une analyse du procédé et de son effet. Format type : « L'anaphore de ‘jamais’ (v. 3, 7, 12) crée un martèlement obsessionnel qui traduit le désespoir du narrateur. » Éviter les citations longues non commentées et les simples relevés sans interprétation."),
            ("Les figures de style au niveau C2",
             "À ce niveau, identifier non seulement la figure mais son effet précis et sa contribution au sens global. Hyperbole : exagération qui révèle l'état émotionnel. Litote : sous-énonciation qui souligne ironiquement. Chiasme : croisement syntaxique qui souligne une opposition. Anacoluthe : rupture syntaxique qui mime un désordre mental. Zeugme : alliance inattendue qui produit un effet comique ou poignant."),
            ("La traduction littéraire",
             "Traduire un texte littéraire exige de rendre non seulement le sens mais le style : rythme, registre, figures. Une traduction mot à mot trahit l'original. Il faut identifier d'abord le registre (soutenu/populaire), les effets sonores (impossible à reproduire à l'identique — trouver un équivalent fonctionnel) et les jeux de mots (nécessitent souvent une note du traducteur)."),
            ("Équivalences et choix du traducteur",
             "Le traducteur fait des choix : domestication (adapter à la culture cible) vs étrangisation (conserver l'étrangeté culturelle). Chaque choix doit être justifiable. Par exemple, traduire un dicton populaire par un dicton équivalent dans la langue cible (domestication) ou par une traduction littérale avec note (étrangisation). Le C2 exige de savoir argumenter ses choix."),
            ("Pièges du commentaire",
             "Paraphrase : résumer sans analyser. Plaquage de cours : réciter des définitions de figures sans les relier au texte précis. Hors-sujet : analyser un aspect non demandé. Déséquilibre : une partie très développée, les autres bâclées. Oublier la conclusion : le commentaire doit fermer sur une synthèse des axes et une ouverture (autre texte, question plus large)."),
        ],
        "traps": [
            ("Paraphrase", "Résumer le contenu du texte au lieu d'analyser ses procédés stylistiques."),
            ("Citation sans analyse", "Citer longuement le texte sans expliquer le procédé et son effet."),
            ("Plaquage de cours", "Réciter des définitions de figures de style sans les ancrer dans l'extrait précis."),
            ("Traduction mot à mot", "Traduire sans adapter le registre ni les équivalences culturelles — trahison du style original."),
        ],
        "summary": [
            "Le commentaire analyse comment le texte fonctionne — procédés stylistiques et effets — pas seulement ce qu'il dit.",
            "Trois lectures : globale, analytique (figures, rythme, lexique), interprétative (axes).",
            "Chaque affirmation est prouvée par une citation suivie d'une analyse du procédé et de l'effet.",
            "Identifier la figure de style ET son effet précis ET sa contribution au sens global.",
            "La traduction littéraire rend le sens ET le style — domestication vs étrangisation.",
            "Conclure sur une synthèse des axes et une ouverture vers une question plus large.",
        ],
        "ex1": {
            "q": "Dans un commentaire littéraire, comment doit-on utiliser les citations du texte ?",
            "opts": [
                "Les citer longuement pour montrer qu'on a lu le texte",
                "Les insérer entre guillemets, puis analyser le procédé stylistique et son effet",
                "Les paraphraser pour éviter les guillemets",
                "Les réserver uniquement à l'introduction et à la conclusion",
            ],
            "ans": "Les insérer entre guillemets, puis analyser le procédé stylistique et son effet",
            "exp": "Une citation sans analyse est une paraphrase déguisée. Le commentaire prouve ses affirmations par la citation, puis explique comment et pourquoi ce procédé produit cet effet.",
        },
        "ex2": {
            "q": "Expliquez la différence entre domestication et étrangisation en traduction.",
            "ans": "La domestication adapte le texte à la culture cible ; l'étrangisation conserve l'étrangeté culturelle de l'original.",
            "exp": "Ces deux stratégies s'opposent : domestiquer rend le texte familier au lecteur cible ; étrangiser lui fait percevoir la différence culturelle de l'œuvre originale.",
            "accept": [
                "Domestication = adapter à la culture du lecteur ; étrangisation = conserver les traits culturels de l'original.",
                "Domestiquer c'est rendre fluide pour le lecteur cible ; étrangiser c'est garder le caractère étranger du texte.",
                "La domestication efface les différences culturelles ; l'étrangisation les met en valeur.",
            ],
        },
        "ex3": {
            "q": "Quel est l'effet de l'anacoluthe dans un texte littéraire ?",
            "opts": [
                "Elle crée un rythme régulier et une impression de sérénité",
                "Elle souligne une opposition entre deux éléments symétriques",
                "Elle mime un désordre mental ou une rupture émotionnelle",
                "Elle amplifie une idée par accumulation d'images",
            ],
            "ans": "Elle mime un désordre mental ou une rupture émotionnelle",
            "exp": "L'anacoluthe est une rupture syntaxique — la phrase change de construction à mi-chemin. Elle reproduit l'irrégularité de la pensée ou d'un trouble psychologique.",
        },
        "game_desc": "Maîtrisez le commentaire de texte et la traduction littéraire au niveau C2",
        "items": [
            ("commentaire", "commentaire de texte", "analyse des procédés stylistiques d'un extrait et de leurs effets", "analyse littéraire", "Le commentaire suit le texte de près pour dégager ses enjeux stylistiques.", "commentaire = analyse des procédés et de leurs effets", "commentaire"),
            ("figure-de-style", "figure de style", "procédé rhétorique produisant un effet particulier sur le lecteur", "procédé stylistique", "L'anaphore, la métaphore et le chiasme sont des figures de style.", "figure de style = procédé rhétorique à effet", "figure de style"),
            ("chiasme", "chiasme", "croisement syntaxique de deux éléments en ordre inversé (ABBA)", "inversion croisée", "« Il faut manger pour vivre et non vivre pour manger » est un chiasme.", "chiasme = croisement syntaxique AB BA", "chiasme"),
            ("zeugme", "zeugme", "alliance inattendue de deux éléments liés à un même verbe mais incompatibles", "alliance discordante", "« Il prit son chapeau et congé » est un zeugme comique.", "zeugme = alliance inattendue de deux éléments", "zeugme"),
            ("anacoluthe", "anacoluthe", "rupture syntaxique à mi-phrase qui mime un désordre mental", "rupture de construction", "L'anacoluthe reproduit la discontinuité de la pensée intérieure.", "anacoluthe = rupture syntaxique mimant le désordre", "anacoluthe"),
            ("domestication", "domestication", "stratégie de traduction qui adapte le texte à la culture cible", "adaptation culturelle", "La domestication rend le texte fluide pour le lecteur cible.", "domestication = adaptation à la culture cible", "domestication"),
            ("etrangisation", "étrangisation", "stratégie de traduction qui conserve l'étrangeté culturelle de l'original", "conservation de l'altérité", "L'étrangisation préserve la différence culturelle de l'œuvre.", "étrangisation = conservation de l'étrangeté culturelle", "étrangisation"),
            ("axe-interpretatif", "axe interprétatif", "angle d'analyse qui organise une partie du commentaire autour d'un enjeu du texte", "angle de lecture", "Un axe interprétatif regroupe procédés stylistiques et sens autour d'un enjeu commun.", "axe interprétatif = angle d'analyse d'une partie", "axe interprétatif"),
        ],
    },
}
