"""francais B2 vocabulary — V05–V08"""

CHAPTERS = {
    "la-litterature": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V05",
        "short": "La Littérature",
        "title": "La Littérature",
        "subtitle": "Vocab — genres, procédés et analyse littéraire",
        "game_desc": "Maîtrisez le vocabulaire de l'analyse littéraire",
        "words": [
            {"word": "la métaphore", "ipa": "/me.ta.fɔʁ/", "def": "figure de style qui identifie deux réalités sans terme de comparaison", "ex": "« La vie est un voyage » est une métaphore classique de la poésie française."},
            {"word": "l'allégorie (f)", "ipa": "/a.le.gɔ.ʁi/", "def": "représentation d'une idée abstraite par une image ou un récit concret", "ex": "La cave de Platon est une allégorie de l'ignorance humaine."},
            {"word": "le narrateur omniscient", "ipa": "/na.ʁa.tœʁ ɔm.ni.sjɑ̃/", "def": "narrateur qui connaît les pensées et actions de tous les personnages", "ex": "Flaubert utilise un narrateur omniscient dans Madame Bovary."},
            {"word": "l'ironie (f)", "ipa": "/i.ʁɔ.ni/", "def": "figure consistant à dire le contraire de ce qu'on veut faire comprendre", "ex": "Voltaire manie l'ironie avec brio dans Candide pour critiquer la société."},
            {"word": "le dénouement", "ipa": "/de.nu.mɑ̃/", "def": "résolution finale de l'intrigue d'une œuvre", "ex": "Le dénouement tragique de Phèdre de Racine est inévitable dès le début."},
            {"word": "le pacte autobiographique", "ipa": "/pakt ɔ.tɔ.bjo.gʁa.fik/", "def": "engagement implicite de l'auteur à raconter véritablement sa propre vie", "ex": "Philippe Lejeune a théorisé le pacte autobiographique dans ses essais."},
            {"word": "l'intertextualité (f)", "ipa": "/ɛ̃.tɛʁ.tɛks.tɥa.li.te/", "def": "réseau de références et de citations entre différents textes littéraires", "ex": "L'intertextualité dans l'œuvre de Borges est une caractéristique majeure."},
            {"word": "le roman à clef", "ipa": "/ʁɔ.mɑ̃ a kle/", "def": "roman dont les personnages fictifs correspondent à des personnes réelles", "ex": "À la recherche du temps perdu de Proust est souvent lu comme un roman à clef."},
            {"word": "la vraisemblance", "ipa": "/vʁɛ.sɑ̃.blɑ̃s/", "def": "caractère de ce qui paraît vrai ou crédible dans un récit", "ex": "Les classiques accordent une grande importance à la vraisemblance."},
            {"word": "le registre", "ipa": "/ʁə.ʒistʁ/", "def": "ton général d'un texte (tragique, comique, lyrique, épique, etc.)", "ex": "Le registre ironique de Flaubert crée une distance avec ses personnages."},
            {"word": "la catharsis", "ipa": "/ka.taʁ.sis/", "def": "purification des émotions provoquée par une œuvre tragique", "ex": "Aristote voyait dans la catharsis la principale vertu de la tragédie."},
            {"word": "la diégèse", "ipa": "/dje.ʒɛz/", "def": "univers fictif dans lequel se déroule le récit", "ex": "La diégèse de Zola reflète fidèlement la société du XIXe siècle."},
            {"word": "le leitmotiv", "ipa": "/lajt.mɔ.tif/", "def": "motif, thème ou phrase qui revient régulièrement dans une œuvre", "ex": "Le leitmotiv de la madeleine structure la mémoire dans l'œuvre de Proust."},
            {"word": "l'anachronisme (m)", "ipa": "/a.na.kʁɔ.nism/", "def": "erreur ou procédé consistant à placer un élément hors de son époque", "ex": "L'auteur commet un anachronisme en plaçant une montre dans la Rome antique."},
            {"word": "le point de vue", "ipa": "/pwɛ̃ də vy/", "def": "perspective narrative depuis laquelle le récit est raconté", "ex": "Le choix du point de vue interne donne accès aux pensées du personnage."},
        ],
        "items": [
            ("litt-metaphore", "la métaphore", "figure de style identifiant deux réalités sans comparaison", "image · style · analogie", "« Le temps est un fleuve » est une métaphore du passage de la vie.", "métaphore = identification directe sans comparaison", "figure de style identifiant deux réalités sans comparaison"),
            ("litt-allegorie", "l'allégorie", "représentation d'une idée abstraite par un récit concret", "symbole · image · abstraction", "La fable de La Fontaine est souvent lue comme une allégorie morale.", "allégorie = idée abstraite représentée concrètement", "représentation d'une idée abstraite par un récit concret"),
            ("litt-ironie", "l'ironie", "dire le contraire de ce qu'on veut faire comprendre", "sarcasme · sous-entendu · dérision", "Voltaire use d'ironie pour critiquer le fanatisme sans le nommer.", "ironie = dire le contraire de ce qu'on pense", "dire le contraire de ce qu'on veut faire comprendre"),
            ("litt-catharsis", "la catharsis", "purification des émotions par une œuvre tragique", "émotion · tragédie · Aristote", "Le spectateur ressort purifié après avoir vécu la catharsis de la tragédie.", "catharsis = purification par les émotions tragiques", "purification des émotions par une œuvre tragique"),
            ("litt-intertextualite", "l'intertextualité", "réseau de références entre différents textes", "citation · référence · dialogue", "L'intertextualité enrichit un texte de multiples couches de sens.", "intertextualité = dialogue entre textes littéraires", "réseau de références entre différents textes"),
            ("litt-registre", "le registre", "ton général d'un texte littéraire", "ton · style · comique", "Choisir le bon registre est essentiel pour l'effet voulu sur le lecteur.", "registre = ton général d'un texte", "ton général d'un texte littéraire"),
            ("litt-denouement", "le dénouement", "résolution finale de l'intrigue d'une œuvre", "fin · conclusion · résolution", "Le dénouement d'une pièce classique résout toutes les tensions de l'intrigue.", "dénouement = résolution finale de l'intrigue", "résolution finale de l'intrigue d'une œuvre"),
            ("litt-point-de-vue", "le point de vue", "perspective depuis laquelle le récit est raconté", "narrateur · interne · externe", "Un point de vue interne nous plonge dans la conscience du personnage.", "point de vue = perspective narrative du récit", "perspective depuis laquelle le récit est raconté"),
        ],
    },

    "la-justice-sociale": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V06",
        "short": "La Justice Sociale",
        "title": "La Justice Sociale",
        "subtitle": "Vocab — inégalités, droits et solidarité",
        "game_desc": "Maîtrisez le vocabulaire de la justice sociale",
        "words": [
            {"word": "la discrimination", "ipa": "/dis.kʁi.mi.na.sjɔ̃/", "def": "traitement inégal fondé sur un critère illégitime (origine, genre, âge...)", "ex": "La loi interdit la discrimination à l'embauche en raison de l'origine ethnique."},
            {"word": "l'équité (f)", "ipa": "/e.ki.te/", "def": "traitement juste qui tient compte des inégalités de départ", "ex": "L'équité suppose d'adapter le traitement selon les besoins de chacun."},
            {"word": "la précarité", "ipa": "/pʁe.ka.ʁi.te/", "def": "situation d'instabilité économique et sociale durable", "ex": "La précarité des travailleurs indépendants s'est aggravée pendant la crise."},
            {"word": "la solidarité", "ipa": "/sɔ.li.da.ʁi.te/", "def": "lien de soutien mutuel au sein d'un groupe ou d'une société", "ex": "La solidarité nationale s'exprime à travers les systèmes de protection sociale."},
            {"word": "l'inclusion (f)", "ipa": "/ɛ̃.kly.zjɔ̃/", "def": "démarche visant à intégrer toutes les personnes dans la société sans discrimination", "ex": "L'école inclusive accueille les élèves en situation de handicap dans les classes ordinaires."},
            {"word": "la marginalisation", "ipa": "/maʁ.ʒi.na.li.za.sjɔ̃/", "def": "processus par lequel des groupes sont exclus de la société dominante", "ex": "La marginalisation des sans-abris est un enjeu majeur dans les grandes villes."},
            {"word": "le plafond de verre", "ipa": "/pla.fɔ̃ də vɛʁ/", "def": "barrière invisible qui empêche certains groupes d'accéder aux postes élevés", "ex": "Le plafond de verre freine encore la carrière de nombreuses femmes."},
            {"word": "l'intersectionnalité (f)", "ipa": "/ɛ̃.tɛʁ.sɛk.sjɔ.na.li.te/", "def": "approche qui analyse les discriminations combinées (genre, race, classe…)", "ex": "L'intersectionnalité permet de comprendre des formes de discrimination multiples."},
            {"word": "la mixité sociale", "ipa": "/mik.si.te sɔ.sjal/", "def": "coexistence de personnes d'origines sociales différentes dans un même lieu", "ex": "La mixité sociale à l'école est jugée essentielle pour réduire les inégalités."},
            {"word": "la redistribution", "ipa": "/ʁə.dis.tʁi.by.sjɔ̃/", "def": "transfert de richesses des plus aisés vers les moins favorisés via l'impôt", "ex": "La redistribution fiscale est le fondement de l'État providence français."},
            {"word": "la mobilité sociale", "ipa": "/mɔ.bi.li.te sɔ.sjal/", "def": "capacité pour un individu de changer de position dans la hiérarchie sociale", "ex": "La mobilité sociale ascendante dépend largement du niveau d'éducation."},
            {"word": "l'empowerment (m)", "ipa": "/ɛm.pawɛʁ.mɑ̃t/", "def": "processus par lequel des individus ou groupes gagnent en pouvoir et autonomie", "ex": "Des programmes d'empowerment soutiennent les femmes dans les pays en développement."},
            {"word": "le revenu universel", "ipa": "/ʁə.və.ny y.ni.vɛʁ.sɛl/", "def": "allocation versée à tous les citoyens sans condition de ressources", "ex": "Des expérimentations de revenu universel ont été menées en Finlande et au Kenya."},
            {"word": "la ségrégation", "ipa": "/se.gʁe.ga.sjɔ̃/", "def": "séparation de groupes sociaux ou ethniques dans l'espace ou les institutions", "ex": "La ségrégation scolaire par le prix du logement accentue les inégalités."},
            {"word": "l'ascenseur social (m)", "ipa": "/a.sɑ̃.sœʁ sɔ.sjal/", "def": "métaphore désignant les mécanismes permettant de progresser socialement", "ex": "Beaucoup estiment que l'ascenseur social est en panne en France."},
        ],
        "items": [
            ("justice-discrimination", "la discrimination", "traitement inégal fondé sur un critère illégitime", "inégalité · origine · genre", "La discrimination positive vise à corriger des inégalités structurelles.", "discrimination = traitement inégal et injuste", "traitement inégal fondé sur un critère illégitime"),
            ("justice-equite", "l'équité", "traitement juste tenant compte des inégalités de départ", "justice · adaptation · besoins", "L'équité va plus loin que l'égalité en compensant les désavantages.", "équité = justice adaptée aux inégalités de départ", "traitement juste tenant compte des inégalités de départ"),
            ("justice-precarite", "la précarité", "situation d'instabilité économique durable", "instabilité · pauvreté · emploi", "La précarité de l'emploi touche surtout les jeunes sans qualification.", "précarité = instabilité économique et sociale durable", "situation d'instabilité économique durable"),
            ("justice-inclusion", "l'inclusion", "intégrer toutes les personnes sans discrimination", "intégration · handicap · diversité", "Une société inclusive reconnaît et valorise toutes les différences.", "inclusion = intégration sans discrimination", "intégrer toutes les personnes sans discrimination"),
            ("justice-plafond-verre", "le plafond de verre", "barrière invisible bloquant l'accès aux postes élevés", "carrière · femmes · inégalité", "Briser le plafond de verre exige des politiques volontaristes en entreprise.", "plafond de verre = barrière invisible à la promotion", "barrière invisible bloquant l'accès aux postes élevés"),
            ("justice-redistribution", "la redistribution", "transfert de richesses via l'impôt", "impôt · fiscalité · État providence", "La redistribution réduit les écarts entre les revenus les plus hauts et les plus bas.", "redistribution = transfert fiscal des riches vers les pauvres", "transfert de richesses via l'impôt"),
            ("justice-mobilite", "la mobilité sociale", "capacité à changer de position dans la hiérarchie sociale", "ascension · classe · éducation", "La mobilité sociale est souvent liée aux opportunités d'accès à l'éducation.", "mobilité sociale = changement de position dans la hiérarchie", "capacité à changer de position dans la hiérarchie sociale"),
            ("justice-ascenseur", "l'ascenseur social", "mécanismes permettant de progresser socialement", "promotion · égalité des chances · méritocratie", "Quand l'ascenseur social est en panne, les inégalités se figent entre générations.", "ascenseur social = mécanismes de progression sociale", "mécanismes permettant de progresser socialement"),
        ],
    },

    "l-economie-avancee": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V07",
        "short": "L'Économie Avancée",
        "title": "L'Économie Avancée",
        "subtitle": "Vocab — marchés, politiques économiques et mondialisation",
        "game_desc": "Maîtrisez le vocabulaire économique avancé",
        "words": [
            {"word": "la stagflation", "ipa": "/staɡ.fla.sjɔ̃/", "def": "combinaison de stagnation économique et d'inflation simultanées", "ex": "La stagflation des années 1970 a remis en cause les théories keynésiennes."},
            {"word": "la déflation", "ipa": "/de.fla.sjɔ̃/", "def": "baisse généralisée et durable des prix dans une économie", "ex": "La déflation peut paralyser une économie car les consommateurs reportent leurs achats."},
            {"word": "le PIB (produit intérieur brut)", "ipa": "/pe.i.be/", "def": "valeur totale des biens et services produits dans un pays sur une période", "ex": "Le PIB de la France a reculé de 8 % en 2020 en raison de la pandémie."},
            {"word": "la dette souveraine", "ipa": "/dɛt su.vʁɛn/", "def": "dette d'un État envers ses créanciers nationaux et internationaux", "ex": "La crise de la dette souveraine grecque a menacé la stabilité de la zone euro."},
            {"word": "le protectionnisme", "ipa": "/pʁɔ.tɛk.sjɔ.nism/", "def": "politique économique qui protège l'industrie nationale de la concurrence étrangère", "ex": "Les droits de douane sont un outil classique du protectionnisme."},
            {"word": "la mondialisation", "ipa": "/mɔ̃.dja.li.za.sjɔ̃/", "def": "intégration croissante des économies et des cultures à l'échelle mondiale", "ex": "La mondialisation a réduit la pauvreté dans certains pays mais creusé les inégalités dans d'autres."},
            {"word": "l'austérité (f)", "ipa": "/ɔs.te.ʁi.te/", "def": "politique de réduction des dépenses publiques pour diminuer les déficits", "ex": "Les politiques d'austérité imposées à la Grèce ont provoqué de graves tensions sociales."},
            {"word": "la spéculation", "ipa": "/spe.ky.la.sjɔ̃/", "def": "opération financière à haut risque visant à tirer profit des fluctuations des marchés", "ex": "La spéculation immobilière a alimenté la bulle qui a éclaté en 2008."},
            {"word": "l'oligopole (m)", "ipa": "/ɔ.li.gɔ.pɔl/", "def": "marché dominé par un petit nombre de grandes entreprises", "ex": "Le secteur des télécommunications est souvent un oligopole dans les petits pays."},
            {"word": "la valeur ajoutée", "ipa": "/va.lœʁ a.ʒu.te/", "def": "valeur créée par une entreprise au-delà du coût de ses intrants", "ex": "La TVA est calculée sur la valeur ajoutée à chaque étape de production."},
            {"word": "l'externalité (f)", "ipa": "/ɛks.tɛʁ.na.li.te/", "def": "effet non marchand d'une activité économique sur des tiers", "ex": "La pollution est une externalité négative de la production industrielle."},
            {"word": "le taux de chômage", "ipa": "/to də ʃo.maʒ/", "def": "pourcentage de personnes sans emploi parmi la population active", "ex": "Le taux de chômage des jeunes dépasse 20 % dans plusieurs pays de l'UE."},
            {"word": "la balance commerciale", "ipa": "/ba.lɑ̃s kɔ.mɛʁ.sjal/", "def": "différence entre les exportations et les importations d'un pays", "ex": "La France affiche un déficit de sa balance commerciale depuis plusieurs années."},
            {"word": "le déficit budgétaire", "ipa": "/de.fi.si byd.ʒe.tɛʁ/", "def": "excédent des dépenses publiques sur les recettes de l'État", "ex": "Réduire le déficit budgétaire est l'objectif principal du plan d'économies du gouvernement."},
            {"word": "l'économie de marché (f)", "ipa": "/e.kɔ.nɔ.mi də maʁ.ʃe/", "def": "système économique fondé sur la loi de l'offre et de la demande", "ex": "Dans une économie de marché, les prix sont fixés par la concurrence."},
        ],
        "items": [
            ("eco-stagflation", "la stagflation", "stagnation économique et inflation simultanées", "inflation · croissance · crise", "La stagflation contraint les banques centrales à des arbitrages difficiles.", "stagflation = stagnation + inflation simultanées", "stagnation économique et inflation simultanées"),
            ("eco-deflation", "la déflation", "baisse généralisée et durable des prix", "prix · consommation · trappe", "La déflation crée une spirale où les agents économiques retardent leurs achats.", "déflation = baisse générale et durable des prix", "baisse généralisée et durable des prix"),
            ("eco-dette-souveraine", "la dette souveraine", "dette d'un État envers ses créanciers", "emprunt · État · crise", "La crise de la dette souveraine peut menacer la monnaie commune d'une union.", "dette souveraine = endettement de l'État", "dette d'un État envers ses créanciers"),
            ("eco-protectionnisme", "le protectionnisme", "politique protégeant l'industrie nationale", "droits de douane · barrières · commerce", "Le protectionnisme peut préserver des emplois mais renchérit les importations.", "protectionnisme = protection de l'industrie nationale", "politique protégeant l'industrie nationale"),
            ("eco-austerite", "l'austérité", "réduction des dépenses publiques pour diminuer les déficits", "coupes · déficit · rigueur", "Les plans d'austérité entraînent souvent une baisse du pouvoir d'achat.", "austérité = réduction des dépenses de l'État", "réduction des dépenses publiques pour diminuer les déficits"),
            ("eco-speculation", "la spéculation", "opération financière à haut risque sur les marchés", "marché · risque · bulle", "La spéculation débridée peut engendrer des crises financières systémiques.", "spéculation = pari financier risqué sur les marchés", "opération financière à haut risque sur les marchés"),
            ("eco-externalite", "l'externalité", "effet non marchand d'une activité sur des tiers", "pollution · coût social · marché", "Les externalités négatives justifient souvent l'intervention de l'État.", "externalité = impact non marchand sur les tiers", "effet non marchand d'une activité sur des tiers"),
            ("eco-balance", "la balance commerciale", "différence exportations moins importations", "exportations · importations · déficit", "Un excédent de la balance commerciale renforce la position d'un pays.", "balance commerciale = exports moins imports", "différence exportations moins importations"),
        ],
    },

    "la-culture-mondiale": {
        "level": "b2",
        "section": "vocabulaire",
        "num": "V08",
        "short": "La Culture Mondiale",
        "title": "La Culture Mondiale",
        "subtitle": "Vocab — identité, patrimoine et soft power",
        "game_desc": "Maîtrisez le vocabulaire de la culture mondiale",
        "words": [
            {"word": "le patrimoine immatériel", "ipa": "/pat.ʁi.mwan i.ma.te.ʁjɛl/", "def": "traditions vivantes transmises entre générations (musique, savoir-faire, rituels)", "ex": "Le repas gastronomique français est inscrit au patrimoine immatériel de l'UNESCO."},
            {"word": "le soft power", "ipa": "/sɔft pawɛʁ/", "def": "influence exercée par un pays à travers sa culture, ses valeurs et son image", "ex": "La diffusion mondiale de la culture américaine illustre un soft power considérable."},
            {"word": "l'acculturation (f)", "ipa": "/a.kyl.ty.ʁa.sjɔ̃/", "def": "processus de transformation culturelle par contact prolongé entre deux cultures", "ex": "L'acculturation des immigrés implique souvent une hybridation culturelle."},
            {"word": "le cosmopolitisme", "ipa": "/kɔz.mɔ.pɔ.li.tism/", "def": "attitude ou philosophie qui se réclame d'un attachement à l'humanité entière", "ex": "Le cosmopolitisme s'oppose aux nationalismes étroits en valorisant l'ouverture."},
            {"word": "la diversité culturelle", "ipa": "/di.vɛʁ.si.te kyl.ty.ʁɛl/", "def": "coexistence de multiples cultures et expressions culturelles dans le monde", "ex": "L'UNESCO défend la diversité culturelle comme patrimoine commun de l'humanité."},
            {"word": "l'impérialisme culturel (m)", "ipa": "/ɛ̃.pe.ʁja.lism kyl.ty.ʁɛl/", "def": "domination des expressions culturelles d'un pays fort sur des cultures locales", "ex": "Certains voient dans la diffusion des séries américaines un impérialisme culturel."},
            {"word": "la francophonie", "ipa": "/fʁɑ̃.kɔ.fɔ.ni/", "def": "ensemble des peuples et des pays qui utilisent le français comme langue", "ex": "La francophonie regroupe plus de 300 millions de locuteurs sur cinq continents."},
            {"word": "l'identité culturelle (f)", "ipa": "/i.dɑ̃.ti.te kyl.ty.ʁɛl/", "def": "sentiment d'appartenance à une culture, une langue ou une communauté", "ex": "La mondialisation peut fragiliser les identités culturelles locales."},
            {"word": "le métissage culturel", "ipa": "/me.ti.saʒ kyl.ty.ʁɛl/", "def": "fusion et mélange de traditions culturelles différentes", "ex": "La musique brésilienne est le produit d'un riche métissage culturel."},
            {"word": "le relativisme culturel", "ipa": "/ʁə.la.ti.vism kyl.ty.ʁɛl/", "def": "principe selon lequel chaque culture doit être comprise dans son propre contexte", "ex": "Le relativisme culturel interdit de juger une pratique sans connaître son contexte."},
            {"word": "la mondialisation culturelle", "ipa": "/mɔ̃.dja.li.za.sjɔ̃ kyl.ty.ʁɛl/", "def": "diffusion mondiale des produits et pratiques culturels au-delà des frontières", "ex": "La mondialisation culturelle homogénéise parfois les modes de vie."},
            {"word": "l'exception culturelle (f)", "ipa": "/ɛk.sɛp.sjɔ̃ kyl.ty.ʁɛl/", "def": "principe français selon lequel la culture ne doit pas être soumise aux lois du marché", "ex": "La France défend l'exception culturelle dans les négociations commerciales internationales."},
            {"word": "le patrimoine mondial", "ipa": "/pat.ʁi.mwan mɔ̃.djal/", "def": "sites et biens culturels ou naturels d'importance universelle protégés par l'UNESCO", "ex": "Le Mont-Saint-Michel figure sur la liste du patrimoine mondial de l'UNESCO."},
            {"word": "la diglossie", "ipa": "/di.ɡlɔ.si/", "def": "situation dans laquelle deux langues coexistent avec des statuts différents dans une société", "ex": "La diglossie entre le breton et le français a longtemps minorisé la langue bretonne."},
            {"word": "la créolisation", "ipa": "/kʁe.ɔ.li.za.sjɔ̃/", "def": "processus de formation d'une nouvelle culture à partir de plusieurs cultures en contact", "ex": "La culture antillaise est le produit d'une créolisation entre l'Europe, l'Afrique et l'Amérique."},
        ],
        "items": [
            ("culture-patrimoine-imm", "le patrimoine immatériel", "traditions vivantes transmises entre générations", "UNESCO · traditions · savoir-faire", "Le flamenco espagnol est inscrit au patrimoine immatériel de l'UNESCO.", "patrimoine immatériel = traditions vivantes protégées", "traditions vivantes transmises entre générations"),
            ("culture-soft-power", "le soft power", "influence culturelle d'un pays dans le monde", "influence · culture · image", "Le cinéma hollywoodien est un vecteur majeur du soft power américain.", "soft power = influence par la culture et les valeurs", "influence culturelle d'un pays dans le monde"),
            ("culture-acculturation", "l'acculturation", "transformation culturelle par contact entre deux cultures", "hybridation · contact · transformation", "L'acculturation n'est pas une simple assimilation mais un échange mutuel.", "acculturation = transformation par contact culturel", "transformation culturelle par contact entre deux cultures"),
            ("culture-cosmopolitisme", "le cosmopolitisme", "attachement à l'humanité entière plutôt qu'à une nation", "ouverture · humanité · diversité", "Le cosmopolitisme rejette les frontières comme limites de l'identité.", "cosmopolitisme = appartenance à l'humanité entière", "attachement à l'humanité entière plutôt qu'à une nation"),
            ("culture-exception", "l'exception culturelle", "principe que la culture n'est pas une marchandise", "France · marché · protection", "L'exception culturelle justifie les subventions au cinéma français.", "exception culturelle = la culture hors du marché", "principe que la culture n'est pas une marchandise"),
            ("culture-metissage", "le métissage culturel", "fusion de traditions culturelles différentes", "mélange · hybride · rencontre", "Le jazz est né du métissage culturel entre traditions africaines et européennes.", "métissage culturel = fusion de cultures différentes", "fusion de traditions culturelles différentes"),
            ("culture-francophonie", "la francophonie", "ensemble des pays utilisant le français", "français · langue · OIF", "La francophonie est un espace de dialogue entre cultures très diverses.", "francophonie = communauté des pays francophones", "ensemble des pays utilisant le français"),
            ("culture-relativisme", "le relativisme culturel", "chaque culture doit être comprise dans son contexte", "contexte · jugement · anthropologie", "Le relativisme culturel invite à comprendre avant de juger.", "relativisme culturel = comprendre chaque culture en son contexte", "chaque culture doit être comprise dans son contexte"),
        ],
    },
}
