"""
francais-en A2 Vocabulary V01–V08  (French for English Speakers)
Generator: gen_francais_en.py
words format: (french_word, ipa, english_def, french_example)
"""

CHAPTERS = {

    # ------------------------------------------------------------------ V01
    "les-emotions": {
        "level": "a2", "section": "vocabulary", "num": "V01",
        "short": "Emotions & Feelings",
        "title": "Emotions & Feelings",
        "subtitle": "Les émotions — expressing how you feel",
        "words": [
            ("heureux / heureuse", "/ø.ʁø/", "happy", "Je suis heureux aujourd'hui."),
            ("triste", "/tʁist/", "sad", "Elle est triste depuis lundi."),
            ("content(e)", "/kɔ̃.tɑ̃/", "pleased / happy", "Je suis content du résultat."),
            ("énervé(e)", "/e.nɛʁ.ve/", "annoyed / irritated", "Il est énervé par le bruit."),
            ("inquiet / inquiète", "/ɛ̃.kjɛ/", "worried / anxious", "Elle est inquiète pour son fils."),
            ("surpris(e)", "/syʁ.pʁi/", "surprised", "Nous sommes surpris par les nouvelles."),
            ("fier / fière", "/fjɛʁ/", "proud", "Il est fier de sa fille."),
            ("déçu(e)", "/de.sy/", "disappointed", "Je suis déçu par ce film."),
            ("soulagé(e)", "/su.la.ʒe/", "relieved", "Elle est soulagée d'avoir réussi."),
            ("nerveux / nerveuse", "/nɛʁ.vø/", "nervous", "Il est nerveux avant l'examen."),
            ("calme", "/kalm/", "calm", "Reste calme — tout va bien."),
            ("en colère", "/ɑ̃ kɔ.lɛʁ/", "angry", "Il est en colère contre son ami."),
            ("amoureux / amoureuse", "/a.mu.ʁø/", "in love", "Elle est amoureuse de Paul."),
            ("gêné(e)", "/ʒe.ne/", "embarrassed", "Il est gêné par sa faute."),
            ("fatigué(e)", "/fa.ti.ɡe/", "tired", "Je suis fatigué après le match."),
        ],
        "game_desc": "Learn French emotion vocabulary with meaning, context, and production.",
        "items": [
            ("em1", "heureux / heureuse", "happy", "joyful", "Je suis très heureux de te revoir.", "Complète: Elle est ___. (happy, f.)", "heureuse"),
            ("em2", "triste", "sad", "sad", "Il est triste car son ami est parti.", "Complète: Je suis ___. (sad)", "triste"),
            ("em3", "inquiet / inquiète", "worried", "anxious", "Elle est inquiète — son fils rentre tard.", "Complète: Il est ___ pour elle. (worried, m.)", "inquiet"),
            ("em4", "déçu(e)", "disappointed", "let down", "Je suis déçu par les résultats.", "Complète: Elle est ___. (disappointed, f.)", "déçue"),
            ("em5", "surpris(e)", "surprised", "amazed", "Nous sommes surpris par ta décision.", "Complète: Il est ___ ! (surprised, m.)", "surpris"),
            ("em6", "en colère", "angry", "furious", "Il est en colère contre son patron.", "Complète: Elle est en ___. (angry)", "colère"),
            ("em7", "fier / fière", "proud", "proud", "Ils sont fiers de leurs enfants.", "Complète: Je suis ___ de toi. (proud, m.)", "fier"),
            ("em8", "soulagé(e)", "relieved", "relieved", "Elle est soulagée d'avoir réussi l'examen.", "Complète: Je suis ___. (relieved, m.)", "soulagé"),
        ],
    },

    # ------------------------------------------------------------------ V02
    "les-professions": {
        "level": "a2", "section": "vocabulary", "num": "V02",
        "short": "Jobs & Professions",
        "title": "Jobs & Professions",
        "subtitle": "Les professions — careers and the workplace",
        "words": [
            ("le médecin", "/me.dɛ̃/", "doctor (general)", "Mon père est médecin."),
            ("l'infirmier / l'infirmière", "/ɛ̃.fiʁ.mje/", "nurse (m/f)", "Elle est infirmière à l'hôpital."),
            ("le professeur", "/pʁo.fɛ.sœʁ/", "teacher / professor", "Elle est professeure de maths."),
            ("l'avocat(e)", "/a.vɔ.ka/", "lawyer", "Il est avocat dans un grand cabinet."),
            ("l'ingénieur(e)", "/ɛ̃.ʒe.njœʁ/", "engineer", "Elle est ingénieure en informatique."),
            ("le / la journaliste", "/ʒuʁ.na.list/", "journalist", "Il est journaliste pour Le Monde."),
            ("le cuisinier / la cuisinière", "/kɥi.zi.nje/", "cook / chef", "Elle est cuisinière dans un restaurant."),
            ("l'acteur / l'actrice", "/ak.tœʁ/", "actor / actress", "Il rêve de devenir acteur."),
            ("le / la secrétaire", "/sə.kʁe.tɛʁ/", "secretary / admin", "Elle est secrétaire dans une école."),
            ("le / la comptable", "/kɔ̃.tabl/", "accountant", "Il est comptable dans une banque."),
            ("le pompier", "/pɔ̃.pje/", "firefighter", "Il est pompier depuis dix ans."),
            ("le policier / la policière", "/pɔ.li.sje/", "police officer", "Elle est policière dans le 13e."),
            ("le vendeur / la vendeuse", "/vɑ̃.dœʁ/", "salesperson / shop assistant", "Elle est vendeuse dans une boutique."),
            ("le chef d'entreprise", "/ʃɛf dɑ̃.tʁə.pʁiz/", "business owner / CEO", "Il est chef d'entreprise."),
            ("travailler comme", "/tʁa.va.je/", "to work as", "Je travaille comme interprète."),
        ],
        "game_desc": "Learn French job and profession vocabulary.",
        "items": [
            ("pr1", "le médecin", "doctor", "GP", "Mon médecin est très compétent.", "Complète: Elle est ___. (doctor)", "médecin"),
            ("pr2", "l'infirmier / l'infirmière", "nurse", "nurse", "L'infirmière prend la tension du patient.", "Complète: Il est ___. (nurse, m.)", "infirmier"),
            ("pr3", "le professeur", "teacher", "teacher", "Elle est professeure de français.", "Complète: Il est ___ de maths. (teacher)", "professeur"),
            ("pr4", "l'avocat(e)", "lawyer", "solicitor", "Il travaille comme avocat depuis 15 ans.", "Complète: Elle est ___. (lawyer, f.)", "avocate"),
            ("pr5", "l'ingénieur(e)", "engineer", "engineer", "Elle est ingénieure dans une start-up.", "Complète: Il est ___. (engineer)", "ingénieur"),
            ("pr6", "le pompier", "firefighter", "firefighter", "Les pompiers ont éteint l'incendie rapidement.", "Complète: Il est ___. (firefighter)", "pompier"),
            ("pr7", "le policier / la policière", "police officer", "police officer", "La policière a aidé la vieille dame.", "Complète: Il est ___. (police officer, m.)", "policier"),
            ("pr8", "travailler comme", "to work as", "work as", "Je travaille comme secrétaire dans une école.", "Complète: Elle ___ comme infirmière. (works)", "travaille"),
        ],
    },

    # ------------------------------------------------------------------ V03
    "la-ville": {
        "level": "a2", "section": "vocabulary", "num": "V03",
        "short": "The Town",
        "title": "The Town & City",
        "subtitle": "La ville — places, directions, and services",
        "words": [
            ("la mairie", "/ma.ʁi/", "town hall", "Je vais à la mairie pour mes papiers."),
            ("la bibliothèque", "/bi.bljɔ.tɛk/", "library", "J'emprunte des livres à la bibliothèque."),
            ("la pharmacie", "/faʁ.ma.si/", "pharmacy / chemist", "Je vais à la pharmacie chercher des médicaments."),
            ("la boulangerie", "/bu.lɑ̃.ʒʁi/", "bakery", "La boulangerie est ouverte dès 7h."),
            ("la boucherie", "/buʃ.ʁi/", "butcher's", "Il achète de la viande à la boucherie."),
            ("le marché", "/maʁ.ʃe/", "market", "On va au marché le samedi matin."),
            ("le supermarché", "/sy.pɛʁ.maʁ.ʃe/", "supermarket", "J'achète mes légumes au supermarché."),
            ("la poste", "/pɔst/", "post office", "Je vais à la poste envoyer un colis."),
            ("la banque", "/bɑ̃k/", "bank", "La banque est fermée le lundi."),
            ("l'hôtel de ville", "/o.tɛl də vil/", "city hall", "Le concert a lieu devant l'hôtel de ville."),
            ("le parc", "/paʁk/", "park", "Les enfants jouent au parc."),
            ("le musée", "/my.ze/", "museum", "Ce musée est gratuit le premier dimanche."),
            ("à gauche / à droite", "/a ɡoʃ / a dʁwat/", "on the left / right", "C'est à gauche du supermarché."),
            ("tout droit", "/tu dʁwa/", "straight ahead", "Allez tout droit et tournez à gauche."),
            ("en face de", "/ɑ̃ fas də/", "opposite / facing", "La pharmacie est en face de la gare."),
        ],
        "game_desc": "Learn French town vocabulary and directional expressions.",
        "items": [
            ("vil1", "la bibliothèque", "library", "library", "J'emprunte des livres à la bibliothèque.", "Complète: La ___ est ouverte jusqu'à 20h. (library)", "bibliothèque"),
            ("vil2", "la pharmacie", "pharmacy", "chemist", "Je vais à la pharmacie pour des médicaments.", "Complète: La ___ est fermée le dimanche. (pharmacy)", "pharmacie"),
            ("vil3", "la boulangerie", "bakery", "bakery", "La boulangerie vend du pain frais le matin.", "Complète: J'achète mon pain à la ___. (bakery)", "boulangerie"),
            ("vil4", "le marché", "market", "market", "On trouve des légumes frais au marché.", "Complète: Le ___ a lieu le samedi. (market)", "marché"),
            ("vil5", "la poste", "post office", "post office", "J'envoie un colis à la poste.", "Complète: La ___ ferme à 17h. (post office)", "poste"),
            ("vil6", "à gauche / à droite", "on the left / right", "left right", "Tournez à gauche après le feu.", "Complète: C'est à ___ de la poste. (right)", "droite"),
            ("vil7", "tout droit", "straight ahead", "straight on", "Continuez tout droit pendant 200 mètres.", "Complète: Allez ___ droit. (straight)", "tout"),
            ("vil8", "en face de", "opposite", "opposite", "La banque est en face de la pharmacie.", "Complète: C'est en ___ de la gare. (opposite)", "face"),
        ],
    },

    # ------------------------------------------------------------------ V04
    "les-loisirs": {
        "level": "a2", "section": "vocabulary", "num": "V04",
        "short": "Hobbies & Free Time",
        "title": "Hobbies & Free Time",
        "subtitle": "Les loisirs — activities, sport, and pastimes",
        "words": [
            ("le loisir", "/lwa.ziʁ/", "leisure / hobby", "Quels sont tes loisirs ?"),
            ("faire du sport", "/fɛʁ dy spɔʁ/", "to do / play sport", "Je fais du sport trois fois par semaine."),
            ("jouer au foot", "/ʒwe o fut/", "to play football", "Il joue au foot le week-end."),
            ("nager / la natation", "/na.ʒe/", "to swim / swimming", "Elle fait de la natation le mardi."),
            ("lire", "/liʁ/", "to read", "Je lis beaucoup pendant les vacances."),
            ("regarder des films", "/ʁə.ɡaʁ.de/", "to watch films", "J'adore regarder des films en VO."),
            ("écouter de la musique", "/e.ku.te/", "to listen to music", "J'écoute de la musique en travaillant."),
            ("jouer d'un instrument", "/ʒwe dœ̃/", "to play an instrument", "Elle joue de la guitare."),
            ("faire de la randonnée", "/ʁɑ̃.dɔ.ne/", "to go hiking", "Nous faisons de la randonnée en montagne."),
            ("le cinéma", "/si.ne.ma/", "cinema / movies", "Je vais au cinéma chaque semaine."),
            ("le théâtre", "/te.atʁ/", "theatre", "Ils sont allés au théâtre samedi."),
            ("voyager", "/vwa.ja.ʒe/", "to travel", "J'adore voyager en Europe."),
            ("cuisiner", "/kɥi.zi.ne/", "to cook", "Il cuisine pour ses amis le week-end."),
            ("dessiner / peindre", "/de.si.ne / pɛ̃dʁ/", "to draw / to paint", "Elle dessine et peint depuis l'enfance."),
            ("le week-end", "/wik.ɛnd/", "weekend", "Qu'est-ce que tu fais le week-end ?"),
        ],
        "game_desc": "Master French hobby and leisure vocabulary.",
        "items": [
            ("loi1", "faire du sport", "to do / play sport", "sport", "Je fais du sport trois fois par semaine.", "Complète: Elle fait ___ sport. (sport)", "du"),
            ("loi2", "jouer au foot", "to play football", "football", "Il joue au foot avec ses amis.", "Complète: Tu joues au ___ ? (football)", "foot"),
            ("loi3", "la natation", "swimming", "swimming", "Elle fait de la natation deux fois par semaine.", "Complète: Je fais de la ___. (swimming)", "natation"),
            ("loi4", "lire", "to read", "reading", "Il adore lire des romans policiers.", "Complète: J'aime ___. (to read)", "lire"),
            ("loi5", "jouer de la guitare", "to play the guitar", "guitar", "Elle joue de la guitare depuis cinq ans.", "Complète: Il joue ___ guitare. (de la)", "de la"),
            ("loi6", "voyager", "to travel", "travel", "J'adore voyager dans les pays francophones.", "Complète: Elle aime ___. (to travel)", "voyager"),
            ("loi7", "cuisiner", "to cook", "cooking", "Il cuisine très bien — un vrai chef !", "Complète: Il aime ___. (to cook)", "cuisiner"),
            ("loi8", "faire de la randonnée", "to go hiking", "hiking", "Nous faisons de la randonnée chaque été.", "Complète: Ils font de la ___. (hiking)", "randonnée"),
        ],
    },

    # ------------------------------------------------------------------ V05
    "les-courses": {
        "level": "a2", "section": "vocabulary", "num": "V05",
        "short": "Shopping",
        "title": "Shopping",
        "subtitle": "Les courses — buying things, prices, and sizes",
        "words": [
            ("faire les courses", "/fɛʁ le kuʁs/", "to do the shopping / grocery shopping", "Je fais les courses le samedi."),
            ("faire du shopping", "/ʃɔ.piŋ/", "to go shopping (clothes/leisure)", "Elle adore faire du shopping en ville."),
            ("le prix", "/pʁi/", "price", "Quel est le prix de ce manteau ?"),
            ("ça coûte combien ?", "/sa kut kɔ̃.bjɛ̃/", "how much does it cost?", "Ça coûte combien, s'il vous plaît ?"),
            ("c'est trop cher", "/sɛ tʁo ʃɛʁ/", "it's too expensive", "C'est trop cher — avez-vous quelque chose de moins cher ?"),
            ("une promotion", "/pʁɔ.mɔ.sjɔ̃/", "a sale / special offer", "Les soldes ont de bonnes promotions."),
            ("les soldes", "/le sɔld/", "the sales", "Je cherche un manteau pendant les soldes."),
            ("la taille", "/taj/", "size (clothing)", "Quelle est votre taille ?"),
            ("essayer", "/e.sɛ.je/", "to try on", "Est-ce que je peux essayer cette robe ?"),
            ("la caisse", "/kɛs/", "till / checkout", "Il faut payer à la caisse."),
            ("payer", "/pe.je/", "to pay", "Je paye par carte bleue."),
            ("la carte bancaire", "/kaʁt bɑ̃.kɛʁ/", "bank card / debit card", "Je paye avec ma carte bancaire."),
            ("le reçu", "/ʁə.sy/", "receipt", "Puis-je avoir un reçu ?"),
            ("rembourser", "/ʁɑ̃.buʁ.se/", "to refund", "On peut vous rembourser dans les 30 jours."),
            ("en solde", "/ɑ̃ sɔld/", "on sale / reduced", "Ce pantalon est en solde — 50% de réduction !"),
        ],
        "game_desc": "Learn French shopping vocabulary — prices, sizes, and transactions.",
        "items": [
            ("shop1", "faire les courses", "to do the shopping", "grocery shop", "Je fais les courses au supermarché.", "Complète: Je fais les ___. (shopping)", "courses"),
            ("shop2", "ça coûte combien ?", "how much does it cost?", "how much", "Ça coûte combien, ce manteau ?", "Complète: Ça ___ combien ? (costs)", "coûte"),
            ("shop3", "c'est trop cher", "it's too expensive", "too expensive", "C'est trop cher — avez-vous moins cher ?", "Complète: C'est trop ___. (expensive)", "cher"),
            ("shop4", "les soldes", "the sales", "sales", "Je cherche des chaussures pendant les soldes.", "Complète: Je vais aux ___. (sales)", "soldes"),
            ("shop5", "la taille", "size (clothing)", "size", "Quelle est votre taille — M ou L ?", "Complète: Quelle est votre ___? (size)", "taille"),
            ("shop6", "essayer", "to try on", "try on", "Je peux essayer cette veste, s'il vous plaît ?", "Complète: Je peux ___ cette robe ? (try on)", "essayer"),
            ("shop7", "payer par carte", "to pay by card", "card payment", "Je paye par carte bancaire, s'il vous plaît.", "Complète: Je ___ par carte. (pay)", "paye"),
            ("shop8", "en solde", "on sale / reduced", "reduced", "Ce manteau est en solde — 40% de réduction !", "Complète: C'est ___ solde. (on sale, en)", "en"),
        ],
    },

    # ------------------------------------------------------------------ V06
    "la-sante": {
        "level": "a2", "section": "vocabulary", "num": "V06",
        "short": "Health",
        "title": "Health & Illness",
        "subtitle": "La santé — symptoms, doctors, and medicines",
        "words": [
            ("avoir mal à", "/a.vwaʁ mal a/", "to have pain in / … hurts", "J'ai mal à la gorge."),
            ("être malade", "/ɛtʁ ma.lad/", "to be ill / sick", "Je suis malade depuis lundi."),
            ("la fièvre", "/la fjɛvʁ/", "fever / temperature", "Il a de la fièvre — 38 degrés."),
            ("la toux", "/la tu/", "cough", "J'ai une toux persistante."),
            ("le rhume", "/lə ʁym/", "cold (illness)", "J'ai un rhume depuis trois jours."),
            ("la grippe", "/la ɡʁip/", "flu", "La grippe est plus grave qu'un rhume."),
            ("le médicament", "/me.di.ka.mɑ̃/", "medicine / medication", "Prenez ce médicament deux fois par jour."),
            ("l'ordonnance", "/lɔʁ.dɔ.nɑ̃s/", "prescription", "Le médecin m'a donné une ordonnance."),
            ("prendre rendez-vous", "/pʁɑ̃dʁ ʁɑ̃.de.vu/", "to make an appointment", "Je dois prendre rendez-vous chez le médecin."),
            ("la salle d'attente", "/sal da.tɑ̃t/", "waiting room", "Il y a du monde dans la salle d'attente."),
            ("l'opération", "/ɔ.pe.ʁa.sjɔ̃/", "operation / surgery", "Il a eu une opération au genou."),
            ("se sentir bien / mal", "/sə sɑ̃.tiʁ/", "to feel well / unwell", "Je ne me sens pas bien aujourd'hui."),
            ("guérir", "/ɡe.ʁiʁ/", "to get better / recover", "J'espère guérir vite."),
            ("allergique à", "/a.lɛʁ.ʒik a/", "allergic to", "Je suis allergique aux arachides."),
            ("les urgences", "/le.zyʁ.ʒɑ̃s/", "A&E / emergency room", "On l'a emmené aux urgences."),
        ],
        "game_desc": "Learn French health and illness vocabulary.",
        "items": [
            ("san1", "être malade", "to be ill", "sick", "Je suis malade — j'ai de la fièvre.", "Complète: Il est ___. (ill)", "malade"),
            ("san2", "avoir de la fièvre", "to have a fever", "fever", "Elle a de la fièvre — 39 degrés.", "Complète: Il a de la ___. (fever)", "fièvre"),
            ("san3", "le rhume", "cold (illness)", "cold", "J'ai un rhume — nez qui coule et mal à la gorge.", "Complète: J'ai un ___. (cold)", "rhume"),
            ("san4", "la grippe", "flu", "flu", "La grippe est plus grave qu'un rhume.", "Complète: Il a la ___. (flu)", "grippe"),
            ("san5", "le médicament", "medicine", "medication", "Prenez ce médicament trois fois par jour.", "Complète: Je prends un ___. (medicine)", "médicament"),
            ("san6", "l'ordonnance", "prescription", "prescription", "Le médecin m'a donné une ordonnance.", "Complète: J'ai besoin d'une ___. (prescription)", "ordonnance"),
            ("san7", "se sentir mal", "to feel unwell", "feel unwell", "Je ne me sens pas bien — j'ai la tête qui tourne.", "Complète: Je me ___ mal. (feel)", "sens"),
            ("san8", "les urgences", "A&E / emergency room", "emergency", "Ils l'ont emmené aux urgences.", "Complète: Il est aux ___. (A&E)", "urgences"),
        ],
    },

    # ------------------------------------------------------------------ V07
    "la-nature": {
        "level": "a2", "section": "vocabulary", "num": "V07",
        "short": "Nature & Environment",
        "title": "Nature & the Environment",
        "subtitle": "La nature — landscapes, animals, and the natural world",
        "words": [
            ("la forêt", "/la fɔ.ʁɛ/", "forest", "Nous nous promenons dans la forêt."),
            ("la montagne", "/la mɔ̃.taɲ/", "mountain", "Je fais du ski à la montagne."),
            ("la mer", "/la mɛʁ/", "sea", "En été, je vais à la mer."),
            ("la rivière", "/la ʁi.vjɛʁ/", "river (small)", "On se baigne dans la rivière."),
            ("le fleuve", "/lə flœv/", "river (large)", "La Seine est un fleuve."),
            ("la campagne", "/la kɑ̃.paɲ/", "countryside", "J'habite à la campagne."),
            ("l'arbre", "/laʁbʁ/", "tree", "Il y a un grand arbre dans le jardin."),
            ("la fleur", "/la flœʁ/", "flower", "Elle a acheté des fleurs pour sa mère."),
            ("l'animal sauvage", "/a.ni.mal so.vaʒ/", "wild animal", "On a vu des animaux sauvages."),
            ("l'oiseau", "/lwa.zo/", "bird", "Les oiseaux chantent le matin."),
            ("le chien / le chat", "/ʃjɛ̃ / ʃa/", "dog / cat", "J'ai un chien et deux chats."),
            ("recycler", "/ʁe.si.kle/", "to recycle", "Je recycle le papier et le verre."),
            ("polluer", "/pɔ.lɥe/", "to pollute", "Les voitures polluent l'atmosphère."),
            ("protéger", "/pʁɔ.te.ʒe/", "to protect", "Il faut protéger l'environnement."),
            ("l'environnement", "/lɑ̃.vi.ʁɔ.nə.mɑ̃/", "environment", "Je veux protéger l'environnement."),
        ],
        "game_desc": "Learn French nature and environment vocabulary.",
        "items": [
            ("nat1", "la forêt", "forest", "woods", "Nous nous promenons dans la forêt.", "Complète: On va dans la ___. (forest)", "forêt"),
            ("nat2", "la montagne", "mountain", "mountains", "Je skie à la montagne en hiver.", "Complète: La ___ est belle en hiver. (mountain)", "montagne"),
            ("nat3", "la mer", "sea", "sea", "En été, je nage dans la mer.", "Complète: La ___ est calme. (sea)", "mer"),
            ("nat4", "la campagne", "countryside", "rural", "J'habite à la campagne, loin de la ville.", "Complète: La ___ est belle en automne. (countryside)", "campagne"),
            ("nat5", "l'arbre", "tree", "tree", "Il y a un grand arbre dans notre jardin.", "Complète: Les ___s perdent leurs feuilles. (tree)", "arbre"),
            ("nat6", "l'oiseau", "bird", "bird", "Les oiseaux chantent le matin.", "Complète: Les ___ chantent. (birds)", "oiseaux"),
            ("nat7", "recycler", "to recycle", "recycling", "Je recycle le papier, le verre et le plastique.", "Complète: Il faut ___. (to recycle)", "recycler"),
            ("nat8", "l'environnement", "environment", "environment", "Il faut protéger l'environnement.", "Complète: Je respecte l'___. (environment)", "environnement"),
        ],
    },

    # ------------------------------------------------------------------ V08
    "les-technologies": {
        "level": "a2", "section": "vocabulary", "num": "V08",
        "short": "Technology",
        "title": "Technology & the Internet",
        "subtitle": "La technologie — digital life and devices",
        "words": [
            ("l'ordinateur", "/lɔʁ.di.na.tœʁ/", "computer", "Je travaille sur mon ordinateur."),
            ("le portable / le smartphone", "/pɔʁ.tabl/", "mobile phone / smartphone", "J'ai perdu mon portable."),
            ("la tablette", "/ta.blɛt/", "tablet", "Elle lit des livres sur sa tablette."),
            ("internet", "/ɛ̃.tɛʁ.nɛt/", "the internet", "Je cherche l'information sur internet."),
            ("le réseau social", "/ʁe.zo sɔ.sjal/", "social network", "Les réseaux sociaux prennent du temps."),
            ("envoyer un message", "/ɑ̃.vwa.je/", "to send a message", "J'envoie un message à ma mère."),
            ("télécharger", "/te.le.ʃaʁ.ʒe/", "to download", "Je télécharge une application."),
            ("le mot de passe", "/mo də pas/", "password", "J'ai oublié mon mot de passe."),
            ("le courriel / l'e-mail", "/ku.ʁjɛl/", "email", "Je t'envoie un courriel."),
            ("se connecter", "/sə kɔ.nɛk.te/", "to log in / connect", "Je me connecte au réseau."),
            ("l'application", "/ap.li.ka.sjɔ̃/", "app / application", "Cette application est très pratique."),
            ("la vidéo", "/vi.de.o/", "video", "Je regarde des vidéos en ligne."),
            ("en ligne", "/ɑ̃ liɲ/", "online", "Je travaille souvent en ligne."),
            ("le Wi-Fi", "/wi.fi/", "Wi-Fi", "Est-ce qu'il y a le Wi-Fi ici ?"),
            ("la batterie", "/ba.tʁi/", "battery", "Ma batterie est à plat !"),
        ],
        "game_desc": "Learn French technology and digital life vocabulary.",
        "items": [
            ("tech1", "l'ordinateur", "computer", "PC", "Je fais mes devoirs sur mon ordinateur.", "Complète: J'ai un ___. (computer)", "ordinateur"),
            ("tech2", "le portable", "mobile phone", "phone", "J'ai perdu mon portable — zut !", "Complète: Mon ___ est mort. (phone)", "portable"),
            ("tech3", "internet", "the internet", "internet", "Je cherche l'information sur internet.", "Complète: Je navigue sur ___. (internet)", "internet"),
            ("tech4", "envoyer un message", "to send a message", "message", "J'envoie un message à ma sœur.", "Complète: Il ___ un message. (sends)", "envoie"),
            ("tech5", "télécharger", "to download", "download", "Je télécharge une nouvelle application.", "Complète: Il faut ___ l'appli. (download)", "télécharger"),
            ("tech6", "le mot de passe", "password", "password", "J'ai oublié mon mot de passe.", "Complète: Quel est ton ___ de passe ? (word)", "mot"),
            ("tech7", "en ligne", "online", "online", "Je travaille souvent en ligne à domicile.", "Complète: Il est ___. (online)", "en ligne"),
            ("tech8", "la batterie", "battery", "battery", "Ma batterie est à plat — besoin de charger.", "Complète: La ___ est vide. (battery)", "batterie"),
        ],
    },
}
