"""
francais-en A1 Vocabulary V01–V10  (French for English Speakers)
Generator: gen_francais_en.py
words format: (french_word, ipa, english_def, french_example)
"""

CHAPTERS = {

    # ------------------------------------------------------------------ V01
    "les-salutations": {
        "level": "a1", "section": "vocabulary", "num": "V01",
        "short": "Greetings",
        "title": "Greetings & Introductions",
        "subtitle": "Les salutations — saying hello, goodbye, and introducing yourself",
        "words": [
            ("bonjour", "/bɔ̃.ʒuʁ/", "hello / good morning", "Bonjour, madame !"),
            ("bonsoir", "/bɔ̃.swaʁ/", "good evening", "Bonsoir, tout le monde !"),
            ("salut", "/sa.ly/", "hi (informal)", "Salut, ça va ?"),
            ("au revoir", "/o ʁə.vwaʁ/", "goodbye", "Au revoir et à bientôt !"),
            ("à bientôt", "/a bjɛ̃.to/", "see you soon", "À bientôt, Marie !"),
            ("à demain", "/a də.mɛ̃/", "see you tomorrow", "À demain, bonne nuit !"),
            ("merci", "/mɛʁ.si/", "thank you", "Merci beaucoup, monsieur."),
            ("s'il vous plaît", "/sil vu plɛ/", "please (formal)", "Un café, s'il vous plaît."),
            ("s'il te plaît", "/sil tə plɛ/", "please (informal)", "Aide-moi, s'il te plaît !"),
            ("excusez-moi", "/ɛks.ky.ze mwa/", "excuse me (formal)", "Excusez-moi, où est la gare ?"),
            ("je m'appelle", "/ʒə ma.pɛl/", "my name is", "Je m'appelle Sophie."),
            ("enchanté(e)", "/ɑ̃.ʃɑ̃.te/", "pleased to meet you", "Enchanté, je suis Paul."),
            ("comment allez-vous ?", "/kɔ.mɑ̃ ta.le vu/", "how are you? (formal)", "Comment allez-vous aujourd'hui ?"),
            ("ça va ?", "/sa va/", "how are you? / fine? (informal)", "Salut ! Ça va ?"),
            ("je vais bien", "/ʒə vɛ bjɛ̃/", "I'm fine", "Ça va ? — Je vais bien, merci !"),
        ],
        "game_desc": "Master French greetings and polite phrases.",
        "items": [
            ("sal1", "bonjour", "hello / good morning", "hi", "Bonjour, comment allez-vous ?", "Complète: ___, madame ! (hello)", "bonjour"),
            ("sal2", "bonsoir", "good evening", "good evening", "Bonsoir, bonne soirée à tous !", "Complète: ___, monsieur ! (good evening)", "bonsoir"),
            ("sal3", "au revoir", "goodbye", "bye", "Au revoir et à bientôt !", "Complète: ___ et bonne journée ! (goodbye)", "au revoir"),
            ("sal4", "merci", "thank you", "thanks", "Merci beaucoup pour votre aide.", "Complète: ___ beaucoup ! (thank you)", "merci"),
            ("sal5", "s'il vous plaît", "please (formal)", "please", "Un thé, s'il vous plaît.", "Complète: L'addition, ___ ! (please formal)", "s'il vous plaît"),
            ("sal6", "excusez-moi", "excuse me (formal)", "sorry", "Excusez-moi, pouvez-vous répéter ?", "Complète: ___, où est la pharmacie ? (excuse me)", "excusez-moi"),
            ("sal7", "je m'appelle", "my name is", "I am called", "Je m'appelle Lucie. Et toi ?", "Complète: ___ Thomas. (my name is)", "je m'appelle"),
            ("sal8", "enchanté(e)", "pleased to meet you", "nice to meet you", "Enchanté de faire votre connaissance.", "Complète: ___, je suis Marie. (pleased to meet you)", "enchanté"),
        ],
    },

    # ------------------------------------------------------------------ V02
    "la-famille": {
        "level": "a1", "section": "vocabulary", "num": "V02",
        "short": "Family",
        "title": "The Family",
        "subtitle": "La famille — family members and relationships",
        "words": [
            ("la famille", "/la fa.mij/", "family", "J'adore ma famille."),
            ("le père", "/lə pɛʁ/", "father", "Mon père est médecin."),
            ("la mère", "/la mɛʁ/", "mother", "Ma mère est professeure."),
            ("le frère", "/lə fʁɛʁ/", "brother", "J'ai deux frères."),
            ("la sœur", "/la sœʁ/", "sister", "Ma sœur s'appelle Emma."),
            ("le fils", "/lə fis/", "son", "C'est le fils de Marie."),
            ("la fille", "/la fij/", "daughter / girl", "Il a une fille et deux fils."),
            ("le mari", "/lə ma.ʁi/", "husband", "Son mari est ingénieur."),
            ("la femme", "/la fam/", "wife / woman", "Sa femme est avocate."),
            ("le grand-père", "/lə ɡʁɑ̃.pɛʁ/", "grandfather", "Mon grand-père a 75 ans."),
            ("la grand-mère", "/la ɡʁɑ̃.mɛʁ/", "grandmother", "Ma grand-mère fait de bons gâteaux."),
            ("l'oncle", "/lɔ̃kl/", "uncle", "Mon oncle habite à Lyon."),
            ("la tante", "/la tɑ̃t/", "aunt", "Ma tante est sympa."),
            ("le cousin / la cousine", "/ku.zɛ̃ / ku.zin/", "cousin (m/f)", "J'ai cinq cousins."),
            ("les parents", "/le pa.ʁɑ̃/", "parents", "Mes parents sont sympas."),
        ],
        "game_desc": "Learn French family vocabulary with meaning, context, and production.",
        "items": [
            ("fam1", "le père", "father", "dad", "Mon père s'appelle Jacques.", "Complète: Mon ___ a 45 ans. (father)", "père"),
            ("fam2", "la mère", "mother", "mum", "Ma mère est infirmière.", "Complète: Ma ___ travaille à Paris. (mother)", "mère"),
            ("fam3", "le frère", "brother", "bro", "J'ai un frère qui s'appelle Paul.", "Complète: Mon ___ a 12 ans. (brother)", "frère"),
            ("fam4", "la sœur", "sister", "sis", "Ma sœur est plus grande que moi.", "Complète: J'ai deux ___. (sisters)", "sœurs"),
            ("fam5", "le fils", "son", "son", "C'est le fils aîné de la famille.", "Complète: Leur ___ est étudiant. (son)", "fils"),
            ("fam6", "la fille", "daughter / girl", "daughter", "Leur fille s'appelle Camille.", "Complète: Ma ___ a huit ans. (daughter)", "fille"),
            ("fam7", "les grands-parents", "grandparents", "grands", "Mes grands-parents habitent en Bretagne.", "Complète: Mes ___-parents sont à la retraite. (grands)", "grands"),
            ("fam8", "les parents", "parents", "parents", "Mes parents sont ensemble depuis 20 ans.", "Complète: Mes ___ sont sympas. (parents)", "parents"),
        ],
    },

    # ------------------------------------------------------------------ V03
    "les-nombres": {
        "level": "a1", "section": "vocabulary", "num": "V03",
        "short": "Numbers",
        "title": "Numbers & Quantities",
        "subtitle": "Les nombres — counting, quantities, and basic maths",
        "words": [
            ("un / une", "/œ̃ / yn/", "one", "J'ai un chien et une chat."),
            ("deux", "/dø/", "two", "J'ai deux frères."),
            ("cinq", "/sɛ̃k/", "five", "Il y a cinq personnes."),
            ("dix", "/dis/", "ten", "Je compte jusqu'à dix."),
            ("vingt", "/vɛ̃/", "twenty", "Il a vingt ans."),
            ("trente", "/tʁɑ̃t/", "thirty", "La réunion dure trente minutes."),
            ("cinquante", "/sɛ̃.kɑ̃t/", "fifty", "Un billet de cinquante euros."),
            ("cent", "/sɑ̃/", "one hundred", "Il y a cent pages."),
            ("mille", "/mil/", "one thousand", "Mille mercis !"),
            ("combien ?", "/kɔ̃.bjɛ̃/", "how much / how many?", "Combien ça coûte ?"),
            ("beaucoup (de)", "/bo.ku/", "a lot (of)", "Il y a beaucoup de monde."),
            ("peu (de)", "/pø/", "few / little", "J'ai peu de temps."),
            ("assez (de)", "/a.se/", "enough (of)", "J'ai assez mangé."),
            ("trop (de)", "/tʁo/", "too much / too many", "Il y a trop de bruit."),
            ("premier / première", "/pʁə.mje/", "first", "C'est la première fois."),
        ],
        "game_desc": "Practice French numbers and quantity words.",
        "items": [
            ("nm1", "combien ?", "how much / how many?", "how much", "Combien ça coûte, s'il vous plaît ?", "Complète: ___ d'élèves ? (how many)", "combien"),
            ("nm2", "beaucoup de", "a lot of", "lots of", "Il y a beaucoup de monde au marché.", "Complète: J'ai ___ de travail. (a lot)", "beaucoup"),
            ("nm3", "peu de", "few / a little", "a little", "J'ai peu de temps ce matin.", "Complète: Il parle ___ français. (a little)", "peu de"),
            ("nm4", "trop de", "too much / too many", "too many", "Il y a trop de bruit dans la rue.", "Complète: C'est ___ cher ! (too)", "trop"),
            ("nm5", "assez de", "enough", "enough", "J'ai assez mangé, merci.", "Complète: Il n'y a pas ___ de pain. (enough)", "assez"),
            ("nm6", "cent", "one hundred", "100", "Il y a cent euros dans mon portefeuille.", "Complète: Un billet de ___ euros. (100)", "cent"),
            ("nm7", "mille", "one thousand", "1000", "Mille personnes étaient présentes.", "Complète: ___ mercis ! (1000)", "mille"),
            ("nm8", "premier / première", "first", "first", "C'est la première fois que je visite Paris.", "Complète: Le ___ janvier. (first)", "premier"),
        ],
    },

    # ------------------------------------------------------------------ V04
    "les-couleurs": {
        "level": "a1", "section": "vocabulary", "num": "V04",
        "short": "Colours",
        "title": "Colours",
        "subtitle": "Les couleurs — colour names and agreement",
        "words": [
            ("rouge", "/ʁuʒ/", "red", "Elle porte une robe rouge."),
            ("bleu / bleue", "/blø/", "blue", "Le ciel est bleu."),
            ("vert / verte", "/vɛʁ/", "green", "L'herbe est verte."),
            ("jaune", "/ʒon/", "yellow", "Le soleil est jaune."),
            ("orange", "/ɔ.ʁɑ̃ʒ/", "orange (invariable)", "J'aime la couleur orange."),
            ("blanc / blanche", "/blɑ̃ / blɑ̃ʃ/", "white", "Le mur est blanc."),
            ("noir / noire", "/nwaʁ/", "black", "Il a un chat noir."),
            ("gris / grise", "/ɡʁi/", "grey", "Le ciel est gris aujourd'hui."),
            ("marron", "/ma.ʁɔ̃/", "brown (invariable)", "J'ai les yeux marron."),
            ("rose", "/ʁoz/", "pink", "Elle aime le rose."),
            ("violet / violette", "/vjɔ.lɛ/", "purple", "Il y a des fleurs violettes."),
            ("beige", "/bɛʒ/", "beige (invariable)", "Un manteau beige."),
            ("clair / claire", "/klɛʁ/", "light (colour)", "Un bleu clair."),
            ("foncé / foncée", "/fɔ̃.se/", "dark (colour)", "Un vert foncé."),
            ("de quelle couleur ?", "/də kɛl ku.lœʁ/", "what colour?", "De quelle couleur est ta voiture ?"),
        ],
        "game_desc": "Learn French colour words and practise agreement.",
        "items": [
            ("col1", "rouge", "red", "red", "Il porte un pull rouge.", "Complète: une fleur ___. (red)", "rouge"),
            ("col2", "bleu / bleue", "blue", "blue", "Le ciel est bleu et la mer est bleue.", "Complète: des yeux ___. (blue, pl.)", "bleus"),
            ("col3", "vert / verte", "green", "green", "Les feuilles sont vertes en été.", "Complète: une robe ___. (green, f.)", "verte"),
            ("col4", "blanc / blanche", "white", "white", "Elle a les cheveux blancs.", "Complète: une chemise ___. (white, f.)", "blanche"),
            ("col5", "noir / noire", "black", "black", "Il a un chat noir et une voiture noire.", "Complète: un sac ___. (black, m.)", "noir"),
            ("col6", "jaune", "yellow", "yellow", "Le soleil est jaune.", "Complète: des fleurs ___. (yellow)", "jaunes"),
            ("col7", "marron", "brown (invariable)", "brown", "J'ai les yeux marron.", "Complète: des chaussures ___. (brown, invariable)", "marron"),
            ("col8", "de quelle couleur ?", "what colour?", "what colour", "De quelle couleur est ton sac ?", "Complète: ___ couleur est ta voiture ? (what)", "de quelle"),
        ],
    },

    # ------------------------------------------------------------------ V05
    "les-aliments": {
        "level": "a1", "section": "vocabulary", "num": "V05",
        "short": "Food & Drink",
        "title": "Food & Drink",
        "subtitle": "Les aliments — eating, drinking, and meals",
        "words": [
            ("le pain", "/lə pɛ̃/", "bread", "Je mange du pain le matin."),
            ("le beurre", "/lə bœʁ/", "butter", "Du pain avec du beurre."),
            ("le fromage", "/lə fʁo.maʒ/", "cheese", "La France a 300 fromages !"),
            ("la viande", "/la vjɑ̃d/", "meat", "Je ne mange pas de viande."),
            ("le poisson", "/lə pwa.sɔ̃/", "fish", "J'aime le poisson grillé."),
            ("les légumes", "/le le.ɡym/", "vegetables", "Je mange beaucoup de légumes."),
            ("les fruits", "/le fʁɥi/", "fruit", "J'adore les fruits en été."),
            ("l'eau", "/lo/", "water", "Un verre d'eau, s'il vous plaît."),
            ("le café", "/lə ka.fe/", "coffee", "Je prends un café au lait."),
            ("le thé", "/lə te/", "tea", "Elle préfère le thé vert."),
            ("le vin", "/lə vɛ̃/", "wine", "Un verre de vin rouge."),
            ("le jus d'orange", "/lə ʒy dɔ.ʁɑ̃ʒ/", "orange juice", "Un jus d'orange pressé."),
            ("le petit-déjeuner", "/pə.ti de.ʒœ.ne/", "breakfast", "Je prends le petit-déjeuner à 7h."),
            ("le déjeuner", "/de.ʒœ.ne/", "lunch", "Le déjeuner est à midi."),
            ("le dîner", "/di.ne/", "dinner", "Nous dînons à 20 heures."),
        ],
        "game_desc": "Master French food and drink vocabulary.",
        "items": [
            ("ali1", "le pain", "bread", "loaf", "Je mange du pain avec du fromage.", "Complète: du ___ et du beurre. (bread)", "pain"),
            ("ali2", "le fromage", "cheese", "cheese", "La France est connue pour ses fromages.", "Complète: un plateau de ___. (cheese)", "fromage"),
            ("ali3", "la viande", "meat", "meat", "Il mange de la viande deux fois par semaine.", "Complète: je ne mange pas de ___. (meat)", "viande"),
            ("ali4", "les légumes", "vegetables", "veggies", "Je mange beaucoup de légumes frais.", "Complète: des ___ du jardin. (vegetables)", "légumes"),
            ("ali5", "l'eau", "water", "water", "Un verre d'eau minérale, s'il vous plaît.", "Complète: Je bois de l'___. (water)", "eau"),
            ("ali6", "le café", "coffee", "coffee", "Je prends un café noir le matin.", "Complète: un ___ crème, s'il vous plaît. (coffee)", "café"),
            ("ali7", "le petit-déjeuner", "breakfast", "breakfast", "Le petit-déjeuner est servi de 7h à 10h.", "Complète: Je prends le petit-___. (breakfast)", "déjeuner"),
            ("ali8", "le dîner", "dinner", "dinner", "Nous dînons en famille ce soir.", "Complète: Le ___ est à 20h. (dinner)", "dîner"),
        ],
    },

    # ------------------------------------------------------------------ V06
    "les-vetements": {
        "level": "a1", "section": "vocabulary", "num": "V06",
        "short": "Clothes",
        "title": "Clothes & Accessories",
        "subtitle": "Les vêtements — what to wear",
        "words": [
            ("le vêtement", "/lə vɛt.mɑ̃/", "clothing / garment", "J'achète des vêtements."),
            ("la chemise", "/la ʃə.miz/", "shirt", "Il porte une chemise bleue."),
            ("le pantalon", "/lə pɑ̃.ta.lɔ̃/", "trousers", "Ce pantalon est trop grand."),
            ("la robe", "/la ʁɔb/", "dress", "Elle porte une belle robe rouge."),
            ("la jupe", "/la ʒyp/", "skirt", "La jupe est trop courte."),
            ("le pull", "/lə pyl/", "jumper / sweater", "Il fait froid — mets un pull !"),
            ("le manteau", "/lə mɑ̃.to/", "coat", "J'ai besoin d'un manteau chaud."),
            ("les chaussures", "/le ʃo.syʁ/", "shoes", "Ces chaussures sont confortables."),
            ("les chaussettes", "/le ʃo.sɛt/", "socks", "J'ai perdu une chaussette !"),
            ("le chapeau", "/lə ʃa.po/", "hat", "Elle porte un chapeau rouge."),
            ("le sac", "/lə sak/", "bag", "Mon sac est lourd aujourd'hui."),
            ("la ceinture", "/la sɛ̃.tyʁ/", "belt", "Il porte une ceinture noire."),
            ("porter", "/pɔʁ.te/", "to wear / to carry", "Elle porte une robe verte."),
            ("mettre", "/mɛtʁ/", "to put on (clothing)", "Mets ton manteau, il fait froid !"),
            ("à la mode", "/a la mɔd/", "in fashion / trendy", "Ces chaussures sont à la mode."),
        ],
        "game_desc": "Learn French clothing and accessories vocabulary.",
        "items": [
            ("vet1", "la chemise", "shirt", "shirt", "Il porte une chemise blanche pour le travail.", "Complète: une ___ rayée. (shirt)", "chemise"),
            ("vet2", "le pantalon", "trousers", "trousers", "Ce pantalon gris va avec tout.", "Complète: un ___ noir. (trousers)", "pantalon"),
            ("vet3", "la robe", "dress", "dress", "Elle porte une jolie robe d'été.", "Complète: une ___ bleue. (dress)", "robe"),
            ("vet4", "le pull", "jumper / sweater", "jumper", "Il fait froid, mets un pull !", "Complète: un ___ chaud. (jumper)", "pull"),
            ("vet5", "le manteau", "coat", "coat", "N'oublie pas ton manteau — il fait froid.", "Complète: un ___ gris. (coat)", "manteau"),
            ("vet6", "les chaussures", "shoes", "shoes", "Ces chaussures sont très confortables.", "Complète: des ___ noires. (shoes)", "chaussures"),
            ("vet7", "porter", "to wear / to carry", "to wear", "Elle porte une robe et des talons hauts.", "Complète: Il ___ un pantalon bleu. (wears)", "porte"),
            ("vet8", "mettre", "to put on", "to put on", "Mets ton manteau avant de sortir !", "Complète: Elle ___ ses chaussures. (puts on)", "met"),
        ],
    },

    # ------------------------------------------------------------------ V07
    "la-maison": {
        "level": "a1", "section": "vocabulary", "num": "V07",
        "short": "The Home",
        "title": "The Home",
        "subtitle": "La maison — rooms and furniture",
        "words": [
            ("la maison", "/la mɛ.zɔ̃/", "house / home", "J'habite dans une grande maison."),
            ("l'appartement", "/la.paʁ.tə.mɑ̃/", "flat / apartment", "Elle habite dans un appartement."),
            ("la cuisine", "/la kɥi.zin/", "kitchen", "Je fais la cuisine le soir."),
            ("le salon", "/lə sa.lɔ̃/", "living room", "Le salon est grand et lumineux."),
            ("la salle à manger", "/la sal a mɑ̃.ʒe/", "dining room", "On mange dans la salle à manger."),
            ("la chambre", "/la ʃɑ̃bʁ/", "bedroom", "Ma chambre est au premier étage."),
            ("la salle de bains", "/la sal də bɛ̃/", "bathroom", "La salle de bains est à gauche."),
            ("les toilettes", "/le twa.lɛt/", "toilet / WC", "Les toilettes sont au bout du couloir."),
            ("le jardin", "/lə ʒaʁ.dɛ̃/", "garden", "Nous avons un petit jardin."),
            ("le lit", "/lə li/", "bed", "Je vais me coucher — bonne nuit !"),
            ("la table", "/la tabl/", "table", "Mets la table pour le dîner !"),
            ("la chaise", "/la ʃɛz/", "chair", "Il reste une chaise libre."),
            ("la fenêtre", "/la fə.nɛtʁ/", "window", "Ouvre la fenêtre, s'il te plaît."),
            ("la porte", "/la pɔʁt/", "door", "Ferme la porte !"),
            ("l'étage", "/le.taʒ/", "floor / storey", "Au premier étage à droite."),
        ],
        "game_desc": "Learn French rooms and home vocabulary.",
        "items": [
            ("mai1", "la maison", "house / home", "home", "J'habite dans une grande maison à Lyon.", "Complète: Je rentre à la ___. (home)", "maison"),
            ("mai2", "la cuisine", "kitchen", "kitchen", "Je fais la cuisine chaque soir.", "Complète: Je prépare le dîner dans la ___. (kitchen)", "cuisine"),
            ("mai3", "le salon", "living room", "lounge", "On regarde la télé dans le salon.", "Complète: Le ___ est au rez-de-chaussée. (living room)", "salon"),
            ("mai4", "la chambre", "bedroom", "bedroom", "Ma chambre est calme et bien rangée.", "Complète: Je dors dans ma ___. (bedroom)", "chambre"),
            ("mai5", "la salle de bains", "bathroom", "bathroom", "La salle de bains a une douche et une baignoire.", "Complète: La ___ de bains est en haut. (salle)", "salle"),
            ("mai6", "le jardin", "garden", "garden", "Les enfants jouent dans le jardin.", "Complète: Il y a des fleurs dans le ___. (garden)", "jardin"),
            ("mai7", "le lit", "bed", "bed", "Je lis au lit avant de dormir.", "Complète: Mon ___ est confortable. (bed)", "lit"),
            ("mai8", "la table", "table", "table", "Mets la table pour le dîner, s'il te plaît.", "Complète: La ___ est ronde. (table)", "table"),
        ],
    },

    # ------------------------------------------------------------------ V08
    "les-transports": {
        "level": "a1", "section": "vocabulary", "num": "V08",
        "short": "Transport",
        "title": "Transport & Getting Around",
        "subtitle": "Les transports — how to get around",
        "words": [
            ("le train", "/lə tʁɛ̃/", "train", "Je prends le train pour Paris."),
            ("l'avion", "/la.vjɔ̃/", "plane / aeroplane", "Je voyage en avion."),
            ("le bus", "/lə bys/", "bus", "Le bus numéro 6 va au centre-ville."),
            ("le métro", "/lə me.tʁo/", "underground / metro", "Je prends le métro tous les jours."),
            ("la voiture", "/la vwa.tyʁ/", "car", "J'ai une petite voiture rouge."),
            ("le vélo", "/lə ve.lo/", "bicycle / bike", "Je vais au travail à vélo."),
            ("à pied", "/a pje/", "on foot", "Je vais à l'école à pied."),
            ("la gare", "/la ɡaʁ/", "train station", "Le train part de la gare à 9h."),
            ("l'aéroport", "/la.e.ʁo.pɔʁ/", "airport", "L'aéroport est loin du centre."),
            ("le billet", "/lə bi.jɛ/", "ticket", "J'achète un billet aller-retour."),
            ("le quai", "/lə ke/", "platform", "Le train part du quai 5."),
            ("à l'heure", "/a lœʁ/", "on time", "Le train est à l'heure."),
            ("en retard", "/ɑ̃ ʁə.taʁ/", "late / delayed", "Le bus est en retard."),
            ("prendre", "/pʁɑ̃dʁ/", "to take (transport)", "Je prends le bus le matin."),
            ("la station", "/la sta.sjɔ̃/", "station (metro/bus)", "Quelle station de métro ?"),
        ],
        "game_desc": "Learn French transport vocabulary and travel phrases.",
        "items": [
            ("tra1", "le train", "train", "train", "Je prends le train pour aller à Lyon.", "Complète: Le ___ arrive à 10h. (train)", "train"),
            ("tra2", "l'avion", "plane", "plane", "Je voyage en avion deux fois par an.", "Complète: Je prends l'___. (plane)", "avion"),
            ("tra3", "le bus", "bus", "bus", "Le bus numéro 12 va au centre-ville.", "Complète: Je prends le ___ 6. (bus)", "bus"),
            ("tra4", "la voiture", "car", "car", "Je vais au travail en voiture.", "Complète: Sa ___ est bleue. (car)", "voiture"),
            ("tra5", "à pied", "on foot", "walking", "Je vais à l'école à pied.", "Complète: Je rentre ___ pied. (on)", "à"),
            ("tra6", "la gare", "train station", "station", "La gare est à 10 minutes à pied.", "Complète: Où est la ___ ? (station)", "gare"),
            ("tra7", "le billet", "ticket", "ticket", "J'achète un billet aller-retour pour Paris.", "Complète: Un ___ de train, s'il vous plaît. (ticket)", "billet"),
            ("tra8", "en retard", "late / delayed", "late", "Le train est en retard de 20 minutes.", "Complète: Le bus est en ___. (late)", "retard"),
        ],
    },

    # ------------------------------------------------------------------ V09
    "le-corps": {
        "level": "a1", "section": "vocabulary", "num": "V09",
        "short": "The Body",
        "title": "The Human Body",
        "subtitle": "Le corps humain — body parts and health",
        "words": [
            ("la tête", "/la tɛt/", "head", "J'ai mal à la tête."),
            ("les yeux", "/le zjø/", "eyes (pl. of œil)", "Elle a les yeux verts."),
            ("le nez", "/lə ne/", "nose", "J'ai le nez qui coule."),
            ("la bouche", "/la buʃ/", "mouth", "Ouvre la bouche !"),
            ("l'oreille", "/lɔ.ʁɛj/", "ear", "J'ai mal à l'oreille."),
            ("les dents", "/le dɑ̃/", "teeth", "Je me brosse les dents."),
            ("le cou", "/lə ku/", "neck", "Il a mal au cou."),
            ("l'épaule", "/le.pol/", "shoulder", "J'ai mal à l'épaule."),
            ("le bras", "/lə bʁa/", "arm", "Il a le bras cassé."),
            ("la main", "/la mɛ̃/", "hand", "Donne-moi la main !"),
            ("le dos", "/lə do/", "back", "J'ai mal au dos."),
            ("la jambe", "/la ʒɑ̃b/", "leg", "Il a la jambe dans le plâtre."),
            ("le pied", "/lə pje/", "foot", "J'ai mal au pied."),
            ("j'ai mal à…", "/ʒe mal a/", "I have pain in… / my … hurts", "J'ai mal à la gorge."),
            ("la santé", "/la sɑ̃.te/", "health", "La santé, c'est important !"),
        ],
        "game_desc": "Learn French body parts and express aches and pains.",
        "items": [
            ("cor1", "la tête", "head", "head", "J'ai mal à la tête ce matin.", "Complète: J'ai mal à la ___. (head)", "tête"),
            ("cor2", "les yeux", "eyes", "eyes", "Elle a les yeux bleus et les cheveux noirs.", "Complète: Il a les ___ verts. (eyes)", "yeux"),
            ("cor3", "la bouche", "mouth", "mouth", "Ouvre la bouche chez le dentiste.", "Complète: Il a une grande ___. (mouth)", "bouche"),
            ("cor4", "le bras", "arm", "arm", "Il s'est cassé le bras au foot.", "Complète: J'ai mal au ___. (arm)", "bras"),
            ("cor5", "la main", "hand", "hand", "Donne-moi la main pour traverser.", "Complète: Il a la ___ gauche blessée. (hand)", "main"),
            ("cor6", "la jambe", "leg", "leg", "Elle a la jambe dans le plâtre.", "Complète: J'ai mal à la ___. (leg)", "jambe"),
            ("cor7", "le pied", "foot", "foot", "J'ai mal au pied après la randonnée.", "Complète: Il s'est blessé au ___. (foot)", "pied"),
            ("cor8", "j'ai mal à…", "my … hurts", "hurts", "J'ai mal à la gorge — je suis malade.", "Complète: J'ai ___ à la tête. (pain)", "mal"),
        ],
    },

    # ------------------------------------------------------------------ V10
    "la-meteo": {
        "level": "a1", "section": "vocabulary", "num": "V10",
        "short": "Weather",
        "title": "Weather & Seasons",
        "subtitle": "La météo — talking about the weather and seasons",
        "words": [
            ("le temps", "/lə tɑ̃/", "weather / time", "Quel temps fait-il ?"),
            ("il fait beau", "/il fɛ bo/", "the weather is nice", "Il fait beau aujourd'hui !"),
            ("il fait mauvais", "/il fɛ mo.vɛ/", "the weather is bad", "Il fait mauvais — reste à la maison."),
            ("il fait chaud", "/il fɛ ʃo/", "it is hot", "Il fait très chaud en été."),
            ("il fait froid", "/il fɛ fʁwa/", "it is cold", "Il fait froid en hiver."),
            ("il pleut", "/il plø/", "it is raining", "Il pleut — prends un parapluie !"),
            ("il neige", "/il nɛʒ/", "it is snowing", "Il neige en décembre dans les Alpes."),
            ("le soleil", "/lə sɔ.lɛj/", "the sun", "Le soleil brille aujourd'hui."),
            ("le nuage", "/lə ny.aʒ/", "cloud", "Il y a des nuages ce matin."),
            ("le vent", "/lə vɑ̃/", "wind", "Il y a beaucoup de vent."),
            ("le printemps", "/lə pʁɛ̃.tɑ̃/", "spring", "J'adore le printemps !"),
            ("l'été", "/le.te/", "summer", "En été, je vais à la plage."),
            ("l'automne", "/lo.tɔn/", "autumn", "Les feuilles tombent en automne."),
            ("l'hiver", "/li.vɛʁ/", "winter", "Il fait très froid en hiver."),
            ("le parapluie", "/lə pa.ʁa.plɥi/", "umbrella", "N'oublie pas ton parapluie !"),
        ],
        "game_desc": "Learn French weather expressions and season vocabulary.",
        "items": [
            ("met1", "il fait beau", "the weather is nice", "nice weather", "Il fait beau — allons à la plage !", "Complète: Il fait ___ aujourd'hui. (nice)", "beau"),
            ("met2", "il fait chaud", "it is hot", "hot", "Il fait très chaud en juillet.", "Complète: Il fait ___ en été. (hot)", "chaud"),
            ("met3", "il fait froid", "it is cold", "cold", "Il fait froid — mets ton manteau.", "Complète: Il fait ___ en hiver. (cold)", "froid"),
            ("met4", "il pleut", "it is raining", "raining", "Il pleut — prends ton parapluie !", "Complète: Il ___ dehors. (is raining)", "pleut"),
            ("met5", "il neige", "it is snowing", "snowing", "Il neige dans les montagnes en décembre.", "Complète: Il ___ en janvier. (is snowing)", "neige"),
            ("met6", "le soleil", "the sun", "sun", "Le soleil brille et il fait chaud.", "Complète: Il y a du ___. (sun)", "soleil"),
            ("met7", "l'été", "summer", "summer", "En été, je vais en vacances à la mer.", "Complète: Il fait chaud en ___. (summer)", "été"),
            ("met8", "l'hiver", "winter", "winter", "En hiver, il fait froid et il neige.", "Complète: Il fait froid en ___. (winter)", "hiver"),
        ],
    },
}
