// AUTO-GENERATED by scripts/gen_course_registry.py — do not edit by hand.
// Chapter registries for the Spanish-track courses (dashboard progress view).
window.WP_COURSES = {
 "espanol-en": {
  "label": "Spanish for English speakers",
  "levels": [
   "a1",
   "a2",
   "b1",
   "b2"
  ],
  "chapters": {
   "a1": {
    "grammar": [
     {
      "slug": "adjective-agreement",
      "label": "Adjective Agreement"
     },
     {
      "slug": "adverbs-frequency",
      "label": "Adverbs of Frequency"
     },
     {
      "slug": "articles",
      "label": "Articles"
     },
     {
      "slug": "basic-commands",
      "label": "Basic Commands"
     },
     {
      "slug": "common-mistakes",
      "label": "Common Mistakes"
     },
     {
      "slug": "demonstratives",
      "label": "Demonstratives"
     },
     {
      "slug": "gustar",
      "label": "Gustar"
     },
     {
      "slug": "hay",
      "label": "Hay"
     },
     {
      "slug": "ir-a-future",
      "label": "Ir a + Infinitive"
     },
     {
      "slug": "negation",
      "label": "Negation"
     },
     {
      "slug": "numbers-time",
      "label": "Numbers & Time"
     },
     {
      "slug": "past-tense-irregular",
      "label": "Past Tense — Irregular"
     },
     {
      "slug": "past-tense-regular",
      "label": "Past Tense — Regular"
     },
     {
      "slug": "prepositions-place",
      "label": "Prepositions of Place"
     },
     {
      "slug": "prepositions-time",
      "label": "Prepositions of Time"
     },
     {
      "slug": "present-progressive",
      "label": "Present Progressive"
     },
     {
      "slug": "present-tense",
      "label": "Present Tense"
     },
     {
      "slug": "pronouns",
      "label": "Subject Pronouns"
     },
     {
      "slug": "question-words",
      "label": "Question Words"
     },
     {
      "slug": "reflexive-verbs",
      "label": "Reflexive Verbs"
     },
     {
      "slug": "regular-verbs-ar",
      "label": "Regular -ar Verbs"
     },
     {
      "slug": "regular-verbs-er-ir",
      "label": "Regular -er / -ir Verbs"
     },
     {
      "slug": "ser-estar",
      "label": "Ser & Estar"
     },
     {
      "slug": "ser-estar-uses",
      "label": "Ser vs Estar in Depth"
     },
     {
      "slug": "tener",
      "label": "Tener — to have"
     }
    ],
    "vocabulary": [
     {
      "slug": "adjectives-feelings",
      "label": "Adjectives &amp; Feelings"
     },
     {
      "slug": "animals",
      "label": "Animals"
     },
     {
      "slug": "body",
      "label": "Body"
     },
     {
      "slug": "clothes",
      "label": "Clothes"
     },
     {
      "slug": "colours",
      "label": "Colours"
     },
     {
      "slug": "daily-routines",
      "label": "Daily Routines"
     },
     {
      "slug": "family",
      "label": "Family"
     },
     {
      "slug": "food-and-drink",
      "label": "Food &amp; Drink"
     },
     {
      "slug": "house-and-home",
      "label": "House &amp; Home"
     },
     {
      "slug": "jobs-and-occupations",
      "label": "Jobs &amp; Occupations"
     },
     {
      "slug": "numbers-and-time",
      "label": "Numbers &amp; Time"
     },
     {
      "slug": "places-in-town",
      "label": "Places in Town"
     }
    ],
    "writing": [
     {
      "slug": "form-filling",
      "label": "Form Filling"
     },
     {
      "slug": "personal-introduction",
      "label": "Personal Introduction"
     },
     {
      "slug": "short-message",
      "label": "Short Message"
     }
    ]
   },
   "a2": {
    "grammar": [
     {
      "slug": "adverbs-manner",
      "label": "Adverbs of Manner"
     },
     {
      "slug": "comparatives-basic",
      "label": "Comparatives"
     },
     {
      "slug": "conjunctions",
      "label": "Conjunctions"
     },
     {
      "slug": "countable-uncountable-basic",
      "label": "Countable & Uncountable"
     },
     {
      "slug": "future-going-to",
      "label": "Future: Going To"
     },
     {
      "slug": "future-will",
      "label": "Future: Will"
     },
     {
      "slug": "indirect-questions",
      "label": "Indirect Questions"
     },
     {
      "slug": "modal-could-might",
      "label": "Possibility"
     },
     {
      "slug": "modal-must-should",
      "label": "Obligation & Advice"
     },
     {
      "slug": "object-pronouns",
      "label": "Object Pronouns"
     },
     {
      "slug": "past-continuous",
      "label": "Past Continuous"
     },
     {
      "slug": "past-simple",
      "label": "Past Simple"
     },
     {
      "slug": "prepositions-movement",
      "label": "Prepositions of Movement"
     },
     {
      "slug": "present-perfect-intro",
      "label": "Present Perfect (Intro)"
     },
     {
      "slug": "quantifiers-basic",
      "label": "Quantifiers"
     },
     {
      "slug": "relative-clauses-basic",
      "label": "Relative Clauses"
     },
     {
      "slug": "short-answers",
      "label": "Short Answers"
     },
     {
      "slug": "too-enough-basic",
      "label": "Too & Enough"
     },
     {
      "slug": "word-order",
      "label": "Word Order"
     }
    ],
    "vocabulary": [
     {
      "slug": "cooking",
      "label": "Cooking"
     },
     {
      "slug": "feelings-emotions",
      "label": "Feelings & Emotions"
     },
     {
      "slug": "health-and-body",
      "label": "Health & Body"
     },
     {
      "slug": "music",
      "label": "Music"
     },
     {
      "slug": "problems-solutions",
      "label": "Problems & Solutions"
     },
     {
      "slug": "school-subjects",
      "label": "School Subjects"
     },
     {
      "slug": "shopping-and-money",
      "label": "Shopping & Money"
     },
     {
      "slug": "sports",
      "label": "Sports"
     },
     {
      "slug": "technology-and-media",
      "label": "Technology & Media"
     },
     {
      "slug": "transport-and-travel",
      "label": "Transport & Travel"
     },
     {
      "slug": "weather-detail",
      "label": "Weather in Detail"
     },
     {
      "slug": "work-and-jobs",
      "label": "Work & Jobs"
     }
    ],
    "writing": [
     {
      "slug": "description",
      "label": "A Description"
     },
     {
      "slug": "informal-email",
      "label": "An Informal Email"
     },
     {
      "slug": "postcard",
      "label": "A Postcard"
     }
    ]
   },
   "b1": {
    "grammar": [
     {
      "slug": "adverbs-frequency",
      "label": "Adverbs of Frequency"
     },
     {
      "slug": "adverbs-manner",
      "label": "Adverbs of Manner"
     },
     {
      "slug": "comparatives-superlatives",
      "label": "Comparatives & Superlatives"
     },
     {
      "slug": "conditional-clauses",
      "label": "Conditional Clauses"
     },
     {
      "slug": "conjunctions-advanced",
      "label": "Advanced Conjunctions"
     },
     {
      "slug": "countable-uncountable",
      "label": "Quantifiers"
     },
     {
      "slug": "future-continuous",
      "label": "Future Continuous"
     },
     {
      "slug": "future-perfect",
      "label": "Future Perfect"
     },
     {
      "slug": "imperatives",
      "label": "Imperatives"
     },
     {
      "slug": "indirect-speech",
      "label": "Indirect Speech"
     },
     {
      "slug": "modal-could-might-advanced",
      "label": "Could & Might"
     },
     {
      "slug": "modal-must-should-advanced",
      "label": "Must & Should"
     },
     {
      "slug": "modal-would",
      "label": "Would"
     },
     {
      "slug": "past-perfect",
      "label": "Past Perfect"
     },
     {
      "slug": "prepositions-time",
      "label": "Time Prepositions"
     },
     {
      "slug": "present-perfect-advanced",
      "label": "Present Perfect"
     },
     {
      "slug": "relative-clauses-advanced",
      "label": "Relative Clauses"
     },
     {
      "slug": "subjunctive-intro",
      "label": "Subjunctive Intro"
     },
     {
      "slug": "verb-forms",
      "label": "Verb Forms"
     }
    ],
    "vocabulary": [
     {
      "slug": "cooking",
      "label": "Cooking"
     },
     {
      "slug": "feelings-emotions",
      "label": "Feelings & Emotions"
     },
     {
      "slug": "health-and-body",
      "label": "Health & Body"
     },
     {
      "slug": "music",
      "label": "Music"
     },
     {
      "slug": "problems-solutions",
      "label": "Problems & Solutions"
     },
     {
      "slug": "school-subjects",
      "label": "School Subjects"
     },
     {
      "slug": "shopping-and-money",
      "label": "Shopping & Money"
     },
     {
      "slug": "sports",
      "label": "Sports"
     },
     {
      "slug": "technology-and-media",
      "label": "Technology & Media"
     },
     {
      "slug": "transport-and-travel",
      "label": "Transport & Travel"
     },
     {
      "slug": "weather-detail",
      "label": "Weather in Detail"
     },
     {
      "slug": "work-and-jobs",
      "label": "Work & Jobs"
     }
    ],
    "writing": [
     {
      "slug": "article-review",
      "label": "A Review"
     },
     {
      "slug": "biography",
      "label": "A Biography"
     },
     {
      "slug": "description-advanced",
      "label": "An Advanced Description"
     },
     {
      "slug": "dialogue",
      "label": "A Dialogue"
     },
     {
      "slug": "formal-email",
      "label": "A Formal Email"
     },
     {
      "slug": "opinion-essay",
      "label": "An Opinion Essay"
     },
     {
      "slug": "postcard-advanced",
      "label": "An Advanced Postcard"
     },
     {
      "slug": "story",
      "label": "A Short Story"
     }
    ]
   },
   "b2": {
    "grammar": [
     {
      "slug": "adverbial-clauses",
      "label": "Adverbial Clauses"
     },
     {
      "slug": "causative-verbs",
      "label": "Causative Verbs"
     },
     {
      "slug": "cleft-sentences",
      "label": "Emphasis"
     },
     {
      "slug": "conditional-advanced",
      "label": "Conditionals"
     },
     {
      "slug": "continuous-forms",
      "label": "Continuous Forms"
     },
     {
      "slug": "inversion",
      "label": "Inversion"
     },
     {
      "slug": "mixed-conditionals",
      "label": "Mixed Conditionals"
     },
     {
      "slug": "modals-advanced",
      "label": "Advanced Modals"
     },
     {
      "slug": "nominalization",
      "label": "Nominalisation"
     },
     {
      "slug": "participle-clauses",
      "label": "Participle Clauses"
     },
     {
      "slug": "passive-voice",
      "label": "The Passive Voice"
     },
     {
      "slug": "perfect-forms",
      "label": "Advanced Perfect Forms"
     },
     {
      "slug": "phrasal-verbs",
      "label": "Spanish Multi-Word Verbs"
     },
     {
      "slug": "reflexive-verbs",
      "label": "Advanced Reflexive Verbs"
     },
     {
      "slug": "reported-speech-advanced",
      "label": "Advanced Reported Speech"
     },
     {
      "slug": "subjunctive-advanced",
      "label": "Subjunctive II"
     },
     {
      "slug": "tense-consistency",
      "label": "Tense Consistency"
     },
     {
      "slug": "voice-and-register",
      "label": "Register"
     }
    ],
    "vocabulary": [
     {
      "slug": "cooking",
      "label": "Cooking"
     },
     {
      "slug": "feelings-emotions",
      "label": "Feelings & Emotions"
     },
     {
      "slug": "health-and-body",
      "label": "Health & Body"
     },
     {
      "slug": "music",
      "label": "Music"
     },
     {
      "slug": "problems-solutions",
      "label": "Problems & Solutions"
     },
     {
      "slug": "school-subjects",
      "label": "School Subjects"
     },
     {
      "slug": "shopping-and-money",
      "label": "Shopping & Money"
     },
     {
      "slug": "sports",
      "label": "Sports"
     },
     {
      "slug": "technology-and-media",
      "label": "Technology & Media"
     },
     {
      "slug": "transport-and-travel",
      "label": "Transport & Travel"
     },
     {
      "slug": "weather-detail",
      "label": "Weather in Detail"
     },
     {
      "slug": "work-and-jobs",
      "label": "Work & Jobs"
     }
    ],
    "writing": [
     {
      "slug": "analysis-essay",
      "label": "Analysis Essay"
     },
     {
      "slug": "article-feature",
      "label": "Feature Article"
     },
     {
      "slug": "character-sketch",
      "label": "Character Sketch"
     },
     {
      "slug": "comparison-essay",
      "label": "Comparison Essay"
     },
     {
      "slug": "formal-letter",
      "label": "Formal Letter"
     },
     {
      "slug": "narrative-essay",
      "label": "Narrative Essay"
     },
     {
      "slug": "opinion-advanced",
      "label": "Advanced Opinion Essay"
     },
     {
      "slug": "report-writing",
      "label": "Report Writing"
     }
    ]
   }
  }
 },
 "espanol": {
  "label": "Spanish",
  "levels": [
   "a1",
   "a2",
   "b1",
   "b2",
   "c1",
   "c2"
  ],
  "chapters": {
   "a1": {
    "grammar": [
     {
      "slug": "adjetivos",
      "label": "Los adjetivos"
     },
     {
      "slug": "articulos",
      "label": "Los Artículos"
     },
     {
      "slug": "demostrativos",
      "label": "Los Demostrativos"
     },
     {
      "slug": "estar",
      "label": "El Verbo ESTAR"
     },
     {
      "slug": "hay",
      "label": "HAY / No hay"
     },
     {
      "slug": "interrogativos",
      "label": "Las Preguntas"
     },
     {
      "slug": "negacion",
      "label": "La Negación"
     },
     {
      "slug": "numeros",
      "label": "Los Números"
     },
     {
      "slug": "posesivos",
      "label": "Los Posesivos"
     },
     {
      "slug": "preposiciones",
      "label": "Preposiciones básicas"
     },
     {
      "slug": "presente-irregular",
      "label": "Verbos irregulares comunes"
     },
     {
      "slug": "presente-regular",
      "label": "Presente Regular"
     },
     {
      "slug": "pronombres",
      "label": "Pronombres Personales"
     },
     {
      "slug": "ser",
      "label": "El Verbo SER"
     },
     {
      "slug": "tener",
      "label": "El verbo TENER"
     }
    ],
    "vocabulary": [
     {
      "slug": "adjetivos-descripcion",
      "label": "Adjetivos Básicos"
     },
     {
      "slug": "animales",
      "label": "Los Animales"
     },
     {
      "slug": "colores",
      "label": "Los Colores"
     },
     {
      "slug": "comida-bebida",
      "label": "Comida y Bebida"
     },
     {
      "slug": "cuerpo-humano",
      "label": "El Cuerpo Humano"
     },
     {
      "slug": "dias-meses",
      "label": "Días y Meses"
     },
     {
      "slug": "familia",
      "label": "La Familia"
     },
     {
      "slug": "lugares-ciudad",
      "label": "La Ciudad"
     },
     {
      "slug": "numeros",
      "label": "Los Números"
     },
     {
      "slug": "profesiones",
      "label": "Las Profesiones"
     },
     {
      "slug": "ropa",
      "label": "La Ropa"
     },
     {
      "slug": "saludos",
      "label": "Saludos y Despedidas"
     }
    ],
    "writing": [
     {
      "slug": "formulario",
      "label": "El Formulario"
     },
     {
      "slug": "mensaje-breve",
      "label": "El Mensaje Breve"
     },
     {
      "slug": "presentacion-personal",
      "label": "La Presentación Personal"
     }
    ]
   },
   "a2": {
    "grammar": [
     {
      "slug": "comparativos",
      "label": "Comparativos"
     },
     {
      "slug": "condicional",
      "label": "Condicional Simple"
     },
     {
      "slug": "conjunciones",
      "label": "Las Conjunciones"
     },
     {
      "slug": "cuantificadores",
      "label": "Los Cuantificadores"
     },
     {
      "slug": "futuro-simple",
      "label": "Futuro Simple"
     },
     {
      "slug": "gerundio",
      "label": "Gerundio"
     },
     {
      "slug": "imperativo",
      "label": "Imperativo"
     },
     {
      "slug": "oraciones-relativas",
      "label": "Oraciones de Relativo"
     },
     {
      "slug": "presente-continuo",
      "label": "El Presente Continuo"
     },
     {
      "slug": "preterito-imperfecto",
      "label": "Pretérito Imperfecto"
     },
     {
      "slug": "preterito-indefinido",
      "label": "Pretérito Indefinido"
     },
     {
      "slug": "preterito-perfecto",
      "label": "Pretérito Perfecto"
     },
     {
      "slug": "pronombres-objeto",
      "label": "Pronombres Objeto"
     },
     {
      "slug": "reflexivos",
      "label": "Verbos Reflexivos"
     },
     {
      "slug": "ser-estar-a2",
      "label": "SER y ESTAR avanzado"
     }
    ],
    "vocabulary": [
     {
      "slug": "casa-hogar",
      "label": "La Casa y el Hogar"
     },
     {
      "slug": "compras",
      "label": "Las Compras"
     },
     {
      "slug": "emociones-sentimientos",
      "label": "Emociones y Sentimientos"
     },
     {
      "slug": "escuela-educacion",
      "label": "La Escuela y la Educación"
     },
     {
      "slug": "naturaleza-medioambiente",
      "label": "La Naturaleza y el Medioambiente"
     },
     {
      "slug": "ocio-tiempo-libre",
      "label": "Ocio y Tiempo Libre"
     },
     {
      "slug": "restaurante-cafeteria",
      "label": "El Restaurante y la Cafetería"
     },
     {
      "slug": "salud-bienestar",
      "label": "Salud y Bienestar"
     },
     {
      "slug": "tecnologia-internet",
      "label": "Tecnología e Internet"
     },
     {
      "slug": "tiempo-atmosferico",
      "label": "El Tiempo Atmosférico"
     },
     {
      "slug": "trabajo-oficina",
      "label": "El Trabajo y la Oficina"
     },
     {
      "slug": "transporte",
      "label": "El Transporte"
     }
    ],
    "writing": [
     {
      "slug": "correo-informal",
      "label": "El Correo Informal"
     },
     {
      "slug": "descripcion",
      "label": "La Descripción"
     },
     {
      "slug": "postal",
      "label": "La Postal"
     }
    ]
   },
   "b1": {
    "grammar": [
     {
      "slug": "conectores-discurso",
      "label": "Conectores del Discurso"
     },
     {
      "slug": "estilo-indirecto",
      "label": "Estilo Indirecto"
     },
     {
      "slug": "indefinidos",
      "label": "Pronombres Indefinidos"
     },
     {
      "slug": "lo-neutro",
      "label": "Lo Neutro"
     },
     {
      "slug": "oraciones-causales-concesivas",
      "label": "Causales y Concesivas"
     },
     {
      "slug": "oraciones-condicionales",
      "label": "Oraciones Condicionales"
     },
     {
      "slug": "perifrasis-verbales",
      "label": "Perífrasis Verbales"
     },
     {
      "slug": "pluscuamperfecto",
      "label": "Pluscuamperfecto"
     },
     {
      "slug": "por-para",
      "label": "POR y PARA"
     },
     {
      "slug": "pronombres-relativos",
      "label": "Pronombres Relativos"
     },
     {
      "slug": "subjuntivo-imperfecto",
      "label": "Subjuntivo Imperfecto"
     },
     {
      "slug": "subjuntivo-presente",
      "label": "Subjuntivo Presente"
     },
     {
      "slug": "subjuntivo-temporal",
      "label": "Subjuntivo Temporal"
     },
     {
      "slug": "verbos-cambio",
      "label": "Verbos de Cambio"
     },
     {
      "slug": "voz-pasiva",
      "label": "La Voz Pasiva"
     }
    ],
    "vocabulary": [
     {
      "slug": "alimentacion-dieta",
      "label": "Alimentación y Dieta"
     },
     {
      "slug": "ciencia-tecnologia",
      "label": "Ciencia y Tecnología"
     },
     {
      "slug": "cultura-arte",
      "label": "Cultura y Arte"
     },
     {
      "slug": "deportes-actividad-fisica",
      "label": "Deportes y Actividad Física"
     },
     {
      "slug": "economia-dinero",
      "label": "Economía y Dinero"
     },
     {
      "slug": "educacion-avanzada",
      "label": "Educación Avanzada"
     },
     {
      "slug": "medio-ambiente",
      "label": "El Medio Ambiente"
     },
     {
      "slug": "personalidad-caracter",
      "label": "Personalidad y Carácter"
     },
     {
      "slug": "politica-sociedad",
      "label": "Política y Sociedad"
     },
     {
      "slug": "relaciones-sociales",
      "label": "Relaciones Sociales"
     },
     {
      "slug": "trabajo-carrera",
      "label": "Trabajo y Carrera"
     },
     {
      "slug": "viajes-turismo",
      "label": "Viajes y Turismo"
     }
    ],
    "writing": [
     {
      "slug": "biografia-resumen",
      "label": "La Biografía Breve"
     },
     {
      "slug": "carta-informal",
      "label": "La Carta Informal"
     },
     {
      "slug": "correo-formal",
      "label": "El Correo Formal"
     },
     {
      "slug": "descripcion-avanzada",
      "label": "La Descripción Avanzada"
     },
     {
      "slug": "dialogo",
      "label": "El Diálogo Escrito"
     },
     {
      "slug": "narracion",
      "label": "La Narración"
     },
     {
      "slug": "redaccion-opinion",
      "label": "La Redacción de Opinión"
     },
     {
      "slug": "resena",
      "label": "La Reseña"
     }
    ]
   },
   "b2": {
    "grammar": [
     {
      "slug": "concordancia-avanzada",
      "label": "Concordancia Avanzada"
     },
     {
      "slug": "construcciones-absolutas",
      "label": "Construcciones Absolutas"
     },
     {
      "slug": "cuantificadores-b2",
      "label": "Cuantificadores Avanzados"
     },
     {
      "slug": "expresiones-tiempo",
      "label": "Expresiones Temporales"
     },
     {
      "slug": "futuro-avanzado",
      "label": "El Futuro Avanzado"
     },
     {
      "slug": "indefinido-imperfecto-perfecto",
      "label": "Contraste de los tres pasados"
     },
     {
      "slug": "lenguaje-formal",
      "label": "Lenguaje Formal"
     },
     {
      "slug": "modo-subjuntivo-expresiones",
      "label": "Subjuntivo: valoracion y emocion"
     },
     {
      "slug": "nominalización",
      "label": "La Nominalización"
     },
     {
      "slug": "oraciones-relativas-b2",
      "label": "Relativas Avanzadas"
     },
     {
      "slug": "oraciones-subordinadas",
      "label": "Oraciones Subordinadas"
     },
     {
      "slug": "preposiciones-b2",
      "label": "Preposiciones Avanzadas"
     },
     {
      "slug": "ser-estar-b2",
      "label": "SER y ESTAR avanzado"
     },
     {
      "slug": "subjuntivo-b2",
      "label": "Subjuntivo: tres clausulas"
     },
     {
      "slug": "subjuntivo-perfecto",
      "label": "Subjuntivo Perfecto"
     }
    ],
    "vocabulary": [
     {
      "slug": "arquitectura-diseno",
      "label": "Arquitectura y Diseño"
     },
     {
      "slug": "ciencia-avanzada",
      "label": "Ciencia Avanzada"
     },
     {
      "slug": "comunicacion-medios",
      "label": "Comunicación y Medios"
     },
     {
      "slug": "economia-global",
      "label": "Economía Global"
     },
     {
      "slug": "filosofia-etica",
      "label": "Filosofía y Ética"
     },
     {
      "slug": "historia-civilizacion",
      "label": "Historia y Civilización"
     },
     {
      "slug": "lenguaje-linguistica",
      "label": "Lenguaje y Lingüística"
     },
     {
      "slug": "literatura-escritura",
      "label": "Literatura y Escritura"
     },
     {
      "slug": "musica-artes-escenicas",
      "label": "Música y Artes Escénicas"
     },
     {
      "slug": "politica-internacional",
      "label": "Política Internacional"
     },
     {
      "slug": "psicologia-conducta",
      "label": "Psicología y Conducta"
     },
     {
      "slug": "sociologia-cultura",
      "label": "Sociología y Cultura"
     }
    ],
    "writing": [
     {
      "slug": "analisis-texto",
      "label": "El Análisis de Texto"
     },
     {
      "slug": "articulo-opinion",
      "label": "El Artículo de Opinión"
     },
     {
      "slug": "carta-formal-b2",
      "label": "La Carta Formal B2"
     },
     {
      "slug": "ensayo-comparativo",
      "label": "El Ensayo Comparativo"
     },
     {
      "slug": "ensayo-opinion",
      "label": "El Ensayo de Opinión"
     },
     {
      "slug": "informe",
      "label": "El Informe"
     },
     {
      "slug": "narracion-avanzada",
      "label": "La Narración Avanzada"
     },
     {
      "slug": "resumen-academico",
      "label": "El Resumen Académico"
     }
    ]
   },
   "c1": {
    "grammar": [
     {
      "slug": "aspecto-verbal",
      "label": "Aspecto Verbal"
     },
     {
      "slug": "construcciones-pasivas-c1",
      "label": "Construcciones Pasivas"
     },
     {
      "slug": "estilo-indirecto-c1",
      "label": "Estilo Indirecto C1"
     },
     {
      "slug": "gramatica-textual",
      "label": "Cohesión Textual"
     },
     {
      "slug": "hipoteticos-avanzados",
      "label": "Condicionales Avanzadas"
     },
     {
      "slug": "modalidad-epistemica",
      "label": "Modalidad y Atenuación"
     },
     {
      "slug": "modalidad-verbal",
      "label": "Modalidad Verbal"
     },
     {
      "slug": "oraciones-escindidas",
      "label": "Oraciones Escindidas"
     },
     {
      "slug": "orden-palabras",
      "label": "Orden de Palabras"
     },
     {
      "slug": "pronominal-c1",
      "label": "El Sistema Pronominal"
     },
     {
      "slug": "regimen-preposicional",
      "label": "Régimen Preposicional"
     },
     {
      "slug": "ser-estar-c1",
      "label": "SER, ESTAR y HABER"
     },
     {
      "slug": "subjuntivo-c1",
      "label": "Subjuntivo Avanzado"
     },
     {
      "slug": "subjuntivo-concesivas",
      "label": "Oraciones Concesivas"
     },
     {
      "slug": "subordinadas-c1",
      "label": "Subordinadas: Modo"
     }
    ],
    "vocabulary": [
     {
      "slug": "arte-estetica",
      "label": "Arte y Estética"
     },
     {
      "slug": "ciencia-investigacion",
      "label": "Ciencia e Investigación"
     },
     {
      "slug": "comunicacion-retorica",
      "label": "Comunicación y Retórica"
     },
     {
      "slug": "derecho-justicia",
      "label": "Derecho y Justicia"
     },
     {
      "slug": "economia-politica-avanzada",
      "label": "Economía Política Avanzada"
     },
     {
      "slug": "educacion-conocimiento",
      "label": "Educación y Conocimiento"
     },
     {
      "slug": "medioambiente-sostenibilidad",
      "label": "Medioambiente y Sostenibilidad"
     },
     {
      "slug": "pensamiento-abstracto",
      "label": "Pensamiento Abstracto"
     },
     {
      "slug": "politica-gobernanza",
      "label": "Política y Gobernanza"
     },
     {
      "slug": "salud-bienestar-avanzado",
      "label": "Salud y Bienestar Avanzado"
     },
     {
      "slug": "sociedad-contemporanea",
      "label": "Sociedad Contemporánea"
     },
     {
      "slug": "tecnologia-digital",
      "label": "Tecnología Digital"
     }
    ],
    "writing": [
     {
      "slug": "analisis-critico",
      "label": "El Análisis Crítico"
     },
     {
      "slug": "carta-institucional",
      "label": "La Carta Institucional"
     },
     {
      "slug": "columna-opinion",
      "label": "La Columna de Opinión"
     },
     {
      "slug": "comentario-critico",
      "label": "El Comentario Crítico"
     },
     {
      "slug": "ensayo-argumentativo",
      "label": "El Ensayo Argumentativo"
     },
     {
      "slug": "texto-academico",
      "label": "El Texto Académico"
     }
    ]
   },
   "c2": {
    "grammar": [
     {
      "slug": "aspecto-lexico",
      "label": "Aspecto Léxico"
     },
     {
      "slug": "construcciones-sinteticas",
      "label": "Construcciones Sintéticas"
     },
     {
      "slug": "creatividad-lexica",
      "label": "Creatividad Léxica"
     },
     {
      "slug": "discurso-referido",
      "label": "Discurso Referido"
     },
     {
      "slug": "estilo-nominal",
      "label": "Estilo Nominal"
     },
     {
      "slug": "generos-textuales",
      "label": "Géneros Textuales"
     },
     {
      "slug": "gramatica-discursiva",
      "label": "Gramática del Discurso"
     },
     {
      "slug": "intensificacion",
      "label": "Intensificación y Atenuación"
     },
     {
      "slug": "negacion-c2",
      "label": "La Negación Avanzada"
     },
     {
      "slug": "perifrasis-c2",
      "label": "Las Perífrasis Verbales"
     },
     {
      "slug": "pragmatica-espanol",
      "label": "Pragmática"
     },
     {
      "slug": "tiempos-literarios",
      "label": "Tiempos Literarios"
     },
     {
      "slug": "topicalizacion",
      "label": "Topicalización"
     },
     {
      "slug": "variacion-linguistica",
      "label": "Variación Lingüística"
     },
     {
      "slug": "verbos-percepcion",
      "label": "Verbos de Percepción"
     }
    ],
    "vocabulary": [
     {
      "slug": "arte-contemporaneo",
      "label": "Arte Contemporáneo"
     },
     {
      "slug": "discurso-poder",
      "label": "Discurso y Poder"
     },
     {
      "slug": "epistemologia",
      "label": "Epistemología"
     },
     {
      "slug": "estetica-critica-cultural",
      "label": "Estética y Crítica Cultural"
     },
     {
      "slug": "estilistica-literaria",
      "label": "Estilística Literaria"
     },
     {
      "slug": "etica-bioetica",
      "label": "Ética y Bioética"
     },
     {
      "slug": "filosofia-del-lenguaje",
      "label": "Filosofía del Lenguaje"
     },
     {
      "slug": "historia-ideas",
      "label": "Historia de las Ideas"
     },
     {
      "slug": "linguistica-avanzada",
      "label": "Lingüística Avanzada"
     },
     {
      "slug": "linguistica-textual",
      "label": "Lingüística Textual"
     },
     {
      "slug": "pensamiento-critico-avanzado",
      "label": "Pensamiento Crítico Avanzado"
     },
     {
      "slug": "sociologia-conocimiento",
      "label": "Sociología del Conocimiento"
     }
    ],
    "writing": [
     {
      "slug": "analisis-literario",
      "label": "El Análisis Literario"
     },
     {
      "slug": "discurso",
      "label": "El Discurso"
     },
     {
      "slug": "ensayo-academico",
      "label": "El Ensayo Académico C2"
     },
     {
      "slug": "escritura-creativa",
      "label": "La Escritura Creativa"
     },
     {
      "slug": "texto-expositivo",
      "label": "El Texto Expositivo"
     }
    ]
   }
  }
 }
};
