#!/usr/bin/env python3
# D5: Generate shared/courses.js — chapter registries for the Spanish-track courses
# so the dashboard can show real progress for Spanish learners. Reads chapter labels
# from each chapter's <h1>. Re-runnable; safe to commit the output.
import re
from pathlib import Path
import json

ROOT = Path('/home/user/wordplay')
H1 = re.compile(r'<h1[^>]*>(.*?)</h1>', re.S)
SECTIONS = ['grammar', 'vocabulary', 'writing']

COURSES = {
    'espanol-en': {'label': 'Spanish for English speakers', 'levels': ['a1', 'a2', 'b1', 'b2']},
    'espanol':    {'label': 'Spanish',                      'levels': ['a1', 'a2', 'b1', 'b2', 'c1', 'c2']},
}

def label_for(idx_path, slug):
    try:
        m = H1.search(idx_path.read_text(encoding='utf-8'))
        if m:
            txt = re.sub(r'<[^>]+>', '', m.group(1)).strip()
            if txt:
                return txt
    except (IOError, UnicodeDecodeError):
        pass
    return slug.replace('-', ' ').title()

out = {}
for course, meta in COURSES.items():
    out[course] = {'label': meta['label'], 'levels': meta['levels'], 'chapters': {}}
    for lv in meta['levels']:
        lvl_obj = {}
        for sec in SECTIONS:
            secdir = ROOT / course / lv / sec
            if not secdir.is_dir():
                continue
            chapters = []
            for chdir in sorted(p for p in secdir.iterdir() if p.is_dir()):
                slug = chdir.name
                idx = chdir / 'index.html'
                if not idx.exists():
                    continue
                chapters.append({'slug': slug, 'label': label_for(idx, slug)})
            if chapters:
                lvl_obj[sec] = chapters
        if lvl_obj:
            out[course]['chapters'][lv] = lvl_obj

js = ("// AUTO-GENERATED by scripts/gen_course_registry.py — do not edit by hand.\n"
      "// Chapter registries for the Spanish-track courses (dashboard progress view).\n"
      "window.WP_COURSES = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
(ROOT / 'shared' / 'courses.js').write_text(js, encoding='utf-8')

# summary
for course in out:
    n = sum(len(s) for lv in out[course]['chapters'].values() for s in lv.values())
    print(f"{course}: {len(out[course]['chapters'])} levels, {n} chapters")
print("wrote shared/courses.js")
